package l7;
public final class a4 implements u9.d {
    public static final a4 f11746a = new Object();
    public static final u9.c f11748b = new u9.c("systemInfo", w.c.h(l.d.o(h0.class, new e0(1))));
    public static final u9.c f11750c = new u9.c("eventName", w.c.h(l.d.o(h0.class, new e0(2))));
    public static final u9.c d = new u9.c("isThickClient", w.c.h(l.d.o(h0.class, new e0(37))));
    public static final u9.c f11753e = new u9.c("clientType", w.c.h(l.d.o(h0.class, new e0(61))));
    public static final u9.c f11755f = new u9.c("modelDownloadLogEvent", w.c.h(l.d.o(h0.class, new e0(3))));
    public static final u9.c f11757g = new u9.c("customModelLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", w.c.h(l.d.o(h0.class, new e0(4))));
    public static final u9.c f11760i = new u9.c("customModelCreateLogEvent", w.c.h(l.d.o(h0.class, new e0(29))));
    public static final u9.c f11762j = new u9.c("onDeviceFaceDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(5))));
    public static final u9.c f11764k = new u9.c("onDeviceFaceLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(59))));
    public static final u9.c f11766l = new u9.c("onDeviceTextDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(6))));
    public static final u9.c f11768m = new u9.c("onDeviceTextDetectionLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(79))));
    public static final u9.c f11769n = new u9.c("onDeviceBarcodeDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(7))));
    public static final u9.c f11771o = new u9.c("onDeviceBarcodeLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(58))));
    public static final u9.c f11773p = new u9.c("onDeviceImageLabelCreateLogEvent", w.c.h(l.d.o(h0.class, new e0(48))));
    public static final u9.c f11775q = new u9.c("onDeviceImageLabelLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(49))));
    public static final u9.c f11777r = new u9.c("onDeviceImageLabelDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(18))));
    public static final u9.c f11779s = new u9.c("onDeviceObjectCreateLogEvent", w.c.h(l.d.o(h0.class, new e0(26))));
    public static final u9.c f11781t = new u9.c("onDeviceObjectLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(27))));
    public static final u9.c f11783u = new u9.c("onDeviceObjectInferenceLogEvent", w.c.h(l.d.o(h0.class, new e0(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(44))));
    public static final u9.c f11786w = new u9.c("onDeviceSegmentationLogEvent", w.c.h(l.d.o(h0.class, new e0(45))));
    public static final u9.c f11788x = new u9.c("onDeviceSmartReplyLogEvent", w.c.h(l.d.o(h0.class, new e0(19))));
    public static final u9.c f11790y = new u9.c("onDeviceLanguageIdentificationLogEvent", w.c.h(l.d.o(h0.class, new e0(21))));
    public static final u9.c f11792z = new u9.c("onDeviceTranslationLogEvent", w.c.h(l.d.o(h0.class, new e0(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", w.c.h(l.d.o(h0.class, new e0(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", w.c.h(l.d.o(h0.class, new e0(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", w.c.h(l.d.o(h0.class, new e0(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", w.c.h(l.d.o(h0.class, new e0(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", w.c.h(l.d.o(h0.class, new e0(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", w.c.h(l.d.o(h0.class, new e0(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", w.c.h(l.d.o(h0.class, new e0(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", w.c.h(l.d.o(h0.class, new e0(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", w.c.h(l.d.o(h0.class, new e0(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", w.c.h(l.d.o(h0.class, new e0(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", w.c.h(l.d.o(h0.class, new e0(42))));
    public static final u9.c f11747a0 = new u9.c("inputImageConstructionLogEvent", w.c.h(l.d.o(h0.class, new e0(50))));
    public static final u9.c f11749b0 = new u9.c("leakedHandleEvent", w.c.h(l.d.o(h0.class, new e0(51))));
    public static final u9.c f11751c0 = new u9.c("cameraSourceLogEvent", w.c.h(l.d.o(h0.class, new e0(52))));
    public static final u9.c f11752d0 = new u9.c("imageLabelOptionalModuleLogEvent", w.c.h(l.d.o(h0.class, new e0(53))));
    public static final u9.c f11754e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", w.c.h(l.d.o(h0.class, new e0(54))));
    public static final u9.c f11756f0 = new u9.c("faceDetectionOptionalModuleLogEvent", w.c.h(l.d.o(h0.class, new e0(60))));
    public static final u9.c f11758g0 = new u9.c("nlClassifierOptionalModuleLogEvent", w.c.h(l.d.o(h0.class, new e0(55))));
    public static final u9.c f11759h0 = new u9.c("nlClassifierClientLibraryLogEvent", w.c.h(l.d.o(h0.class, new e0(56))));
    public static final u9.c f11761i0 = new u9.c("accelerationAllowlistLogEvent", w.c.h(l.d.o(h0.class, new e0(57))));
    public static final u9.c f11763j0 = new u9.c("toxicityDetectionCreateEvent", w.c.h(l.d.o(h0.class, new e0(62))));
    public static final u9.c f11765k0 = new u9.c("toxicityDetectionLoadEvent", w.c.h(l.d.o(h0.class, new e0(63))));
    public static final u9.c f11767l0 = new u9.c("toxicityDetectionInferenceEvent", w.c.h(l.d.o(h0.class, new e0(64))));
    public static final u9.c m0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", w.c.h(l.d.o(h0.class, new e0(65))));
    public static final u9.c f11770n0 = new u9.c("customImageLabelOptionalModuleLogEvent", w.c.h(l.d.o(h0.class, new e0(66))));
    public static final u9.c f11772o0 = new u9.c("codeScannerScanApiEvent", w.c.h(l.d.o(h0.class, new e0(67))));
    public static final u9.c f11774p0 = new u9.c("codeScannerOptionalModuleEvent", w.c.h(l.d.o(h0.class, new e0(68))));
    public static final u9.c f11776q0 = new u9.c("onDeviceExplicitContentCreateLogEvent", w.c.h(l.d.o(h0.class, new e0(70))));
    public static final u9.c f11778r0 = new u9.c("onDeviceExplicitContentLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(71))));
    public static final u9.c f11780s0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", w.c.h(l.d.o(h0.class, new e0(72))));
    public static final u9.c f11782t0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", w.c.h(l.d.o(h0.class, new e0(73))));
    public static final u9.c f11784u0 = new u9.c("onDeviceSelfieFaceCreateLogEvent", w.c.h(l.d.o(h0.class, new e0(74))));
    public static final u9.c f11785v0 = new u9.c("onDeviceSelfieFaceLoadLogEvent", w.c.h(l.d.o(h0.class, new e0(75))));
    public static final u9.c f11787w0 = new u9.c("onDeviceSelfieFaceLogEvent", w.c.h(l.d.o(h0.class, new e0(76))));
    public static final u9.c f11789x0 = new u9.c("aggregatedOnDeviceSelfieFaceLogEvent", w.c.h(l.d.o(h0.class, new e0(77))));
    public static final u9.c f11791y0 = new u9.c("smartReplyOptionalModuleLogEvent", w.c.h(l.d.o(h0.class, new e0(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        v7 v7Var = (v7) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f11748b, v7Var.f12071a);
        eVar.e(f11750c, v7Var.f12072b);
        eVar.e(d, null);
        eVar.e(f11753e, v7Var.f12073c);
        eVar.e(f11755f, null);
        eVar.e(f11757g, null);
        eVar.e(h, null);
        eVar.e(f11760i, null);
        eVar.e(f11762j, null);
        eVar.e(f11764k, null);
        eVar.e(f11766l, null);
        eVar.e(f11768m, null);
        eVar.e(f11769n, null);
        eVar.e(f11771o, null);
        eVar.e(f11773p, null);
        eVar.e(f11775q, v7Var.d);
        eVar.e(f11777r, v7Var.f12074e);
        eVar.e(f11779s, null);
        eVar.e(f11781t, null);
        eVar.e(f11783u, null);
        eVar.e(v, null);
        eVar.e(f11786w, null);
        eVar.e(f11788x, null);
        eVar.e(f11790y, null);
        eVar.e(f11792z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, v7Var.f12075f);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f11747a0, null);
        eVar.e(f11749b0, null);
        eVar.e(f11751c0, null);
        eVar.e(f11752d0, null);
        eVar.e(f11754e0, null);
        eVar.e(f11756f0, null);
        eVar.e(f11758g0, null);
        eVar.e(f11759h0, null);
        eVar.e(f11761i0, null);
        eVar.e(f11763j0, null);
        eVar.e(f11765k0, null);
        eVar.e(f11767l0, null);
        eVar.e(m0, null);
        eVar.e(f11770n0, null);
        eVar.e(f11772o0, null);
        eVar.e(f11774p0, null);
        eVar.e(f11776q0, null);
        eVar.e(f11778r0, null);
        eVar.e(f11780s0, null);
        eVar.e(f11782t0, null);
        eVar.e(f11784u0, null);
        eVar.e(f11785v0, null);
        eVar.e(f11787w0, null);
        eVar.e(f11789x0, null);
        eVar.e(f11791y0, null);
    }
}
