package l7;
public final class a4 implements u9.d {
    public static final a4 f11477a = new Object();
    public static final u9.c f11479b = new u9.c("systemInfo", vh.w2.h(kf.k0.o(h0.class, new e0(1))));
    public static final u9.c f11481c = new u9.c("eventName", vh.w2.h(kf.k0.o(h0.class, new e0(2))));
    public static final u9.c d = new u9.c("isThickClient", vh.w2.h(kf.k0.o(h0.class, new e0(37))));
    public static final u9.c e = new u9.c("clientType", vh.w2.h(kf.k0.o(h0.class, new e0(61))));
    public static final u9.c f11485f = new u9.c("modelDownloadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(3))));
    public static final u9.c f11487g = new u9.c("customModelLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(4))));
    public static final u9.c f11490i = new u9.c("customModelCreateLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(29))));
    public static final u9.c f11492j = new u9.c("onDeviceFaceDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(5))));
    public static final u9.c f11494k = new u9.c("onDeviceFaceLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(59))));
    public static final u9.c f11496l = new u9.c("onDeviceTextDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(6))));
    public static final u9.c f11498m = new u9.c("onDeviceTextDetectionLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(79))));
    public static final u9.c f11499n = new u9.c("onDeviceBarcodeDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(7))));
    public static final u9.c f11501o = new u9.c("onDeviceBarcodeLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(58))));
    public static final u9.c f11503p = new u9.c("onDeviceImageLabelCreateLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(48))));
    public static final u9.c f11505q = new u9.c("onDeviceImageLabelLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(49))));
    public static final u9.c f11507r = new u9.c("onDeviceImageLabelDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(18))));
    public static final u9.c f11509s = new u9.c("onDeviceObjectCreateLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(26))));
    public static final u9.c f11511t = new u9.c("onDeviceObjectLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(27))));
    public static final u9.c f11513u = new u9.c("onDeviceObjectInferenceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(44))));
    public static final u9.c f11516w = new u9.c("onDeviceSegmentationLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(45))));
    public static final u9.c f11518x = new u9.c("onDeviceSmartReplyLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(19))));
    public static final u9.c f11520y = new u9.c("onDeviceLanguageIdentificationLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(21))));
    public static final u9.c f11522z = new u9.c("onDeviceTranslationLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", vh.w2.h(kf.k0.o(h0.class, new e0(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(42))));
    public static final u9.c f11478a0 = new u9.c("inputImageConstructionLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(50))));
    public static final u9.c f11480b0 = new u9.c("leakedHandleEvent", vh.w2.h(kf.k0.o(h0.class, new e0(51))));
    public static final u9.c f11482c0 = new u9.c("cameraSourceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(52))));
    public static final u9.c f11483d0 = new u9.c("imageLabelOptionalModuleLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(53))));
    public static final u9.c f11484e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(54))));
    public static final u9.c f11486f0 = new u9.c("faceDetectionOptionalModuleLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(60))));
    public static final u9.c f11488g0 = new u9.c("nlClassifierOptionalModuleLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(55))));
    public static final u9.c f11489h0 = new u9.c("nlClassifierClientLibraryLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(56))));
    public static final u9.c f11491i0 = new u9.c("accelerationAllowlistLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(57))));
    public static final u9.c f11493j0 = new u9.c("toxicityDetectionCreateEvent", vh.w2.h(kf.k0.o(h0.class, new e0(62))));
    public static final u9.c f11495k0 = new u9.c("toxicityDetectionLoadEvent", vh.w2.h(kf.k0.o(h0.class, new e0(63))));
    public static final u9.c f11497l0 = new u9.c("toxicityDetectionInferenceEvent", vh.w2.h(kf.k0.o(h0.class, new e0(64))));
    public static final u9.c m0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(65))));
    public static final u9.c f11500n0 = new u9.c("customImageLabelOptionalModuleLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(66))));
    public static final u9.c f11502o0 = new u9.c("codeScannerScanApiEvent", vh.w2.h(kf.k0.o(h0.class, new e0(67))));
    public static final u9.c f11504p0 = new u9.c("codeScannerOptionalModuleEvent", vh.w2.h(kf.k0.o(h0.class, new e0(68))));
    public static final u9.c f11506q0 = new u9.c("onDeviceExplicitContentCreateLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(70))));
    public static final u9.c f11508r0 = new u9.c("onDeviceExplicitContentLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(71))));
    public static final u9.c f11510s0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(72))));
    public static final u9.c f11512t0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(73))));
    public static final u9.c f11514u0 = new u9.c("onDeviceSelfieFaceCreateLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(74))));
    public static final u9.c f11515v0 = new u9.c("onDeviceSelfieFaceLoadLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(75))));
    public static final u9.c f11517w0 = new u9.c("onDeviceSelfieFaceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(76))));
    public static final u9.c f11519x0 = new u9.c("aggregatedOnDeviceSelfieFaceLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(77))));
    public static final u9.c f11521y0 = new u9.c("smartReplyOptionalModuleLogEvent", vh.w2.h(kf.k0.o(h0.class, new e0(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        v7 v7Var = (v7) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f11479b, v7Var.f11779a);
        eVar.e(f11481c, v7Var.f11780b);
        eVar.e(d, null);
        eVar.e(e, v7Var.f11781c);
        eVar.e(f11485f, null);
        eVar.e(f11487g, null);
        eVar.e(h, null);
        eVar.e(f11490i, null);
        eVar.e(f11492j, null);
        eVar.e(f11494k, null);
        eVar.e(f11496l, null);
        eVar.e(f11498m, null);
        eVar.e(f11499n, null);
        eVar.e(f11501o, null);
        eVar.e(f11503p, null);
        eVar.e(f11505q, v7Var.d);
        eVar.e(f11507r, v7Var.e);
        eVar.e(f11509s, null);
        eVar.e(f11511t, null);
        eVar.e(f11513u, null);
        eVar.e(v, null);
        eVar.e(f11516w, null);
        eVar.e(f11518x, null);
        eVar.e(f11520y, null);
        eVar.e(f11522z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, v7Var.f11782f);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f11478a0, null);
        eVar.e(f11480b0, null);
        eVar.e(f11482c0, null);
        eVar.e(f11483d0, null);
        eVar.e(f11484e0, null);
        eVar.e(f11486f0, null);
        eVar.e(f11488g0, null);
        eVar.e(f11489h0, null);
        eVar.e(f11491i0, null);
        eVar.e(f11493j0, null);
        eVar.e(f11495k0, null);
        eVar.e(f11497l0, null);
        eVar.e(m0, null);
        eVar.e(f11500n0, null);
        eVar.e(f11502o0, null);
        eVar.e(f11504p0, null);
        eVar.e(f11506q0, null);
        eVar.e(f11508r0, null);
        eVar.e(f11510s0, null);
        eVar.e(f11512t0, null);
        eVar.e(f11514u0, null);
        eVar.e(f11515v0, null);
        eVar.e(f11517w0, null);
        eVar.e(f11519x0, null);
        eVar.e(f11521y0, null);
    }
}
