package l7;
public final class a4 implements u9.d {
    public static final a4 f11367a = new Object();
    public static final u9.c f11369b = new u9.c("systemInfo", vh.v2.h(kh.a2.o(h0.class, new e0(1))));
    public static final u9.c f11371c = new u9.c("eventName", vh.v2.h(kh.a2.o(h0.class, new e0(2))));
    public static final u9.c d = new u9.c("isThickClient", vh.v2.h(kh.a2.o(h0.class, new e0(37))));
    public static final u9.c e = new u9.c("clientType", vh.v2.h(kh.a2.o(h0.class, new e0(61))));
    public static final u9.c f11375f = new u9.c("modelDownloadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(3))));
    public static final u9.c f11377g = new u9.c("customModelLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(4))));
    public static final u9.c f11380i = new u9.c("customModelCreateLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(29))));
    public static final u9.c f11382j = new u9.c("onDeviceFaceDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(5))));
    public static final u9.c f11384k = new u9.c("onDeviceFaceLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(59))));
    public static final u9.c f11386l = new u9.c("onDeviceTextDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(6))));
    public static final u9.c f11388m = new u9.c("onDeviceTextDetectionLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(79))));
    public static final u9.c f11389n = new u9.c("onDeviceBarcodeDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(7))));
    public static final u9.c f11391o = new u9.c("onDeviceBarcodeLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(58))));
    public static final u9.c f11393p = new u9.c("onDeviceImageLabelCreateLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(48))));
    public static final u9.c f11395q = new u9.c("onDeviceImageLabelLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(49))));
    public static final u9.c f11397r = new u9.c("onDeviceImageLabelDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(18))));
    public static final u9.c f11399s = new u9.c("onDeviceObjectCreateLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(26))));
    public static final u9.c f11401t = new u9.c("onDeviceObjectLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(27))));
    public static final u9.c f11403u = new u9.c("onDeviceObjectInferenceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(44))));
    public static final u9.c f11406w = new u9.c("onDeviceSegmentationLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(45))));
    public static final u9.c f11408x = new u9.c("onDeviceSmartReplyLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(19))));
    public static final u9.c f11410y = new u9.c("onDeviceLanguageIdentificationLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(21))));
    public static final u9.c f11412z = new u9.c("onDeviceTranslationLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", vh.v2.h(kh.a2.o(h0.class, new e0(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(42))));
    public static final u9.c f11368a0 = new u9.c("inputImageConstructionLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(50))));
    public static final u9.c f11370b0 = new u9.c("leakedHandleEvent", vh.v2.h(kh.a2.o(h0.class, new e0(51))));
    public static final u9.c f11372c0 = new u9.c("cameraSourceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(52))));
    public static final u9.c f11373d0 = new u9.c("imageLabelOptionalModuleLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(53))));
    public static final u9.c f11374e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(54))));
    public static final u9.c f11376f0 = new u9.c("faceDetectionOptionalModuleLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(60))));
    public static final u9.c f11378g0 = new u9.c("nlClassifierOptionalModuleLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(55))));
    public static final u9.c f11379h0 = new u9.c("nlClassifierClientLibraryLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(56))));
    public static final u9.c f11381i0 = new u9.c("accelerationAllowlistLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(57))));
    public static final u9.c f11383j0 = new u9.c("toxicityDetectionCreateEvent", vh.v2.h(kh.a2.o(h0.class, new e0(62))));
    public static final u9.c f11385k0 = new u9.c("toxicityDetectionLoadEvent", vh.v2.h(kh.a2.o(h0.class, new e0(63))));
    public static final u9.c f11387l0 = new u9.c("toxicityDetectionInferenceEvent", vh.v2.h(kh.a2.o(h0.class, new e0(64))));
    public static final u9.c m0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(65))));
    public static final u9.c f11390n0 = new u9.c("customImageLabelOptionalModuleLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(66))));
    public static final u9.c f11392o0 = new u9.c("codeScannerScanApiEvent", vh.v2.h(kh.a2.o(h0.class, new e0(67))));
    public static final u9.c f11394p0 = new u9.c("codeScannerOptionalModuleEvent", vh.v2.h(kh.a2.o(h0.class, new e0(68))));
    public static final u9.c f11396q0 = new u9.c("onDeviceExplicitContentCreateLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(70))));
    public static final u9.c f11398r0 = new u9.c("onDeviceExplicitContentLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(71))));
    public static final u9.c f11400s0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(72))));
    public static final u9.c f11402t0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(73))));
    public static final u9.c f11404u0 = new u9.c("onDeviceSelfieFaceCreateLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(74))));
    public static final u9.c f11405v0 = new u9.c("onDeviceSelfieFaceLoadLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(75))));
    public static final u9.c f11407w0 = new u9.c("onDeviceSelfieFaceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(76))));
    public static final u9.c f11409x0 = new u9.c("aggregatedOnDeviceSelfieFaceLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(77))));
    public static final u9.c f11411y0 = new u9.c("smartReplyOptionalModuleLogEvent", vh.v2.h(kh.a2.o(h0.class, new e0(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        v7 v7Var = (v7) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f11369b, v7Var.f11669a);
        eVar.e(f11371c, v7Var.f11670b);
        eVar.e(d, null);
        eVar.e(e, v7Var.f11671c);
        eVar.e(f11375f, null);
        eVar.e(f11377g, null);
        eVar.e(h, null);
        eVar.e(f11380i, null);
        eVar.e(f11382j, null);
        eVar.e(f11384k, null);
        eVar.e(f11386l, null);
        eVar.e(f11388m, null);
        eVar.e(f11389n, null);
        eVar.e(f11391o, null);
        eVar.e(f11393p, null);
        eVar.e(f11395q, v7Var.d);
        eVar.e(f11397r, v7Var.e);
        eVar.e(f11399s, null);
        eVar.e(f11401t, null);
        eVar.e(f11403u, null);
        eVar.e(v, null);
        eVar.e(f11406w, null);
        eVar.e(f11408x, null);
        eVar.e(f11410y, null);
        eVar.e(f11412z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, v7Var.f11672f);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f11368a0, null);
        eVar.e(f11370b0, null);
        eVar.e(f11372c0, null);
        eVar.e(f11373d0, null);
        eVar.e(f11374e0, null);
        eVar.e(f11376f0, null);
        eVar.e(f11378g0, null);
        eVar.e(f11379h0, null);
        eVar.e(f11381i0, null);
        eVar.e(f11383j0, null);
        eVar.e(f11385k0, null);
        eVar.e(f11387l0, null);
        eVar.e(m0, null);
        eVar.e(f11390n0, null);
        eVar.e(f11392o0, null);
        eVar.e(f11394p0, null);
        eVar.e(f11396q0, null);
        eVar.e(f11398r0, null);
        eVar.e(f11400s0, null);
        eVar.e(f11402t0, null);
        eVar.e(f11404u0, null);
        eVar.e(f11405v0, null);
        eVar.e(f11407w0, null);
        eVar.e(f11409x0, null);
        eVar.e(f11411y0, null);
    }
}
