package l7;
public final class g5 implements s9.d {
    public static final g5 f14588a = new Object();
    public static final s9.c f14591b = new s9.c("systemInfo", u3.c.h(j7.l1.q(w.class, new s(1))));
    public static final s9.c f14594c = new s9.c("eventName", u3.c.h(j7.l1.q(w.class, new s(2))));
    public static final s9.c d = new s9.c("isThickClient", u3.c.h(j7.l1.q(w.class, new s(37))));
    public static final s9.c f14599e = new s9.c("clientType", u3.c.h(j7.l1.q(w.class, new s(61))));
    public static final s9.c f14602f = new s9.c("modelDownloadLogEvent", u3.c.h(j7.l1.q(w.class, new s(3))));
    public static final s9.c f14605g = new s9.c("customModelLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(20))));
    public static final s9.c h = new s9.c("customModelInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(4))));
    public static final s9.c f14610i = new s9.c("customModelCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(29))));
    public static final s9.c f14613j = new s9.c("onDeviceFaceDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(5))));
    public static final s9.c f14616k = new s9.c("onDeviceFaceLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(59))));
    public static final s9.c f14619l = new s9.c("onDeviceTextDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(6))));
    public static final s9.c f14621m = new s9.c("onDeviceTextDetectionLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(79))));
    public static final s9.c f14623n = new s9.c("onDeviceBarcodeDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(7))));
    public static final s9.c f14626o = new s9.c("onDeviceBarcodeLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(58))));
    public static final s9.c f14629p = new s9.c("onDeviceImageLabelCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(48))));
    public static final s9.c f14632q = new s9.c("onDeviceImageLabelLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(49))));
    public static final s9.c f14635r = new s9.c("onDeviceImageLabelDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(18))));
    public static final s9.c f14638s = new s9.c("onDeviceObjectCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(26))));
    public static final s9.c f14641t = new s9.c("onDeviceObjectLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(27))));
    public static final s9.c f14644u = new s9.c("onDeviceObjectInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(28))));
    public static final s9.c v = new s9.c("onDevicePoseDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(44))));
    public static final s9.c f14649w = new s9.c("onDeviceSegmentationLogEvent", u3.c.h(j7.l1.q(w.class, new s(45))));
    public static final s9.c f14652x = new s9.c("onDeviceSmartReplyLogEvent", u3.c.h(j7.l1.q(w.class, new s(19))));
    public static final s9.c f14655y = new s9.c("onDeviceLanguageIdentificationLogEvent", u3.c.h(j7.l1.q(w.class, new s(21))));
    public static final s9.c f14658z = new s9.c("onDeviceTranslationLogEvent", u3.c.h(j7.l1.q(w.class, new s(22))));
    public static final s9.c A = new s9.c("cloudFaceDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(8))));
    public static final s9.c B = new s9.c("cloudCropHintDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(9))));
    public static final s9.c C = new s9.c("cloudDocumentTextDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(10))));
    public static final s9.c D = new s9.c("cloudImagePropertiesDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(11))));
    public static final s9.c E = new s9.c("cloudImageLabelDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(12))));
    public static final s9.c F = new s9.c("cloudLandmarkDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(13))));
    public static final s9.c G = new s9.c("cloudLogoDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(14))));
    public static final s9.c H = new s9.c("cloudSafeSearchDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(15))));
    public static final s9.c I = new s9.c("cloudTextDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(16))));
    public static final s9.c J = new s9.c("cloudWebSearchDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(17))));
    public static final s9.c K = new s9.c("automlImageLabelingCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(23))));
    public static final s9.c L = new s9.c("automlImageLabelingLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(24))));
    public static final s9.c M = new s9.c("automlImageLabelingInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(25))));
    public static final s9.c N = new s9.c("isModelDownloadedLogEvent", u3.c.h(j7.l1.q(w.class, new s(39))));
    public static final s9.c O = new s9.c("deleteModelLogEvent", u3.c.h(j7.l1.q(w.class, new s(40))));
    public static final s9.c P = new s9.c("aggregatedAutomlImageLabelingInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(30))));
    public static final s9.c Q = new s9.c("aggregatedCustomModelInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(31))));
    public static final s9.c R = new s9.c("aggregatedOnDeviceFaceDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(32))));
    public static final s9.c S = new s9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(33))));
    public static final s9.c T = new s9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(34))));
    public static final s9.c U = new s9.c("aggregatedOnDeviceObjectInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(35))));
    public static final s9.c V = new s9.c("aggregatedOnDeviceTextDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(36))));
    public static final s9.c W = new s9.c("aggregatedOnDevicePoseDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(46))));
    public static final s9.c X = new s9.c("aggregatedOnDeviceSegmentationLogEvent", u3.c.h(j7.l1.q(w.class, new s(47))));
    public static final s9.c Y = new s9.c("pipelineAccelerationInferenceEvents", u3.c.h(j7.l1.q(w.class, new s(69))));
    public static final s9.c Z = new s9.c("remoteConfigLogEvent", u3.c.h(j7.l1.q(w.class, new s(42))));
    public static final s9.c f14589a0 = new s9.c("inputImageConstructionLogEvent", u3.c.h(j7.l1.q(w.class, new s(50))));
    public static final s9.c f14592b0 = new s9.c("leakedHandleEvent", u3.c.h(j7.l1.q(w.class, new s(51))));
    public static final s9.c f14595c0 = new s9.c("cameraSourceLogEvent", u3.c.h(j7.l1.q(w.class, new s(52))));
    public static final s9.c f14597d0 = new s9.c("imageLabelOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(53))));
    public static final s9.c f14600e0 = new s9.c("languageIdentificationOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(54))));
    public static final s9.c f14603f0 = new s9.c("faceDetectionOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(60))));
    public static final s9.c f14606g0 = new s9.c("documentDetectionOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(85))));
    public static final s9.c f14608h0 = new s9.c("documentCroppingOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(86))));
    public static final s9.c f14611i0 = new s9.c("documentEnhancementOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(87))));
    public static final s9.c f14614j0 = new s9.c("nlClassifierOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(55))));
    public static final s9.c f14617k0 = new s9.c("nlClassifierClientLibraryLogEvent", u3.c.h(j7.l1.q(w.class, new s(56))));
    public static final s9.c f14620l0 = new s9.c("accelerationAllowlistLogEvent", u3.c.h(j7.l1.q(w.class, new s(57))));
    public static final s9.c m0 = new s9.c("toxicityDetectionCreateEvent", u3.c.h(j7.l1.q(w.class, new s(62))));
    public static final s9.c f14624n0 = new s9.c("toxicityDetectionLoadEvent", u3.c.h(j7.l1.q(w.class, new s(63))));
    public static final s9.c f14627o0 = new s9.c("toxicityDetectionInferenceEvent", u3.c.h(j7.l1.q(w.class, new s(64))));
    public static final s9.c f14630p0 = new s9.c("barcodeDetectionOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(65))));
    public static final s9.c f14633q0 = new s9.c("customImageLabelOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(66))));
    public static final s9.c f14636r0 = new s9.c("codeScannerScanApiEvent", u3.c.h(j7.l1.q(w.class, new s(67))));
    public static final s9.c f14639s0 = new s9.c("codeScannerOptionalModuleEvent", u3.c.h(j7.l1.q(w.class, new s(68))));
    public static final s9.c f14642t0 = new s9.c("onDeviceExplicitContentCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(70))));
    public static final s9.c f14645u0 = new s9.c("onDeviceExplicitContentLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(71))));
    public static final s9.c f14647v0 = new s9.c("onDeviceExplicitContentInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(72))));
    public static final s9.c f14650w0 = new s9.c("aggregatedOnDeviceExplicitContentLogEvent", u3.c.h(j7.l1.q(w.class, new s(73))));
    public static final s9.c f14653x0 = new s9.c("onDeviceFaceMeshCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(74))));
    public static final s9.c f14656y0 = new s9.c("onDeviceFaceMeshLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(75))));
    public static final s9.c f14659z0 = new s9.c("onDeviceFaceMeshLogEvent", u3.c.h(j7.l1.q(w.class, new s(76))));
    public static final s9.c A0 = new s9.c("aggregatedOnDeviceFaceMeshLogEvent", u3.c.h(j7.l1.q(w.class, new s(77))));
    public static final s9.c B0 = new s9.c("smartReplyOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(78))));
    public static final s9.c C0 = new s9.c("textDetectionOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(80))));
    public static final s9.c D0 = new s9.c("onDeviceImageQualityAnalysisCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(81))));
    public static final s9.c E0 = new s9.c("onDeviceImageQualityAnalysisLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(82))));
    public static final s9.c F0 = new s9.c("onDeviceImageQualityAnalysisLogEvent", u3.c.h(j7.l1.q(w.class, new s(83))));
    public static final s9.c G0 = new s9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", u3.c.h(j7.l1.q(w.class, new s(84))));
    public static final s9.c H0 = new s9.c("imageQualityAnalysisOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(88))));
    public static final s9.c I0 = new s9.c("imageCaptioningOptionalModuleLogEvent", u3.c.h(j7.l1.q(w.class, new s(89))));
    public static final s9.c J0 = new s9.c("onDeviceImageCaptioningCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(90))));
    public static final s9.c K0 = new s9.c("onDeviceImageCaptioningLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(91))));
    public static final s9.c L0 = new s9.c("onDeviceImageCaptioningInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(92))));
    public static final s9.c M0 = new s9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", u3.c.h(j7.l1.q(w.class, new s(93))));
    public static final s9.c N0 = new s9.c("onDeviceDocumentDetectionCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(94))));
    public static final s9.c O0 = new s9.c("onDeviceDocumentDetectionLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(95))));
    public static final s9.c P0 = new s9.c("onDeviceDocumentDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(96))));
    public static final s9.c Q0 = new s9.c("aggregatedOnDeviceDocumentDetectionLogEvent", u3.c.h(j7.l1.q(w.class, new s(97))));
    public static final s9.c R0 = new s9.c("onDeviceDocumentCroppingCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(98))));
    public static final s9.c S0 = new s9.c("onDeviceDocumentCroppingLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(99))));
    public static final s9.c T0 = new s9.c("onDeviceDocumentCroppingLogEvent", u3.c.h(j7.l1.q(w.class, new s(100))));
    public static final s9.c U0 = new s9.c("aggregatedOnDeviceDocumentCroppingLogEvent", u3.c.h(j7.l1.q(w.class, new s(101))));
    public static final s9.c V0 = new s9.c("onDeviceDocumentEnhancementCreateLogEvent", u3.c.h(j7.l1.q(w.class, new s(102))));
    public static final s9.c W0 = new s9.c("onDeviceDocumentEnhancementLoadLogEvent", u3.c.h(j7.l1.q(w.class, new s(103))));
    public static final s9.c X0 = j7.l1.s(104, s9.c.a("onDeviceDocumentEnhancementLogEvent"));
    public static final s9.c Y0 = j7.l1.s(105, s9.c.a("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    public static final s9.c Z0 = j7.l1.s(106, s9.c.a("scannerAutoZoomEvent"));
    public static final s9.c f14590a1 = j7.l1.s(107, s9.c.a("lowLightAutoExposureComputationEvent"));
    public static final s9.c f14593b1 = j7.l1.s(108, s9.c.a("lowLightFrameProcessEvent"));
    public static final s9.c f14596c1 = j7.l1.s(109, s9.c.a("lowLightSceneDetectionEvent"));
    public static final s9.c f14598d1 = j7.l1.s(110, s9.c.a("onDeviceStainRemovalLogEvent"));
    public static final s9.c f14601e1 = j7.l1.s(111, s9.c.a("aggregatedOnDeviceStainRemovalLogEvent"));
    public static final s9.c f14604f1 = j7.l1.s(112, s9.c.a("stainRemovalOptionalModuleLogEvent"));
    public static final s9.c f14607g1 = j7.l1.s(113, s9.c.a("onDeviceShadowRemovalLogEvent"));
    public static final s9.c f14609h1 = j7.l1.s(114, s9.c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
    public static final s9.c f14612i1 = j7.l1.s(115, s9.c.a("shadowRemovalOptionalModuleLogEvent"));
    public static final s9.c f14615j1 = j7.l1.s(116, s9.c.a("onDeviceDigitalInkSegmentationLogEvent"));
    public static final s9.c f14618k1 = j7.l1.s(117, s9.c.a("onDeviceDocumentScannerStartLogEvent"));
    public static final s9.c l1 = j7.l1.s(118, s9.c.a("onDeviceDocumentScannerFinishLogEvent"));
    public static final s9.c f14622m1 = j7.l1.s(119, s9.c.a("onDeviceDocumentScannerUiStartLogEvent"));
    public static final s9.c f14625n1 = j7.l1.s(120, s9.c.a("onDeviceDocumentScannerUiFinishLogEvent"));
    public static final s9.c f14628o1 = j7.l1.s(121, s9.c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
    public static final s9.c f14631p1 = j7.l1.s(122, s9.c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    public static final s9.c f14634q1 = j7.l1.s(123, s9.c.a("onDeviceDocumentScannerUiCreateLogEvent"));
    public static final s9.c f14637r1 = j7.l1.s(124, s9.c.a("onDeviceSubjectSegmentationCreateLogEvent"));
    public static final s9.c f14640s1 = j7.l1.s(125, s9.c.a("onDeviceSubjectSegmentationLoadLogEvent"));
    public static final s9.c f14643t1 = j7.l1.s(126, s9.c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
    public static final s9.c f14646u1 = j7.l1.s(127, s9.c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    public static final s9.c f14648v1 = j7.l1.s(128, s9.c.a("subjectSegmentationOptionalModuleLogEvent"));
    public static final s9.c f14651w1 = j7.l1.s(129, s9.c.a("documentScannerUiModuleScreenViewEvent"));
    public static final s9.c f14654x1 = j7.l1.s(130, s9.c.a("documentScannerUiModuleScreenClickEvent"));
    public static final s9.c f14657y1 = j7.l1.s(131, s9.c.a("documentScannerUiModuleScreenErrorEvent"));

    @Override
    public final void a(Object obj, Object obj2) {
        ib ibVar = (ib) obj;
        s9.e eVar = (s9.e) obj2;
        eVar.e(f14591b, ibVar.f14831a);
        eVar.e(f14594c, ibVar.f14832b);
        eVar.e(d, null);
        eVar.e(f14599e, ibVar.f14833c);
        eVar.e(f14602f, null);
        eVar.e(f14605g, null);
        eVar.e(h, null);
        eVar.e(f14610i, null);
        eVar.e(f14613j, null);
        eVar.e(f14616k, null);
        eVar.e(f14619l, null);
        eVar.e(f14621m, null);
        eVar.e(f14623n, null);
        eVar.e(f14626o, null);
        eVar.e(f14629p, null);
        eVar.e(f14632q, null);
        eVar.e(f14635r, null);
        eVar.e(f14638s, null);
        eVar.e(f14641t, null);
        eVar.e(f14644u, null);
        eVar.e(v, null);
        eVar.e(f14649w, null);
        eVar.e(f14652x, null);
        eVar.e(f14655y, null);
        eVar.e(f14658z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f14589a0, null);
        eVar.e(f14592b0, null);
        eVar.e(f14595c0, null);
        eVar.e(f14597d0, null);
        eVar.e(f14600e0, null);
        eVar.e(f14603f0, null);
        eVar.e(f14606g0, null);
        eVar.e(f14608h0, null);
        eVar.e(f14611i0, null);
        eVar.e(f14614j0, null);
        eVar.e(f14617k0, null);
        eVar.e(f14620l0, null);
        eVar.e(m0, null);
        eVar.e(f14624n0, null);
        eVar.e(f14627o0, null);
        eVar.e(f14630p0, null);
        eVar.e(f14633q0, null);
        eVar.e(f14636r0, null);
        eVar.e(f14639s0, null);
        eVar.e(f14642t0, null);
        eVar.e(f14645u0, null);
        eVar.e(f14647v0, null);
        eVar.e(f14650w0, null);
        eVar.e(f14653x0, null);
        eVar.e(f14656y0, null);
        eVar.e(f14659z0, null);
        eVar.e(A0, null);
        eVar.e(B0, null);
        eVar.e(C0, null);
        eVar.e(D0, null);
        eVar.e(E0, null);
        eVar.e(F0, null);
        eVar.e(G0, null);
        eVar.e(H0, null);
        eVar.e(I0, null);
        eVar.e(J0, null);
        eVar.e(K0, null);
        eVar.e(L0, null);
        eVar.e(M0, null);
        eVar.e(N0, null);
        eVar.e(O0, null);
        eVar.e(P0, null);
        eVar.e(Q0, null);
        eVar.e(R0, null);
        eVar.e(S0, null);
        eVar.e(T0, null);
        eVar.e(U0, null);
        eVar.e(V0, null);
        eVar.e(W0, null);
        eVar.e(X0, null);
        eVar.e(Y0, null);
        eVar.e(Z0, null);
        eVar.e(f14590a1, null);
        eVar.e(f14593b1, null);
        eVar.e(f14596c1, null);
        eVar.e(f14598d1, null);
        eVar.e(f14601e1, null);
        eVar.e(f14604f1, null);
        eVar.e(f14607g1, null);
        eVar.e(f14609h1, null);
        eVar.e(f14612i1, null);
        eVar.e(f14615j1, null);
        eVar.e(f14618k1, null);
        eVar.e(l1, null);
        eVar.e(f14622m1, null);
        eVar.e(f14625n1, null);
        eVar.e(f14628o1, null);
        eVar.e(f14631p1, null);
        eVar.e(f14634q1, null);
        eVar.e(f14637r1, ibVar.d);
        eVar.e(f14640s1, ibVar.f14834e);
        eVar.e(f14643t1, ibVar.f14835f);
        eVar.e(f14646u1, ibVar.f14836g);
        eVar.e(f14648v1, null);
        eVar.e(f14651w1, null);
        eVar.e(f14654x1, null);
        eVar.e(f14657y1, null);
    }
}
