package j7;
public final class a4 implements s9.d {
    public static final a4 f10905a = new Object();
    public static final s9.c f10907b = new s9.c("systemInfo", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(1))));
    public static final s9.c f10909c = new s9.c("eventName", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(2))));
    public static final s9.c d = new s9.c("isThickClient", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(37))));
    public static final s9.c f10912e = new s9.c("clientType", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(61))));
    public static final s9.c f10914f = new s9.c("modelDownloadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(3))));
    public static final s9.c f10916g = new s9.c("customModelLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(20))));
    public static final s9.c h = new s9.c("customModelInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(4))));
    public static final s9.c f10919i = new s9.c("customModelCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(29))));
    public static final s9.c f10921j = new s9.c("onDeviceFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(5))));
    public static final s9.c f10923k = new s9.c("onDeviceFaceLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(59))));
    public static final s9.c f10925l = new s9.c("onDeviceTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(6))));
    public static final s9.c f10927m = new s9.c("onDeviceTextDetectionLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(79))));
    public static final s9.c f10928n = new s9.c("onDeviceBarcodeDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(7))));
    public static final s9.c f10930o = new s9.c("onDeviceBarcodeLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(58))));
    public static final s9.c f10932p = new s9.c("onDeviceImageLabelCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(48))));
    public static final s9.c f10934q = new s9.c("onDeviceImageLabelLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(49))));
    public static final s9.c f10936r = new s9.c("onDeviceImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(18))));
    public static final s9.c f10938s = new s9.c("onDeviceObjectCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(26))));
    public static final s9.c f10940t = new s9.c("onDeviceObjectLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(27))));
    public static final s9.c f10942u = new s9.c("onDeviceObjectInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(28))));
    public static final s9.c v = new s9.c("onDevicePoseDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(44))));
    public static final s9.c f10945w = new s9.c("onDeviceSegmentationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(45))));
    public static final s9.c f10947x = new s9.c("onDeviceSmartReplyLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(19))));
    public static final s9.c f10949y = new s9.c("onDeviceLanguageIdentificationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(21))));
    public static final s9.c f10951z = new s9.c("onDeviceTranslationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(22))));
    public static final s9.c A = new s9.c("cloudFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(8))));
    public static final s9.c B = new s9.c("cloudCropHintDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(9))));
    public static final s9.c C = new s9.c("cloudDocumentTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(10))));
    public static final s9.c D = new s9.c("cloudImagePropertiesDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(11))));
    public static final s9.c E = new s9.c("cloudImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(12))));
    public static final s9.c F = new s9.c("cloudLandmarkDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(13))));
    public static final s9.c G = new s9.c("cloudLogoDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(14))));
    public static final s9.c H = new s9.c("cloudSafeSearchDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(15))));
    public static final s9.c I = new s9.c("cloudTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(16))));
    public static final s9.c J = new s9.c("cloudWebSearchDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(17))));
    public static final s9.c K = new s9.c("automlImageLabelingCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(23))));
    public static final s9.c L = new s9.c("automlImageLabelingLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(24))));
    public static final s9.c M = new s9.c("automlImageLabelingInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(25))));
    public static final s9.c N = new s9.c("isModelDownloadedLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(39))));
    public static final s9.c O = new s9.c("deleteModelLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(40))));
    public static final s9.c P = new s9.c("aggregatedAutomlImageLabelingInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(30))));
    public static final s9.c Q = new s9.c("aggregatedCustomModelInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(31))));
    public static final s9.c R = new s9.c("aggregatedOnDeviceFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(32))));
    public static final s9.c S = new s9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(33))));
    public static final s9.c T = new s9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(34))));
    public static final s9.c U = new s9.c("aggregatedOnDeviceObjectInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(35))));
    public static final s9.c V = new s9.c("aggregatedOnDeviceTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(36))));
    public static final s9.c W = new s9.c("aggregatedOnDevicePoseDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(46))));
    public static final s9.c X = new s9.c("aggregatedOnDeviceSegmentationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(47))));
    public static final s9.c Y = new s9.c("pipelineAccelerationInferenceEvents", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(69))));
    public static final s9.c Z = new s9.c("remoteConfigLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(42))));
    public static final s9.c f10906a0 = new s9.c("inputImageConstructionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(50))));
    public static final s9.c f10908b0 = new s9.c("leakedHandleEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(51))));
    public static final s9.c f10910c0 = new s9.c("cameraSourceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(52))));
    public static final s9.c f10911d0 = new s9.c("imageLabelOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(53))));
    public static final s9.c f10913e0 = new s9.c("languageIdentificationOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(54))));
    public static final s9.c f10915f0 = new s9.c("faceDetectionOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(60))));
    public static final s9.c f10917g0 = new s9.c("nlClassifierOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(55))));
    public static final s9.c f10918h0 = new s9.c("nlClassifierClientLibraryLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(56))));
    public static final s9.c f10920i0 = new s9.c("accelerationAllowlistLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(57))));
    public static final s9.c f10922j0 = new s9.c("toxicityDetectionCreateEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(62))));
    public static final s9.c f10924k0 = new s9.c("toxicityDetectionLoadEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(63))));
    public static final s9.c f10926l0 = new s9.c("toxicityDetectionInferenceEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(64))));
    public static final s9.c m0 = new s9.c("barcodeDetectionOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(65))));
    public static final s9.c f10929n0 = new s9.c("customImageLabelOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(66))));
    public static final s9.c f10931o0 = new s9.c("codeScannerScanApiEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(67))));
    public static final s9.c f10933p0 = new s9.c("codeScannerOptionalModuleEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(68))));
    public static final s9.c f10935q0 = new s9.c("onDeviceExplicitContentCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(70))));
    public static final s9.c f10937r0 = new s9.c("onDeviceExplicitContentLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(71))));
    public static final s9.c f10939s0 = new s9.c("onDeviceExplicitContentInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(72))));
    public static final s9.c f10941t0 = new s9.c("aggregatedOnDeviceExplicitContentLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(73))));
    public static final s9.c f10943u0 = new s9.c("onDeviceSelfieFaceCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(74))));
    public static final s9.c f10944v0 = new s9.c("onDeviceSelfieFaceLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(75))));
    public static final s9.c f10946w0 = new s9.c("onDeviceSelfieFaceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(76))));
    public static final s9.c f10948x0 = new s9.c("aggregatedOnDeviceSelfieFaceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(77))));
    public static final s9.c f10950y0 = new s9.c("smartReplyOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.r(h0.class, new e0(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        v7 v7Var = (v7) obj;
        s9.e eVar = (s9.e) obj2;
        eVar.e(f10907b, v7Var.f11230a);
        eVar.e(f10909c, v7Var.f11231b);
        eVar.e(d, null);
        eVar.e(f10912e, v7Var.f11232c);
        eVar.e(f10914f, null);
        eVar.e(f10916g, null);
        eVar.e(h, null);
        eVar.e(f10919i, null);
        eVar.e(f10921j, null);
        eVar.e(f10923k, null);
        eVar.e(f10925l, null);
        eVar.e(f10927m, null);
        eVar.e(f10928n, null);
        eVar.e(f10930o, null);
        eVar.e(f10932p, null);
        eVar.e(f10934q, v7Var.d);
        eVar.e(f10936r, v7Var.f11233e);
        eVar.e(f10938s, null);
        eVar.e(f10940t, null);
        eVar.e(f10942u, null);
        eVar.e(v, null);
        eVar.e(f10945w, null);
        eVar.e(f10947x, null);
        eVar.e(f10949y, null);
        eVar.e(f10951z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, v7Var.f11234f);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f10906a0, null);
        eVar.e(f10908b0, null);
        eVar.e(f10910c0, null);
        eVar.e(f10911d0, null);
        eVar.e(f10913e0, null);
        eVar.e(f10915f0, null);
        eVar.e(f10917g0, null);
        eVar.e(f10918h0, null);
        eVar.e(f10920i0, null);
        eVar.e(f10922j0, null);
        eVar.e(f10924k0, null);
        eVar.e(f10926l0, null);
        eVar.e(m0, null);
        eVar.e(f10929n0, null);
        eVar.e(f10931o0, null);
        eVar.e(f10933p0, null);
        eVar.e(f10935q0, null);
        eVar.e(f10937r0, null);
        eVar.e(f10939s0, null);
        eVar.e(f10941t0, null);
        eVar.e(f10943u0, null);
        eVar.e(f10944v0, null);
        eVar.e(f10946w0, null);
        eVar.e(f10948x0, null);
        eVar.e(f10950y0, null);
    }
}
