package j7;
public final class g5 implements q9.d {
    public static final g5 f13729a = new Object();
    public static final q9.c f13732b = new q9.c("systemInfo", ta.b.g(j3.r0.r(w.class, new s(1))));
    public static final q9.c f13735c = new q9.c("eventName", ta.b.g(j3.r0.r(w.class, new s(2))));
    public static final q9.c d = new q9.c("isThickClient", ta.b.g(j3.r0.r(w.class, new s(37))));
    public static final q9.c f13740e = new q9.c("clientType", ta.b.g(j3.r0.r(w.class, new s(61))));
    public static final q9.c f13743f = new q9.c("modelDownloadLogEvent", ta.b.g(j3.r0.r(w.class, new s(3))));
    public static final q9.c f13746g = new q9.c("customModelLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(20))));
    public static final q9.c h = new q9.c("customModelInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(4))));
    public static final q9.c f13751i = new q9.c("customModelCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(29))));
    public static final q9.c f13754j = new q9.c("onDeviceFaceDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(5))));
    public static final q9.c f13757k = new q9.c("onDeviceFaceLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(59))));
    public static final q9.c f13760l = new q9.c("onDeviceTextDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(6))));
    public static final q9.c f13762m = new q9.c("onDeviceTextDetectionLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(79))));
    public static final q9.c f13764n = new q9.c("onDeviceBarcodeDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(7))));
    public static final q9.c f13767o = new q9.c("onDeviceBarcodeLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(58))));
    public static final q9.c f13770p = new q9.c("onDeviceImageLabelCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(48))));
    public static final q9.c f13773q = new q9.c("onDeviceImageLabelLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(49))));
    public static final q9.c f13776r = new q9.c("onDeviceImageLabelDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(18))));
    public static final q9.c f13779s = new q9.c("onDeviceObjectCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(26))));
    public static final q9.c f13782t = new q9.c("onDeviceObjectLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(27))));
    public static final q9.c f13785u = new q9.c("onDeviceObjectInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(28))));
    public static final q9.c v = new q9.c("onDevicePoseDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(44))));
    public static final q9.c f13790w = new q9.c("onDeviceSegmentationLogEvent", ta.b.g(j3.r0.r(w.class, new s(45))));
    public static final q9.c f13793x = new q9.c("onDeviceSmartReplyLogEvent", ta.b.g(j3.r0.r(w.class, new s(19))));
    public static final q9.c f13796y = new q9.c("onDeviceLanguageIdentificationLogEvent", ta.b.g(j3.r0.r(w.class, new s(21))));
    public static final q9.c f13799z = new q9.c("onDeviceTranslationLogEvent", ta.b.g(j3.r0.r(w.class, new s(22))));
    public static final q9.c A = new q9.c("cloudFaceDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(8))));
    public static final q9.c B = new q9.c("cloudCropHintDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(9))));
    public static final q9.c C = new q9.c("cloudDocumentTextDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(10))));
    public static final q9.c D = new q9.c("cloudImagePropertiesDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(11))));
    public static final q9.c E = new q9.c("cloudImageLabelDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(12))));
    public static final q9.c F = new q9.c("cloudLandmarkDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(13))));
    public static final q9.c G = new q9.c("cloudLogoDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(14))));
    public static final q9.c H = new q9.c("cloudSafeSearchDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(15))));
    public static final q9.c I = new q9.c("cloudTextDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(16))));
    public static final q9.c J = new q9.c("cloudWebSearchDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(17))));
    public static final q9.c K = new q9.c("automlImageLabelingCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(23))));
    public static final q9.c L = new q9.c("automlImageLabelingLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(24))));
    public static final q9.c M = new q9.c("automlImageLabelingInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(25))));
    public static final q9.c N = new q9.c("isModelDownloadedLogEvent", ta.b.g(j3.r0.r(w.class, new s(39))));
    public static final q9.c O = new q9.c("deleteModelLogEvent", ta.b.g(j3.r0.r(w.class, new s(40))));
    public static final q9.c P = new q9.c("aggregatedAutomlImageLabelingInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(30))));
    public static final q9.c Q = new q9.c("aggregatedCustomModelInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(31))));
    public static final q9.c R = new q9.c("aggregatedOnDeviceFaceDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(32))));
    public static final q9.c S = new q9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(33))));
    public static final q9.c T = new q9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(34))));
    public static final q9.c U = new q9.c("aggregatedOnDeviceObjectInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(35))));
    public static final q9.c V = new q9.c("aggregatedOnDeviceTextDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(36))));
    public static final q9.c W = new q9.c("aggregatedOnDevicePoseDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(46))));
    public static final q9.c X = new q9.c("aggregatedOnDeviceSegmentationLogEvent", ta.b.g(j3.r0.r(w.class, new s(47))));
    public static final q9.c Y = new q9.c("pipelineAccelerationInferenceEvents", ta.b.g(j3.r0.r(w.class, new s(69))));
    public static final q9.c Z = new q9.c("remoteConfigLogEvent", ta.b.g(j3.r0.r(w.class, new s(42))));
    public static final q9.c f13730a0 = new q9.c("inputImageConstructionLogEvent", ta.b.g(j3.r0.r(w.class, new s(50))));
    public static final q9.c f13733b0 = new q9.c("leakedHandleEvent", ta.b.g(j3.r0.r(w.class, new s(51))));
    public static final q9.c f13736c0 = new q9.c("cameraSourceLogEvent", ta.b.g(j3.r0.r(w.class, new s(52))));
    public static final q9.c f13738d0 = new q9.c("imageLabelOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(53))));
    public static final q9.c f13741e0 = new q9.c("languageIdentificationOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(54))));
    public static final q9.c f13744f0 = new q9.c("faceDetectionOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(60))));
    public static final q9.c f13747g0 = new q9.c("documentDetectionOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(85))));
    public static final q9.c f13749h0 = new q9.c("documentCroppingOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(86))));
    public static final q9.c f13752i0 = new q9.c("documentEnhancementOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(87))));
    public static final q9.c f13755j0 = new q9.c("nlClassifierOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(55))));
    public static final q9.c f13758k0 = new q9.c("nlClassifierClientLibraryLogEvent", ta.b.g(j3.r0.r(w.class, new s(56))));
    public static final q9.c f13761l0 = new q9.c("accelerationAllowlistLogEvent", ta.b.g(j3.r0.r(w.class, new s(57))));
    public static final q9.c m0 = new q9.c("toxicityDetectionCreateEvent", ta.b.g(j3.r0.r(w.class, new s(62))));
    public static final q9.c f13765n0 = new q9.c("toxicityDetectionLoadEvent", ta.b.g(j3.r0.r(w.class, new s(63))));
    public static final q9.c f13768o0 = new q9.c("toxicityDetectionInferenceEvent", ta.b.g(j3.r0.r(w.class, new s(64))));
    public static final q9.c f13771p0 = new q9.c("barcodeDetectionOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(65))));
    public static final q9.c f13774q0 = new q9.c("customImageLabelOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(66))));
    public static final q9.c f13777r0 = new q9.c("codeScannerScanApiEvent", ta.b.g(j3.r0.r(w.class, new s(67))));
    public static final q9.c f13780s0 = new q9.c("codeScannerOptionalModuleEvent", ta.b.g(j3.r0.r(w.class, new s(68))));
    public static final q9.c f13783t0 = new q9.c("onDeviceExplicitContentCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(70))));
    public static final q9.c f13786u0 = new q9.c("onDeviceExplicitContentLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(71))));
    public static final q9.c f13788v0 = new q9.c("onDeviceExplicitContentInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(72))));
    public static final q9.c f13791w0 = new q9.c("aggregatedOnDeviceExplicitContentLogEvent", ta.b.g(j3.r0.r(w.class, new s(73))));
    public static final q9.c f13794x0 = new q9.c("onDeviceFaceMeshCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(74))));
    public static final q9.c f13797y0 = new q9.c("onDeviceFaceMeshLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(75))));
    public static final q9.c f13800z0 = new q9.c("onDeviceFaceMeshLogEvent", ta.b.g(j3.r0.r(w.class, new s(76))));
    public static final q9.c A0 = new q9.c("aggregatedOnDeviceFaceMeshLogEvent", ta.b.g(j3.r0.r(w.class, new s(77))));
    public static final q9.c B0 = new q9.c("smartReplyOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(78))));
    public static final q9.c C0 = new q9.c("textDetectionOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(80))));
    public static final q9.c D0 = new q9.c("onDeviceImageQualityAnalysisCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(81))));
    public static final q9.c E0 = new q9.c("onDeviceImageQualityAnalysisLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(82))));
    public static final q9.c F0 = new q9.c("onDeviceImageQualityAnalysisLogEvent", ta.b.g(j3.r0.r(w.class, new s(83))));
    public static final q9.c G0 = new q9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", ta.b.g(j3.r0.r(w.class, new s(84))));
    public static final q9.c H0 = new q9.c("imageQualityAnalysisOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(88))));
    public static final q9.c I0 = new q9.c("imageCaptioningOptionalModuleLogEvent", ta.b.g(j3.r0.r(w.class, new s(89))));
    public static final q9.c J0 = new q9.c("onDeviceImageCaptioningCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(90))));
    public static final q9.c K0 = new q9.c("onDeviceImageCaptioningLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(91))));
    public static final q9.c L0 = new q9.c("onDeviceImageCaptioningInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(92))));
    public static final q9.c M0 = new q9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", ta.b.g(j3.r0.r(w.class, new s(93))));
    public static final q9.c N0 = new q9.c("onDeviceDocumentDetectionCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(94))));
    public static final q9.c O0 = new q9.c("onDeviceDocumentDetectionLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(95))));
    public static final q9.c P0 = new q9.c("onDeviceDocumentDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(96))));
    public static final q9.c Q0 = new q9.c("aggregatedOnDeviceDocumentDetectionLogEvent", ta.b.g(j3.r0.r(w.class, new s(97))));
    public static final q9.c R0 = new q9.c("onDeviceDocumentCroppingCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(98))));
    public static final q9.c S0 = new q9.c("onDeviceDocumentCroppingLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(99))));
    public static final q9.c T0 = new q9.c("onDeviceDocumentCroppingLogEvent", ta.b.g(j3.r0.r(w.class, new s(100))));
    public static final q9.c U0 = new q9.c("aggregatedOnDeviceDocumentCroppingLogEvent", ta.b.g(j3.r0.r(w.class, new s(101))));
    public static final q9.c V0 = new q9.c("onDeviceDocumentEnhancementCreateLogEvent", ta.b.g(j3.r0.r(w.class, new s(102))));
    public static final q9.c W0 = new q9.c("onDeviceDocumentEnhancementLoadLogEvent", ta.b.g(j3.r0.r(w.class, new s(103))));
    public static final q9.c X0 = j3.r0.t(104, q9.c.a("onDeviceDocumentEnhancementLogEvent"));
    public static final q9.c Y0 = j3.r0.t(105, q9.c.a("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    public static final q9.c Z0 = j3.r0.t(106, q9.c.a("scannerAutoZoomEvent"));
    public static final q9.c f13731a1 = j3.r0.t(107, q9.c.a("lowLightAutoExposureComputationEvent"));
    public static final q9.c f13734b1 = j3.r0.t(108, q9.c.a("lowLightFrameProcessEvent"));
    public static final q9.c f13737c1 = j3.r0.t(109, q9.c.a("lowLightSceneDetectionEvent"));
    public static final q9.c f13739d1 = j3.r0.t(110, q9.c.a("onDeviceStainRemovalLogEvent"));
    public static final q9.c f13742e1 = j3.r0.t(111, q9.c.a("aggregatedOnDeviceStainRemovalLogEvent"));
    public static final q9.c f13745f1 = j3.r0.t(112, q9.c.a("stainRemovalOptionalModuleLogEvent"));
    public static final q9.c f13748g1 = j3.r0.t(113, q9.c.a("onDeviceShadowRemovalLogEvent"));
    public static final q9.c f13750h1 = j3.r0.t(114, q9.c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
    public static final q9.c f13753i1 = j3.r0.t(115, q9.c.a("shadowRemovalOptionalModuleLogEvent"));
    public static final q9.c f13756j1 = j3.r0.t(116, q9.c.a("onDeviceDigitalInkSegmentationLogEvent"));
    public static final q9.c f13759k1 = j3.r0.t(117, q9.c.a("onDeviceDocumentScannerStartLogEvent"));
    public static final q9.c l1 = j3.r0.t(118, q9.c.a("onDeviceDocumentScannerFinishLogEvent"));
    public static final q9.c f13763m1 = j3.r0.t(119, q9.c.a("onDeviceDocumentScannerUiStartLogEvent"));
    public static final q9.c f13766n1 = j3.r0.t(120, q9.c.a("onDeviceDocumentScannerUiFinishLogEvent"));
    public static final q9.c f13769o1 = j3.r0.t(121, q9.c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
    public static final q9.c f13772p1 = j3.r0.t(122, q9.c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    public static final q9.c f13775q1 = j3.r0.t(123, q9.c.a("onDeviceDocumentScannerUiCreateLogEvent"));
    public static final q9.c f13778r1 = j3.r0.t(124, q9.c.a("onDeviceSubjectSegmentationCreateLogEvent"));
    public static final q9.c f13781s1 = j3.r0.t(125, q9.c.a("onDeviceSubjectSegmentationLoadLogEvent"));
    public static final q9.c f13784t1 = j3.r0.t(126, q9.c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
    public static final q9.c f13787u1 = j3.r0.t(127, q9.c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    public static final q9.c f13789v1 = j3.r0.t(128, q9.c.a("subjectSegmentationOptionalModuleLogEvent"));
    public static final q9.c f13792w1 = j3.r0.t(129, q9.c.a("documentScannerUiModuleScreenViewEvent"));
    public static final q9.c f13795x1 = j3.r0.t(130, q9.c.a("documentScannerUiModuleScreenClickEvent"));
    public static final q9.c f13798y1 = j3.r0.t(131, q9.c.a("documentScannerUiModuleScreenErrorEvent"));

    @Override
    public final void a(Object obj, Object obj2) {
        ib ibVar = (ib) obj;
        q9.e eVar = (q9.e) obj2;
        eVar.g(f13732b, ibVar.f13972a);
        eVar.g(f13735c, ibVar.f13973b);
        eVar.g(d, null);
        eVar.g(f13740e, ibVar.f13974c);
        eVar.g(f13743f, null);
        eVar.g(f13746g, null);
        eVar.g(h, null);
        eVar.g(f13751i, null);
        eVar.g(f13754j, null);
        eVar.g(f13757k, null);
        eVar.g(f13760l, null);
        eVar.g(f13762m, null);
        eVar.g(f13764n, null);
        eVar.g(f13767o, null);
        eVar.g(f13770p, null);
        eVar.g(f13773q, null);
        eVar.g(f13776r, null);
        eVar.g(f13779s, null);
        eVar.g(f13782t, null);
        eVar.g(f13785u, null);
        eVar.g(v, null);
        eVar.g(f13790w, null);
        eVar.g(f13793x, null);
        eVar.g(f13796y, null);
        eVar.g(f13799z, null);
        eVar.g(A, null);
        eVar.g(B, null);
        eVar.g(C, null);
        eVar.g(D, null);
        eVar.g(E, null);
        eVar.g(F, null);
        eVar.g(G, null);
        eVar.g(H, null);
        eVar.g(I, null);
        eVar.g(J, null);
        eVar.g(K, null);
        eVar.g(L, null);
        eVar.g(M, null);
        eVar.g(N, null);
        eVar.g(O, null);
        eVar.g(P, null);
        eVar.g(Q, null);
        eVar.g(R, null);
        eVar.g(S, null);
        eVar.g(T, null);
        eVar.g(U, null);
        eVar.g(V, null);
        eVar.g(W, null);
        eVar.g(X, null);
        eVar.g(Y, null);
        eVar.g(Z, null);
        eVar.g(f13730a0, null);
        eVar.g(f13733b0, null);
        eVar.g(f13736c0, null);
        eVar.g(f13738d0, null);
        eVar.g(f13741e0, null);
        eVar.g(f13744f0, null);
        eVar.g(f13747g0, null);
        eVar.g(f13749h0, null);
        eVar.g(f13752i0, null);
        eVar.g(f13755j0, null);
        eVar.g(f13758k0, null);
        eVar.g(f13761l0, null);
        eVar.g(m0, null);
        eVar.g(f13765n0, null);
        eVar.g(f13768o0, null);
        eVar.g(f13771p0, null);
        eVar.g(f13774q0, null);
        eVar.g(f13777r0, null);
        eVar.g(f13780s0, null);
        eVar.g(f13783t0, null);
        eVar.g(f13786u0, null);
        eVar.g(f13788v0, null);
        eVar.g(f13791w0, null);
        eVar.g(f13794x0, null);
        eVar.g(f13797y0, null);
        eVar.g(f13800z0, null);
        eVar.g(A0, null);
        eVar.g(B0, null);
        eVar.g(C0, null);
        eVar.g(D0, null);
        eVar.g(E0, null);
        eVar.g(F0, null);
        eVar.g(G0, null);
        eVar.g(H0, null);
        eVar.g(I0, null);
        eVar.g(J0, null);
        eVar.g(K0, null);
        eVar.g(L0, null);
        eVar.g(M0, null);
        eVar.g(N0, null);
        eVar.g(O0, null);
        eVar.g(P0, null);
        eVar.g(Q0, null);
        eVar.g(R0, null);
        eVar.g(S0, null);
        eVar.g(T0, null);
        eVar.g(U0, null);
        eVar.g(V0, null);
        eVar.g(W0, null);
        eVar.g(X0, null);
        eVar.g(Y0, null);
        eVar.g(Z0, null);
        eVar.g(f13731a1, null);
        eVar.g(f13734b1, null);
        eVar.g(f13737c1, null);
        eVar.g(f13739d1, null);
        eVar.g(f13742e1, null);
        eVar.g(f13745f1, null);
        eVar.g(f13748g1, null);
        eVar.g(f13750h1, null);
        eVar.g(f13753i1, null);
        eVar.g(f13756j1, null);
        eVar.g(f13759k1, null);
        eVar.g(l1, null);
        eVar.g(f13763m1, null);
        eVar.g(f13766n1, null);
        eVar.g(f13769o1, null);
        eVar.g(f13772p1, null);
        eVar.g(f13775q1, null);
        eVar.g(f13778r1, ibVar.d);
        eVar.g(f13781s1, ibVar.f13975e);
        eVar.g(f13784t1, ibVar.f13976f);
        eVar.g(f13787u1, ibVar.f13977g);
        eVar.g(f13789v1, null);
        eVar.g(f13792w1, null);
        eVar.g(f13795x1, null);
        eVar.g(f13798y1, null);
    }
}
