package j7;
public final class y2 implements u9.d {
    public static final y2 f9811a = new Object();
    public static final u9.c f9813b = new u9.c("systemInfo", w.c.h(e2.c.n(i.class, new e(1))));
    public static final u9.c f9815c = new u9.c("eventName", w.c.h(e2.c.n(i.class, new e(2))));
    public static final u9.c d = new u9.c("isThickClient", w.c.h(e2.c.n(i.class, new e(37))));
    public static final u9.c f9818e = new u9.c("clientType", w.c.h(e2.c.n(i.class, new e(61))));
    public static final u9.c f9820f = new u9.c("modelDownloadLogEvent", w.c.h(e2.c.n(i.class, new e(3))));
    public static final u9.c f9822g = new u9.c("customModelLoadLogEvent", w.c.h(e2.c.n(i.class, new e(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", w.c.h(e2.c.n(i.class, new e(4))));
    public static final u9.c f9825i = new u9.c("customModelCreateLogEvent", w.c.h(e2.c.n(i.class, new e(29))));
    public static final u9.c f9827j = new u9.c("onDeviceFaceDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(5))));
    public static final u9.c f9829k = new u9.c("onDeviceFaceLoadLogEvent", w.c.h(e2.c.n(i.class, new e(59))));
    public static final u9.c f9831l = new u9.c("onDeviceTextDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(6))));
    public static final u9.c f9833m = new u9.c("onDeviceTextDetectionLoadLogEvent", w.c.h(e2.c.n(i.class, new e(79))));
    public static final u9.c f9834n = new u9.c("onDeviceBarcodeDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(7))));
    public static final u9.c f9836o = new u9.c("onDeviceBarcodeLoadLogEvent", w.c.h(e2.c.n(i.class, new e(58))));
    public static final u9.c f9838p = new u9.c("onDeviceImageLabelCreateLogEvent", w.c.h(e2.c.n(i.class, new e(48))));
    public static final u9.c f9840q = new u9.c("onDeviceImageLabelLoadLogEvent", w.c.h(e2.c.n(i.class, new e(49))));
    public static final u9.c f9842r = new u9.c("onDeviceImageLabelDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(18))));
    public static final u9.c f9844s = new u9.c("onDeviceObjectCreateLogEvent", w.c.h(e2.c.n(i.class, new e(26))));
    public static final u9.c f9846t = new u9.c("onDeviceObjectLoadLogEvent", w.c.h(e2.c.n(i.class, new e(27))));
    public static final u9.c f9848u = new u9.c("onDeviceObjectInferenceLogEvent", w.c.h(e2.c.n(i.class, new e(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(44))));
    public static final u9.c f9851w = new u9.c("onDeviceSegmentationLogEvent", w.c.h(e2.c.n(i.class, new e(45))));
    public static final u9.c f9853x = new u9.c("onDeviceSmartReplyLogEvent", w.c.h(e2.c.n(i.class, new e(19))));
    public static final u9.c f9855y = new u9.c("onDeviceLanguageIdentificationLogEvent", w.c.h(e2.c.n(i.class, new e(21))));
    public static final u9.c f9857z = new u9.c("onDeviceTranslationLogEvent", w.c.h(e2.c.n(i.class, new e(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", w.c.h(e2.c.n(i.class, new e(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", w.c.h(e2.c.n(i.class, new e(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", w.c.h(e2.c.n(i.class, new e(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", w.c.h(e2.c.n(i.class, new e(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", w.c.h(e2.c.n(i.class, new e(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", w.c.h(e2.c.n(i.class, new e(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", w.c.h(e2.c.n(i.class, new e(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", w.c.h(e2.c.n(i.class, new e(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", w.c.h(e2.c.n(i.class, new e(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", w.c.h(e2.c.n(i.class, new e(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", w.c.h(e2.c.n(i.class, new e(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", w.c.h(e2.c.n(i.class, new e(42))));
    public static final u9.c f9812a0 = new u9.c("inputImageConstructionLogEvent", w.c.h(e2.c.n(i.class, new e(50))));
    public static final u9.c f9814b0 = new u9.c("leakedHandleEvent", w.c.h(e2.c.n(i.class, new e(51))));
    public static final u9.c f9816c0 = new u9.c("cameraSourceLogEvent", w.c.h(e2.c.n(i.class, new e(52))));
    public static final u9.c f9817d0 = new u9.c("imageLabelOptionalModuleLogEvent", w.c.h(e2.c.n(i.class, new e(53))));
    public static final u9.c f9819e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", w.c.h(e2.c.n(i.class, new e(54))));
    public static final u9.c f9821f0 = new u9.c("faceDetectionOptionalModuleLogEvent", w.c.h(e2.c.n(i.class, new e(60))));
    public static final u9.c f9823g0 = new u9.c("nlClassifierOptionalModuleLogEvent", w.c.h(e2.c.n(i.class, new e(55))));
    public static final u9.c f9824h0 = new u9.c("nlClassifierClientLibraryLogEvent", w.c.h(e2.c.n(i.class, new e(56))));
    public static final u9.c f9826i0 = new u9.c("accelerationAllowlistLogEvent", w.c.h(e2.c.n(i.class, new e(57))));
    public static final u9.c f9828j0 = new u9.c("toxicityDetectionCreateEvent", w.c.h(e2.c.n(i.class, new e(62))));
    public static final u9.c f9830k0 = new u9.c("toxicityDetectionLoadEvent", w.c.h(e2.c.n(i.class, new e(63))));
    public static final u9.c f9832l0 = new u9.c("toxicityDetectionInferenceEvent", w.c.h(e2.c.n(i.class, new e(64))));
    public static final u9.c m0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", w.c.h(e2.c.n(i.class, new e(65))));
    public static final u9.c f9835n0 = new u9.c("customImageLabelOptionalModuleLogEvent", w.c.h(e2.c.n(i.class, new e(66))));
    public static final u9.c f9837o0 = new u9.c("codeScannerScanApiEvent", w.c.h(e2.c.n(i.class, new e(67))));
    public static final u9.c f9839p0 = new u9.c("codeScannerOptionalModuleEvent", w.c.h(e2.c.n(i.class, new e(68))));
    public static final u9.c f9841q0 = new u9.c("onDeviceExplicitContentCreateLogEvent", w.c.h(e2.c.n(i.class, new e(70))));
    public static final u9.c f9843r0 = new u9.c("onDeviceExplicitContentLoadLogEvent", w.c.h(e2.c.n(i.class, new e(71))));
    public static final u9.c f9845s0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", w.c.h(e2.c.n(i.class, new e(72))));
    public static final u9.c f9847t0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", w.c.h(e2.c.n(i.class, new e(73))));
    public static final u9.c f9849u0 = new u9.c("onDeviceSelfieFaceCreateLogEvent", w.c.h(e2.c.n(i.class, new e(74))));
    public static final u9.c f9850v0 = new u9.c("onDeviceSelfieFaceLoadLogEvent", w.c.h(e2.c.n(i.class, new e(75))));
    public static final u9.c f9852w0 = new u9.c("onDeviceSelfieFaceLogEvent", w.c.h(e2.c.n(i.class, new e(76))));
    public static final u9.c f9854x0 = new u9.c("aggregatedOnDeviceSelfieFaceLogEvent", w.c.h(e2.c.n(i.class, new e(77))));
    public static final u9.c f9856y0 = new u9.c("smartReplyOptionalModuleLogEvent", w.c.h(e2.c.n(i.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        n6 n6Var = (n6) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f9813b, n6Var.f9712a);
        eVar.e(f9815c, n6Var.f9713b);
        eVar.e(d, null);
        eVar.e(f9818e, n6Var.f9714c);
        eVar.e(f9820f, null);
        eVar.e(f9822g, null);
        eVar.e(h, null);
        eVar.e(f9825i, null);
        eVar.e(f9827j, null);
        eVar.e(f9829k, null);
        eVar.e(f9831l, null);
        eVar.e(f9833m, null);
        eVar.e(f9834n, null);
        eVar.e(f9836o, null);
        eVar.e(f9838p, null);
        eVar.e(f9840q, null);
        eVar.e(f9842r, null);
        eVar.e(f9844s, null);
        eVar.e(f9846t, null);
        eVar.e(f9848u, null);
        eVar.e(v, null);
        eVar.e(f9851w, null);
        eVar.e(f9853x, null);
        eVar.e(f9855y, n6Var.d);
        eVar.e(f9857z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f9812a0, null);
        eVar.e(f9814b0, null);
        eVar.e(f9816c0, null);
        eVar.e(f9817d0, null);
        eVar.e(f9819e0, null);
        eVar.e(f9821f0, null);
        eVar.e(f9823g0, null);
        eVar.e(f9824h0, null);
        eVar.e(f9826i0, null);
        eVar.e(f9828j0, null);
        eVar.e(f9830k0, null);
        eVar.e(f9832l0, null);
        eVar.e(m0, null);
        eVar.e(f9835n0, null);
        eVar.e(f9837o0, null);
        eVar.e(f9839p0, null);
        eVar.e(f9841q0, null);
        eVar.e(f9843r0, null);
        eVar.e(f9845s0, null);
        eVar.e(f9847t0, null);
        eVar.e(f9849u0, null);
        eVar.e(f9850v0, null);
        eVar.e(f9852w0, null);
        eVar.e(f9854x0, null);
        eVar.e(f9856y0, null);
    }
}
