package j7;
public final class y2 implements u9.d {
    public static final y2 f9187a = new Object();
    public static final u9.c f9189b = new u9.c("systemInfo", vh.v2.h(e2.c.n(i.class, new e(1))));
    public static final u9.c f9191c = new u9.c("eventName", vh.v2.h(e2.c.n(i.class, new e(2))));
    public static final u9.c d = new u9.c("isThickClient", vh.v2.h(e2.c.n(i.class, new e(37))));
    public static final u9.c e = new u9.c("clientType", vh.v2.h(e2.c.n(i.class, new e(61))));
    public static final u9.c f9195f = new u9.c("modelDownloadLogEvent", vh.v2.h(e2.c.n(i.class, new e(3))));
    public static final u9.c f9197g = new u9.c("customModelLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", vh.v2.h(e2.c.n(i.class, new e(4))));
    public static final u9.c f9200i = new u9.c("customModelCreateLogEvent", vh.v2.h(e2.c.n(i.class, new e(29))));
    public static final u9.c f9202j = new u9.c("onDeviceFaceDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(5))));
    public static final u9.c f9204k = new u9.c("onDeviceFaceLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(59))));
    public static final u9.c f9206l = new u9.c("onDeviceTextDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(6))));
    public static final u9.c f9208m = new u9.c("onDeviceTextDetectionLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(79))));
    public static final u9.c f9209n = new u9.c("onDeviceBarcodeDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(7))));
    public static final u9.c f9211o = new u9.c("onDeviceBarcodeLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(58))));
    public static final u9.c f9213p = new u9.c("onDeviceImageLabelCreateLogEvent", vh.v2.h(e2.c.n(i.class, new e(48))));
    public static final u9.c f9215q = new u9.c("onDeviceImageLabelLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(49))));
    public static final u9.c f9217r = new u9.c("onDeviceImageLabelDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(18))));
    public static final u9.c f9219s = new u9.c("onDeviceObjectCreateLogEvent", vh.v2.h(e2.c.n(i.class, new e(26))));
    public static final u9.c f9221t = new u9.c("onDeviceObjectLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(27))));
    public static final u9.c f9223u = new u9.c("onDeviceObjectInferenceLogEvent", vh.v2.h(e2.c.n(i.class, new e(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(44))));
    public static final u9.c f9226w = new u9.c("onDeviceSegmentationLogEvent", vh.v2.h(e2.c.n(i.class, new e(45))));
    public static final u9.c f9228x = new u9.c("onDeviceSmartReplyLogEvent", vh.v2.h(e2.c.n(i.class, new e(19))));
    public static final u9.c f9230y = new u9.c("onDeviceLanguageIdentificationLogEvent", vh.v2.h(e2.c.n(i.class, new e(21))));
    public static final u9.c f9232z = new u9.c("onDeviceTranslationLogEvent", vh.v2.h(e2.c.n(i.class, new e(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", vh.v2.h(e2.c.n(i.class, new e(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", vh.v2.h(e2.c.n(i.class, new e(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", vh.v2.h(e2.c.n(i.class, new e(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", vh.v2.h(e2.c.n(i.class, new e(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", vh.v2.h(e2.c.n(i.class, new e(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", vh.v2.h(e2.c.n(i.class, new e(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", vh.v2.h(e2.c.n(i.class, new e(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", vh.v2.h(e2.c.n(i.class, new e(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", vh.v2.h(e2.c.n(i.class, new e(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", vh.v2.h(e2.c.n(i.class, new e(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", vh.v2.h(e2.c.n(i.class, new e(42))));
    public static final u9.c f9188a0 = new u9.c("inputImageConstructionLogEvent", vh.v2.h(e2.c.n(i.class, new e(50))));
    public static final u9.c f9190b0 = new u9.c("leakedHandleEvent", vh.v2.h(e2.c.n(i.class, new e(51))));
    public static final u9.c f9192c0 = new u9.c("cameraSourceLogEvent", vh.v2.h(e2.c.n(i.class, new e(52))));
    public static final u9.c f9193d0 = new u9.c("imageLabelOptionalModuleLogEvent", vh.v2.h(e2.c.n(i.class, new e(53))));
    public static final u9.c f9194e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", vh.v2.h(e2.c.n(i.class, new e(54))));
    public static final u9.c f9196f0 = new u9.c("faceDetectionOptionalModuleLogEvent", vh.v2.h(e2.c.n(i.class, new e(60))));
    public static final u9.c f9198g0 = new u9.c("nlClassifierOptionalModuleLogEvent", vh.v2.h(e2.c.n(i.class, new e(55))));
    public static final u9.c f9199h0 = new u9.c("nlClassifierClientLibraryLogEvent", vh.v2.h(e2.c.n(i.class, new e(56))));
    public static final u9.c f9201i0 = new u9.c("accelerationAllowlistLogEvent", vh.v2.h(e2.c.n(i.class, new e(57))));
    public static final u9.c f9203j0 = new u9.c("toxicityDetectionCreateEvent", vh.v2.h(e2.c.n(i.class, new e(62))));
    public static final u9.c f9205k0 = new u9.c("toxicityDetectionLoadEvent", vh.v2.h(e2.c.n(i.class, new e(63))));
    public static final u9.c f9207l0 = new u9.c("toxicityDetectionInferenceEvent", vh.v2.h(e2.c.n(i.class, new e(64))));
    public static final u9.c m0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", vh.v2.h(e2.c.n(i.class, new e(65))));
    public static final u9.c f9210n0 = new u9.c("customImageLabelOptionalModuleLogEvent", vh.v2.h(e2.c.n(i.class, new e(66))));
    public static final u9.c f9212o0 = new u9.c("codeScannerScanApiEvent", vh.v2.h(e2.c.n(i.class, new e(67))));
    public static final u9.c f9214p0 = new u9.c("codeScannerOptionalModuleEvent", vh.v2.h(e2.c.n(i.class, new e(68))));
    public static final u9.c f9216q0 = new u9.c("onDeviceExplicitContentCreateLogEvent", vh.v2.h(e2.c.n(i.class, new e(70))));
    public static final u9.c f9218r0 = new u9.c("onDeviceExplicitContentLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(71))));
    public static final u9.c f9220s0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", vh.v2.h(e2.c.n(i.class, new e(72))));
    public static final u9.c f9222t0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", vh.v2.h(e2.c.n(i.class, new e(73))));
    public static final u9.c f9224u0 = new u9.c("onDeviceSelfieFaceCreateLogEvent", vh.v2.h(e2.c.n(i.class, new e(74))));
    public static final u9.c f9225v0 = new u9.c("onDeviceSelfieFaceLoadLogEvent", vh.v2.h(e2.c.n(i.class, new e(75))));
    public static final u9.c f9227w0 = new u9.c("onDeviceSelfieFaceLogEvent", vh.v2.h(e2.c.n(i.class, new e(76))));
    public static final u9.c f9229x0 = new u9.c("aggregatedOnDeviceSelfieFaceLogEvent", vh.v2.h(e2.c.n(i.class, new e(77))));
    public static final u9.c f9231y0 = new u9.c("smartReplyOptionalModuleLogEvent", vh.v2.h(e2.c.n(i.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        n6 n6Var = (n6) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f9189b, n6Var.f9093a);
        eVar.e(f9191c, n6Var.f9094b);
        eVar.e(d, null);
        eVar.e(e, n6Var.f9095c);
        eVar.e(f9195f, null);
        eVar.e(f9197g, null);
        eVar.e(h, null);
        eVar.e(f9200i, null);
        eVar.e(f9202j, null);
        eVar.e(f9204k, null);
        eVar.e(f9206l, null);
        eVar.e(f9208m, null);
        eVar.e(f9209n, null);
        eVar.e(f9211o, null);
        eVar.e(f9213p, null);
        eVar.e(f9215q, null);
        eVar.e(f9217r, null);
        eVar.e(f9219s, null);
        eVar.e(f9221t, null);
        eVar.e(f9223u, null);
        eVar.e(v, null);
        eVar.e(f9226w, null);
        eVar.e(f9228x, null);
        eVar.e(f9230y, n6Var.d);
        eVar.e(f9232z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f9188a0, null);
        eVar.e(f9190b0, null);
        eVar.e(f9192c0, null);
        eVar.e(f9193d0, null);
        eVar.e(f9194e0, null);
        eVar.e(f9196f0, null);
        eVar.e(f9198g0, null);
        eVar.e(f9199h0, null);
        eVar.e(f9201i0, null);
        eVar.e(f9203j0, null);
        eVar.e(f9205k0, null);
        eVar.e(f9207l0, null);
        eVar.e(m0, null);
        eVar.e(f9210n0, null);
        eVar.e(f9212o0, null);
        eVar.e(f9214p0, null);
        eVar.e(f9216q0, null);
        eVar.e(f9218r0, null);
        eVar.e(f9220s0, null);
        eVar.e(f9222t0, null);
        eVar.e(f9224u0, null);
        eVar.e(f9225v0, null);
        eVar.e(f9227w0, null);
        eVar.e(f9229x0, null);
        eVar.e(f9231y0, null);
    }
}
