package j7;
public final class y2 implements u9.d {
    public static final y2 f9169a = new Object();
    public static final u9.c f9171b = new u9.c("systemInfo", vh.w2.h(e2.c.n(i.class, new e(1))));
    public static final u9.c f9173c = new u9.c("eventName", vh.w2.h(e2.c.n(i.class, new e(2))));
    public static final u9.c d = new u9.c("isThickClient", vh.w2.h(e2.c.n(i.class, new e(37))));
    public static final u9.c e = new u9.c("clientType", vh.w2.h(e2.c.n(i.class, new e(61))));
    public static final u9.c f9177f = new u9.c("modelDownloadLogEvent", vh.w2.h(e2.c.n(i.class, new e(3))));
    public static final u9.c f9179g = new u9.c("customModelLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", vh.w2.h(e2.c.n(i.class, new e(4))));
    public static final u9.c f9182i = new u9.c("customModelCreateLogEvent", vh.w2.h(e2.c.n(i.class, new e(29))));
    public static final u9.c f9184j = new u9.c("onDeviceFaceDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(5))));
    public static final u9.c f9186k = new u9.c("onDeviceFaceLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(59))));
    public static final u9.c f9188l = new u9.c("onDeviceTextDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(6))));
    public static final u9.c f9190m = new u9.c("onDeviceTextDetectionLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(79))));
    public static final u9.c f9191n = new u9.c("onDeviceBarcodeDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(7))));
    public static final u9.c f9193o = new u9.c("onDeviceBarcodeLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(58))));
    public static final u9.c f9195p = new u9.c("onDeviceImageLabelCreateLogEvent", vh.w2.h(e2.c.n(i.class, new e(48))));
    public static final u9.c f9197q = new u9.c("onDeviceImageLabelLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(49))));
    public static final u9.c f9199r = new u9.c("onDeviceImageLabelDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(18))));
    public static final u9.c f9201s = new u9.c("onDeviceObjectCreateLogEvent", vh.w2.h(e2.c.n(i.class, new e(26))));
    public static final u9.c f9203t = new u9.c("onDeviceObjectLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(27))));
    public static final u9.c f9205u = new u9.c("onDeviceObjectInferenceLogEvent", vh.w2.h(e2.c.n(i.class, new e(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(44))));
    public static final u9.c f9208w = new u9.c("onDeviceSegmentationLogEvent", vh.w2.h(e2.c.n(i.class, new e(45))));
    public static final u9.c f9210x = new u9.c("onDeviceSmartReplyLogEvent", vh.w2.h(e2.c.n(i.class, new e(19))));
    public static final u9.c f9212y = new u9.c("onDeviceLanguageIdentificationLogEvent", vh.w2.h(e2.c.n(i.class, new e(21))));
    public static final u9.c f9214z = new u9.c("onDeviceTranslationLogEvent", vh.w2.h(e2.c.n(i.class, new e(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", vh.w2.h(e2.c.n(i.class, new e(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", vh.w2.h(e2.c.n(i.class, new e(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", vh.w2.h(e2.c.n(i.class, new e(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", vh.w2.h(e2.c.n(i.class, new e(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", vh.w2.h(e2.c.n(i.class, new e(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", vh.w2.h(e2.c.n(i.class, new e(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", vh.w2.h(e2.c.n(i.class, new e(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", vh.w2.h(e2.c.n(i.class, new e(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", vh.w2.h(e2.c.n(i.class, new e(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", vh.w2.h(e2.c.n(i.class, new e(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", vh.w2.h(e2.c.n(i.class, new e(42))));
    public static final u9.c f9170a0 = new u9.c("inputImageConstructionLogEvent", vh.w2.h(e2.c.n(i.class, new e(50))));
    public static final u9.c f9172b0 = new u9.c("leakedHandleEvent", vh.w2.h(e2.c.n(i.class, new e(51))));
    public static final u9.c f9174c0 = new u9.c("cameraSourceLogEvent", vh.w2.h(e2.c.n(i.class, new e(52))));
    public static final u9.c f9175d0 = new u9.c("imageLabelOptionalModuleLogEvent", vh.w2.h(e2.c.n(i.class, new e(53))));
    public static final u9.c f9176e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", vh.w2.h(e2.c.n(i.class, new e(54))));
    public static final u9.c f9178f0 = new u9.c("faceDetectionOptionalModuleLogEvent", vh.w2.h(e2.c.n(i.class, new e(60))));
    public static final u9.c f9180g0 = new u9.c("nlClassifierOptionalModuleLogEvent", vh.w2.h(e2.c.n(i.class, new e(55))));
    public static final u9.c f9181h0 = new u9.c("nlClassifierClientLibraryLogEvent", vh.w2.h(e2.c.n(i.class, new e(56))));
    public static final u9.c f9183i0 = new u9.c("accelerationAllowlistLogEvent", vh.w2.h(e2.c.n(i.class, new e(57))));
    public static final u9.c f9185j0 = new u9.c("toxicityDetectionCreateEvent", vh.w2.h(e2.c.n(i.class, new e(62))));
    public static final u9.c f9187k0 = new u9.c("toxicityDetectionLoadEvent", vh.w2.h(e2.c.n(i.class, new e(63))));
    public static final u9.c f9189l0 = new u9.c("toxicityDetectionInferenceEvent", vh.w2.h(e2.c.n(i.class, new e(64))));
    public static final u9.c m0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", vh.w2.h(e2.c.n(i.class, new e(65))));
    public static final u9.c f9192n0 = new u9.c("customImageLabelOptionalModuleLogEvent", vh.w2.h(e2.c.n(i.class, new e(66))));
    public static final u9.c f9194o0 = new u9.c("codeScannerScanApiEvent", vh.w2.h(e2.c.n(i.class, new e(67))));
    public static final u9.c f9196p0 = new u9.c("codeScannerOptionalModuleEvent", vh.w2.h(e2.c.n(i.class, new e(68))));
    public static final u9.c f9198q0 = new u9.c("onDeviceExplicitContentCreateLogEvent", vh.w2.h(e2.c.n(i.class, new e(70))));
    public static final u9.c f9200r0 = new u9.c("onDeviceExplicitContentLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(71))));
    public static final u9.c f9202s0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", vh.w2.h(e2.c.n(i.class, new e(72))));
    public static final u9.c f9204t0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", vh.w2.h(e2.c.n(i.class, new e(73))));
    public static final u9.c f9206u0 = new u9.c("onDeviceSelfieFaceCreateLogEvent", vh.w2.h(e2.c.n(i.class, new e(74))));
    public static final u9.c f9207v0 = new u9.c("onDeviceSelfieFaceLoadLogEvent", vh.w2.h(e2.c.n(i.class, new e(75))));
    public static final u9.c f9209w0 = new u9.c("onDeviceSelfieFaceLogEvent", vh.w2.h(e2.c.n(i.class, new e(76))));
    public static final u9.c f9211x0 = new u9.c("aggregatedOnDeviceSelfieFaceLogEvent", vh.w2.h(e2.c.n(i.class, new e(77))));
    public static final u9.c f9213y0 = new u9.c("smartReplyOptionalModuleLogEvent", vh.w2.h(e2.c.n(i.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        n6 n6Var = (n6) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f9171b, n6Var.f9075a);
        eVar.e(f9173c, n6Var.f9076b);
        eVar.e(d, null);
        eVar.e(e, n6Var.f9077c);
        eVar.e(f9177f, null);
        eVar.e(f9179g, null);
        eVar.e(h, null);
        eVar.e(f9182i, null);
        eVar.e(f9184j, null);
        eVar.e(f9186k, null);
        eVar.e(f9188l, null);
        eVar.e(f9190m, null);
        eVar.e(f9191n, null);
        eVar.e(f9193o, null);
        eVar.e(f9195p, null);
        eVar.e(f9197q, null);
        eVar.e(f9199r, null);
        eVar.e(f9201s, null);
        eVar.e(f9203t, null);
        eVar.e(f9205u, null);
        eVar.e(v, null);
        eVar.e(f9208w, null);
        eVar.e(f9210x, null);
        eVar.e(f9212y, n6Var.d);
        eVar.e(f9214z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f9170a0, null);
        eVar.e(f9172b0, null);
        eVar.e(f9174c0, null);
        eVar.e(f9175d0, null);
        eVar.e(f9176e0, null);
        eVar.e(f9178f0, null);
        eVar.e(f9180g0, null);
        eVar.e(f9181h0, null);
        eVar.e(f9183i0, null);
        eVar.e(f9185j0, null);
        eVar.e(f9187k0, null);
        eVar.e(f9189l0, null);
        eVar.e(m0, null);
        eVar.e(f9192n0, null);
        eVar.e(f9194o0, null);
        eVar.e(f9196p0, null);
        eVar.e(f9198q0, null);
        eVar.e(f9200r0, null);
        eVar.e(f9202s0, null);
        eVar.e(f9204t0, null);
        eVar.e(f9206u0, null);
        eVar.e(f9207v0, null);
        eVar.e(f9209w0, null);
        eVar.e(f9211x0, null);
        eVar.e(f9213y0, null);
    }
}
