package v7;
public final class v2 implements ia.d {
    public static final v2 f47599a = new Object();
    public static final ia.c f47601b = new ia.c("systemInfo", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(1))));
    public static final ia.c f47603c = new ia.c("eventName", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(2))));
    public static final ia.c d = new ia.c("isThickClient", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(37))));
    public static final ia.c f47606e = new ia.c("clientType", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(61))));
    public static final ia.c f47608f = new ia.c("modelDownloadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(3))));
    public static final ia.c f47610g = new ia.c("customModelLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(4))));
    public static final ia.c f47613i = new ia.c("customModelCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(29))));
    public static final ia.c f47615j = new ia.c("onDeviceFaceDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(5))));
    public static final ia.c f47617k = new ia.c("onDeviceFaceLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(59))));
    public static final ia.c f47619l = new ia.c("onDeviceTextDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(6))));
    public static final ia.c f47621m = new ia.c("onDeviceTextDetectionLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(79))));
    public static final ia.c f47622n = new ia.c("onDeviceBarcodeDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(7))));
    public static final ia.c f47624o = new ia.c("onDeviceBarcodeLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(58))));
    public static final ia.c f47626p = new ia.c("onDeviceImageLabelCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(48))));
    public static final ia.c f47628q = new ia.c("onDeviceImageLabelLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(49))));
    public static final ia.c f47630r = new ia.c("onDeviceImageLabelDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(18))));
    public static final ia.c f47632s = new ia.c("onDeviceObjectCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(26))));
    public static final ia.c f47634t = new ia.c("onDeviceObjectLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(27))));
    public static final ia.c f47636u = new ia.c("onDeviceObjectInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(44))));
    public static final ia.c f47639w = new ia.c("onDeviceSegmentationLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(45))));
    public static final ia.c f47641x = new ia.c("onDeviceSmartReplyLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(19))));
    public static final ia.c f47643y = new ia.c("onDeviceLanguageIdentificationLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(21))));
    public static final ia.c f47645z = new ia.c("onDeviceTranslationLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(42))));
    public static final ia.c f47600a0 = new ia.c("inputImageConstructionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(50))));
    public static final ia.c f47602b0 = new ia.c("leakedHandleEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(51))));
    public static final ia.c f47604c0 = new ia.c("cameraSourceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(52))));
    public static final ia.c f47605d0 = new ia.c("imageLabelOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(53))));
    public static final ia.c f47607e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(54))));
    public static final ia.c f47609f0 = new ia.c("faceDetectionOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(60))));
    public static final ia.c f47611g0 = new ia.c("nlClassifierOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(55))));
    public static final ia.c f47612h0 = new ia.c("nlClassifierClientLibraryLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(56))));
    public static final ia.c f47614i0 = new ia.c("accelerationAllowlistLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(57))));
    public static final ia.c f47616j0 = new ia.c("toxicityDetectionCreateEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(62))));
    public static final ia.c f47618k0 = new ia.c("toxicityDetectionLoadEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(63))));
    public static final ia.c f47620l0 = new ia.c("toxicityDetectionInferenceEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(64))));
    public static final ia.c m0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(65))));
    public static final ia.c f47623n0 = new ia.c("customImageLabelOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(66))));
    public static final ia.c f47625o0 = new ia.c("codeScannerScanApiEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(67))));
    public static final ia.c f47627p0 = new ia.c("codeScannerOptionalModuleEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(68))));
    public static final ia.c f47629q0 = new ia.c("onDeviceExplicitContentCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(70))));
    public static final ia.c f47631r0 = new ia.c("onDeviceExplicitContentLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(71))));
    public static final ia.c f47633s0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(72))));
    public static final ia.c f47635t0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(73))));
    public static final ia.c f47637u0 = new ia.c("onDeviceSelfieFaceCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(74))));
    public static final ia.c f47638v0 = new ia.c("onDeviceSelfieFaceLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(75))));
    public static final ia.c f47640w0 = new ia.c("onDeviceSelfieFaceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(76))));
    public static final ia.c f47642x0 = new ia.c("aggregatedOnDeviceSelfieFaceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(77))));
    public static final ia.c f47644y0 = new ia.c("smartReplyOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        k6 k6Var = (k6) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f47601b, k6Var.f47505a);
        eVar.a(f47603c, k6Var.f47506b);
        eVar.a(d, null);
        eVar.a(f47606e, k6Var.f47507c);
        eVar.a(f47608f, null);
        eVar.a(f47610g, null);
        eVar.a(h, null);
        eVar.a(f47613i, null);
        eVar.a(f47615j, null);
        eVar.a(f47617k, null);
        eVar.a(f47619l, null);
        eVar.a(f47621m, null);
        eVar.a(f47622n, null);
        eVar.a(f47624o, null);
        eVar.a(f47626p, null);
        eVar.a(f47628q, null);
        eVar.a(f47630r, null);
        eVar.a(f47632s, null);
        eVar.a(f47634t, null);
        eVar.a(f47636u, null);
        eVar.a(v, null);
        eVar.a(f47639w, null);
        eVar.a(f47641x, null);
        eVar.a(f47643y, k6Var.d);
        eVar.a(f47645z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f47600a0, null);
        eVar.a(f47602b0, null);
        eVar.a(f47604c0, null);
        eVar.a(f47605d0, null);
        eVar.a(f47607e0, null);
        eVar.a(f47609f0, null);
        eVar.a(f47611g0, null);
        eVar.a(f47612h0, null);
        eVar.a(f47614i0, null);
        eVar.a(f47616j0, null);
        eVar.a(f47618k0, null);
        eVar.a(f47620l0, null);
        eVar.a(m0, null);
        eVar.a(f47623n0, null);
        eVar.a(f47625o0, null);
        eVar.a(f47627p0, null);
        eVar.a(f47629q0, null);
        eVar.a(f47631r0, null);
        eVar.a(f47633s0, null);
        eVar.a(f47635t0, null);
        eVar.a(f47637u0, null);
        eVar.a(f47638v0, null);
        eVar.a(f47640w0, null);
        eVar.a(f47642x0, null);
        eVar.a(f47644y0, null);
    }
}
