package v7;
public final class v2 implements ia.d {
    public static final v2 f43141a = new Object();
    public static final ia.c f43143b = new ia.c("systemInfo", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(1))));
    public static final ia.c f43145c = new ia.c("eventName", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(2))));
    public static final ia.c d = new ia.c("isThickClient", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(37))));
    public static final ia.c e = new ia.c("clientType", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(61))));
    public static final ia.c f43149f = new ia.c("modelDownloadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(3))));
    public static final ia.c f43151g = new ia.c("customModelLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(4))));
    public static final ia.c f43154i = new ia.c("customModelCreateLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(29))));
    public static final ia.c f43156j = new ia.c("onDeviceFaceDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(5))));
    public static final ia.c f43158k = new ia.c("onDeviceFaceLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(59))));
    public static final ia.c f43160l = new ia.c("onDeviceTextDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(6))));
    public static final ia.c f43162m = new ia.c("onDeviceTextDetectionLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(79))));
    public static final ia.c f43163n = new ia.c("onDeviceBarcodeDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(7))));
    public static final ia.c f43165o = new ia.c("onDeviceBarcodeLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(58))));
    public static final ia.c f43167p = new ia.c("onDeviceImageLabelCreateLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(48))));
    public static final ia.c f43169q = new ia.c("onDeviceImageLabelLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(49))));
    public static final ia.c f43171r = new ia.c("onDeviceImageLabelDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(18))));
    public static final ia.c f43173s = new ia.c("onDeviceObjectCreateLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(26))));
    public static final ia.c f43175t = new ia.c("onDeviceObjectLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(27))));
    public static final ia.c f43177u = new ia.c("onDeviceObjectInferenceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(44))));
    public static final ia.c f43180w = new ia.c("onDeviceSegmentationLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(45))));
    public static final ia.c f43182x = new ia.c("onDeviceSmartReplyLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(19))));
    public static final ia.c f43184y = new ia.c("onDeviceLanguageIdentificationLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(21))));
    public static final ia.c f43186z = new ia.c("onDeviceTranslationLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(42))));
    public static final ia.c f43142a0 = new ia.c("inputImageConstructionLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(50))));
    public static final ia.c f43144b0 = new ia.c("leakedHandleEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(51))));
    public static final ia.c f43146c0 = new ia.c("cameraSourceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(52))));
    public static final ia.c f43147d0 = new ia.c("imageLabelOptionalModuleLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(53))));
    public static final ia.c f43148e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(54))));
    public static final ia.c f43150f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(60))));
    public static final ia.c f43152g0 = new ia.c("nlClassifierOptionalModuleLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(55))));
    public static final ia.c f43153h0 = new ia.c("nlClassifierClientLibraryLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(56))));
    public static final ia.c f43155i0 = new ia.c("accelerationAllowlistLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(57))));
    public static final ia.c f43157j0 = new ia.c("toxicityDetectionCreateEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(62))));
    public static final ia.c f43159k0 = new ia.c("toxicityDetectionLoadEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(63))));
    public static final ia.c f43161l0 = new ia.c("toxicityDetectionInferenceEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(64))));
    public static final ia.c m0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(65))));
    public static final ia.c f43164n0 = new ia.c("customImageLabelOptionalModuleLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(66))));
    public static final ia.c f43166o0 = new ia.c("codeScannerScanApiEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(67))));
    public static final ia.c f43168p0 = new ia.c("codeScannerOptionalModuleEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(68))));
    public static final ia.c f43170q0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(70))));
    public static final ia.c f43172r0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(71))));
    public static final ia.c f43174s0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(72))));
    public static final ia.c f43176t0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(73))));
    public static final ia.c f43178u0 = new ia.c("onDeviceSelfieFaceCreateLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(74))));
    public static final ia.c f43179v0 = new ia.c("onDeviceSelfieFaceLoadLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(75))));
    public static final ia.c f43181w0 = new ia.c("onDeviceSelfieFaceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(76))));
    public static final ia.c f43183x0 = new ia.c("aggregatedOnDeviceSelfieFaceLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(77))));
    public static final ia.c f43185y0 = new ia.c("smartReplyOptionalModuleLogEvent", hc.b.p(org.telegram.ui.Cells.r6.k(h.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        k6 k6Var = (k6) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f43143b, k6Var.f43050a);
        eVar.a(f43145c, k6Var.f43051b);
        eVar.a(d, null);
        eVar.a(e, k6Var.f43052c);
        eVar.a(f43149f, null);
        eVar.a(f43151g, null);
        eVar.a(h, null);
        eVar.a(f43154i, null);
        eVar.a(f43156j, null);
        eVar.a(f43158k, null);
        eVar.a(f43160l, null);
        eVar.a(f43162m, null);
        eVar.a(f43163n, null);
        eVar.a(f43165o, null);
        eVar.a(f43167p, null);
        eVar.a(f43169q, null);
        eVar.a(f43171r, null);
        eVar.a(f43173s, null);
        eVar.a(f43175t, null);
        eVar.a(f43177u, null);
        eVar.a(v, null);
        eVar.a(f43180w, null);
        eVar.a(f43182x, null);
        eVar.a(f43184y, k6Var.d);
        eVar.a(f43186z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f43142a0, null);
        eVar.a(f43144b0, null);
        eVar.a(f43146c0, null);
        eVar.a(f43147d0, null);
        eVar.a(f43148e0, null);
        eVar.a(f43150f0, null);
        eVar.a(f43152g0, null);
        eVar.a(f43153h0, null);
        eVar.a(f43155i0, null);
        eVar.a(f43157j0, null);
        eVar.a(f43159k0, null);
        eVar.a(f43161l0, null);
        eVar.a(m0, null);
        eVar.a(f43164n0, null);
        eVar.a(f43166o0, null);
        eVar.a(f43168p0, null);
        eVar.a(f43170q0, null);
        eVar.a(f43172r0, null);
        eVar.a(f43174s0, null);
        eVar.a(f43176t0, null);
        eVar.a(f43178u0, null);
        eVar.a(f43179v0, null);
        eVar.a(f43181w0, null);
        eVar.a(f43183x0, null);
        eVar.a(f43185y0, null);
    }
}
