package v7;
public final class v2 implements ia.d {
    public static final v2 f47627a = new Object();
    public static final ia.c f47629b = new ia.c("systemInfo", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(1))));
    public static final ia.c f47631c = new ia.c("eventName", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(2))));
    public static final ia.c d = new ia.c("isThickClient", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(37))));
    public static final ia.c f47634e = new ia.c("clientType", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(61))));
    public static final ia.c f47636f = new ia.c("modelDownloadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(3))));
    public static final ia.c f47638g = new ia.c("customModelLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(4))));
    public static final ia.c f47641i = new ia.c("customModelCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(29))));
    public static final ia.c f47643j = new ia.c("onDeviceFaceDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(5))));
    public static final ia.c f47645k = new ia.c("onDeviceFaceLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(59))));
    public static final ia.c f47647l = new ia.c("onDeviceTextDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(6))));
    public static final ia.c f47649m = new ia.c("onDeviceTextDetectionLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(79))));
    public static final ia.c f47650n = new ia.c("onDeviceBarcodeDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(7))));
    public static final ia.c f47652o = new ia.c("onDeviceBarcodeLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(58))));
    public static final ia.c f47654p = new ia.c("onDeviceImageLabelCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(48))));
    public static final ia.c f47656q = new ia.c("onDeviceImageLabelLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(49))));
    public static final ia.c f47658r = new ia.c("onDeviceImageLabelDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(18))));
    public static final ia.c f47660s = new ia.c("onDeviceObjectCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(26))));
    public static final ia.c f47662t = new ia.c("onDeviceObjectLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(27))));
    public static final ia.c f47664u = new ia.c("onDeviceObjectInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(44))));
    public static final ia.c f47667w = new ia.c("onDeviceSegmentationLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(45))));
    public static final ia.c f47669x = new ia.c("onDeviceSmartReplyLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(19))));
    public static final ia.c f47671y = new ia.c("onDeviceLanguageIdentificationLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(21))));
    public static final ia.c f47673z = new ia.c("onDeviceTranslationLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(42))));
    public static final ia.c f47628a0 = new ia.c("inputImageConstructionLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(50))));
    public static final ia.c f47630b0 = new ia.c("leakedHandleEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(51))));
    public static final ia.c f47632c0 = new ia.c("cameraSourceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(52))));
    public static final ia.c f47633d0 = new ia.c("imageLabelOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(53))));
    public static final ia.c f47635e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(54))));
    public static final ia.c f47637f0 = new ia.c("faceDetectionOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(60))));
    public static final ia.c f47639g0 = new ia.c("nlClassifierOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(55))));
    public static final ia.c f47640h0 = new ia.c("nlClassifierClientLibraryLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(56))));
    public static final ia.c f47642i0 = new ia.c("accelerationAllowlistLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(57))));
    public static final ia.c f47644j0 = new ia.c("toxicityDetectionCreateEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(62))));
    public static final ia.c f47646k0 = new ia.c("toxicityDetectionLoadEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(63))));
    public static final ia.c f47648l0 = new ia.c("toxicityDetectionInferenceEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(64))));
    public static final ia.c m0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(65))));
    public static final ia.c f47651n0 = new ia.c("customImageLabelOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(66))));
    public static final ia.c f47653o0 = new ia.c("codeScannerScanApiEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(67))));
    public static final ia.c f47655p0 = new ia.c("codeScannerOptionalModuleEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(68))));
    public static final ia.c f47657q0 = new ia.c("onDeviceExplicitContentCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(70))));
    public static final ia.c f47659r0 = new ia.c("onDeviceExplicitContentLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(71))));
    public static final ia.c f47661s0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(72))));
    public static final ia.c f47663t0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(73))));
    public static final ia.c f47665u0 = new ia.c("onDeviceSelfieFaceCreateLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(74))));
    public static final ia.c f47666v0 = new ia.c("onDeviceSelfieFaceLoadLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(75))));
    public static final ia.c f47668w0 = new ia.c("onDeviceSelfieFaceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(76))));
    public static final ia.c f47670x0 = new ia.c("aggregatedOnDeviceSelfieFaceLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(77))));
    public static final ia.c f47672y0 = new ia.c("smartReplyOptionalModuleLogEvent", i2.g.n(org.telegram.ui.Cells.p6.k(h.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        k6 k6Var = (k6) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f47629b, k6Var.f47533a);
        eVar.a(f47631c, k6Var.f47534b);
        eVar.a(d, null);
        eVar.a(f47634e, k6Var.f47535c);
        eVar.a(f47636f, null);
        eVar.a(f47638g, null);
        eVar.a(h, null);
        eVar.a(f47641i, null);
        eVar.a(f47643j, null);
        eVar.a(f47645k, null);
        eVar.a(f47647l, null);
        eVar.a(f47649m, null);
        eVar.a(f47650n, null);
        eVar.a(f47652o, null);
        eVar.a(f47654p, null);
        eVar.a(f47656q, null);
        eVar.a(f47658r, null);
        eVar.a(f47660s, null);
        eVar.a(f47662t, null);
        eVar.a(f47664u, null);
        eVar.a(v, null);
        eVar.a(f47667w, null);
        eVar.a(f47669x, null);
        eVar.a(f47671y, k6Var.d);
        eVar.a(f47673z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f47628a0, null);
        eVar.a(f47630b0, null);
        eVar.a(f47632c0, null);
        eVar.a(f47633d0, null);
        eVar.a(f47635e0, null);
        eVar.a(f47637f0, null);
        eVar.a(f47639g0, null);
        eVar.a(f47640h0, null);
        eVar.a(f47642i0, null);
        eVar.a(f47644j0, null);
        eVar.a(f47646k0, null);
        eVar.a(f47648l0, null);
        eVar.a(m0, null);
        eVar.a(f47651n0, null);
        eVar.a(f47653o0, null);
        eVar.a(f47655p0, null);
        eVar.a(f47657q0, null);
        eVar.a(f47659r0, null);
        eVar.a(f47661s0, null);
        eVar.a(f47663t0, null);
        eVar.a(f47665u0, null);
        eVar.a(f47666v0, null);
        eVar.a(f47668w0, null);
        eVar.a(f47670x0, null);
        eVar.a(f47672y0, null);
    }
}
