package v7;
public final class w2 implements ia.d {
    public static final w2 f44381a = new Object();
    public static final ia.c f44383b = new ia.c("systemInfo", hg.k0.m(t8.b.l(h.class, new e(1))));
    public static final ia.c f44385c = new ia.c("eventName", hg.k0.m(t8.b.l(h.class, new e(2))));
    public static final ia.c d = new ia.c("isThickClient", hg.k0.m(t8.b.l(h.class, new e(37))));
    public static final ia.c e = new ia.c("clientType", hg.k0.m(t8.b.l(h.class, new e(61))));
    public static final ia.c f44389f = new ia.c("modelDownloadLogEvent", hg.k0.m(t8.b.l(h.class, new e(3))));
    public static final ia.c f44391g = new ia.c("customModelLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hg.k0.m(t8.b.l(h.class, new e(4))));
    public static final ia.c f44394i = new ia.c("customModelCreateLogEvent", hg.k0.m(t8.b.l(h.class, new e(29))));
    public static final ia.c f44396j = new ia.c("onDeviceFaceDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(5))));
    public static final ia.c f44398k = new ia.c("onDeviceFaceLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(59))));
    public static final ia.c f44400l = new ia.c("onDeviceTextDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(6))));
    public static final ia.c f44402m = new ia.c("onDeviceTextDetectionLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(79))));
    public static final ia.c f44403n = new ia.c("onDeviceBarcodeDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(7))));
    public static final ia.c f44405o = new ia.c("onDeviceBarcodeLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(58))));
    public static final ia.c f44407p = new ia.c("onDeviceImageLabelCreateLogEvent", hg.k0.m(t8.b.l(h.class, new e(48))));
    public static final ia.c f44409q = new ia.c("onDeviceImageLabelLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(49))));
    public static final ia.c f44411r = new ia.c("onDeviceImageLabelDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(18))));
    public static final ia.c f44413s = new ia.c("onDeviceObjectCreateLogEvent", hg.k0.m(t8.b.l(h.class, new e(26))));
    public static final ia.c f44415t = new ia.c("onDeviceObjectLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(27))));
    public static final ia.c f44417u = new ia.c("onDeviceObjectInferenceLogEvent", hg.k0.m(t8.b.l(h.class, new e(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(44))));
    public static final ia.c f44420w = new ia.c("onDeviceSegmentationLogEvent", hg.k0.m(t8.b.l(h.class, new e(45))));
    public static final ia.c f44422x = new ia.c("onDeviceSmartReplyLogEvent", hg.k0.m(t8.b.l(h.class, new e(19))));
    public static final ia.c f44424y = new ia.c("onDeviceLanguageIdentificationLogEvent", hg.k0.m(t8.b.l(h.class, new e(21))));
    public static final ia.c f44426z = new ia.c("onDeviceTranslationLogEvent", hg.k0.m(t8.b.l(h.class, new e(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hg.k0.m(t8.b.l(h.class, new e(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hg.k0.m(t8.b.l(h.class, new e(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hg.k0.m(t8.b.l(h.class, new e(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hg.k0.m(t8.b.l(h.class, new e(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hg.k0.m(t8.b.l(h.class, new e(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hg.k0.m(t8.b.l(h.class, new e(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hg.k0.m(t8.b.l(h.class, new e(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hg.k0.m(t8.b.l(h.class, new e(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hg.k0.m(t8.b.l(h.class, new e(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hg.k0.m(t8.b.l(h.class, new e(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hg.k0.m(t8.b.l(h.class, new e(42))));
    public static final ia.c f44382a0 = new ia.c("inputImageConstructionLogEvent", hg.k0.m(t8.b.l(h.class, new e(50))));
    public static final ia.c f44384b0 = new ia.c("leakedHandleEvent", hg.k0.m(t8.b.l(h.class, new e(51))));
    public static final ia.c f44386c0 = new ia.c("cameraSourceLogEvent", hg.k0.m(t8.b.l(h.class, new e(52))));
    public static final ia.c f44387d0 = new ia.c("imageLabelOptionalModuleLogEvent", hg.k0.m(t8.b.l(h.class, new e(53))));
    public static final ia.c f44388e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hg.k0.m(t8.b.l(h.class, new e(54))));
    public static final ia.c f44390f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hg.k0.m(t8.b.l(h.class, new e(60))));
    public static final ia.c f44392g0 = new ia.c("nlClassifierOptionalModuleLogEvent", hg.k0.m(t8.b.l(h.class, new e(55))));
    public static final ia.c f44393h0 = new ia.c("nlClassifierClientLibraryLogEvent", hg.k0.m(t8.b.l(h.class, new e(56))));
    public static final ia.c f44395i0 = new ia.c("accelerationAllowlistLogEvent", hg.k0.m(t8.b.l(h.class, new e(57))));
    public static final ia.c f44397j0 = new ia.c("toxicityDetectionCreateEvent", hg.k0.m(t8.b.l(h.class, new e(62))));
    public static final ia.c f44399k0 = new ia.c("toxicityDetectionLoadEvent", hg.k0.m(t8.b.l(h.class, new e(63))));
    public static final ia.c f44401l0 = new ia.c("toxicityDetectionInferenceEvent", hg.k0.m(t8.b.l(h.class, new e(64))));
    public static final ia.c m0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hg.k0.m(t8.b.l(h.class, new e(65))));
    public static final ia.c f44404n0 = new ia.c("customImageLabelOptionalModuleLogEvent", hg.k0.m(t8.b.l(h.class, new e(66))));
    public static final ia.c f44406o0 = new ia.c("codeScannerScanApiEvent", hg.k0.m(t8.b.l(h.class, new e(67))));
    public static final ia.c f44408p0 = new ia.c("codeScannerOptionalModuleEvent", hg.k0.m(t8.b.l(h.class, new e(68))));
    public static final ia.c f44410q0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hg.k0.m(t8.b.l(h.class, new e(70))));
    public static final ia.c f44412r0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(71))));
    public static final ia.c f44414s0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hg.k0.m(t8.b.l(h.class, new e(72))));
    public static final ia.c f44416t0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hg.k0.m(t8.b.l(h.class, new e(73))));
    public static final ia.c f44418u0 = new ia.c("onDeviceSelfieFaceCreateLogEvent", hg.k0.m(t8.b.l(h.class, new e(74))));
    public static final ia.c f44419v0 = new ia.c("onDeviceSelfieFaceLoadLogEvent", hg.k0.m(t8.b.l(h.class, new e(75))));
    public static final ia.c f44421w0 = new ia.c("onDeviceSelfieFaceLogEvent", hg.k0.m(t8.b.l(h.class, new e(76))));
    public static final ia.c f44423x0 = new ia.c("aggregatedOnDeviceSelfieFaceLogEvent", hg.k0.m(t8.b.l(h.class, new e(77))));
    public static final ia.c f44425y0 = new ia.c("smartReplyOptionalModuleLogEvent", hg.k0.m(t8.b.l(h.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        k6 k6Var = (k6) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f44383b, k6Var.f44283a);
        eVar.a(f44385c, k6Var.f44284b);
        eVar.a(d, null);
        eVar.a(e, k6Var.f44285c);
        eVar.a(f44389f, null);
        eVar.a(f44391g, null);
        eVar.a(h, null);
        eVar.a(f44394i, null);
        eVar.a(f44396j, null);
        eVar.a(f44398k, null);
        eVar.a(f44400l, null);
        eVar.a(f44402m, null);
        eVar.a(f44403n, null);
        eVar.a(f44405o, null);
        eVar.a(f44407p, null);
        eVar.a(f44409q, null);
        eVar.a(f44411r, null);
        eVar.a(f44413s, null);
        eVar.a(f44415t, null);
        eVar.a(f44417u, null);
        eVar.a(v, null);
        eVar.a(f44420w, null);
        eVar.a(f44422x, null);
        eVar.a(f44424y, k6Var.d);
        eVar.a(f44426z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f44382a0, null);
        eVar.a(f44384b0, null);
        eVar.a(f44386c0, null);
        eVar.a(f44387d0, null);
        eVar.a(f44388e0, null);
        eVar.a(f44390f0, null);
        eVar.a(f44392g0, null);
        eVar.a(f44393h0, null);
        eVar.a(f44395i0, null);
        eVar.a(f44397j0, null);
        eVar.a(f44399k0, null);
        eVar.a(f44401l0, null);
        eVar.a(m0, null);
        eVar.a(f44404n0, null);
        eVar.a(f44406o0, null);
        eVar.a(f44408p0, null);
        eVar.a(f44410q0, null);
        eVar.a(f44412r0, null);
        eVar.a(f44414s0, null);
        eVar.a(f44416t0, null);
        eVar.a(f44418u0, null);
        eVar.a(f44419v0, null);
        eVar.a(f44421w0, null);
        eVar.a(f44423x0, null);
        eVar.a(f44425y0, null);
    }
}
