package v7;
public final class w2 implements ia.d {
    public static final w2 f48093a = new Object();
    public static final ia.c f48095b = new ia.c("systemInfo", hg.c.m(sa.e.l(h.class, new e(1))));
    public static final ia.c f48097c = new ia.c("eventName", hg.c.m(sa.e.l(h.class, new e(2))));
    public static final ia.c d = new ia.c("isThickClient", hg.c.m(sa.e.l(h.class, new e(37))));
    public static final ia.c f48100e = new ia.c("clientType", hg.c.m(sa.e.l(h.class, new e(61))));
    public static final ia.c f48102f = new ia.c("modelDownloadLogEvent", hg.c.m(sa.e.l(h.class, new e(3))));
    public static final ia.c f48104g = new ia.c("customModelLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hg.c.m(sa.e.l(h.class, new e(4))));
    public static final ia.c f48107i = new ia.c("customModelCreateLogEvent", hg.c.m(sa.e.l(h.class, new e(29))));
    public static final ia.c f48109j = new ia.c("onDeviceFaceDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(5))));
    public static final ia.c f48111k = new ia.c("onDeviceFaceLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(59))));
    public static final ia.c f48113l = new ia.c("onDeviceTextDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(6))));
    public static final ia.c f48115m = new ia.c("onDeviceTextDetectionLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(79))));
    public static final ia.c f48116n = new ia.c("onDeviceBarcodeDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(7))));
    public static final ia.c f48118o = new ia.c("onDeviceBarcodeLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(58))));
    public static final ia.c f48120p = new ia.c("onDeviceImageLabelCreateLogEvent", hg.c.m(sa.e.l(h.class, new e(48))));
    public static final ia.c f48122q = new ia.c("onDeviceImageLabelLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(49))));
    public static final ia.c f48124r = new ia.c("onDeviceImageLabelDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(18))));
    public static final ia.c f48126s = new ia.c("onDeviceObjectCreateLogEvent", hg.c.m(sa.e.l(h.class, new e(26))));
    public static final ia.c f48128t = new ia.c("onDeviceObjectLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(27))));
    public static final ia.c f48130u = new ia.c("onDeviceObjectInferenceLogEvent", hg.c.m(sa.e.l(h.class, new e(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(44))));
    public static final ia.c f48133w = new ia.c("onDeviceSegmentationLogEvent", hg.c.m(sa.e.l(h.class, new e(45))));
    public static final ia.c f48135x = new ia.c("onDeviceSmartReplyLogEvent", hg.c.m(sa.e.l(h.class, new e(19))));
    public static final ia.c f48137y = new ia.c("onDeviceLanguageIdentificationLogEvent", hg.c.m(sa.e.l(h.class, new e(21))));
    public static final ia.c f48139z = new ia.c("onDeviceTranslationLogEvent", hg.c.m(sa.e.l(h.class, new e(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hg.c.m(sa.e.l(h.class, new e(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hg.c.m(sa.e.l(h.class, new e(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hg.c.m(sa.e.l(h.class, new e(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hg.c.m(sa.e.l(h.class, new e(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hg.c.m(sa.e.l(h.class, new e(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hg.c.m(sa.e.l(h.class, new e(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hg.c.m(sa.e.l(h.class, new e(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hg.c.m(sa.e.l(h.class, new e(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hg.c.m(sa.e.l(h.class, new e(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hg.c.m(sa.e.l(h.class, new e(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hg.c.m(sa.e.l(h.class, new e(42))));
    public static final ia.c f48094a0 = new ia.c("inputImageConstructionLogEvent", hg.c.m(sa.e.l(h.class, new e(50))));
    public static final ia.c f48096b0 = new ia.c("leakedHandleEvent", hg.c.m(sa.e.l(h.class, new e(51))));
    public static final ia.c f48098c0 = new ia.c("cameraSourceLogEvent", hg.c.m(sa.e.l(h.class, new e(52))));
    public static final ia.c f48099d0 = new ia.c("imageLabelOptionalModuleLogEvent", hg.c.m(sa.e.l(h.class, new e(53))));
    public static final ia.c f48101e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hg.c.m(sa.e.l(h.class, new e(54))));
    public static final ia.c f48103f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hg.c.m(sa.e.l(h.class, new e(60))));
    public static final ia.c f48105g0 = new ia.c("nlClassifierOptionalModuleLogEvent", hg.c.m(sa.e.l(h.class, new e(55))));
    public static final ia.c f48106h0 = new ia.c("nlClassifierClientLibraryLogEvent", hg.c.m(sa.e.l(h.class, new e(56))));
    public static final ia.c f48108i0 = new ia.c("accelerationAllowlistLogEvent", hg.c.m(sa.e.l(h.class, new e(57))));
    public static final ia.c f48110j0 = new ia.c("toxicityDetectionCreateEvent", hg.c.m(sa.e.l(h.class, new e(62))));
    public static final ia.c f48112k0 = new ia.c("toxicityDetectionLoadEvent", hg.c.m(sa.e.l(h.class, new e(63))));
    public static final ia.c f48114l0 = new ia.c("toxicityDetectionInferenceEvent", hg.c.m(sa.e.l(h.class, new e(64))));
    public static final ia.c m0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hg.c.m(sa.e.l(h.class, new e(65))));
    public static final ia.c f48117n0 = new ia.c("customImageLabelOptionalModuleLogEvent", hg.c.m(sa.e.l(h.class, new e(66))));
    public static final ia.c f48119o0 = new ia.c("codeScannerScanApiEvent", hg.c.m(sa.e.l(h.class, new e(67))));
    public static final ia.c f48121p0 = new ia.c("codeScannerOptionalModuleEvent", hg.c.m(sa.e.l(h.class, new e(68))));
    public static final ia.c f48123q0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hg.c.m(sa.e.l(h.class, new e(70))));
    public static final ia.c f48125r0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(71))));
    public static final ia.c f48127s0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hg.c.m(sa.e.l(h.class, new e(72))));
    public static final ia.c f48129t0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hg.c.m(sa.e.l(h.class, new e(73))));
    public static final ia.c f48131u0 = new ia.c("onDeviceSelfieFaceCreateLogEvent", hg.c.m(sa.e.l(h.class, new e(74))));
    public static final ia.c f48132v0 = new ia.c("onDeviceSelfieFaceLoadLogEvent", hg.c.m(sa.e.l(h.class, new e(75))));
    public static final ia.c f48134w0 = new ia.c("onDeviceSelfieFaceLogEvent", hg.c.m(sa.e.l(h.class, new e(76))));
    public static final ia.c f48136x0 = new ia.c("aggregatedOnDeviceSelfieFaceLogEvent", hg.c.m(sa.e.l(h.class, new e(77))));
    public static final ia.c f48138y0 = new ia.c("smartReplyOptionalModuleLogEvent", hg.c.m(sa.e.l(h.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        k6 k6Var = (k6) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f48095b, k6Var.f47993a);
        eVar.a(f48097c, k6Var.f47994b);
        eVar.a(d, null);
        eVar.a(f48100e, k6Var.f47995c);
        eVar.a(f48102f, null);
        eVar.a(f48104g, null);
        eVar.a(h, null);
        eVar.a(f48107i, null);
        eVar.a(f48109j, null);
        eVar.a(f48111k, null);
        eVar.a(f48113l, null);
        eVar.a(f48115m, null);
        eVar.a(f48116n, null);
        eVar.a(f48118o, null);
        eVar.a(f48120p, null);
        eVar.a(f48122q, null);
        eVar.a(f48124r, null);
        eVar.a(f48126s, null);
        eVar.a(f48128t, null);
        eVar.a(f48130u, null);
        eVar.a(v, null);
        eVar.a(f48133w, null);
        eVar.a(f48135x, null);
        eVar.a(f48137y, k6Var.d);
        eVar.a(f48139z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f48094a0, null);
        eVar.a(f48096b0, null);
        eVar.a(f48098c0, null);
        eVar.a(f48099d0, null);
        eVar.a(f48101e0, null);
        eVar.a(f48103f0, null);
        eVar.a(f48105g0, null);
        eVar.a(f48106h0, null);
        eVar.a(f48108i0, null);
        eVar.a(f48110j0, null);
        eVar.a(f48112k0, null);
        eVar.a(f48114l0, null);
        eVar.a(m0, null);
        eVar.a(f48117n0, null);
        eVar.a(f48119o0, null);
        eVar.a(f48121p0, null);
        eVar.a(f48123q0, null);
        eVar.a(f48125r0, null);
        eVar.a(f48127s0, null);
        eVar.a(f48129t0, null);
        eVar.a(f48131u0, null);
        eVar.a(f48132v0, null);
        eVar.a(f48134w0, null);
        eVar.a(f48136x0, null);
        eVar.a(f48138y0, null);
    }
}
