package v7;
public final class x2 implements ia.d {
    public static final x2 f49441a = new Object();
    public static final ia.c f49443b = new ia.c("systemInfo", hg.c.m(sc.v.l(h.class, new e(1))));
    public static final ia.c f49445c = new ia.c("eventName", hg.c.m(sc.v.l(h.class, new e(2))));
    public static final ia.c d = new ia.c("isThickClient", hg.c.m(sc.v.l(h.class, new e(37))));
    public static final ia.c f49448e = new ia.c("clientType", hg.c.m(sc.v.l(h.class, new e(61))));
    public static final ia.c f49450f = new ia.c("modelDownloadLogEvent", hg.c.m(sc.v.l(h.class, new e(3))));
    public static final ia.c f49452g = new ia.c("customModelLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hg.c.m(sc.v.l(h.class, new e(4))));
    public static final ia.c f49455i = new ia.c("customModelCreateLogEvent", hg.c.m(sc.v.l(h.class, new e(29))));
    public static final ia.c f49457j = new ia.c("onDeviceFaceDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(5))));
    public static final ia.c f49459k = new ia.c("onDeviceFaceLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(59))));
    public static final ia.c f49461l = new ia.c("onDeviceTextDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(6))));
    public static final ia.c f49463m = new ia.c("onDeviceTextDetectionLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(79))));
    public static final ia.c f49464n = new ia.c("onDeviceBarcodeDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(7))));
    public static final ia.c f49466o = new ia.c("onDeviceBarcodeLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(58))));
    public static final ia.c f49468p = new ia.c("onDeviceImageLabelCreateLogEvent", hg.c.m(sc.v.l(h.class, new e(48))));
    public static final ia.c f49470q = new ia.c("onDeviceImageLabelLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(49))));
    public static final ia.c f49472r = new ia.c("onDeviceImageLabelDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(18))));
    public static final ia.c f49474s = new ia.c("onDeviceObjectCreateLogEvent", hg.c.m(sc.v.l(h.class, new e(26))));
    public static final ia.c f49476t = new ia.c("onDeviceObjectLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(27))));
    public static final ia.c f49478u = new ia.c("onDeviceObjectInferenceLogEvent", hg.c.m(sc.v.l(h.class, new e(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(44))));
    public static final ia.c f49481w = new ia.c("onDeviceSegmentationLogEvent", hg.c.m(sc.v.l(h.class, new e(45))));
    public static final ia.c f49483x = new ia.c("onDeviceSmartReplyLogEvent", hg.c.m(sc.v.l(h.class, new e(19))));
    public static final ia.c f49485y = new ia.c("onDeviceLanguageIdentificationLogEvent", hg.c.m(sc.v.l(h.class, new e(21))));
    public static final ia.c f49487z = new ia.c("onDeviceTranslationLogEvent", hg.c.m(sc.v.l(h.class, new e(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hg.c.m(sc.v.l(h.class, new e(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hg.c.m(sc.v.l(h.class, new e(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hg.c.m(sc.v.l(h.class, new e(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hg.c.m(sc.v.l(h.class, new e(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hg.c.m(sc.v.l(h.class, new e(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hg.c.m(sc.v.l(h.class, new e(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hg.c.m(sc.v.l(h.class, new e(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hg.c.m(sc.v.l(h.class, new e(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hg.c.m(sc.v.l(h.class, new e(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hg.c.m(sc.v.l(h.class, new e(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hg.c.m(sc.v.l(h.class, new e(42))));
    public static final ia.c f49442a0 = new ia.c("inputImageConstructionLogEvent", hg.c.m(sc.v.l(h.class, new e(50))));
    public static final ia.c f49444b0 = new ia.c("leakedHandleEvent", hg.c.m(sc.v.l(h.class, new e(51))));
    public static final ia.c f49446c0 = new ia.c("cameraSourceLogEvent", hg.c.m(sc.v.l(h.class, new e(52))));
    public static final ia.c f49447d0 = new ia.c("imageLabelOptionalModuleLogEvent", hg.c.m(sc.v.l(h.class, new e(53))));
    public static final ia.c f49449e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hg.c.m(sc.v.l(h.class, new e(54))));
    public static final ia.c f49451f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hg.c.m(sc.v.l(h.class, new e(60))));
    public static final ia.c f49453g0 = new ia.c("nlClassifierOptionalModuleLogEvent", hg.c.m(sc.v.l(h.class, new e(55))));
    public static final ia.c f49454h0 = new ia.c("nlClassifierClientLibraryLogEvent", hg.c.m(sc.v.l(h.class, new e(56))));
    public static final ia.c f49456i0 = new ia.c("accelerationAllowlistLogEvent", hg.c.m(sc.v.l(h.class, new e(57))));
    public static final ia.c f49458j0 = new ia.c("toxicityDetectionCreateEvent", hg.c.m(sc.v.l(h.class, new e(62))));
    public static final ia.c f49460k0 = new ia.c("toxicityDetectionLoadEvent", hg.c.m(sc.v.l(h.class, new e(63))));
    public static final ia.c f49462l0 = new ia.c("toxicityDetectionInferenceEvent", hg.c.m(sc.v.l(h.class, new e(64))));
    public static final ia.c m0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hg.c.m(sc.v.l(h.class, new e(65))));
    public static final ia.c f49465n0 = new ia.c("customImageLabelOptionalModuleLogEvent", hg.c.m(sc.v.l(h.class, new e(66))));
    public static final ia.c f49467o0 = new ia.c("codeScannerScanApiEvent", hg.c.m(sc.v.l(h.class, new e(67))));
    public static final ia.c f49469p0 = new ia.c("codeScannerOptionalModuleEvent", hg.c.m(sc.v.l(h.class, new e(68))));
    public static final ia.c f49471q0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hg.c.m(sc.v.l(h.class, new e(70))));
    public static final ia.c f49473r0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(71))));
    public static final ia.c f49475s0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hg.c.m(sc.v.l(h.class, new e(72))));
    public static final ia.c f49477t0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hg.c.m(sc.v.l(h.class, new e(73))));
    public static final ia.c f49479u0 = new ia.c("onDeviceSelfieFaceCreateLogEvent", hg.c.m(sc.v.l(h.class, new e(74))));
    public static final ia.c f49480v0 = new ia.c("onDeviceSelfieFaceLoadLogEvent", hg.c.m(sc.v.l(h.class, new e(75))));
    public static final ia.c f49482w0 = new ia.c("onDeviceSelfieFaceLogEvent", hg.c.m(sc.v.l(h.class, new e(76))));
    public static final ia.c f49484x0 = new ia.c("aggregatedOnDeviceSelfieFaceLogEvent", hg.c.m(sc.v.l(h.class, new e(77))));
    public static final ia.c f49486y0 = new ia.c("smartReplyOptionalModuleLogEvent", hg.c.m(sc.v.l(h.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        l6 l6Var = (l6) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f49443b, l6Var.f49349a);
        eVar.a(f49445c, l6Var.f49350b);
        eVar.a(d, null);
        eVar.a(f49448e, l6Var.f49351c);
        eVar.a(f49450f, null);
        eVar.a(f49452g, null);
        eVar.a(h, null);
        eVar.a(f49455i, null);
        eVar.a(f49457j, null);
        eVar.a(f49459k, null);
        eVar.a(f49461l, null);
        eVar.a(f49463m, null);
        eVar.a(f49464n, null);
        eVar.a(f49466o, null);
        eVar.a(f49468p, null);
        eVar.a(f49470q, null);
        eVar.a(f49472r, null);
        eVar.a(f49474s, null);
        eVar.a(f49476t, null);
        eVar.a(f49478u, null);
        eVar.a(v, null);
        eVar.a(f49481w, null);
        eVar.a(f49483x, null);
        eVar.a(f49485y, l6Var.d);
        eVar.a(f49487z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f49442a0, null);
        eVar.a(f49444b0, null);
        eVar.a(f49446c0, null);
        eVar.a(f49447d0, null);
        eVar.a(f49449e0, null);
        eVar.a(f49451f0, null);
        eVar.a(f49453g0, null);
        eVar.a(f49454h0, null);
        eVar.a(f49456i0, null);
        eVar.a(f49458j0, null);
        eVar.a(f49460k0, null);
        eVar.a(f49462l0, null);
        eVar.a(m0, null);
        eVar.a(f49465n0, null);
        eVar.a(f49467o0, null);
        eVar.a(f49469p0, null);
        eVar.a(f49471q0, null);
        eVar.a(f49473r0, null);
        eVar.a(f49475s0, null);
        eVar.a(f49477t0, null);
        eVar.a(f49479u0, null);
        eVar.a(f49480v0, null);
        eVar.a(f49482w0, null);
        eVar.a(f49484x0, null);
        eVar.a(f49486y0, null);
    }
}
