package x7;
public final class u3 implements ia.d {
    public static final u3 f49672a = new Object();
    public static final ia.c f49674b = new ia.c("systemInfo", hg.c.m(sa.e.n(c0.class, new z(1))));
    public static final ia.c f49676c = new ia.c("eventName", hg.c.m(sa.e.n(c0.class, new z(2))));
    public static final ia.c d = new ia.c("isThickClient", hg.c.m(sa.e.n(c0.class, new z(37))));
    public static final ia.c f49679e = new ia.c("clientType", hg.c.m(sa.e.n(c0.class, new z(61))));
    public static final ia.c f49681f = new ia.c("modelDownloadLogEvent", hg.c.m(sa.e.n(c0.class, new z(3))));
    public static final ia.c f49683g = new ia.c("customModelLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hg.c.m(sa.e.n(c0.class, new z(4))));
    public static final ia.c f49686i = new ia.c("customModelCreateLogEvent", hg.c.m(sa.e.n(c0.class, new z(29))));
    public static final ia.c f49688j = new ia.c("onDeviceFaceDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(5))));
    public static final ia.c f49690k = new ia.c("onDeviceFaceLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(59))));
    public static final ia.c f49692l = new ia.c("onDeviceTextDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(6))));
    public static final ia.c f49694m = new ia.c("onDeviceTextDetectionLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(79))));
    public static final ia.c f49695n = new ia.c("onDeviceBarcodeDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(7))));
    public static final ia.c f49697o = new ia.c("onDeviceBarcodeLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(58))));
    public static final ia.c f49699p = new ia.c("onDeviceImageLabelCreateLogEvent", hg.c.m(sa.e.n(c0.class, new z(48))));
    public static final ia.c f49701q = new ia.c("onDeviceImageLabelLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(49))));
    public static final ia.c f49703r = new ia.c("onDeviceImageLabelDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(18))));
    public static final ia.c f49705s = new ia.c("onDeviceObjectCreateLogEvent", hg.c.m(sa.e.n(c0.class, new z(26))));
    public static final ia.c f49707t = new ia.c("onDeviceObjectLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(27))));
    public static final ia.c f49709u = new ia.c("onDeviceObjectInferenceLogEvent", hg.c.m(sa.e.n(c0.class, new z(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(44))));
    public static final ia.c f49712w = new ia.c("onDeviceSegmentationLogEvent", hg.c.m(sa.e.n(c0.class, new z(45))));
    public static final ia.c f49714x = new ia.c("onDeviceSmartReplyLogEvent", hg.c.m(sa.e.n(c0.class, new z(19))));
    public static final ia.c f49716y = new ia.c("onDeviceLanguageIdentificationLogEvent", hg.c.m(sa.e.n(c0.class, new z(21))));
    public static final ia.c f49718z = new ia.c("onDeviceTranslationLogEvent", hg.c.m(sa.e.n(c0.class, new z(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hg.c.m(sa.e.n(c0.class, new z(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hg.c.m(sa.e.n(c0.class, new z(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hg.c.m(sa.e.n(c0.class, new z(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hg.c.m(sa.e.n(c0.class, new z(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hg.c.m(sa.e.n(c0.class, new z(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hg.c.m(sa.e.n(c0.class, new z(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hg.c.m(sa.e.n(c0.class, new z(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hg.c.m(sa.e.n(c0.class, new z(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hg.c.m(sa.e.n(c0.class, new z(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hg.c.m(sa.e.n(c0.class, new z(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hg.c.m(sa.e.n(c0.class, new z(42))));
    public static final ia.c f49673a0 = new ia.c("inputImageConstructionLogEvent", hg.c.m(sa.e.n(c0.class, new z(50))));
    public static final ia.c f49675b0 = new ia.c("leakedHandleEvent", hg.c.m(sa.e.n(c0.class, new z(51))));
    public static final ia.c f49677c0 = new ia.c("cameraSourceLogEvent", hg.c.m(sa.e.n(c0.class, new z(52))));
    public static final ia.c f49678d0 = new ia.c("imageLabelOptionalModuleLogEvent", hg.c.m(sa.e.n(c0.class, new z(53))));
    public static final ia.c f49680e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hg.c.m(sa.e.n(c0.class, new z(54))));
    public static final ia.c f49682f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hg.c.m(sa.e.n(c0.class, new z(60))));
    public static final ia.c f49684g0 = new ia.c("nlClassifierOptionalModuleLogEvent", hg.c.m(sa.e.n(c0.class, new z(55))));
    public static final ia.c f49685h0 = new ia.c("nlClassifierClientLibraryLogEvent", hg.c.m(sa.e.n(c0.class, new z(56))));
    public static final ia.c f49687i0 = new ia.c("accelerationAllowlistLogEvent", hg.c.m(sa.e.n(c0.class, new z(57))));
    public static final ia.c f49689j0 = new ia.c("toxicityDetectionCreateEvent", hg.c.m(sa.e.n(c0.class, new z(62))));
    public static final ia.c f49691k0 = new ia.c("toxicityDetectionLoadEvent", hg.c.m(sa.e.n(c0.class, new z(63))));
    public static final ia.c f49693l0 = new ia.c("toxicityDetectionInferenceEvent", hg.c.m(sa.e.n(c0.class, new z(64))));
    public static final ia.c m0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hg.c.m(sa.e.n(c0.class, new z(65))));
    public static final ia.c f49696n0 = new ia.c("customImageLabelOptionalModuleLogEvent", hg.c.m(sa.e.n(c0.class, new z(66))));
    public static final ia.c f49698o0 = new ia.c("codeScannerScanApiEvent", hg.c.m(sa.e.n(c0.class, new z(67))));
    public static final ia.c f49700p0 = new ia.c("codeScannerOptionalModuleEvent", hg.c.m(sa.e.n(c0.class, new z(68))));
    public static final ia.c f49702q0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hg.c.m(sa.e.n(c0.class, new z(70))));
    public static final ia.c f49704r0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(71))));
    public static final ia.c f49706s0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hg.c.m(sa.e.n(c0.class, new z(72))));
    public static final ia.c f49708t0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hg.c.m(sa.e.n(c0.class, new z(73))));
    public static final ia.c f49710u0 = new ia.c("onDeviceSelfieFaceCreateLogEvent", hg.c.m(sa.e.n(c0.class, new z(74))));
    public static final ia.c f49711v0 = new ia.c("onDeviceSelfieFaceLoadLogEvent", hg.c.m(sa.e.n(c0.class, new z(75))));
    public static final ia.c f49713w0 = new ia.c("onDeviceSelfieFaceLogEvent", hg.c.m(sa.e.n(c0.class, new z(76))));
    public static final ia.c f49715x0 = new ia.c("aggregatedOnDeviceSelfieFaceLogEvent", hg.c.m(sa.e.n(c0.class, new z(77))));
    public static final ia.c f49717y0 = new ia.c("smartReplyOptionalModuleLogEvent", hg.c.m(sa.e.n(c0.class, new z(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        p7 p7Var = (p7) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f49674b, p7Var.f49627a);
        eVar.a(f49676c, p7Var.f49628b);
        eVar.a(d, null);
        eVar.a(f49679e, p7Var.f49629c);
        eVar.a(f49681f, null);
        eVar.a(f49683g, null);
        eVar.a(h, null);
        eVar.a(f49686i, null);
        eVar.a(f49688j, null);
        eVar.a(f49690k, null);
        eVar.a(f49692l, null);
        eVar.a(f49694m, null);
        eVar.a(f49695n, null);
        eVar.a(f49697o, null);
        eVar.a(f49699p, null);
        eVar.a(f49701q, p7Var.d);
        eVar.a(f49703r, p7Var.f49630e);
        eVar.a(f49705s, null);
        eVar.a(f49707t, null);
        eVar.a(f49709u, null);
        eVar.a(v, null);
        eVar.a(f49712w, null);
        eVar.a(f49714x, null);
        eVar.a(f49716y, null);
        eVar.a(f49718z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, p7Var.f49631f);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f49673a0, null);
        eVar.a(f49675b0, null);
        eVar.a(f49677c0, null);
        eVar.a(f49678d0, null);
        eVar.a(f49680e0, null);
        eVar.a(f49682f0, null);
        eVar.a(f49684g0, null);
        eVar.a(f49685h0, null);
        eVar.a(f49687i0, null);
        eVar.a(f49689j0, null);
        eVar.a(f49691k0, null);
        eVar.a(f49693l0, null);
        eVar.a(m0, null);
        eVar.a(f49696n0, null);
        eVar.a(f49698o0, null);
        eVar.a(f49700p0, null);
        eVar.a(f49702q0, null);
        eVar.a(f49704r0, null);
        eVar.a(f49706s0, null);
        eVar.a(f49708t0, null);
        eVar.a(f49710u0, null);
        eVar.a(f49711v0, null);
        eVar.a(f49713w0, null);
        eVar.a(f49715x0, null);
        eVar.a(f49717y0, null);
    }
}
