package x7;
public final class u3 implements ia.d {
    public static final u3 f45875a = new Object();
    public static final ia.c f45877b = new ia.c("systemInfo", hg.c.m(v7.j.l(c0.class, new z(1))));
    public static final ia.c f45879c = new ia.c("eventName", hg.c.m(v7.j.l(c0.class, new z(2))));
    public static final ia.c d = new ia.c("isThickClient", hg.c.m(v7.j.l(c0.class, new z(37))));
    public static final ia.c e = new ia.c("clientType", hg.c.m(v7.j.l(c0.class, new z(61))));
    public static final ia.c f45883f = new ia.c("modelDownloadLogEvent", hg.c.m(v7.j.l(c0.class, new z(3))));
    public static final ia.c f45885g = new ia.c("customModelLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hg.c.m(v7.j.l(c0.class, new z(4))));
    public static final ia.c f45888i = new ia.c("customModelCreateLogEvent", hg.c.m(v7.j.l(c0.class, new z(29))));
    public static final ia.c f45890j = new ia.c("onDeviceFaceDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(5))));
    public static final ia.c f45892k = new ia.c("onDeviceFaceLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(59))));
    public static final ia.c f45894l = new ia.c("onDeviceTextDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(6))));
    public static final ia.c f45896m = new ia.c("onDeviceTextDetectionLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(79))));
    public static final ia.c f45897n = new ia.c("onDeviceBarcodeDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(7))));
    public static final ia.c f45899o = new ia.c("onDeviceBarcodeLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(58))));
    public static final ia.c f45901p = new ia.c("onDeviceImageLabelCreateLogEvent", hg.c.m(v7.j.l(c0.class, new z(48))));
    public static final ia.c f45903q = new ia.c("onDeviceImageLabelLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(49))));
    public static final ia.c f45905r = new ia.c("onDeviceImageLabelDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(18))));
    public static final ia.c f45907s = new ia.c("onDeviceObjectCreateLogEvent", hg.c.m(v7.j.l(c0.class, new z(26))));
    public static final ia.c f45909t = new ia.c("onDeviceObjectLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(27))));
    public static final ia.c f45911u = new ia.c("onDeviceObjectInferenceLogEvent", hg.c.m(v7.j.l(c0.class, new z(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(44))));
    public static final ia.c f45914w = new ia.c("onDeviceSegmentationLogEvent", hg.c.m(v7.j.l(c0.class, new z(45))));
    public static final ia.c f45916x = new ia.c("onDeviceSmartReplyLogEvent", hg.c.m(v7.j.l(c0.class, new z(19))));
    public static final ia.c f45918y = new ia.c("onDeviceLanguageIdentificationLogEvent", hg.c.m(v7.j.l(c0.class, new z(21))));
    public static final ia.c f45920z = new ia.c("onDeviceTranslationLogEvent", hg.c.m(v7.j.l(c0.class, new z(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hg.c.m(v7.j.l(c0.class, new z(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hg.c.m(v7.j.l(c0.class, new z(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hg.c.m(v7.j.l(c0.class, new z(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hg.c.m(v7.j.l(c0.class, new z(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hg.c.m(v7.j.l(c0.class, new z(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hg.c.m(v7.j.l(c0.class, new z(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hg.c.m(v7.j.l(c0.class, new z(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hg.c.m(v7.j.l(c0.class, new z(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hg.c.m(v7.j.l(c0.class, new z(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hg.c.m(v7.j.l(c0.class, new z(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hg.c.m(v7.j.l(c0.class, new z(42))));
    public static final ia.c f45876a0 = new ia.c("inputImageConstructionLogEvent", hg.c.m(v7.j.l(c0.class, new z(50))));
    public static final ia.c f45878b0 = new ia.c("leakedHandleEvent", hg.c.m(v7.j.l(c0.class, new z(51))));
    public static final ia.c f45880c0 = new ia.c("cameraSourceLogEvent", hg.c.m(v7.j.l(c0.class, new z(52))));
    public static final ia.c f45881d0 = new ia.c("imageLabelOptionalModuleLogEvent", hg.c.m(v7.j.l(c0.class, new z(53))));
    public static final ia.c f45882e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hg.c.m(v7.j.l(c0.class, new z(54))));
    public static final ia.c f45884f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hg.c.m(v7.j.l(c0.class, new z(60))));
    public static final ia.c f45886g0 = new ia.c("nlClassifierOptionalModuleLogEvent", hg.c.m(v7.j.l(c0.class, new z(55))));
    public static final ia.c f45887h0 = new ia.c("nlClassifierClientLibraryLogEvent", hg.c.m(v7.j.l(c0.class, new z(56))));
    public static final ia.c f45889i0 = new ia.c("accelerationAllowlistLogEvent", hg.c.m(v7.j.l(c0.class, new z(57))));
    public static final ia.c f45891j0 = new ia.c("toxicityDetectionCreateEvent", hg.c.m(v7.j.l(c0.class, new z(62))));
    public static final ia.c f45893k0 = new ia.c("toxicityDetectionLoadEvent", hg.c.m(v7.j.l(c0.class, new z(63))));
    public static final ia.c f45895l0 = new ia.c("toxicityDetectionInferenceEvent", hg.c.m(v7.j.l(c0.class, new z(64))));
    public static final ia.c m0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hg.c.m(v7.j.l(c0.class, new z(65))));
    public static final ia.c f45898n0 = new ia.c("customImageLabelOptionalModuleLogEvent", hg.c.m(v7.j.l(c0.class, new z(66))));
    public static final ia.c f45900o0 = new ia.c("codeScannerScanApiEvent", hg.c.m(v7.j.l(c0.class, new z(67))));
    public static final ia.c f45902p0 = new ia.c("codeScannerOptionalModuleEvent", hg.c.m(v7.j.l(c0.class, new z(68))));
    public static final ia.c f45904q0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hg.c.m(v7.j.l(c0.class, new z(70))));
    public static final ia.c f45906r0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(71))));
    public static final ia.c f45908s0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hg.c.m(v7.j.l(c0.class, new z(72))));
    public static final ia.c f45910t0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hg.c.m(v7.j.l(c0.class, new z(73))));
    public static final ia.c f45912u0 = new ia.c("onDeviceSelfieFaceCreateLogEvent", hg.c.m(v7.j.l(c0.class, new z(74))));
    public static final ia.c f45913v0 = new ia.c("onDeviceSelfieFaceLoadLogEvent", hg.c.m(v7.j.l(c0.class, new z(75))));
    public static final ia.c f45915w0 = new ia.c("onDeviceSelfieFaceLogEvent", hg.c.m(v7.j.l(c0.class, new z(76))));
    public static final ia.c f45917x0 = new ia.c("aggregatedOnDeviceSelfieFaceLogEvent", hg.c.m(v7.j.l(c0.class, new z(77))));
    public static final ia.c f45919y0 = new ia.c("smartReplyOptionalModuleLogEvent", hg.c.m(v7.j.l(c0.class, new z(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        p7 p7Var = (p7) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f45877b, p7Var.f45834a);
        eVar.a(f45879c, p7Var.f45835b);
        eVar.a(d, null);
        eVar.a(e, p7Var.f45836c);
        eVar.a(f45883f, null);
        eVar.a(f45885g, null);
        eVar.a(h, null);
        eVar.a(f45888i, null);
        eVar.a(f45890j, null);
        eVar.a(f45892k, null);
        eVar.a(f45894l, null);
        eVar.a(f45896m, null);
        eVar.a(f45897n, null);
        eVar.a(f45899o, null);
        eVar.a(f45901p, null);
        eVar.a(f45903q, p7Var.d);
        eVar.a(f45905r, p7Var.e);
        eVar.a(f45907s, null);
        eVar.a(f45909t, null);
        eVar.a(f45911u, null);
        eVar.a(v, null);
        eVar.a(f45914w, null);
        eVar.a(f45916x, null);
        eVar.a(f45918y, null);
        eVar.a(f45920z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, p7Var.f45837f);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f45876a0, null);
        eVar.a(f45878b0, null);
        eVar.a(f45880c0, null);
        eVar.a(f45881d0, null);
        eVar.a(f45882e0, null);
        eVar.a(f45884f0, null);
        eVar.a(f45886g0, null);
        eVar.a(f45887h0, null);
        eVar.a(f45889i0, null);
        eVar.a(f45891j0, null);
        eVar.a(f45893k0, null);
        eVar.a(f45895l0, null);
        eVar.a(m0, null);
        eVar.a(f45898n0, null);
        eVar.a(f45900o0, null);
        eVar.a(f45902p0, null);
        eVar.a(f45904q0, null);
        eVar.a(f45906r0, null);
        eVar.a(f45908s0, null);
        eVar.a(f45910t0, null);
        eVar.a(f45912u0, null);
        eVar.a(f45913v0, null);
        eVar.a(f45915w0, null);
        eVar.a(f45917x0, null);
        eVar.a(f45919y0, null);
    }
}
