package f7;
public enum k6 implements g {
    NO_ERROR(0),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(1),
    INCOMPATIBLE_OUTPUT(2),
    INCOMPATIBLE_TFLITE_VERSION(3),
    MISSING_OP(4),
    DATA_TYPE_ERROR(6),
    TFLITE_INTERNAL_ERROR(7),
    TFLITE_UNKNOWN_ERROR(8),
    REMOTE_MODEL_INVALID(9),
    TIME_OUT_FETCHING_MODEL_METADATA(5),
    MODEL_NOT_DOWNLOADED(100),
    URI_EXPIRED(101),
    NO_NETWORK_CONNECTION(102),
    METERED_NETWORK(103),
    DOWNLOAD_FAILED(104),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(105),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(106),
    REMOTE_MODEL_INVALID(107),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(108),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(109),
    REMOTE_MODEL_INVALID(110),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(111),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(112),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(113),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(114),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(115),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(116),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(201),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(202),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(203),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(204),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(205),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(206),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(207),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(301),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(302),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(303),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(304),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(305),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(400),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(401),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(402),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(403),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(404),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(405),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(406),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(407),
    UNKNOWN_ERROR(9999);
    
    public final int f5731a;

    k6(int i9) {
        this.f5731a = i9;
    }

    @Override
    public final int zza() {
        return this.f5731a;
    }
}
