package f7;
public final class y2 implements q9.d {
    public static final y2 f5856a = new Object();
    public static final q9.c f5858b = new q9.c("systemInfo", ta.b.g(e2.c.q(i.class, new e(1))));
    public static final q9.c f5860c = new q9.c("eventName", ta.b.g(e2.c.q(i.class, new e(2))));
    public static final q9.c d = new q9.c("isThickClient", ta.b.g(e2.c.q(i.class, new e(37))));
    public static final q9.c f5863e = new q9.c("clientType", ta.b.g(e2.c.q(i.class, new e(61))));
    public static final q9.c f5865f = new q9.c("modelDownloadLogEvent", ta.b.g(e2.c.q(i.class, new e(3))));
    public static final q9.c f5867g = new q9.c("customModelLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(20))));
    public static final q9.c h = new q9.c("customModelInferenceLogEvent", ta.b.g(e2.c.q(i.class, new e(4))));
    public static final q9.c f5870i = new q9.c("customModelCreateLogEvent", ta.b.g(e2.c.q(i.class, new e(29))));
    public static final q9.c f5872j = new q9.c("onDeviceFaceDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(5))));
    public static final q9.c f5874k = new q9.c("onDeviceFaceLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(59))));
    public static final q9.c f5876l = new q9.c("onDeviceTextDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(6))));
    public static final q9.c f5878m = new q9.c("onDeviceTextDetectionLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(79))));
    public static final q9.c f5879n = new q9.c("onDeviceBarcodeDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(7))));
    public static final q9.c f5881o = new q9.c("onDeviceBarcodeLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(58))));
    public static final q9.c f5883p = new q9.c("onDeviceImageLabelCreateLogEvent", ta.b.g(e2.c.q(i.class, new e(48))));
    public static final q9.c f5885q = new q9.c("onDeviceImageLabelLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(49))));
    public static final q9.c f5887r = new q9.c("onDeviceImageLabelDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(18))));
    public static final q9.c f5889s = new q9.c("onDeviceObjectCreateLogEvent", ta.b.g(e2.c.q(i.class, new e(26))));
    public static final q9.c f5891t = new q9.c("onDeviceObjectLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(27))));
    public static final q9.c f5893u = new q9.c("onDeviceObjectInferenceLogEvent", ta.b.g(e2.c.q(i.class, new e(28))));
    public static final q9.c v = new q9.c("onDevicePoseDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(44))));
    public static final q9.c f5896w = new q9.c("onDeviceSegmentationLogEvent", ta.b.g(e2.c.q(i.class, new e(45))));
    public static final q9.c f5898x = new q9.c("onDeviceSmartReplyLogEvent", ta.b.g(e2.c.q(i.class, new e(19))));
    public static final q9.c f5900y = new q9.c("onDeviceLanguageIdentificationLogEvent", ta.b.g(e2.c.q(i.class, new e(21))));
    public static final q9.c f5902z = new q9.c("onDeviceTranslationLogEvent", ta.b.g(e2.c.q(i.class, new e(22))));
    public static final q9.c A = new q9.c("cloudFaceDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(8))));
    public static final q9.c B = new q9.c("cloudCropHintDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(9))));
    public static final q9.c C = new q9.c("cloudDocumentTextDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(10))));
    public static final q9.c D = new q9.c("cloudImagePropertiesDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(11))));
    public static final q9.c E = new q9.c("cloudImageLabelDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(12))));
    public static final q9.c F = new q9.c("cloudLandmarkDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(13))));
    public static final q9.c G = new q9.c("cloudLogoDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(14))));
    public static final q9.c H = new q9.c("cloudSafeSearchDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(15))));
    public static final q9.c I = new q9.c("cloudTextDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(16))));
    public static final q9.c J = new q9.c("cloudWebSearchDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(17))));
    public static final q9.c K = new q9.c("automlImageLabelingCreateLogEvent", ta.b.g(e2.c.q(i.class, new e(23))));
    public static final q9.c L = new q9.c("automlImageLabelingLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(24))));
    public static final q9.c M = new q9.c("automlImageLabelingInferenceLogEvent", ta.b.g(e2.c.q(i.class, new e(25))));
    public static final q9.c N = new q9.c("isModelDownloadedLogEvent", ta.b.g(e2.c.q(i.class, new e(39))));
    public static final q9.c O = new q9.c("deleteModelLogEvent", ta.b.g(e2.c.q(i.class, new e(40))));
    public static final q9.c P = new q9.c("aggregatedAutomlImageLabelingInferenceLogEvent", ta.b.g(e2.c.q(i.class, new e(30))));
    public static final q9.c Q = new q9.c("aggregatedCustomModelInferenceLogEvent", ta.b.g(e2.c.q(i.class, new e(31))));
    public static final q9.c R = new q9.c("aggregatedOnDeviceFaceDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(32))));
    public static final q9.c S = new q9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(33))));
    public static final q9.c T = new q9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(34))));
    public static final q9.c U = new q9.c("aggregatedOnDeviceObjectInferenceLogEvent", ta.b.g(e2.c.q(i.class, new e(35))));
    public static final q9.c V = new q9.c("aggregatedOnDeviceTextDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(36))));
    public static final q9.c W = new q9.c("aggregatedOnDevicePoseDetectionLogEvent", ta.b.g(e2.c.q(i.class, new e(46))));
    public static final q9.c X = new q9.c("aggregatedOnDeviceSegmentationLogEvent", ta.b.g(e2.c.q(i.class, new e(47))));
    public static final q9.c Y = new q9.c("pipelineAccelerationInferenceEvents", ta.b.g(e2.c.q(i.class, new e(69))));
    public static final q9.c Z = new q9.c("remoteConfigLogEvent", ta.b.g(e2.c.q(i.class, new e(42))));
    public static final q9.c f5857a0 = new q9.c("inputImageConstructionLogEvent", ta.b.g(e2.c.q(i.class, new e(50))));
    public static final q9.c f5859b0 = new q9.c("leakedHandleEvent", ta.b.g(e2.c.q(i.class, new e(51))));
    public static final q9.c f5861c0 = new q9.c("cameraSourceLogEvent", ta.b.g(e2.c.q(i.class, new e(52))));
    public static final q9.c f5862d0 = new q9.c("imageLabelOptionalModuleLogEvent", ta.b.g(e2.c.q(i.class, new e(53))));
    public static final q9.c f5864e0 = new q9.c("languageIdentificationOptionalModuleLogEvent", ta.b.g(e2.c.q(i.class, new e(54))));
    public static final q9.c f5866f0 = new q9.c("faceDetectionOptionalModuleLogEvent", ta.b.g(e2.c.q(i.class, new e(60))));
    public static final q9.c f5868g0 = new q9.c("nlClassifierOptionalModuleLogEvent", ta.b.g(e2.c.q(i.class, new e(55))));
    public static final q9.c f5869h0 = new q9.c("nlClassifierClientLibraryLogEvent", ta.b.g(e2.c.q(i.class, new e(56))));
    public static final q9.c f5871i0 = new q9.c("accelerationAllowlistLogEvent", ta.b.g(e2.c.q(i.class, new e(57))));
    public static final q9.c f5873j0 = new q9.c("toxicityDetectionCreateEvent", ta.b.g(e2.c.q(i.class, new e(62))));
    public static final q9.c f5875k0 = new q9.c("toxicityDetectionLoadEvent", ta.b.g(e2.c.q(i.class, new e(63))));
    public static final q9.c f5877l0 = new q9.c("toxicityDetectionInferenceEvent", ta.b.g(e2.c.q(i.class, new e(64))));
    public static final q9.c m0 = new q9.c("barcodeDetectionOptionalModuleLogEvent", ta.b.g(e2.c.q(i.class, new e(65))));
    public static final q9.c f5880n0 = new q9.c("customImageLabelOptionalModuleLogEvent", ta.b.g(e2.c.q(i.class, new e(66))));
    public static final q9.c f5882o0 = new q9.c("codeScannerScanApiEvent", ta.b.g(e2.c.q(i.class, new e(67))));
    public static final q9.c f5884p0 = new q9.c("codeScannerOptionalModuleEvent", ta.b.g(e2.c.q(i.class, new e(68))));
    public static final q9.c f5886q0 = new q9.c("onDeviceExplicitContentCreateLogEvent", ta.b.g(e2.c.q(i.class, new e(70))));
    public static final q9.c f5888r0 = new q9.c("onDeviceExplicitContentLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(71))));
    public static final q9.c f5890s0 = new q9.c("onDeviceExplicitContentInferenceLogEvent", ta.b.g(e2.c.q(i.class, new e(72))));
    public static final q9.c f5892t0 = new q9.c("aggregatedOnDeviceExplicitContentLogEvent", ta.b.g(e2.c.q(i.class, new e(73))));
    public static final q9.c f5894u0 = new q9.c("onDeviceSelfieFaceCreateLogEvent", ta.b.g(e2.c.q(i.class, new e(74))));
    public static final q9.c f5895v0 = new q9.c("onDeviceSelfieFaceLoadLogEvent", ta.b.g(e2.c.q(i.class, new e(75))));
    public static final q9.c f5897w0 = new q9.c("onDeviceSelfieFaceLogEvent", ta.b.g(e2.c.q(i.class, new e(76))));
    public static final q9.c f5899x0 = new q9.c("aggregatedOnDeviceSelfieFaceLogEvent", ta.b.g(e2.c.q(i.class, new e(77))));
    public static final q9.c f5901y0 = new q9.c("smartReplyOptionalModuleLogEvent", ta.b.g(e2.c.q(i.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        m6 m6Var = (m6) obj;
        q9.e eVar = (q9.e) obj2;
        eVar.g(f5858b, m6Var.f5752a);
        eVar.g(f5860c, m6Var.f5753b);
        eVar.g(d, null);
        eVar.g(f5863e, m6Var.f5754c);
        eVar.g(f5865f, null);
        eVar.g(f5867g, null);
        eVar.g(h, null);
        eVar.g(f5870i, null);
        eVar.g(f5872j, null);
        eVar.g(f5874k, null);
        eVar.g(f5876l, null);
        eVar.g(f5878m, null);
        eVar.g(f5879n, null);
        eVar.g(f5881o, null);
        eVar.g(f5883p, null);
        eVar.g(f5885q, null);
        eVar.g(f5887r, null);
        eVar.g(f5889s, null);
        eVar.g(f5891t, null);
        eVar.g(f5893u, null);
        eVar.g(v, null);
        eVar.g(f5896w, null);
        eVar.g(f5898x, null);
        eVar.g(f5900y, m6Var.d);
        eVar.g(f5902z, null);
        eVar.g(A, null);
        eVar.g(B, null);
        eVar.g(C, null);
        eVar.g(D, null);
        eVar.g(E, null);
        eVar.g(F, null);
        eVar.g(G, null);
        eVar.g(H, null);
        eVar.g(I, null);
        eVar.g(J, null);
        eVar.g(K, null);
        eVar.g(L, null);
        eVar.g(M, null);
        eVar.g(N, null);
        eVar.g(O, null);
        eVar.g(P, null);
        eVar.g(Q, null);
        eVar.g(R, null);
        eVar.g(S, null);
        eVar.g(T, null);
        eVar.g(U, null);
        eVar.g(V, null);
        eVar.g(W, null);
        eVar.g(X, null);
        eVar.g(Y, null);
        eVar.g(Z, null);
        eVar.g(f5857a0, null);
        eVar.g(f5859b0, null);
        eVar.g(f5861c0, null);
        eVar.g(f5862d0, null);
        eVar.g(f5864e0, null);
        eVar.g(f5866f0, null);
        eVar.g(f5868g0, null);
        eVar.g(f5869h0, null);
        eVar.g(f5871i0, null);
        eVar.g(f5873j0, null);
        eVar.g(f5875k0, null);
        eVar.g(f5877l0, null);
        eVar.g(m0, null);
        eVar.g(f5880n0, null);
        eVar.g(f5882o0, null);
        eVar.g(f5884p0, null);
        eVar.g(f5886q0, null);
        eVar.g(f5888r0, null);
        eVar.g(f5890s0, null);
        eVar.g(f5892t0, null);
        eVar.g(f5894u0, null);
        eVar.g(f5895v0, null);
        eVar.g(f5897w0, null);
        eVar.g(f5899x0, null);
        eVar.g(f5901y0, null);
    }
}
