package k7;
public final class g3 implements u9.d {
    public static final g3 f9794a = new Object();
    public static final u9.c f9796b = new u9.c("systemInfo", vh.w2.h(e2.c.o(d.class, new a(1))));
    public static final u9.c f9798c = new u9.c("eventName", vh.w2.h(e2.c.o(d.class, new a(2))));
    public static final u9.c d = new u9.c("isThickClient", vh.w2.h(e2.c.o(d.class, new a(37))));
    public static final u9.c e = new u9.c("clientType", vh.w2.h(e2.c.o(d.class, new a(61))));
    public static final u9.c f9802f = new u9.c("modelDownloadLogEvent", vh.w2.h(e2.c.o(d.class, new a(3))));
    public static final u9.c f9804g = new u9.c("customModelLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(4))));
    public static final u9.c f9807i = new u9.c("customModelCreateLogEvent", vh.w2.h(e2.c.o(d.class, new a(29))));
    public static final u9.c f9809j = new u9.c("onDeviceFaceDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(5))));
    public static final u9.c f9811k = new u9.c("onDeviceFaceLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(59))));
    public static final u9.c f9813l = new u9.c("onDeviceTextDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(6))));
    public static final u9.c f9815m = new u9.c("onDeviceTextDetectionLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(79))));
    public static final u9.c f9816n = new u9.c("onDeviceBarcodeDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(7))));
    public static final u9.c f9818o = new u9.c("onDeviceBarcodeLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(58))));
    public static final u9.c f9820p = new u9.c("onDeviceImageLabelCreateLogEvent", vh.w2.h(e2.c.o(d.class, new a(48))));
    public static final u9.c f9822q = new u9.c("onDeviceImageLabelLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(49))));
    public static final u9.c f9824r = new u9.c("onDeviceImageLabelDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(18))));
    public static final u9.c f9826s = new u9.c("onDeviceObjectCreateLogEvent", vh.w2.h(e2.c.o(d.class, new a(26))));
    public static final u9.c f9828t = new u9.c("onDeviceObjectLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(27))));
    public static final u9.c f9830u = new u9.c("onDeviceObjectInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(44))));
    public static final u9.c f9833w = new u9.c("onDeviceSegmentationLogEvent", vh.w2.h(e2.c.o(d.class, new a(45))));
    public static final u9.c f9835x = new u9.c("onDeviceSmartReplyLogEvent", vh.w2.h(e2.c.o(d.class, new a(19))));
    public static final u9.c f9837y = new u9.c("onDeviceLanguageIdentificationLogEvent", vh.w2.h(e2.c.o(d.class, new a(21))));
    public static final u9.c f9839z = new u9.c("onDeviceTranslationLogEvent", vh.w2.h(e2.c.o(d.class, new a(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", vh.w2.h(e2.c.o(d.class, new a(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", vh.w2.h(e2.c.o(d.class, new a(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", vh.w2.h(e2.c.o(d.class, new a(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", vh.w2.h(e2.c.o(d.class, new a(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", vh.w2.h(e2.c.o(d.class, new a(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", vh.w2.h(e2.c.o(d.class, new a(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", vh.w2.h(e2.c.o(d.class, new a(42))));
    public static final u9.c f9795a0 = new u9.c("inputImageConstructionLogEvent", vh.w2.h(e2.c.o(d.class, new a(50))));
    public static final u9.c f9797b0 = new u9.c("leakedHandleEvent", vh.w2.h(e2.c.o(d.class, new a(51))));
    public static final u9.c f9799c0 = new u9.c("cameraSourceLogEvent", vh.w2.h(e2.c.o(d.class, new a(52))));
    public static final u9.c f9800d0 = new u9.c("imageLabelOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(53))));
    public static final u9.c f9801e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(54))));
    public static final u9.c f9803f0 = new u9.c("faceDetectionOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(60))));
    public static final u9.c f9805g0 = new u9.c("documentDetectionOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(85))));
    public static final u9.c f9806h0 = new u9.c("documentCroppingOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(86))));
    public static final u9.c f9808i0 = new u9.c("documentEnhancementOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(87))));
    public static final u9.c f9810j0 = new u9.c("nlClassifierOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(55))));
    public static final u9.c f9812k0 = new u9.c("nlClassifierClientLibraryLogEvent", vh.w2.h(e2.c.o(d.class, new a(56))));
    public static final u9.c f9814l0 = new u9.c("accelerationAllowlistLogEvent", vh.w2.h(e2.c.o(d.class, new a(57))));
    public static final u9.c m0 = new u9.c("toxicityDetectionCreateEvent", vh.w2.h(e2.c.o(d.class, new a(62))));
    public static final u9.c f9817n0 = new u9.c("toxicityDetectionLoadEvent", vh.w2.h(e2.c.o(d.class, new a(63))));
    public static final u9.c f9819o0 = new u9.c("toxicityDetectionInferenceEvent", vh.w2.h(e2.c.o(d.class, new a(64))));
    public static final u9.c f9821p0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(65))));
    public static final u9.c f9823q0 = new u9.c("customImageLabelOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(66))));
    public static final u9.c f9825r0 = new u9.c("codeScannerScanApiEvent", vh.w2.h(e2.c.o(d.class, new a(67))));
    public static final u9.c f9827s0 = new u9.c("codeScannerOptionalModuleEvent", vh.w2.h(e2.c.o(d.class, new a(68))));
    public static final u9.c f9829t0 = new u9.c("onDeviceExplicitContentCreateLogEvent", vh.w2.h(e2.c.o(d.class, new a(70))));
    public static final u9.c f9831u0 = new u9.c("onDeviceExplicitContentLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(71))));
    public static final u9.c f9832v0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(72))));
    public static final u9.c f9834w0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", vh.w2.h(e2.c.o(d.class, new a(73))));
    public static final u9.c f9836x0 = new u9.c("onDeviceFaceMeshCreateLogEvent", vh.w2.h(e2.c.o(d.class, new a(74))));
    public static final u9.c f9838y0 = new u9.c("onDeviceFaceMeshLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(75))));
    public static final u9.c f9840z0 = new u9.c("onDeviceFaceMeshLogEvent", vh.w2.h(e2.c.o(d.class, new a(76))));
    public static final u9.c A0 = new u9.c("aggregatedOnDeviceFaceMeshLogEvent", vh.w2.h(e2.c.o(d.class, new a(77))));
    public static final u9.c B0 = new u9.c("smartReplyOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(78))));
    public static final u9.c C0 = new u9.c("textDetectionOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(80))));
    public static final u9.c D0 = new u9.c("onDeviceImageQualityAnalysisCreateLogEvent", vh.w2.h(e2.c.o(d.class, new a(81))));
    public static final u9.c E0 = new u9.c("onDeviceImageQualityAnalysisLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(82))));
    public static final u9.c F0 = new u9.c("onDeviceImageQualityAnalysisLogEvent", vh.w2.h(e2.c.o(d.class, new a(83))));
    public static final u9.c G0 = new u9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", vh.w2.h(e2.c.o(d.class, new a(84))));
    public static final u9.c H0 = new u9.c("imageQualityAnalysisOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(88))));
    public static final u9.c I0 = new u9.c("imageCaptioningOptionalModuleLogEvent", vh.w2.h(e2.c.o(d.class, new a(89))));
    public static final u9.c J0 = new u9.c("onDeviceImageCaptioningCreateLogEvent", vh.w2.h(e2.c.o(d.class, new a(90))));
    public static final u9.c K0 = new u9.c("onDeviceImageCaptioningLoadLogEvent", vh.w2.h(e2.c.o(d.class, new a(91))));
    public static final u9.c L0 = new u9.c("onDeviceImageCaptioningInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(92))));
    public static final u9.c M0 = new u9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", vh.w2.h(e2.c.o(d.class, new a(93))));

    @Override
    public final void a(Object obj, Object obj2) {
        k7 k7Var = (k7) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f9796b, k7Var.f9874a);
        eVar.e(f9798c, k7Var.f9875b);
        eVar.e(d, null);
        eVar.e(e, null);
        eVar.e(f9802f, null);
        eVar.e(f9804g, null);
        eVar.e(h, null);
        eVar.e(f9807i, null);
        eVar.e(f9809j, null);
        eVar.e(f9811k, null);
        eVar.e(f9813l, null);
        eVar.e(f9815m, null);
        eVar.e(f9816n, null);
        eVar.e(f9818o, null);
        eVar.e(f9820p, null);
        eVar.e(f9822q, null);
        eVar.e(f9824r, null);
        eVar.e(f9826s, null);
        eVar.e(f9828t, null);
        eVar.e(f9830u, null);
        eVar.e(v, null);
        eVar.e(f9833w, null);
        eVar.e(f9835x, null);
        eVar.e(f9837y, null);
        eVar.e(f9839z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f9795a0, k7Var.f9876c);
        eVar.e(f9797b0, null);
        eVar.e(f9799c0, null);
        eVar.e(f9800d0, null);
        eVar.e(f9801e0, null);
        eVar.e(f9803f0, null);
        eVar.e(f9805g0, null);
        eVar.e(f9806h0, null);
        eVar.e(f9808i0, null);
        eVar.e(f9810j0, null);
        eVar.e(f9812k0, null);
        eVar.e(f9814l0, null);
        eVar.e(m0, null);
        eVar.e(f9817n0, null);
        eVar.e(f9819o0, null);
        eVar.e(f9821p0, null);
        eVar.e(f9823q0, null);
        eVar.e(f9825r0, null);
        eVar.e(f9827s0, null);
        eVar.e(f9829t0, null);
        eVar.e(f9831u0, null);
        eVar.e(f9832v0, null);
        eVar.e(f9834w0, null);
        eVar.e(f9836x0, null);
        eVar.e(f9838y0, null);
        eVar.e(f9840z0, null);
        eVar.e(A0, null);
        eVar.e(B0, null);
        eVar.e(C0, null);
        eVar.e(D0, null);
        eVar.e(E0, null);
        eVar.e(F0, null);
        eVar.e(G0, null);
        eVar.e(H0, null);
        eVar.e(I0, null);
        eVar.e(J0, null);
        eVar.e(K0, null);
        eVar.e(L0, null);
        eVar.e(M0, null);
    }
}
