package k7;
public final class g3 implements u9.d {
    public static final g3 f9814a = new Object();
    public static final u9.c f9816b = new u9.c("systemInfo", vh.v2.h(e2.c.o(d.class, new a(1))));
    public static final u9.c f9818c = new u9.c("eventName", vh.v2.h(e2.c.o(d.class, new a(2))));
    public static final u9.c d = new u9.c("isThickClient", vh.v2.h(e2.c.o(d.class, new a(37))));
    public static final u9.c e = new u9.c("clientType", vh.v2.h(e2.c.o(d.class, new a(61))));
    public static final u9.c f9822f = new u9.c("modelDownloadLogEvent", vh.v2.h(e2.c.o(d.class, new a(3))));
    public static final u9.c f9824g = new u9.c("customModelLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(4))));
    public static final u9.c f9827i = new u9.c("customModelCreateLogEvent", vh.v2.h(e2.c.o(d.class, new a(29))));
    public static final u9.c f9829j = new u9.c("onDeviceFaceDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(5))));
    public static final u9.c f9831k = new u9.c("onDeviceFaceLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(59))));
    public static final u9.c f9833l = new u9.c("onDeviceTextDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(6))));
    public static final u9.c f9835m = new u9.c("onDeviceTextDetectionLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(79))));
    public static final u9.c f9836n = new u9.c("onDeviceBarcodeDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(7))));
    public static final u9.c f9838o = new u9.c("onDeviceBarcodeLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(58))));
    public static final u9.c f9840p = new u9.c("onDeviceImageLabelCreateLogEvent", vh.v2.h(e2.c.o(d.class, new a(48))));
    public static final u9.c f9842q = new u9.c("onDeviceImageLabelLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(49))));
    public static final u9.c f9844r = new u9.c("onDeviceImageLabelDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(18))));
    public static final u9.c f9846s = new u9.c("onDeviceObjectCreateLogEvent", vh.v2.h(e2.c.o(d.class, new a(26))));
    public static final u9.c f9848t = new u9.c("onDeviceObjectLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(27))));
    public static final u9.c f9850u = new u9.c("onDeviceObjectInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(44))));
    public static final u9.c f9853w = new u9.c("onDeviceSegmentationLogEvent", vh.v2.h(e2.c.o(d.class, new a(45))));
    public static final u9.c f9855x = new u9.c("onDeviceSmartReplyLogEvent", vh.v2.h(e2.c.o(d.class, new a(19))));
    public static final u9.c f9857y = new u9.c("onDeviceLanguageIdentificationLogEvent", vh.v2.h(e2.c.o(d.class, new a(21))));
    public static final u9.c f9859z = new u9.c("onDeviceTranslationLogEvent", vh.v2.h(e2.c.o(d.class, new a(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", vh.v2.h(e2.c.o(d.class, new a(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", vh.v2.h(e2.c.o(d.class, new a(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", vh.v2.h(e2.c.o(d.class, new a(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", vh.v2.h(e2.c.o(d.class, new a(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", vh.v2.h(e2.c.o(d.class, new a(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", vh.v2.h(e2.c.o(d.class, new a(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", vh.v2.h(e2.c.o(d.class, new a(42))));
    public static final u9.c f9815a0 = new u9.c("inputImageConstructionLogEvent", vh.v2.h(e2.c.o(d.class, new a(50))));
    public static final u9.c f9817b0 = new u9.c("leakedHandleEvent", vh.v2.h(e2.c.o(d.class, new a(51))));
    public static final u9.c f9819c0 = new u9.c("cameraSourceLogEvent", vh.v2.h(e2.c.o(d.class, new a(52))));
    public static final u9.c f9820d0 = new u9.c("imageLabelOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(53))));
    public static final u9.c f9821e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(54))));
    public static final u9.c f9823f0 = new u9.c("faceDetectionOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(60))));
    public static final u9.c f9825g0 = new u9.c("documentDetectionOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(85))));
    public static final u9.c f9826h0 = new u9.c("documentCroppingOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(86))));
    public static final u9.c f9828i0 = new u9.c("documentEnhancementOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(87))));
    public static final u9.c f9830j0 = new u9.c("nlClassifierOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(55))));
    public static final u9.c f9832k0 = new u9.c("nlClassifierClientLibraryLogEvent", vh.v2.h(e2.c.o(d.class, new a(56))));
    public static final u9.c f9834l0 = new u9.c("accelerationAllowlistLogEvent", vh.v2.h(e2.c.o(d.class, new a(57))));
    public static final u9.c m0 = new u9.c("toxicityDetectionCreateEvent", vh.v2.h(e2.c.o(d.class, new a(62))));
    public static final u9.c f9837n0 = new u9.c("toxicityDetectionLoadEvent", vh.v2.h(e2.c.o(d.class, new a(63))));
    public static final u9.c f9839o0 = new u9.c("toxicityDetectionInferenceEvent", vh.v2.h(e2.c.o(d.class, new a(64))));
    public static final u9.c f9841p0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(65))));
    public static final u9.c f9843q0 = new u9.c("customImageLabelOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(66))));
    public static final u9.c f9845r0 = new u9.c("codeScannerScanApiEvent", vh.v2.h(e2.c.o(d.class, new a(67))));
    public static final u9.c f9847s0 = new u9.c("codeScannerOptionalModuleEvent", vh.v2.h(e2.c.o(d.class, new a(68))));
    public static final u9.c f9849t0 = new u9.c("onDeviceExplicitContentCreateLogEvent", vh.v2.h(e2.c.o(d.class, new a(70))));
    public static final u9.c f9851u0 = new u9.c("onDeviceExplicitContentLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(71))));
    public static final u9.c f9852v0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(72))));
    public static final u9.c f9854w0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", vh.v2.h(e2.c.o(d.class, new a(73))));
    public static final u9.c f9856x0 = new u9.c("onDeviceFaceMeshCreateLogEvent", vh.v2.h(e2.c.o(d.class, new a(74))));
    public static final u9.c f9858y0 = new u9.c("onDeviceFaceMeshLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(75))));
    public static final u9.c f9860z0 = new u9.c("onDeviceFaceMeshLogEvent", vh.v2.h(e2.c.o(d.class, new a(76))));
    public static final u9.c A0 = new u9.c("aggregatedOnDeviceFaceMeshLogEvent", vh.v2.h(e2.c.o(d.class, new a(77))));
    public static final u9.c B0 = new u9.c("smartReplyOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(78))));
    public static final u9.c C0 = new u9.c("textDetectionOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(80))));
    public static final u9.c D0 = new u9.c("onDeviceImageQualityAnalysisCreateLogEvent", vh.v2.h(e2.c.o(d.class, new a(81))));
    public static final u9.c E0 = new u9.c("onDeviceImageQualityAnalysisLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(82))));
    public static final u9.c F0 = new u9.c("onDeviceImageQualityAnalysisLogEvent", vh.v2.h(e2.c.o(d.class, new a(83))));
    public static final u9.c G0 = new u9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", vh.v2.h(e2.c.o(d.class, new a(84))));
    public static final u9.c H0 = new u9.c("imageQualityAnalysisOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(88))));
    public static final u9.c I0 = new u9.c("imageCaptioningOptionalModuleLogEvent", vh.v2.h(e2.c.o(d.class, new a(89))));
    public static final u9.c J0 = new u9.c("onDeviceImageCaptioningCreateLogEvent", vh.v2.h(e2.c.o(d.class, new a(90))));
    public static final u9.c K0 = new u9.c("onDeviceImageCaptioningLoadLogEvent", vh.v2.h(e2.c.o(d.class, new a(91))));
    public static final u9.c L0 = new u9.c("onDeviceImageCaptioningInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(92))));
    public static final u9.c M0 = new u9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", vh.v2.h(e2.c.o(d.class, new a(93))));

    @Override
    public final void a(Object obj, Object obj2) {
        k7 k7Var = (k7) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f9816b, k7Var.f9894a);
        eVar.e(f9818c, k7Var.f9895b);
        eVar.e(d, null);
        eVar.e(e, null);
        eVar.e(f9822f, null);
        eVar.e(f9824g, null);
        eVar.e(h, null);
        eVar.e(f9827i, null);
        eVar.e(f9829j, null);
        eVar.e(f9831k, null);
        eVar.e(f9833l, null);
        eVar.e(f9835m, null);
        eVar.e(f9836n, null);
        eVar.e(f9838o, null);
        eVar.e(f9840p, null);
        eVar.e(f9842q, null);
        eVar.e(f9844r, null);
        eVar.e(f9846s, null);
        eVar.e(f9848t, null);
        eVar.e(f9850u, null);
        eVar.e(v, null);
        eVar.e(f9853w, null);
        eVar.e(f9855x, null);
        eVar.e(f9857y, null);
        eVar.e(f9859z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f9815a0, k7Var.f9896c);
        eVar.e(f9817b0, null);
        eVar.e(f9819c0, null);
        eVar.e(f9820d0, null);
        eVar.e(f9821e0, null);
        eVar.e(f9823f0, null);
        eVar.e(f9825g0, null);
        eVar.e(f9826h0, null);
        eVar.e(f9828i0, null);
        eVar.e(f9830j0, null);
        eVar.e(f9832k0, null);
        eVar.e(f9834l0, null);
        eVar.e(m0, null);
        eVar.e(f9837n0, null);
        eVar.e(f9839o0, null);
        eVar.e(f9841p0, null);
        eVar.e(f9843q0, null);
        eVar.e(f9845r0, null);
        eVar.e(f9847s0, null);
        eVar.e(f9849t0, null);
        eVar.e(f9851u0, null);
        eVar.e(f9852v0, null);
        eVar.e(f9854w0, null);
        eVar.e(f9856x0, null);
        eVar.e(f9858y0, null);
        eVar.e(f9860z0, null);
        eVar.e(A0, null);
        eVar.e(B0, null);
        eVar.e(C0, null);
        eVar.e(D0, null);
        eVar.e(E0, null);
        eVar.e(F0, null);
        eVar.e(G0, null);
        eVar.e(H0, null);
        eVar.e(I0, null);
        eVar.e(J0, null);
        eVar.e(K0, null);
        eVar.e(L0, null);
        eVar.e(M0, null);
    }
}
