package k7;
public final class g3 implements u9.d {
    public static final g3 f10538a = new Object();
    public static final u9.c f10540b = new u9.c("systemInfo", w.c.h(e2.c.o(d.class, new a(1))));
    public static final u9.c f10542c = new u9.c("eventName", w.c.h(e2.c.o(d.class, new a(2))));
    public static final u9.c d = new u9.c("isThickClient", w.c.h(e2.c.o(d.class, new a(37))));
    public static final u9.c f10545e = new u9.c("clientType", w.c.h(e2.c.o(d.class, new a(61))));
    public static final u9.c f10547f = new u9.c("modelDownloadLogEvent", w.c.h(e2.c.o(d.class, new a(3))));
    public static final u9.c f10549g = new u9.c("customModelLoadLogEvent", w.c.h(e2.c.o(d.class, new a(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(4))));
    public static final u9.c f10552i = new u9.c("customModelCreateLogEvent", w.c.h(e2.c.o(d.class, new a(29))));
    public static final u9.c f10554j = new u9.c("onDeviceFaceDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(5))));
    public static final u9.c f10556k = new u9.c("onDeviceFaceLoadLogEvent", w.c.h(e2.c.o(d.class, new a(59))));
    public static final u9.c f10558l = new u9.c("onDeviceTextDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(6))));
    public static final u9.c f10560m = new u9.c("onDeviceTextDetectionLoadLogEvent", w.c.h(e2.c.o(d.class, new a(79))));
    public static final u9.c f10561n = new u9.c("onDeviceBarcodeDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(7))));
    public static final u9.c f10563o = new u9.c("onDeviceBarcodeLoadLogEvent", w.c.h(e2.c.o(d.class, new a(58))));
    public static final u9.c f10565p = new u9.c("onDeviceImageLabelCreateLogEvent", w.c.h(e2.c.o(d.class, new a(48))));
    public static final u9.c f10567q = new u9.c("onDeviceImageLabelLoadLogEvent", w.c.h(e2.c.o(d.class, new a(49))));
    public static final u9.c f10569r = new u9.c("onDeviceImageLabelDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(18))));
    public static final u9.c f10571s = new u9.c("onDeviceObjectCreateLogEvent", w.c.h(e2.c.o(d.class, new a(26))));
    public static final u9.c f10573t = new u9.c("onDeviceObjectLoadLogEvent", w.c.h(e2.c.o(d.class, new a(27))));
    public static final u9.c f10575u = new u9.c("onDeviceObjectInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(44))));
    public static final u9.c f10578w = new u9.c("onDeviceSegmentationLogEvent", w.c.h(e2.c.o(d.class, new a(45))));
    public static final u9.c f10580x = new u9.c("onDeviceSmartReplyLogEvent", w.c.h(e2.c.o(d.class, new a(19))));
    public static final u9.c f10582y = new u9.c("onDeviceLanguageIdentificationLogEvent", w.c.h(e2.c.o(d.class, new a(21))));
    public static final u9.c f10584z = new u9.c("onDeviceTranslationLogEvent", w.c.h(e2.c.o(d.class, new a(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", w.c.h(e2.c.o(d.class, new a(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", w.c.h(e2.c.o(d.class, new a(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", w.c.h(e2.c.o(d.class, new a(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", w.c.h(e2.c.o(d.class, new a(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", w.c.h(e2.c.o(d.class, new a(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", w.c.h(e2.c.o(d.class, new a(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", w.c.h(e2.c.o(d.class, new a(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", w.c.h(e2.c.o(d.class, new a(42))));
    public static final u9.c f10539a0 = new u9.c("inputImageConstructionLogEvent", w.c.h(e2.c.o(d.class, new a(50))));
    public static final u9.c f10541b0 = new u9.c("leakedHandleEvent", w.c.h(e2.c.o(d.class, new a(51))));
    public static final u9.c f10543c0 = new u9.c("cameraSourceLogEvent", w.c.h(e2.c.o(d.class, new a(52))));
    public static final u9.c f10544d0 = new u9.c("imageLabelOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(53))));
    public static final u9.c f10546e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(54))));
    public static final u9.c f10548f0 = new u9.c("faceDetectionOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(60))));
    public static final u9.c f10550g0 = new u9.c("documentDetectionOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(85))));
    public static final u9.c f10551h0 = new u9.c("documentCroppingOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(86))));
    public static final u9.c f10553i0 = new u9.c("documentEnhancementOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(87))));
    public static final u9.c f10555j0 = new u9.c("nlClassifierOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(55))));
    public static final u9.c f10557k0 = new u9.c("nlClassifierClientLibraryLogEvent", w.c.h(e2.c.o(d.class, new a(56))));
    public static final u9.c f10559l0 = new u9.c("accelerationAllowlistLogEvent", w.c.h(e2.c.o(d.class, new a(57))));
    public static final u9.c m0 = new u9.c("toxicityDetectionCreateEvent", w.c.h(e2.c.o(d.class, new a(62))));
    public static final u9.c f10562n0 = new u9.c("toxicityDetectionLoadEvent", w.c.h(e2.c.o(d.class, new a(63))));
    public static final u9.c f10564o0 = new u9.c("toxicityDetectionInferenceEvent", w.c.h(e2.c.o(d.class, new a(64))));
    public static final u9.c f10566p0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(65))));
    public static final u9.c f10568q0 = new u9.c("customImageLabelOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(66))));
    public static final u9.c f10570r0 = new u9.c("codeScannerScanApiEvent", w.c.h(e2.c.o(d.class, new a(67))));
    public static final u9.c f10572s0 = new u9.c("codeScannerOptionalModuleEvent", w.c.h(e2.c.o(d.class, new a(68))));
    public static final u9.c f10574t0 = new u9.c("onDeviceExplicitContentCreateLogEvent", w.c.h(e2.c.o(d.class, new a(70))));
    public static final u9.c f10576u0 = new u9.c("onDeviceExplicitContentLoadLogEvent", w.c.h(e2.c.o(d.class, new a(71))));
    public static final u9.c f10577v0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(72))));
    public static final u9.c f10579w0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", w.c.h(e2.c.o(d.class, new a(73))));
    public static final u9.c f10581x0 = new u9.c("onDeviceFaceMeshCreateLogEvent", w.c.h(e2.c.o(d.class, new a(74))));
    public static final u9.c f10583y0 = new u9.c("onDeviceFaceMeshLoadLogEvent", w.c.h(e2.c.o(d.class, new a(75))));
    public static final u9.c f10585z0 = new u9.c("onDeviceFaceMeshLogEvent", w.c.h(e2.c.o(d.class, new a(76))));
    public static final u9.c A0 = new u9.c("aggregatedOnDeviceFaceMeshLogEvent", w.c.h(e2.c.o(d.class, new a(77))));
    public static final u9.c B0 = new u9.c("smartReplyOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(78))));
    public static final u9.c C0 = new u9.c("textDetectionOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(80))));
    public static final u9.c D0 = new u9.c("onDeviceImageQualityAnalysisCreateLogEvent", w.c.h(e2.c.o(d.class, new a(81))));
    public static final u9.c E0 = new u9.c("onDeviceImageQualityAnalysisLoadLogEvent", w.c.h(e2.c.o(d.class, new a(82))));
    public static final u9.c F0 = new u9.c("onDeviceImageQualityAnalysisLogEvent", w.c.h(e2.c.o(d.class, new a(83))));
    public static final u9.c G0 = new u9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", w.c.h(e2.c.o(d.class, new a(84))));
    public static final u9.c H0 = new u9.c("imageQualityAnalysisOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(88))));
    public static final u9.c I0 = new u9.c("imageCaptioningOptionalModuleLogEvent", w.c.h(e2.c.o(d.class, new a(89))));
    public static final u9.c J0 = new u9.c("onDeviceImageCaptioningCreateLogEvent", w.c.h(e2.c.o(d.class, new a(90))));
    public static final u9.c K0 = new u9.c("onDeviceImageCaptioningLoadLogEvent", w.c.h(e2.c.o(d.class, new a(91))));
    public static final u9.c L0 = new u9.c("onDeviceImageCaptioningInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(92))));
    public static final u9.c M0 = new u9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", w.c.h(e2.c.o(d.class, new a(93))));

    @Override
    public final void a(Object obj, Object obj2) {
        k7 k7Var = (k7) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f10540b, k7Var.f10620a);
        eVar.e(f10542c, k7Var.f10621b);
        eVar.e(d, null);
        eVar.e(f10545e, null);
        eVar.e(f10547f, null);
        eVar.e(f10549g, null);
        eVar.e(h, null);
        eVar.e(f10552i, null);
        eVar.e(f10554j, null);
        eVar.e(f10556k, null);
        eVar.e(f10558l, null);
        eVar.e(f10560m, null);
        eVar.e(f10561n, null);
        eVar.e(f10563o, null);
        eVar.e(f10565p, null);
        eVar.e(f10567q, null);
        eVar.e(f10569r, null);
        eVar.e(f10571s, null);
        eVar.e(f10573t, null);
        eVar.e(f10575u, null);
        eVar.e(v, null);
        eVar.e(f10578w, null);
        eVar.e(f10580x, null);
        eVar.e(f10582y, null);
        eVar.e(f10584z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f10539a0, k7Var.f10622c);
        eVar.e(f10541b0, null);
        eVar.e(f10543c0, null);
        eVar.e(f10544d0, null);
        eVar.e(f10546e0, null);
        eVar.e(f10548f0, null);
        eVar.e(f10550g0, null);
        eVar.e(f10551h0, null);
        eVar.e(f10553i0, null);
        eVar.e(f10555j0, null);
        eVar.e(f10557k0, null);
        eVar.e(f10559l0, null);
        eVar.e(m0, null);
        eVar.e(f10562n0, null);
        eVar.e(f10564o0, null);
        eVar.e(f10566p0, null);
        eVar.e(f10568q0, null);
        eVar.e(f10570r0, null);
        eVar.e(f10572s0, null);
        eVar.e(f10574t0, null);
        eVar.e(f10576u0, null);
        eVar.e(f10577v0, null);
        eVar.e(f10579w0, null);
        eVar.e(f10581x0, null);
        eVar.e(f10583y0, null);
        eVar.e(f10585z0, null);
        eVar.e(A0, null);
        eVar.e(B0, null);
        eVar.e(C0, null);
        eVar.e(D0, null);
        eVar.e(E0, null);
        eVar.e(F0, null);
        eVar.e(G0, null);
        eVar.e(H0, null);
        eVar.e(I0, null);
        eVar.e(J0, null);
        eVar.e(K0, null);
        eVar.e(L0, null);
        eVar.e(M0, null);
    }
}
