package k7;

public enum gb implements u {
    NO_ERROR(0),
    NATIVE_LIBRARY_LOAD_ERROR(1),
    INCOMPATIBLE_OUTPUT(2),
    INCOMPATIBLE_TFLITE_VERSION(3),
    MISSING_OP(4),
    DATA_TYPE_ERROR(6),
    TFLITE_INTERNAL_ERROR(7),
    TFLITE_UNKNOWN_ERROR(8),
    REMOTE_MODEL_INVALID(9),
    TIME_OUT_FETCHING_MODEL_METADATA(5),
    MODEL_NOT_DOWNLOADED(100),
    URI_EXPIRED(101),
    NO_NETWORK_CONNECTION(102),
    METERED_NETWORK(103),
    DOWNLOAD_FAILED(104),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(105),
    NATIVE_LIBRARY_LOAD_ERROR(106),
    REMOTE_MODEL_INVALID(107),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(108),
    NATIVE_LIBRARY_LOAD_ERROR(109),
    REMOTE_MODEL_INVALID(110),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(111),
    NATIVE_LIBRARY_LOAD_ERROR(112),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(113),
    NATIVE_LIBRARY_LOAD_ERROR(114),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(115),
    NATIVE_LIBRARY_LOAD_ERROR(116),
    OPTIONAL_MODULE_NOT_AVAILABLE(201),
    OPTIONAL_MODULE_INIT_ERROR(202),
    OPTIONAL_MODULE_INFERENCE_ERROR(203),
    NATIVE_LIBRARY_LOAD_ERROR(204),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(205),
    NATIVE_LIBRARY_LOAD_ERROR(206),
    OPTIONAL_MODULE_CREATE_ERROR(207),
    CAMERAX_SOURCE_ERROR(301),
    CAMERA1_SOURCE_CANT_START_ERROR(302),
    CAMERA1_SOURCE_NO_SUITABLE_SIZE_ERROR(303),
    CAMERA1_SOURCE_NO_SUITABLE_FPS_ERROR(304),
    CAMERA1_SOURCE_NO_BYTE_SOURCE_FOUND_ERROR(305),
    CODE_SCANNER_UNAVAILABLE(400),
    CODE_SCANNER_CANCELLED(401),
    CODE_SCANNER_CAMERA_PERMISSION_NOT_GRANTED(402),
    CODE_SCANNER_APP_NAME_UNAVAILABLE(403),
    CODE_SCANNER_TASK_IN_PROGRESS(404),
    CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR(405),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(406),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(407),
    LOW_LIGHT_AUTO_EXPOSURE_COMPUTATION_FAILURE(500),
    LOW_LIGHT_IMAGE_CAPTURE_PROCESSING_FAILURE(501),
    PERMISSION_DENIED(600),
    CANCELLED(601),
    GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(602),
    LOW_MEMORY(603),
    UNKNOWN_ERROR(9999);


    public final int f14663a;

    gb(int i10) {
        this.f14663a = i10;
    }

    @Override
    public final int zza() {
        return this.f14663a;
    }
}
