package w7;
public final class g3 implements ia.d {
    public static final g3 f44652a = new Object();
    public static final ia.c f44654b = new ia.c("systemInfo", hg.c.o(w.c.j(d.class, new a(1))));
    public static final ia.c f44656c = new ia.c("eventName", hg.c.o(w.c.j(d.class, new a(2))));
    public static final ia.c d = new ia.c("isThickClient", hg.c.o(w.c.j(d.class, new a(37))));
    public static final ia.c e = new ia.c("clientType", hg.c.o(w.c.j(d.class, new a(61))));
    public static final ia.c f44660f = new ia.c("modelDownloadLogEvent", hg.c.o(w.c.j(d.class, new a(3))));
    public static final ia.c f44662g = new ia.c("customModelLoadLogEvent", hg.c.o(w.c.j(d.class, new a(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(4))));
    public static final ia.c f44665i = new ia.c("customModelCreateLogEvent", hg.c.o(w.c.j(d.class, new a(29))));
    public static final ia.c f44667j = new ia.c("onDeviceFaceDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(5))));
    public static final ia.c f44669k = new ia.c("onDeviceFaceLoadLogEvent", hg.c.o(w.c.j(d.class, new a(59))));
    public static final ia.c f44671l = new ia.c("onDeviceTextDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(6))));
    public static final ia.c f44673m = new ia.c("onDeviceTextDetectionLoadLogEvent", hg.c.o(w.c.j(d.class, new a(79))));
    public static final ia.c f44674n = new ia.c("onDeviceBarcodeDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(7))));
    public static final ia.c f44676o = new ia.c("onDeviceBarcodeLoadLogEvent", hg.c.o(w.c.j(d.class, new a(58))));
    public static final ia.c f44678p = new ia.c("onDeviceImageLabelCreateLogEvent", hg.c.o(w.c.j(d.class, new a(48))));
    public static final ia.c f44680q = new ia.c("onDeviceImageLabelLoadLogEvent", hg.c.o(w.c.j(d.class, new a(49))));
    public static final ia.c f44682r = new ia.c("onDeviceImageLabelDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(18))));
    public static final ia.c f44684s = new ia.c("onDeviceObjectCreateLogEvent", hg.c.o(w.c.j(d.class, new a(26))));
    public static final ia.c f44686t = new ia.c("onDeviceObjectLoadLogEvent", hg.c.o(w.c.j(d.class, new a(27))));
    public static final ia.c f44688u = new ia.c("onDeviceObjectInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(44))));
    public static final ia.c f44691w = new ia.c("onDeviceSegmentationLogEvent", hg.c.o(w.c.j(d.class, new a(45))));
    public static final ia.c f44693x = new ia.c("onDeviceSmartReplyLogEvent", hg.c.o(w.c.j(d.class, new a(19))));
    public static final ia.c f44695y = new ia.c("onDeviceLanguageIdentificationLogEvent", hg.c.o(w.c.j(d.class, new a(21))));
    public static final ia.c f44697z = new ia.c("onDeviceTranslationLogEvent", hg.c.o(w.c.j(d.class, new a(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hg.c.o(w.c.j(d.class, new a(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hg.c.o(w.c.j(d.class, new a(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hg.c.o(w.c.j(d.class, new a(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hg.c.o(w.c.j(d.class, new a(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hg.c.o(w.c.j(d.class, new a(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hg.c.o(w.c.j(d.class, new a(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hg.c.o(w.c.j(d.class, new a(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hg.c.o(w.c.j(d.class, new a(42))));
    public static final ia.c f44653a0 = new ia.c("inputImageConstructionLogEvent", hg.c.o(w.c.j(d.class, new a(50))));
    public static final ia.c f44655b0 = new ia.c("leakedHandleEvent", hg.c.o(w.c.j(d.class, new a(51))));
    public static final ia.c f44657c0 = new ia.c("cameraSourceLogEvent", hg.c.o(w.c.j(d.class, new a(52))));
    public static final ia.c f44658d0 = new ia.c("imageLabelOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(53))));
    public static final ia.c f44659e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(54))));
    public static final ia.c f44661f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(60))));
    public static final ia.c f44663g0 = new ia.c("documentDetectionOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(85))));
    public static final ia.c f44664h0 = new ia.c("documentCroppingOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(86))));
    public static final ia.c f44666i0 = new ia.c("documentEnhancementOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(87))));
    public static final ia.c f44668j0 = new ia.c("nlClassifierOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(55))));
    public static final ia.c f44670k0 = new ia.c("nlClassifierClientLibraryLogEvent", hg.c.o(w.c.j(d.class, new a(56))));
    public static final ia.c f44672l0 = new ia.c("accelerationAllowlistLogEvent", hg.c.o(w.c.j(d.class, new a(57))));
    public static final ia.c m0 = new ia.c("toxicityDetectionCreateEvent", hg.c.o(w.c.j(d.class, new a(62))));
    public static final ia.c f44675n0 = new ia.c("toxicityDetectionLoadEvent", hg.c.o(w.c.j(d.class, new a(63))));
    public static final ia.c f44677o0 = new ia.c("toxicityDetectionInferenceEvent", hg.c.o(w.c.j(d.class, new a(64))));
    public static final ia.c f44679p0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(65))));
    public static final ia.c f44681q0 = new ia.c("customImageLabelOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(66))));
    public static final ia.c f44683r0 = new ia.c("codeScannerScanApiEvent", hg.c.o(w.c.j(d.class, new a(67))));
    public static final ia.c f44685s0 = new ia.c("codeScannerOptionalModuleEvent", hg.c.o(w.c.j(d.class, new a(68))));
    public static final ia.c f44687t0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hg.c.o(w.c.j(d.class, new a(70))));
    public static final ia.c f44689u0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hg.c.o(w.c.j(d.class, new a(71))));
    public static final ia.c f44690v0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(72))));
    public static final ia.c f44692w0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hg.c.o(w.c.j(d.class, new a(73))));
    public static final ia.c f44694x0 = new ia.c("onDeviceFaceMeshCreateLogEvent", hg.c.o(w.c.j(d.class, new a(74))));
    public static final ia.c f44696y0 = new ia.c("onDeviceFaceMeshLoadLogEvent", hg.c.o(w.c.j(d.class, new a(75))));
    public static final ia.c f44698z0 = new ia.c("onDeviceFaceMeshLogEvent", hg.c.o(w.c.j(d.class, new a(76))));
    public static final ia.c A0 = new ia.c("aggregatedOnDeviceFaceMeshLogEvent", hg.c.o(w.c.j(d.class, new a(77))));
    public static final ia.c B0 = new ia.c("smartReplyOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(78))));
    public static final ia.c C0 = new ia.c("textDetectionOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(80))));
    public static final ia.c D0 = new ia.c("onDeviceImageQualityAnalysisCreateLogEvent", hg.c.o(w.c.j(d.class, new a(81))));
    public static final ia.c E0 = new ia.c("onDeviceImageQualityAnalysisLoadLogEvent", hg.c.o(w.c.j(d.class, new a(82))));
    public static final ia.c F0 = new ia.c("onDeviceImageQualityAnalysisLogEvent", hg.c.o(w.c.j(d.class, new a(83))));
    public static final ia.c G0 = new ia.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", hg.c.o(w.c.j(d.class, new a(84))));
    public static final ia.c H0 = new ia.c("imageQualityAnalysisOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(88))));
    public static final ia.c I0 = new ia.c("imageCaptioningOptionalModuleLogEvent", hg.c.o(w.c.j(d.class, new a(89))));
    public static final ia.c J0 = new ia.c("onDeviceImageCaptioningCreateLogEvent", hg.c.o(w.c.j(d.class, new a(90))));
    public static final ia.c K0 = new ia.c("onDeviceImageCaptioningLoadLogEvent", hg.c.o(w.c.j(d.class, new a(91))));
    public static final ia.c L0 = new ia.c("onDeviceImageCaptioningInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(92))));
    public static final ia.c M0 = new ia.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", hg.c.o(w.c.j(d.class, new a(93))));

    @Override
    public final void a(Object obj, Object obj2) {
        k7 k7Var = (k7) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f44654b, k7Var.f44730a);
        eVar.a(f44656c, k7Var.f44731b);
        eVar.a(d, null);
        eVar.a(e, null);
        eVar.a(f44660f, null);
        eVar.a(f44662g, null);
        eVar.a(h, null);
        eVar.a(f44665i, null);
        eVar.a(f44667j, null);
        eVar.a(f44669k, null);
        eVar.a(f44671l, null);
        eVar.a(f44673m, null);
        eVar.a(f44674n, null);
        eVar.a(f44676o, null);
        eVar.a(f44678p, null);
        eVar.a(f44680q, null);
        eVar.a(f44682r, null);
        eVar.a(f44684s, null);
        eVar.a(f44686t, null);
        eVar.a(f44688u, null);
        eVar.a(v, null);
        eVar.a(f44691w, null);
        eVar.a(f44693x, null);
        eVar.a(f44695y, null);
        eVar.a(f44697z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f44653a0, k7Var.f44732c);
        eVar.a(f44655b0, null);
        eVar.a(f44657c0, null);
        eVar.a(f44658d0, null);
        eVar.a(f44659e0, null);
        eVar.a(f44661f0, null);
        eVar.a(f44663g0, null);
        eVar.a(f44664h0, null);
        eVar.a(f44666i0, null);
        eVar.a(f44668j0, null);
        eVar.a(f44670k0, null);
        eVar.a(f44672l0, null);
        eVar.a(m0, null);
        eVar.a(f44675n0, null);
        eVar.a(f44677o0, null);
        eVar.a(f44679p0, null);
        eVar.a(f44681q0, null);
        eVar.a(f44683r0, null);
        eVar.a(f44685s0, null);
        eVar.a(f44687t0, null);
        eVar.a(f44689u0, null);
        eVar.a(f44690v0, null);
        eVar.a(f44692w0, null);
        eVar.a(f44694x0, null);
        eVar.a(f44696y0, null);
        eVar.a(f44698z0, null);
        eVar.a(A0, null);
        eVar.a(B0, null);
        eVar.a(C0, null);
        eVar.a(D0, null);
        eVar.a(E0, null);
        eVar.a(F0, null);
        eVar.a(G0, null);
        eVar.a(H0, null);
        eVar.a(I0, null);
        eVar.a(J0, null);
        eVar.a(K0, null);
        eVar.a(L0, null);
        eVar.a(M0, null);
    }
}
