package z7;
public final class g5 implements ia.d {
    public static final g5 f48530a = new Object();
    public static final ia.c f48533b = new ia.c("systemInfo", hg.c.m(v7.j.m(w.class, new s(1))));
    public static final ia.c f48536c = new ia.c("eventName", hg.c.m(v7.j.m(w.class, new s(2))));
    public static final ia.c d = new ia.c("isThickClient", hg.c.m(v7.j.m(w.class, new s(37))));
    public static final ia.c e = new ia.c("clientType", hg.c.m(v7.j.m(w.class, new s(61))));
    public static final ia.c f48543f = new ia.c("modelDownloadLogEvent", hg.c.m(v7.j.m(w.class, new s(3))));
    public static final ia.c f48546g = new ia.c("customModelLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(4))));
    public static final ia.c f48551i = new ia.c("customModelCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(29))));
    public static final ia.c f48554j = new ia.c("onDeviceFaceDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(5))));
    public static final ia.c f48557k = new ia.c("onDeviceFaceLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(59))));
    public static final ia.c f48560l = new ia.c("onDeviceTextDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(6))));
    public static final ia.c f48562m = new ia.c("onDeviceTextDetectionLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(79))));
    public static final ia.c f48564n = new ia.c("onDeviceBarcodeDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(7))));
    public static final ia.c f48567o = new ia.c("onDeviceBarcodeLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(58))));
    public static final ia.c f48570p = new ia.c("onDeviceImageLabelCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(48))));
    public static final ia.c f48573q = new ia.c("onDeviceImageLabelLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(49))));
    public static final ia.c f48576r = new ia.c("onDeviceImageLabelDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(18))));
    public static final ia.c f48579s = new ia.c("onDeviceObjectCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(26))));
    public static final ia.c f48582t = new ia.c("onDeviceObjectLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(27))));
    public static final ia.c f48585u = new ia.c("onDeviceObjectInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(44))));
    public static final ia.c f48590w = new ia.c("onDeviceSegmentationLogEvent", hg.c.m(v7.j.m(w.class, new s(45))));
    public static final ia.c f48593x = new ia.c("onDeviceSmartReplyLogEvent", hg.c.m(v7.j.m(w.class, new s(19))));
    public static final ia.c f48596y = new ia.c("onDeviceLanguageIdentificationLogEvent", hg.c.m(v7.j.m(w.class, new s(21))));
    public static final ia.c f48599z = new ia.c("onDeviceTranslationLogEvent", hg.c.m(v7.j.m(w.class, new s(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hg.c.m(v7.j.m(w.class, new s(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hg.c.m(v7.j.m(w.class, new s(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hg.c.m(v7.j.m(w.class, new s(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hg.c.m(v7.j.m(w.class, new s(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hg.c.m(v7.j.m(w.class, new s(42))));
    public static final ia.c f48531a0 = new ia.c("inputImageConstructionLogEvent", hg.c.m(v7.j.m(w.class, new s(50))));
    public static final ia.c f48534b0 = new ia.c("leakedHandleEvent", hg.c.m(v7.j.m(w.class, new s(51))));
    public static final ia.c f48537c0 = new ia.c("cameraSourceLogEvent", hg.c.m(v7.j.m(w.class, new s(52))));
    public static final ia.c f48539d0 = new ia.c("imageLabelOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(53))));
    public static final ia.c f48541e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(54))));
    public static final ia.c f48544f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(60))));
    public static final ia.c f48547g0 = new ia.c("documentDetectionOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(85))));
    public static final ia.c f48549h0 = new ia.c("documentCroppingOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(86))));
    public static final ia.c f48552i0 = new ia.c("documentEnhancementOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(87))));
    public static final ia.c f48555j0 = new ia.c("nlClassifierOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(55))));
    public static final ia.c f48558k0 = new ia.c("nlClassifierClientLibraryLogEvent", hg.c.m(v7.j.m(w.class, new s(56))));
    public static final ia.c f48561l0 = new ia.c("accelerationAllowlistLogEvent", hg.c.m(v7.j.m(w.class, new s(57))));
    public static final ia.c m0 = new ia.c("toxicityDetectionCreateEvent", hg.c.m(v7.j.m(w.class, new s(62))));
    public static final ia.c f48565n0 = new ia.c("toxicityDetectionLoadEvent", hg.c.m(v7.j.m(w.class, new s(63))));
    public static final ia.c f48568o0 = new ia.c("toxicityDetectionInferenceEvent", hg.c.m(v7.j.m(w.class, new s(64))));
    public static final ia.c f48571p0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(65))));
    public static final ia.c f48574q0 = new ia.c("customImageLabelOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(66))));
    public static final ia.c f48577r0 = new ia.c("codeScannerScanApiEvent", hg.c.m(v7.j.m(w.class, new s(67))));
    public static final ia.c f48580s0 = new ia.c("codeScannerOptionalModuleEvent", hg.c.m(v7.j.m(w.class, new s(68))));
    public static final ia.c f48583t0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(70))));
    public static final ia.c f48586u0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(71))));
    public static final ia.c f48588v0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(72))));
    public static final ia.c f48591w0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hg.c.m(v7.j.m(w.class, new s(73))));
    public static final ia.c f48594x0 = new ia.c("onDeviceFaceMeshCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(74))));
    public static final ia.c f48597y0 = new ia.c("onDeviceFaceMeshLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(75))));
    public static final ia.c f48600z0 = new ia.c("onDeviceFaceMeshLogEvent", hg.c.m(v7.j.m(w.class, new s(76))));
    public static final ia.c A0 = new ia.c("aggregatedOnDeviceFaceMeshLogEvent", hg.c.m(v7.j.m(w.class, new s(77))));
    public static final ia.c B0 = new ia.c("smartReplyOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(78))));
    public static final ia.c C0 = new ia.c("textDetectionOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(80))));
    public static final ia.c D0 = new ia.c("onDeviceImageQualityAnalysisCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(81))));
    public static final ia.c E0 = new ia.c("onDeviceImageQualityAnalysisLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(82))));
    public static final ia.c F0 = new ia.c("onDeviceImageQualityAnalysisLogEvent", hg.c.m(v7.j.m(w.class, new s(83))));
    public static final ia.c G0 = new ia.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", hg.c.m(v7.j.m(w.class, new s(84))));
    public static final ia.c H0 = new ia.c("imageQualityAnalysisOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(88))));
    public static final ia.c I0 = new ia.c("imageCaptioningOptionalModuleLogEvent", hg.c.m(v7.j.m(w.class, new s(89))));
    public static final ia.c J0 = new ia.c("onDeviceImageCaptioningCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(90))));
    public static final ia.c K0 = new ia.c("onDeviceImageCaptioningLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(91))));
    public static final ia.c L0 = new ia.c("onDeviceImageCaptioningInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(92))));
    public static final ia.c M0 = new ia.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", hg.c.m(v7.j.m(w.class, new s(93))));
    public static final ia.c N0 = new ia.c("onDeviceDocumentDetectionCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(94))));
    public static final ia.c O0 = new ia.c("onDeviceDocumentDetectionLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(95))));
    public static final ia.c P0 = new ia.c("onDeviceDocumentDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(96))));
    public static final ia.c Q0 = new ia.c("aggregatedOnDeviceDocumentDetectionLogEvent", hg.c.m(v7.j.m(w.class, new s(97))));
    public static final ia.c R0 = new ia.c("onDeviceDocumentCroppingCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(98))));
    public static final ia.c S0 = new ia.c("onDeviceDocumentCroppingLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(99))));
    public static final ia.c T0 = new ia.c("onDeviceDocumentCroppingLogEvent", hg.c.m(v7.j.m(w.class, new s(100))));
    public static final ia.c U0 = new ia.c("aggregatedOnDeviceDocumentCroppingLogEvent", hg.c.m(v7.j.m(w.class, new s(101))));
    public static final ia.c V0 = new ia.c("onDeviceDocumentEnhancementCreateLogEvent", hg.c.m(v7.j.m(w.class, new s(102))));
    public static final ia.c W0 = new ia.c("onDeviceDocumentEnhancementLoadLogEvent", hg.c.m(v7.j.m(w.class, new s(103))));
    public static final ia.c X0 = v7.j.f(104, ia.c.a("onDeviceDocumentEnhancementLogEvent"));
    public static final ia.c Y0 = v7.j.f(105, ia.c.a("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    public static final ia.c Z0 = v7.j.f(106, ia.c.a("scannerAutoZoomEvent"));
    public static final ia.c f48532a1 = v7.j.f(107, ia.c.a("lowLightAutoExposureComputationEvent"));
    public static final ia.c f48535b1 = v7.j.f(108, ia.c.a("lowLightFrameProcessEvent"));
    public static final ia.c f48538c1 = v7.j.f(109, ia.c.a("lowLightSceneDetectionEvent"));
    public static final ia.c f48540d1 = v7.j.f(110, ia.c.a("onDeviceStainRemovalLogEvent"));
    public static final ia.c f48542e1 = v7.j.f(111, ia.c.a("aggregatedOnDeviceStainRemovalLogEvent"));
    public static final ia.c f48545f1 = v7.j.f(112, ia.c.a("stainRemovalOptionalModuleLogEvent"));
    public static final ia.c f48548g1 = v7.j.f(113, ia.c.a("onDeviceShadowRemovalLogEvent"));
    public static final ia.c f48550h1 = v7.j.f(114, ia.c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
    public static final ia.c f48553i1 = v7.j.f(115, ia.c.a("shadowRemovalOptionalModuleLogEvent"));
    public static final ia.c f48556j1 = v7.j.f(116, ia.c.a("onDeviceDigitalInkSegmentationLogEvent"));
    public static final ia.c f48559k1 = v7.j.f(117, ia.c.a("onDeviceDocumentScannerStartLogEvent"));
    public static final ia.c l1 = v7.j.f(118, ia.c.a("onDeviceDocumentScannerFinishLogEvent"));
    public static final ia.c f48563m1 = v7.j.f(119, ia.c.a("onDeviceDocumentScannerUiStartLogEvent"));
    public static final ia.c f48566n1 = v7.j.f(120, ia.c.a("onDeviceDocumentScannerUiFinishLogEvent"));
    public static final ia.c f48569o1 = v7.j.f(121, ia.c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
    public static final ia.c f48572p1 = v7.j.f(122, ia.c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    public static final ia.c f48575q1 = v7.j.f(123, ia.c.a("onDeviceDocumentScannerUiCreateLogEvent"));
    public static final ia.c f48578r1 = v7.j.f(124, ia.c.a("onDeviceSubjectSegmentationCreateLogEvent"));
    public static final ia.c f48581s1 = v7.j.f(125, ia.c.a("onDeviceSubjectSegmentationLoadLogEvent"));
    public static final ia.c f48584t1 = v7.j.f(126, ia.c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
    public static final ia.c f48587u1 = v7.j.f(127, ia.c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    public static final ia.c f48589v1 = v7.j.f(128, ia.c.a("subjectSegmentationOptionalModuleLogEvent"));
    public static final ia.c f48592w1 = v7.j.f(129, ia.c.a("documentScannerUiModuleScreenViewEvent"));
    public static final ia.c f48595x1 = v7.j.f(130, ia.c.a("documentScannerUiModuleScreenClickEvent"));
    public static final ia.c f48598y1 = v7.j.f(131, ia.c.a("documentScannerUiModuleScreenErrorEvent"));

    @Override
    public final void a(Object obj, Object obj2) {
        ib ibVar = (ib) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f48533b, ibVar.f48767a);
        eVar.a(f48536c, ibVar.f48768b);
        eVar.a(d, null);
        eVar.a(e, ibVar.f48769c);
        eVar.a(f48543f, null);
        eVar.a(f48546g, null);
        eVar.a(h, null);
        eVar.a(f48551i, null);
        eVar.a(f48554j, null);
        eVar.a(f48557k, null);
        eVar.a(f48560l, null);
        eVar.a(f48562m, null);
        eVar.a(f48564n, null);
        eVar.a(f48567o, null);
        eVar.a(f48570p, null);
        eVar.a(f48573q, null);
        eVar.a(f48576r, null);
        eVar.a(f48579s, null);
        eVar.a(f48582t, null);
        eVar.a(f48585u, null);
        eVar.a(v, null);
        eVar.a(f48590w, null);
        eVar.a(f48593x, null);
        eVar.a(f48596y, null);
        eVar.a(f48599z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f48531a0, null);
        eVar.a(f48534b0, null);
        eVar.a(f48537c0, null);
        eVar.a(f48539d0, null);
        eVar.a(f48541e0, null);
        eVar.a(f48544f0, null);
        eVar.a(f48547g0, null);
        eVar.a(f48549h0, null);
        eVar.a(f48552i0, null);
        eVar.a(f48555j0, null);
        eVar.a(f48558k0, null);
        eVar.a(f48561l0, null);
        eVar.a(m0, null);
        eVar.a(f48565n0, null);
        eVar.a(f48568o0, null);
        eVar.a(f48571p0, null);
        eVar.a(f48574q0, null);
        eVar.a(f48577r0, null);
        eVar.a(f48580s0, null);
        eVar.a(f48583t0, null);
        eVar.a(f48586u0, null);
        eVar.a(f48588v0, null);
        eVar.a(f48591w0, null);
        eVar.a(f48594x0, null);
        eVar.a(f48597y0, null);
        eVar.a(f48600z0, null);
        eVar.a(A0, null);
        eVar.a(B0, null);
        eVar.a(C0, null);
        eVar.a(D0, null);
        eVar.a(E0, null);
        eVar.a(F0, null);
        eVar.a(G0, null);
        eVar.a(H0, null);
        eVar.a(I0, null);
        eVar.a(J0, null);
        eVar.a(K0, null);
        eVar.a(L0, null);
        eVar.a(M0, null);
        eVar.a(N0, null);
        eVar.a(O0, null);
        eVar.a(P0, null);
        eVar.a(Q0, null);
        eVar.a(R0, null);
        eVar.a(S0, null);
        eVar.a(T0, null);
        eVar.a(U0, null);
        eVar.a(V0, null);
        eVar.a(W0, null);
        eVar.a(X0, null);
        eVar.a(Y0, null);
        eVar.a(Z0, null);
        eVar.a(f48532a1, null);
        eVar.a(f48535b1, null);
        eVar.a(f48538c1, null);
        eVar.a(f48540d1, null);
        eVar.a(f48542e1, null);
        eVar.a(f48545f1, null);
        eVar.a(f48548g1, null);
        eVar.a(f48550h1, null);
        eVar.a(f48553i1, null);
        eVar.a(f48556j1, null);
        eVar.a(f48559k1, null);
        eVar.a(l1, null);
        eVar.a(f48563m1, null);
        eVar.a(f48566n1, null);
        eVar.a(f48569o1, null);
        eVar.a(f48572p1, null);
        eVar.a(f48575q1, null);
        eVar.a(f48578r1, ibVar.d);
        eVar.a(f48581s1, ibVar.e);
        eVar.a(f48584t1, ibVar.f48770f);
        eVar.a(f48587u1, ibVar.f48771g);
        eVar.a(f48589v1, null);
        eVar.a(f48592w1, null);
        eVar.a(f48595x1, null);
        eVar.a(f48598y1, null);
    }
}
