package z7;
public final class g5 implements ia.d {
    public static final g5 f50870a = new Object();
    public static final ia.c f50873b = new ia.c("systemInfo", i2.g.n(w.f.k(w.class, new s(1))));
    public static final ia.c f50876c = new ia.c("eventName", i2.g.n(w.f.k(w.class, new s(2))));
    public static final ia.c d = new ia.c("isThickClient", i2.g.n(w.f.k(w.class, new s(37))));
    public static final ia.c f50881e = new ia.c("clientType", i2.g.n(w.f.k(w.class, new s(61))));
    public static final ia.c f50884f = new ia.c("modelDownloadLogEvent", i2.g.n(w.f.k(w.class, new s(3))));
    public static final ia.c f50887g = new ia.c("customModelLoadLogEvent", i2.g.n(w.f.k(w.class, new s(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(4))));
    public static final ia.c f50892i = new ia.c("customModelCreateLogEvent", i2.g.n(w.f.k(w.class, new s(29))));
    public static final ia.c f50895j = new ia.c("onDeviceFaceDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(5))));
    public static final ia.c f50898k = new ia.c("onDeviceFaceLoadLogEvent", i2.g.n(w.f.k(w.class, new s(59))));
    public static final ia.c f50901l = new ia.c("onDeviceTextDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(6))));
    public static final ia.c f50903m = new ia.c("onDeviceTextDetectionLoadLogEvent", i2.g.n(w.f.k(w.class, new s(79))));
    public static final ia.c f50905n = new ia.c("onDeviceBarcodeDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(7))));
    public static final ia.c f50908o = new ia.c("onDeviceBarcodeLoadLogEvent", i2.g.n(w.f.k(w.class, new s(58))));
    public static final ia.c f50911p = new ia.c("onDeviceImageLabelCreateLogEvent", i2.g.n(w.f.k(w.class, new s(48))));
    public static final ia.c f50914q = new ia.c("onDeviceImageLabelLoadLogEvent", i2.g.n(w.f.k(w.class, new s(49))));
    public static final ia.c f50917r = new ia.c("onDeviceImageLabelDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(18))));
    public static final ia.c f50920s = new ia.c("onDeviceObjectCreateLogEvent", i2.g.n(w.f.k(w.class, new s(26))));
    public static final ia.c f50923t = new ia.c("onDeviceObjectLoadLogEvent", i2.g.n(w.f.k(w.class, new s(27))));
    public static final ia.c f50926u = new ia.c("onDeviceObjectInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(44))));
    public static final ia.c f50931w = new ia.c("onDeviceSegmentationLogEvent", i2.g.n(w.f.k(w.class, new s(45))));
    public static final ia.c f50934x = new ia.c("onDeviceSmartReplyLogEvent", i2.g.n(w.f.k(w.class, new s(19))));
    public static final ia.c f50937y = new ia.c("onDeviceLanguageIdentificationLogEvent", i2.g.n(w.f.k(w.class, new s(21))));
    public static final ia.c f50940z = new ia.c("onDeviceTranslationLogEvent", i2.g.n(w.f.k(w.class, new s(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", i2.g.n(w.f.k(w.class, new s(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", i2.g.n(w.f.k(w.class, new s(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", i2.g.n(w.f.k(w.class, new s(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", i2.g.n(w.f.k(w.class, new s(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", i2.g.n(w.f.k(w.class, new s(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", i2.g.n(w.f.k(w.class, new s(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", i2.g.n(w.f.k(w.class, new s(42))));
    public static final ia.c f50871a0 = new ia.c("inputImageConstructionLogEvent", i2.g.n(w.f.k(w.class, new s(50))));
    public static final ia.c f50874b0 = new ia.c("leakedHandleEvent", i2.g.n(w.f.k(w.class, new s(51))));
    public static final ia.c f50877c0 = new ia.c("cameraSourceLogEvent", i2.g.n(w.f.k(w.class, new s(52))));
    public static final ia.c f50879d0 = new ia.c("imageLabelOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(53))));
    public static final ia.c f50882e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(54))));
    public static final ia.c f50885f0 = new ia.c("faceDetectionOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(60))));
    public static final ia.c f50888g0 = new ia.c("documentDetectionOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(85))));
    public static final ia.c f50890h0 = new ia.c("documentCroppingOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(86))));
    public static final ia.c f50893i0 = new ia.c("documentEnhancementOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(87))));
    public static final ia.c f50896j0 = new ia.c("nlClassifierOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(55))));
    public static final ia.c f50899k0 = new ia.c("nlClassifierClientLibraryLogEvent", i2.g.n(w.f.k(w.class, new s(56))));
    public static final ia.c f50902l0 = new ia.c("accelerationAllowlistLogEvent", i2.g.n(w.f.k(w.class, new s(57))));
    public static final ia.c m0 = new ia.c("toxicityDetectionCreateEvent", i2.g.n(w.f.k(w.class, new s(62))));
    public static final ia.c f50906n0 = new ia.c("toxicityDetectionLoadEvent", i2.g.n(w.f.k(w.class, new s(63))));
    public static final ia.c f50909o0 = new ia.c("toxicityDetectionInferenceEvent", i2.g.n(w.f.k(w.class, new s(64))));
    public static final ia.c f50912p0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(65))));
    public static final ia.c f50915q0 = new ia.c("customImageLabelOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(66))));
    public static final ia.c f50918r0 = new ia.c("codeScannerScanApiEvent", i2.g.n(w.f.k(w.class, new s(67))));
    public static final ia.c f50921s0 = new ia.c("codeScannerOptionalModuleEvent", i2.g.n(w.f.k(w.class, new s(68))));
    public static final ia.c f50924t0 = new ia.c("onDeviceExplicitContentCreateLogEvent", i2.g.n(w.f.k(w.class, new s(70))));
    public static final ia.c f50927u0 = new ia.c("onDeviceExplicitContentLoadLogEvent", i2.g.n(w.f.k(w.class, new s(71))));
    public static final ia.c f50929v0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(72))));
    public static final ia.c f50932w0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", i2.g.n(w.f.k(w.class, new s(73))));
    public static final ia.c f50935x0 = new ia.c("onDeviceFaceMeshCreateLogEvent", i2.g.n(w.f.k(w.class, new s(74))));
    public static final ia.c f50938y0 = new ia.c("onDeviceFaceMeshLoadLogEvent", i2.g.n(w.f.k(w.class, new s(75))));
    public static final ia.c f50941z0 = new ia.c("onDeviceFaceMeshLogEvent", i2.g.n(w.f.k(w.class, new s(76))));
    public static final ia.c A0 = new ia.c("aggregatedOnDeviceFaceMeshLogEvent", i2.g.n(w.f.k(w.class, new s(77))));
    public static final ia.c B0 = new ia.c("smartReplyOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(78))));
    public static final ia.c C0 = new ia.c("textDetectionOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(80))));
    public static final ia.c D0 = new ia.c("onDeviceImageQualityAnalysisCreateLogEvent", i2.g.n(w.f.k(w.class, new s(81))));
    public static final ia.c E0 = new ia.c("onDeviceImageQualityAnalysisLoadLogEvent", i2.g.n(w.f.k(w.class, new s(82))));
    public static final ia.c F0 = new ia.c("onDeviceImageQualityAnalysisLogEvent", i2.g.n(w.f.k(w.class, new s(83))));
    public static final ia.c G0 = new ia.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", i2.g.n(w.f.k(w.class, new s(84))));
    public static final ia.c H0 = new ia.c("imageQualityAnalysisOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(88))));
    public static final ia.c I0 = new ia.c("imageCaptioningOptionalModuleLogEvent", i2.g.n(w.f.k(w.class, new s(89))));
    public static final ia.c J0 = new ia.c("onDeviceImageCaptioningCreateLogEvent", i2.g.n(w.f.k(w.class, new s(90))));
    public static final ia.c K0 = new ia.c("onDeviceImageCaptioningLoadLogEvent", i2.g.n(w.f.k(w.class, new s(91))));
    public static final ia.c L0 = new ia.c("onDeviceImageCaptioningInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(92))));
    public static final ia.c M0 = new ia.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", i2.g.n(w.f.k(w.class, new s(93))));
    public static final ia.c N0 = new ia.c("onDeviceDocumentDetectionCreateLogEvent", i2.g.n(w.f.k(w.class, new s(94))));
    public static final ia.c O0 = new ia.c("onDeviceDocumentDetectionLoadLogEvent", i2.g.n(w.f.k(w.class, new s(95))));
    public static final ia.c P0 = new ia.c("onDeviceDocumentDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(96))));
    public static final ia.c Q0 = new ia.c("aggregatedOnDeviceDocumentDetectionLogEvent", i2.g.n(w.f.k(w.class, new s(97))));
    public static final ia.c R0 = new ia.c("onDeviceDocumentCroppingCreateLogEvent", i2.g.n(w.f.k(w.class, new s(98))));
    public static final ia.c S0 = new ia.c("onDeviceDocumentCroppingLoadLogEvent", i2.g.n(w.f.k(w.class, new s(99))));
    public static final ia.c T0 = new ia.c("onDeviceDocumentCroppingLogEvent", i2.g.n(w.f.k(w.class, new s(100))));
    public static final ia.c U0 = new ia.c("aggregatedOnDeviceDocumentCroppingLogEvent", i2.g.n(w.f.k(w.class, new s(101))));
    public static final ia.c V0 = new ia.c("onDeviceDocumentEnhancementCreateLogEvent", i2.g.n(w.f.k(w.class, new s(102))));
    public static final ia.c W0 = new ia.c("onDeviceDocumentEnhancementLoadLogEvent", i2.g.n(w.f.k(w.class, new s(103))));
    public static final ia.c X0 = w.f.f(104, ia.c.a("onDeviceDocumentEnhancementLogEvent"));
    public static final ia.c Y0 = w.f.f(105, ia.c.a("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    public static final ia.c Z0 = w.f.f(106, ia.c.a("scannerAutoZoomEvent"));
    public static final ia.c f50872a1 = w.f.f(107, ia.c.a("lowLightAutoExposureComputationEvent"));
    public static final ia.c f50875b1 = w.f.f(108, ia.c.a("lowLightFrameProcessEvent"));
    public static final ia.c f50878c1 = w.f.f(109, ia.c.a("lowLightSceneDetectionEvent"));
    public static final ia.c f50880d1 = w.f.f(110, ia.c.a("onDeviceStainRemovalLogEvent"));
    public static final ia.c f50883e1 = w.f.f(111, ia.c.a("aggregatedOnDeviceStainRemovalLogEvent"));
    public static final ia.c f50886f1 = w.f.f(112, ia.c.a("stainRemovalOptionalModuleLogEvent"));
    public static final ia.c f50889g1 = w.f.f(113, ia.c.a("onDeviceShadowRemovalLogEvent"));
    public static final ia.c f50891h1 = w.f.f(114, ia.c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
    public static final ia.c f50894i1 = w.f.f(115, ia.c.a("shadowRemovalOptionalModuleLogEvent"));
    public static final ia.c f50897j1 = w.f.f(116, ia.c.a("onDeviceDigitalInkSegmentationLogEvent"));
    public static final ia.c f50900k1 = w.f.f(117, ia.c.a("onDeviceDocumentScannerStartLogEvent"));
    public static final ia.c l1 = w.f.f(118, ia.c.a("onDeviceDocumentScannerFinishLogEvent"));
    public static final ia.c f50904m1 = w.f.f(119, ia.c.a("onDeviceDocumentScannerUiStartLogEvent"));
    public static final ia.c f50907n1 = w.f.f(120, ia.c.a("onDeviceDocumentScannerUiFinishLogEvent"));
    public static final ia.c f50910o1 = w.f.f(121, ia.c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
    public static final ia.c f50913p1 = w.f.f(122, ia.c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    public static final ia.c f50916q1 = w.f.f(123, ia.c.a("onDeviceDocumentScannerUiCreateLogEvent"));
    public static final ia.c f50919r1 = w.f.f(124, ia.c.a("onDeviceSubjectSegmentationCreateLogEvent"));
    public static final ia.c f50922s1 = w.f.f(125, ia.c.a("onDeviceSubjectSegmentationLoadLogEvent"));
    public static final ia.c f50925t1 = w.f.f(126, ia.c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
    public static final ia.c f50928u1 = w.f.f(127, ia.c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    public static final ia.c f50930v1 = w.f.f(128, ia.c.a("subjectSegmentationOptionalModuleLogEvent"));
    public static final ia.c f50933w1 = w.f.f(129, ia.c.a("documentScannerUiModuleScreenViewEvent"));
    public static final ia.c f50936x1 = w.f.f(130, ia.c.a("documentScannerUiModuleScreenClickEvent"));
    public static final ia.c f50939y1 = w.f.f(131, ia.c.a("documentScannerUiModuleScreenErrorEvent"));

    @Override
    public final void a(Object obj, Object obj2) {
        ib ibVar = (ib) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f50873b, ibVar.f51112a);
        eVar.a(f50876c, ibVar.f51113b);
        eVar.a(d, null);
        eVar.a(f50881e, ibVar.f51114c);
        eVar.a(f50884f, null);
        eVar.a(f50887g, null);
        eVar.a(h, null);
        eVar.a(f50892i, null);
        eVar.a(f50895j, null);
        eVar.a(f50898k, null);
        eVar.a(f50901l, null);
        eVar.a(f50903m, null);
        eVar.a(f50905n, null);
        eVar.a(f50908o, null);
        eVar.a(f50911p, null);
        eVar.a(f50914q, null);
        eVar.a(f50917r, null);
        eVar.a(f50920s, null);
        eVar.a(f50923t, null);
        eVar.a(f50926u, null);
        eVar.a(v, null);
        eVar.a(f50931w, null);
        eVar.a(f50934x, null);
        eVar.a(f50937y, null);
        eVar.a(f50940z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f50871a0, null);
        eVar.a(f50874b0, null);
        eVar.a(f50877c0, null);
        eVar.a(f50879d0, null);
        eVar.a(f50882e0, null);
        eVar.a(f50885f0, null);
        eVar.a(f50888g0, null);
        eVar.a(f50890h0, null);
        eVar.a(f50893i0, null);
        eVar.a(f50896j0, null);
        eVar.a(f50899k0, null);
        eVar.a(f50902l0, null);
        eVar.a(m0, null);
        eVar.a(f50906n0, null);
        eVar.a(f50909o0, null);
        eVar.a(f50912p0, null);
        eVar.a(f50915q0, null);
        eVar.a(f50918r0, null);
        eVar.a(f50921s0, null);
        eVar.a(f50924t0, null);
        eVar.a(f50927u0, null);
        eVar.a(f50929v0, null);
        eVar.a(f50932w0, null);
        eVar.a(f50935x0, null);
        eVar.a(f50938y0, null);
        eVar.a(f50941z0, null);
        eVar.a(A0, null);
        eVar.a(B0, null);
        eVar.a(C0, null);
        eVar.a(D0, null);
        eVar.a(E0, null);
        eVar.a(F0, null);
        eVar.a(G0, null);
        eVar.a(H0, null);
        eVar.a(I0, null);
        eVar.a(J0, null);
        eVar.a(K0, null);
        eVar.a(L0, null);
        eVar.a(M0, null);
        eVar.a(N0, null);
        eVar.a(O0, null);
        eVar.a(P0, null);
        eVar.a(Q0, null);
        eVar.a(R0, null);
        eVar.a(S0, null);
        eVar.a(T0, null);
        eVar.a(U0, null);
        eVar.a(V0, null);
        eVar.a(W0, null);
        eVar.a(X0, null);
        eVar.a(Y0, null);
        eVar.a(Z0, null);
        eVar.a(f50872a1, null);
        eVar.a(f50875b1, null);
        eVar.a(f50878c1, null);
        eVar.a(f50880d1, null);
        eVar.a(f50883e1, null);
        eVar.a(f50886f1, null);
        eVar.a(f50889g1, null);
        eVar.a(f50891h1, null);
        eVar.a(f50894i1, null);
        eVar.a(f50897j1, null);
        eVar.a(f50900k1, null);
        eVar.a(l1, null);
        eVar.a(f50904m1, null);
        eVar.a(f50907n1, null);
        eVar.a(f50910o1, null);
        eVar.a(f50913p1, null);
        eVar.a(f50916q1, null);
        eVar.a(f50919r1, ibVar.d);
        eVar.a(f50922s1, ibVar.f51115e);
        eVar.a(f50925t1, ibVar.f51116f);
        eVar.a(f50928u1, ibVar.f51117g);
        eVar.a(f50930v1, null);
        eVar.a(f50933w1, null);
        eVar.a(f50936x1, null);
        eVar.a(f50939y1, null);
    }
}
