package z7;
public final class g5 implements ia.d {
    public static final g5 f52543a = new Object();
    public static final ia.c f52546b = new ia.c("systemInfo", hg.k0.m(t8.b.o(w.class, new s(1))));
    public static final ia.c f52549c = new ia.c("eventName", hg.k0.m(t8.b.o(w.class, new s(2))));
    public static final ia.c d = new ia.c("isThickClient", hg.k0.m(t8.b.o(w.class, new s(37))));
    public static final ia.c f52554e = new ia.c("clientType", hg.k0.m(t8.b.o(w.class, new s(61))));
    public static final ia.c f52557f = new ia.c("modelDownloadLogEvent", hg.k0.m(t8.b.o(w.class, new s(3))));
    public static final ia.c f52560g = new ia.c("customModelLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(4))));
    public static final ia.c f52565i = new ia.c("customModelCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(29))));
    public static final ia.c f52568j = new ia.c("onDeviceFaceDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(5))));
    public static final ia.c f52571k = new ia.c("onDeviceFaceLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(59))));
    public static final ia.c f52574l = new ia.c("onDeviceTextDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(6))));
    public static final ia.c f52576m = new ia.c("onDeviceTextDetectionLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(79))));
    public static final ia.c f52578n = new ia.c("onDeviceBarcodeDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(7))));
    public static final ia.c f52581o = new ia.c("onDeviceBarcodeLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(58))));
    public static final ia.c f52584p = new ia.c("onDeviceImageLabelCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(48))));
    public static final ia.c f52587q = new ia.c("onDeviceImageLabelLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(49))));
    public static final ia.c f52590r = new ia.c("onDeviceImageLabelDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(18))));
    public static final ia.c f52593s = new ia.c("onDeviceObjectCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(26))));
    public static final ia.c f52596t = new ia.c("onDeviceObjectLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(27))));
    public static final ia.c f52599u = new ia.c("onDeviceObjectInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(44))));
    public static final ia.c f52604w = new ia.c("onDeviceSegmentationLogEvent", hg.k0.m(t8.b.o(w.class, new s(45))));
    public static final ia.c f52607x = new ia.c("onDeviceSmartReplyLogEvent", hg.k0.m(t8.b.o(w.class, new s(19))));
    public static final ia.c f52610y = new ia.c("onDeviceLanguageIdentificationLogEvent", hg.k0.m(t8.b.o(w.class, new s(21))));
    public static final ia.c f52613z = new ia.c("onDeviceTranslationLogEvent", hg.k0.m(t8.b.o(w.class, new s(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hg.k0.m(t8.b.o(w.class, new s(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hg.k0.m(t8.b.o(w.class, new s(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hg.k0.m(t8.b.o(w.class, new s(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hg.k0.m(t8.b.o(w.class, new s(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hg.k0.m(t8.b.o(w.class, new s(42))));
    public static final ia.c f52544a0 = new ia.c("inputImageConstructionLogEvent", hg.k0.m(t8.b.o(w.class, new s(50))));
    public static final ia.c f52547b0 = new ia.c("leakedHandleEvent", hg.k0.m(t8.b.o(w.class, new s(51))));
    public static final ia.c f52550c0 = new ia.c("cameraSourceLogEvent", hg.k0.m(t8.b.o(w.class, new s(52))));
    public static final ia.c f52552d0 = new ia.c("imageLabelOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(53))));
    public static final ia.c f52555e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(54))));
    public static final ia.c f52558f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(60))));
    public static final ia.c f52561g0 = new ia.c("documentDetectionOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(85))));
    public static final ia.c f52563h0 = new ia.c("documentCroppingOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(86))));
    public static final ia.c f52566i0 = new ia.c("documentEnhancementOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(87))));
    public static final ia.c f52569j0 = new ia.c("nlClassifierOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(55))));
    public static final ia.c f52572k0 = new ia.c("nlClassifierClientLibraryLogEvent", hg.k0.m(t8.b.o(w.class, new s(56))));
    public static final ia.c f52575l0 = new ia.c("accelerationAllowlistLogEvent", hg.k0.m(t8.b.o(w.class, new s(57))));
    public static final ia.c m0 = new ia.c("toxicityDetectionCreateEvent", hg.k0.m(t8.b.o(w.class, new s(62))));
    public static final ia.c f52579n0 = new ia.c("toxicityDetectionLoadEvent", hg.k0.m(t8.b.o(w.class, new s(63))));
    public static final ia.c f52582o0 = new ia.c("toxicityDetectionInferenceEvent", hg.k0.m(t8.b.o(w.class, new s(64))));
    public static final ia.c f52585p0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(65))));
    public static final ia.c f52588q0 = new ia.c("customImageLabelOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(66))));
    public static final ia.c f52591r0 = new ia.c("codeScannerScanApiEvent", hg.k0.m(t8.b.o(w.class, new s(67))));
    public static final ia.c f52594s0 = new ia.c("codeScannerOptionalModuleEvent", hg.k0.m(t8.b.o(w.class, new s(68))));
    public static final ia.c f52597t0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(70))));
    public static final ia.c f52600u0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(71))));
    public static final ia.c f52602v0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(72))));
    public static final ia.c f52605w0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hg.k0.m(t8.b.o(w.class, new s(73))));
    public static final ia.c f52608x0 = new ia.c("onDeviceFaceMeshCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(74))));
    public static final ia.c f52611y0 = new ia.c("onDeviceFaceMeshLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(75))));
    public static final ia.c f52614z0 = new ia.c("onDeviceFaceMeshLogEvent", hg.k0.m(t8.b.o(w.class, new s(76))));
    public static final ia.c A0 = new ia.c("aggregatedOnDeviceFaceMeshLogEvent", hg.k0.m(t8.b.o(w.class, new s(77))));
    public static final ia.c B0 = new ia.c("smartReplyOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(78))));
    public static final ia.c C0 = new ia.c("textDetectionOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(80))));
    public static final ia.c D0 = new ia.c("onDeviceImageQualityAnalysisCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(81))));
    public static final ia.c E0 = new ia.c("onDeviceImageQualityAnalysisLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(82))));
    public static final ia.c F0 = new ia.c("onDeviceImageQualityAnalysisLogEvent", hg.k0.m(t8.b.o(w.class, new s(83))));
    public static final ia.c G0 = new ia.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", hg.k0.m(t8.b.o(w.class, new s(84))));
    public static final ia.c H0 = new ia.c("imageQualityAnalysisOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(88))));
    public static final ia.c I0 = new ia.c("imageCaptioningOptionalModuleLogEvent", hg.k0.m(t8.b.o(w.class, new s(89))));
    public static final ia.c J0 = new ia.c("onDeviceImageCaptioningCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(90))));
    public static final ia.c K0 = new ia.c("onDeviceImageCaptioningLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(91))));
    public static final ia.c L0 = new ia.c("onDeviceImageCaptioningInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(92))));
    public static final ia.c M0 = new ia.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", hg.k0.m(t8.b.o(w.class, new s(93))));
    public static final ia.c N0 = new ia.c("onDeviceDocumentDetectionCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(94))));
    public static final ia.c O0 = new ia.c("onDeviceDocumentDetectionLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(95))));
    public static final ia.c P0 = new ia.c("onDeviceDocumentDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(96))));
    public static final ia.c Q0 = new ia.c("aggregatedOnDeviceDocumentDetectionLogEvent", hg.k0.m(t8.b.o(w.class, new s(97))));
    public static final ia.c R0 = new ia.c("onDeviceDocumentCroppingCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(98))));
    public static final ia.c S0 = new ia.c("onDeviceDocumentCroppingLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(99))));
    public static final ia.c T0 = new ia.c("onDeviceDocumentCroppingLogEvent", hg.k0.m(t8.b.o(w.class, new s(100))));
    public static final ia.c U0 = new ia.c("aggregatedOnDeviceDocumentCroppingLogEvent", hg.k0.m(t8.b.o(w.class, new s(101))));
    public static final ia.c V0 = new ia.c("onDeviceDocumentEnhancementCreateLogEvent", hg.k0.m(t8.b.o(w.class, new s(102))));
    public static final ia.c W0 = new ia.c("onDeviceDocumentEnhancementLoadLogEvent", hg.k0.m(t8.b.o(w.class, new s(103))));
    public static final ia.c X0 = t8.b.g(104, ia.c.a("onDeviceDocumentEnhancementLogEvent"));
    public static final ia.c Y0 = t8.b.g(105, ia.c.a("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    public static final ia.c Z0 = t8.b.g(106, ia.c.a("scannerAutoZoomEvent"));
    public static final ia.c f52545a1 = t8.b.g(107, ia.c.a("lowLightAutoExposureComputationEvent"));
    public static final ia.c f52548b1 = t8.b.g(108, ia.c.a("lowLightFrameProcessEvent"));
    public static final ia.c f52551c1 = t8.b.g(109, ia.c.a("lowLightSceneDetectionEvent"));
    public static final ia.c f52553d1 = t8.b.g(110, ia.c.a("onDeviceStainRemovalLogEvent"));
    public static final ia.c f52556e1 = t8.b.g(111, ia.c.a("aggregatedOnDeviceStainRemovalLogEvent"));
    public static final ia.c f52559f1 = t8.b.g(112, ia.c.a("stainRemovalOptionalModuleLogEvent"));
    public static final ia.c f52562g1 = t8.b.g(113, ia.c.a("onDeviceShadowRemovalLogEvent"));
    public static final ia.c f52564h1 = t8.b.g(114, ia.c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
    public static final ia.c f52567i1 = t8.b.g(115, ia.c.a("shadowRemovalOptionalModuleLogEvent"));
    public static final ia.c f52570j1 = t8.b.g(116, ia.c.a("onDeviceDigitalInkSegmentationLogEvent"));
    public static final ia.c f52573k1 = t8.b.g(117, ia.c.a("onDeviceDocumentScannerStartLogEvent"));
    public static final ia.c l1 = t8.b.g(118, ia.c.a("onDeviceDocumentScannerFinishLogEvent"));
    public static final ia.c f52577m1 = t8.b.g(119, ia.c.a("onDeviceDocumentScannerUiStartLogEvent"));
    public static final ia.c f52580n1 = t8.b.g(120, ia.c.a("onDeviceDocumentScannerUiFinishLogEvent"));
    public static final ia.c f52583o1 = t8.b.g(121, ia.c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
    public static final ia.c f52586p1 = t8.b.g(122, ia.c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    public static final ia.c f52589q1 = t8.b.g(123, ia.c.a("onDeviceDocumentScannerUiCreateLogEvent"));
    public static final ia.c f52592r1 = t8.b.g(124, ia.c.a("onDeviceSubjectSegmentationCreateLogEvent"));
    public static final ia.c f52595s1 = t8.b.g(125, ia.c.a("onDeviceSubjectSegmentationLoadLogEvent"));
    public static final ia.c f52598t1 = t8.b.g(126, ia.c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
    public static final ia.c f52601u1 = t8.b.g(127, ia.c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    public static final ia.c f52603v1 = t8.b.g(128, ia.c.a("subjectSegmentationOptionalModuleLogEvent"));
    public static final ia.c f52606w1 = t8.b.g(129, ia.c.a("documentScannerUiModuleScreenViewEvent"));
    public static final ia.c f52609x1 = t8.b.g(130, ia.c.a("documentScannerUiModuleScreenClickEvent"));
    public static final ia.c f52612y1 = t8.b.g(131, ia.c.a("documentScannerUiModuleScreenErrorEvent"));

    @Override
    public final void a(Object obj, Object obj2) {
        ib ibVar = (ib) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(f52546b, ibVar.f52785a);
        eVar.a(f52549c, ibVar.f52786b);
        eVar.a(d, null);
        eVar.a(f52554e, ibVar.f52787c);
        eVar.a(f52557f, null);
        eVar.a(f52560g, null);
        eVar.a(h, null);
        eVar.a(f52565i, null);
        eVar.a(f52568j, null);
        eVar.a(f52571k, null);
        eVar.a(f52574l, null);
        eVar.a(f52576m, null);
        eVar.a(f52578n, null);
        eVar.a(f52581o, null);
        eVar.a(f52584p, null);
        eVar.a(f52587q, null);
        eVar.a(f52590r, null);
        eVar.a(f52593s, null);
        eVar.a(f52596t, null);
        eVar.a(f52599u, null);
        eVar.a(v, null);
        eVar.a(f52604w, null);
        eVar.a(f52607x, null);
        eVar.a(f52610y, null);
        eVar.a(f52613z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(f52544a0, null);
        eVar.a(f52547b0, null);
        eVar.a(f52550c0, null);
        eVar.a(f52552d0, null);
        eVar.a(f52555e0, null);
        eVar.a(f52558f0, null);
        eVar.a(f52561g0, null);
        eVar.a(f52563h0, null);
        eVar.a(f52566i0, null);
        eVar.a(f52569j0, null);
        eVar.a(f52572k0, null);
        eVar.a(f52575l0, null);
        eVar.a(m0, null);
        eVar.a(f52579n0, null);
        eVar.a(f52582o0, null);
        eVar.a(f52585p0, null);
        eVar.a(f52588q0, null);
        eVar.a(f52591r0, null);
        eVar.a(f52594s0, null);
        eVar.a(f52597t0, null);
        eVar.a(f52600u0, null);
        eVar.a(f52602v0, null);
        eVar.a(f52605w0, null);
        eVar.a(f52608x0, null);
        eVar.a(f52611y0, null);
        eVar.a(f52614z0, null);
        eVar.a(A0, null);
        eVar.a(B0, null);
        eVar.a(C0, null);
        eVar.a(D0, null);
        eVar.a(E0, null);
        eVar.a(F0, null);
        eVar.a(G0, null);
        eVar.a(H0, null);
        eVar.a(I0, null);
        eVar.a(J0, null);
        eVar.a(K0, null);
        eVar.a(L0, null);
        eVar.a(M0, null);
        eVar.a(N0, null);
        eVar.a(O0, null);
        eVar.a(P0, null);
        eVar.a(Q0, null);
        eVar.a(R0, null);
        eVar.a(S0, null);
        eVar.a(T0, null);
        eVar.a(U0, null);
        eVar.a(V0, null);
        eVar.a(W0, null);
        eVar.a(X0, null);
        eVar.a(Y0, null);
        eVar.a(Z0, null);
        eVar.a(f52545a1, null);
        eVar.a(f52548b1, null);
        eVar.a(f52551c1, null);
        eVar.a(f52553d1, null);
        eVar.a(f52556e1, null);
        eVar.a(f52559f1, null);
        eVar.a(f52562g1, null);
        eVar.a(f52564h1, null);
        eVar.a(f52567i1, null);
        eVar.a(f52570j1, null);
        eVar.a(f52573k1, null);
        eVar.a(l1, null);
        eVar.a(f52577m1, null);
        eVar.a(f52580n1, null);
        eVar.a(f52583o1, null);
        eVar.a(f52586p1, null);
        eVar.a(f52589q1, null);
        eVar.a(f52592r1, ibVar.d);
        eVar.a(f52595s1, ibVar.f52788e);
        eVar.a(f52598t1, ibVar.f52789f);
        eVar.a(f52601u1, ibVar.f52790g);
        eVar.a(f52603v1, null);
        eVar.a(f52606w1, null);
        eVar.a(f52609x1, null);
        eVar.a(f52612y1, null);
    }
}
