package i7;
public final class g3 implements s9.d {
    public static final g3 f8327a = new Object();
    public static final s9.c f8329b = new s9.c("systemInfo", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(1))));
    public static final s9.c f8331c = new s9.c("eventName", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(2))));
    public static final s9.c d = new s9.c("isThickClient", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(37))));
    public static final s9.c f8334e = new s9.c("clientType", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(61))));
    public static final s9.c f8336f = new s9.c("modelDownloadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(3))));
    public static final s9.c f8338g = new s9.c("customModelLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(20))));
    public static final s9.c h = new s9.c("customModelInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(4))));
    public static final s9.c f8341i = new s9.c("customModelCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(29))));
    public static final s9.c f8343j = new s9.c("onDeviceFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(5))));
    public static final s9.c f8345k = new s9.c("onDeviceFaceLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(59))));
    public static final s9.c f8347l = new s9.c("onDeviceTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(6))));
    public static final s9.c f8349m = new s9.c("onDeviceTextDetectionLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(79))));
    public static final s9.c f8350n = new s9.c("onDeviceBarcodeDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(7))));
    public static final s9.c f8352o = new s9.c("onDeviceBarcodeLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(58))));
    public static final s9.c f8354p = new s9.c("onDeviceImageLabelCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(48))));
    public static final s9.c f8356q = new s9.c("onDeviceImageLabelLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(49))));
    public static final s9.c f8358r = new s9.c("onDeviceImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(18))));
    public static final s9.c f8360s = new s9.c("onDeviceObjectCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(26))));
    public static final s9.c f8362t = new s9.c("onDeviceObjectLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(27))));
    public static final s9.c f8364u = new s9.c("onDeviceObjectInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(28))));
    public static final s9.c v = new s9.c("onDevicePoseDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(44))));
    public static final s9.c f8367w = new s9.c("onDeviceSegmentationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(45))));
    public static final s9.c f8369x = new s9.c("onDeviceSmartReplyLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(19))));
    public static final s9.c f8371y = new s9.c("onDeviceLanguageIdentificationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(21))));
    public static final s9.c f8373z = new s9.c("onDeviceTranslationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(22))));
    public static final s9.c A = new s9.c("cloudFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(8))));
    public static final s9.c B = new s9.c("cloudCropHintDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(9))));
    public static final s9.c C = new s9.c("cloudDocumentTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(10))));
    public static final s9.c D = new s9.c("cloudImagePropertiesDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(11))));
    public static final s9.c E = new s9.c("cloudImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(12))));
    public static final s9.c F = new s9.c("cloudLandmarkDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(13))));
    public static final s9.c G = new s9.c("cloudLogoDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(14))));
    public static final s9.c H = new s9.c("cloudSafeSearchDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(15))));
    public static final s9.c I = new s9.c("cloudTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(16))));
    public static final s9.c J = new s9.c("cloudWebSearchDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(17))));
    public static final s9.c K = new s9.c("automlImageLabelingCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(23))));
    public static final s9.c L = new s9.c("automlImageLabelingLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(24))));
    public static final s9.c M = new s9.c("automlImageLabelingInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(25))));
    public static final s9.c N = new s9.c("isModelDownloadedLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(39))));
    public static final s9.c O = new s9.c("deleteModelLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(40))));
    public static final s9.c P = new s9.c("aggregatedAutomlImageLabelingInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(30))));
    public static final s9.c Q = new s9.c("aggregatedCustomModelInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(31))));
    public static final s9.c R = new s9.c("aggregatedOnDeviceFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(32))));
    public static final s9.c S = new s9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(33))));
    public static final s9.c T = new s9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(34))));
    public static final s9.c U = new s9.c("aggregatedOnDeviceObjectInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(35))));
    public static final s9.c V = new s9.c("aggregatedOnDeviceTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(36))));
    public static final s9.c W = new s9.c("aggregatedOnDevicePoseDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(46))));
    public static final s9.c X = new s9.c("aggregatedOnDeviceSegmentationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(47))));
    public static final s9.c Y = new s9.c("pipelineAccelerationInferenceEvents", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(69))));
    public static final s9.c Z = new s9.c("remoteConfigLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(42))));
    public static final s9.c f8328a0 = new s9.c("inputImageConstructionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(50))));
    public static final s9.c f8330b0 = new s9.c("leakedHandleEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(51))));
    public static final s9.c f8332c0 = new s9.c("cameraSourceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(52))));
    public static final s9.c f8333d0 = new s9.c("imageLabelOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(53))));
    public static final s9.c f8335e0 = new s9.c("languageIdentificationOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(54))));
    public static final s9.c f8337f0 = new s9.c("faceDetectionOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(60))));
    public static final s9.c f8339g0 = new s9.c("documentDetectionOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(85))));
    public static final s9.c f8340h0 = new s9.c("documentCroppingOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(86))));
    public static final s9.c f8342i0 = new s9.c("documentEnhancementOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(87))));
    public static final s9.c f8344j0 = new s9.c("nlClassifierOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(55))));
    public static final s9.c f8346k0 = new s9.c("nlClassifierClientLibraryLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(56))));
    public static final s9.c f8348l0 = new s9.c("accelerationAllowlistLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(57))));
    public static final s9.c m0 = new s9.c("toxicityDetectionCreateEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(62))));
    public static final s9.c f8351n0 = new s9.c("toxicityDetectionLoadEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(63))));
    public static final s9.c f8353o0 = new s9.c("toxicityDetectionInferenceEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(64))));
    public static final s9.c f8355p0 = new s9.c("barcodeDetectionOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(65))));
    public static final s9.c f8357q0 = new s9.c("customImageLabelOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(66))));
    public static final s9.c f8359r0 = new s9.c("codeScannerScanApiEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(67))));
    public static final s9.c f8361s0 = new s9.c("codeScannerOptionalModuleEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(68))));
    public static final s9.c f8363t0 = new s9.c("onDeviceExplicitContentCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(70))));
    public static final s9.c f8365u0 = new s9.c("onDeviceExplicitContentLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(71))));
    public static final s9.c f8366v0 = new s9.c("onDeviceExplicitContentInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(72))));
    public static final s9.c f8368w0 = new s9.c("aggregatedOnDeviceExplicitContentLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(73))));
    public static final s9.c f8370x0 = new s9.c("onDeviceFaceMeshCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(74))));
    public static final s9.c f8372y0 = new s9.c("onDeviceFaceMeshLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(75))));
    public static final s9.c f8374z0 = new s9.c("onDeviceFaceMeshLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(76))));
    public static final s9.c A0 = new s9.c("aggregatedOnDeviceFaceMeshLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(77))));
    public static final s9.c B0 = new s9.c("smartReplyOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(78))));
    public static final s9.c C0 = new s9.c("textDetectionOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(80))));
    public static final s9.c D0 = new s9.c("onDeviceImageQualityAnalysisCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(81))));
    public static final s9.c E0 = new s9.c("onDeviceImageQualityAnalysisLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(82))));
    public static final s9.c F0 = new s9.c("onDeviceImageQualityAnalysisLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(83))));
    public static final s9.c G0 = new s9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(84))));
    public static final s9.c H0 = new s9.c("imageQualityAnalysisOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(88))));
    public static final s9.c I0 = new s9.c("imageCaptioningOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(89))));
    public static final s9.c J0 = new s9.c("onDeviceImageCaptioningCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(90))));
    public static final s9.c K0 = new s9.c("onDeviceImageCaptioningLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(91))));
    public static final s9.c L0 = new s9.c("onDeviceImageCaptioningInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(92))));
    public static final s9.c M0 = new s9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.q(d.class, new a(93))));

    @Override
    public final void a(Object obj, Object obj2) {
        k7 k7Var = (k7) obj;
        s9.e eVar = (s9.e) obj2;
        eVar.e(f8329b, k7Var.f8409a);
        eVar.e(f8331c, k7Var.f8410b);
        eVar.e(d, null);
        eVar.e(f8334e, null);
        eVar.e(f8336f, null);
        eVar.e(f8338g, null);
        eVar.e(h, null);
        eVar.e(f8341i, null);
        eVar.e(f8343j, null);
        eVar.e(f8345k, null);
        eVar.e(f8347l, null);
        eVar.e(f8349m, null);
        eVar.e(f8350n, null);
        eVar.e(f8352o, null);
        eVar.e(f8354p, null);
        eVar.e(f8356q, null);
        eVar.e(f8358r, null);
        eVar.e(f8360s, null);
        eVar.e(f8362t, null);
        eVar.e(f8364u, null);
        eVar.e(v, null);
        eVar.e(f8367w, null);
        eVar.e(f8369x, null);
        eVar.e(f8371y, null);
        eVar.e(f8373z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f8328a0, k7Var.f8411c);
        eVar.e(f8330b0, null);
        eVar.e(f8332c0, null);
        eVar.e(f8333d0, null);
        eVar.e(f8335e0, null);
        eVar.e(f8337f0, null);
        eVar.e(f8339g0, null);
        eVar.e(f8340h0, null);
        eVar.e(f8342i0, null);
        eVar.e(f8344j0, null);
        eVar.e(f8346k0, null);
        eVar.e(f8348l0, null);
        eVar.e(m0, null);
        eVar.e(f8351n0, null);
        eVar.e(f8353o0, null);
        eVar.e(f8355p0, null);
        eVar.e(f8357q0, null);
        eVar.e(f8359r0, null);
        eVar.e(f8361s0, null);
        eVar.e(f8363t0, null);
        eVar.e(f8365u0, null);
        eVar.e(f8366v0, null);
        eVar.e(f8368w0, null);
        eVar.e(f8370x0, null);
        eVar.e(f8372y0, null);
        eVar.e(f8374z0, null);
        eVar.e(A0, null);
        eVar.e(B0, null);
        eVar.e(C0, null);
        eVar.e(D0, null);
        eVar.e(E0, null);
        eVar.e(F0, null);
        eVar.e(G0, null);
        eVar.e(H0, null);
        eVar.e(I0, null);
        eVar.e(J0, null);
        eVar.e(K0, null);
        eVar.e(L0, null);
        eVar.e(M0, null);
    }
}
