package org.telegram.ui;

import android.app.Activity;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffColorFilter;
import android.text.SpannableString;
import android.text.SpannableStringBuilder;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
public final class a00 extends vz {
    public final b00 E;

    public a00(b00 b00Var, Activity activity, org.telegram.ui.ActionBar.n2 n2Var) {
        super(activity);
        this.E = b00Var;
        this.f43022y = new float[2];
        this.f43018r = n2Var;
        FrameLayout frameLayout = new FrameLayout(activity);
        this.f43012a = frameLayout;
        int dp = AndroidUtilities.dp(8.0f);
        int i10 = org.telegram.ui.ActionBar.i6.e7;
        int x02 = org.telegram.ui.ActionBar.i6.x0(null, i10, false);
        int v = org.telegram.ui.ActionBar.i6.v(org.telegram.ui.ActionBar.i6.x0(null, i10, false), org.telegram.ui.ActionBar.i6.x0(null, org.telegram.ui.ActionBar.i6.f20888i6, false));
        frameLayout.setBackground(org.telegram.ui.ActionBar.i6.j0(dp, dp, dp, dp, x02, v, v));
        frameLayout.setOnClickListener(new tz(this, 0));
        addView(frameLayout, w7.x5.a(48.0f, 22.0f, 9.0f, 22.0f, 0.0f, -1, 55));
        org.telegram.ui.ActionBar.j5 j5Var = new org.telegram.ui.ActionBar.j5(activity);
        this.f43013b = j5Var;
        j5Var.setTextSize(16);
        int i11 = org.telegram.ui.ActionBar.i6.G6;
        j5Var.setTextColor(org.telegram.ui.ActionBar.i6.x0(null, i11, false));
        SpannableString spannableString = new SpannableString("t.me/folder/N3k/dImA/bIo");
        ?? obj = new Object();
        obj.f30974a |= 256;
        spannableString.setSpan(new org.telegram.ui.Components.u11(obj, 0), 0, spannableString.length(), 33);
        j5Var.l(spannableString, false);
        j5Var.setAlpha(1.0f);
        frameLayout.addView(j5Var, w7.x5.a(-2.0f, 20.0f, 0.0f, 40.0f, 0.0f, -1, 23));
        org.telegram.ui.ActionBar.j5 j5Var2 = new org.telegram.ui.ActionBar.j5(activity);
        this.f43014c = j5Var2;
        j5Var2.setTextSize(16);
        j5Var2.setTextColor(org.telegram.ui.ActionBar.i6.x0(null, i11, false));
        j5Var2.l(spannableString, false);
        j5Var2.setAlpha(0.0f);
        frameLayout.addView(j5Var2, w7.x5.a(-2.0f, 20.0f, 0.0f, 40.0f, 0.0f, -1, 23));
        ImageView imageView = new ImageView(activity);
        this.d = imageView;
        imageView.setImageDrawable(getContext().getResources().getDrawable(R.drawable.ic_ab_other));
        imageView.setScaleType(ImageView.ScaleType.CENTER);
        imageView.setColorFilter(new PorterDuffColorFilter(org.telegram.ui.ActionBar.i6.x0(null, org.telegram.ui.ActionBar.i6.f21054r5, false), PorterDuff.Mode.SRC_IN));
        imageView.setAlpha(0.0f);
        imageView.setVisibility(8);
        imageView.setContentDescription(LocaleController.getString(R.string.AccDescrMoreOptions));
        imageView.setOnClickListener(new tz(this, 1));
        frameLayout.addView(imageView, w7.x5.a(40.0f, 4.0f, 4.0f, 4.0f, 4.0f, 40, 21));
        ci.g9 g9Var = new ci.g9(activity);
        Paint paint = new Paint();
        g9Var.f5128b = paint;
        g9Var.f5130e = new float[8];
        g9Var.d = new Path();
        g9Var.setWillNotDraw(false);
        paint.setColor(org.telegram.ui.ActionBar.i6.x0(null, org.telegram.ui.ActionBar.i6.Oh, false));
        this.f43015e = g9Var;
        addView(g9Var, w7.x5.a(42.0f, 22.0f, 69.0f, 22.0f, 0.0f, -1, 55));
        ai.q4 q4Var = new ai.q4(activity, 25);
        this.f43016f = q4Var;
        q4Var.setGravity(17);
        int i12 = org.telegram.ui.ActionBar.i6.Sh;
        q4Var.setTextColor(org.telegram.ui.ActionBar.i6.x0(null, i12, false));
        q4Var.setBackground(org.telegram.ui.ActionBar.i6.Z(822083583, 8, 8));
        q4Var.setTypeface(AndroidUtilities.bold());
        q4Var.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder = new SpannableStringBuilder();
        spannableStringBuilder.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.er(0, activity.getDrawable(R.drawable.msg_copy_filled)), 0, 1, 0);
        spannableStringBuilder.setSpan(new org.telegram.ui.Cells.q2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder.append((CharSequence) LocaleController.getString(R.string.LinkActionCopy));
        spannableStringBuilder.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.q2(AndroidUtilities.dp(5.0f)), spannableStringBuilder.length() - 1, spannableStringBuilder.length(), 0);
        q4Var.setText(spannableStringBuilder);
        q4Var.setOnClickListener(new tz(this, 2));
        q4Var.setAlpha(0.0f);
        q4Var.setVisibility(8);
        g9Var.addView(q4Var, w7.x5.e(-1, -1, 3));
        ai.q4 q4Var2 = new ai.q4(activity, 26);
        this.h = q4Var2;
        q4Var2.setGravity(17);
        q4Var2.setTextColor(org.telegram.ui.ActionBar.i6.x0(null, i12, false));
        q4Var2.setBackground(org.telegram.ui.ActionBar.i6.Z(822083583, 8, 8));
        q4Var2.setTypeface(AndroidUtilities.bold());
        q4Var2.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder2 = new SpannableStringBuilder();
        spannableStringBuilder2.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.er(0, activity.getDrawable(R.drawable.msg_share_filled)), 0, 1, 0);
        spannableStringBuilder2.setSpan(new org.telegram.ui.Cells.q2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder2.append((CharSequence) LocaleController.getString(R.string.LinkActionShare));
        spannableStringBuilder2.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.q2(AndroidUtilities.dp(5.0f)), spannableStringBuilder2.length() - 1, spannableStringBuilder2.length(), 0);
        q4Var2.setText(spannableStringBuilder2);
        q4Var2.setOnClickListener(new tz(this, 3));
        q4Var2.setAlpha(0.0f);
        q4Var2.setVisibility(8);
        g9Var.addView(q4Var2, w7.x5.e(-1, -1, 5));
        TextView textView = new TextView(activity);
        this.f43017n = textView;
        textView.setGravity(17);
        textView.setTextColor(org.telegram.ui.ActionBar.i6.x0(null, i12, false));
        textView.setBackground(org.telegram.ui.ActionBar.i6.Z(822083583, 8, 8));
        textView.setTypeface(AndroidUtilities.bold());
        textView.setTextSize(14.0f);
        textView.setText("Generate Invite Link");
        textView.setOnClickListener(new ai.e2(this, 18));
        textView.setAlpha(1.0f);
        textView.setVisibility(0);
        g9Var.addView(textView, w7.x5.d(-1.0f, -1));
    }
}
