package org.telegram.ui;

import android.app.Activity;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffColorFilter;
import android.text.SpannableString;
import android.text.SpannableStringBuilder;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
public final class c00 extends xz {
    public final d00 E;

    public c00(d00 d00Var, Activity activity, org.telegram.ui.ActionBar.o2 o2Var) {
        super(activity);
        this.E = d00Var;
        this.f39741y = new float[2];
        this.f39737r = o2Var;
        FrameLayout frameLayout = new FrameLayout(activity);
        this.f39732a = frameLayout;
        int dp = AndroidUtilities.dp(8.0f);
        int i10 = org.telegram.ui.ActionBar.j6.e7;
        int w02 = org.telegram.ui.ActionBar.j6.w0(null, i10, false);
        int v = org.telegram.ui.ActionBar.j6.v(org.telegram.ui.ActionBar.j6.w0(null, i10, false), org.telegram.ui.ActionBar.j6.w0(null, org.telegram.ui.ActionBar.j6.f18953i6, false));
        frameLayout.setBackground(org.telegram.ui.ActionBar.j6.i0(dp, dp, dp, dp, w02, v, v));
        frameLayout.setOnClickListener(new wz(this, 0));
        addView(frameLayout, w7.x5.d(-1, 48.0f, 55, 22.0f, 9.0f, 22.0f, 0.0f));
        org.telegram.ui.ActionBar.k5 k5Var = new org.telegram.ui.ActionBar.k5(activity);
        this.f39733b = k5Var;
        k5Var.setTextSize(16);
        int i11 = org.telegram.ui.ActionBar.j6.G6;
        k5Var.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i11, false));
        SpannableString spannableString = new SpannableString("t.me/folder/N3k/dImA/bIo");
        ?? obj = new Object();
        obj.f26908a |= 256;
        spannableString.setSpan(new org.telegram.ui.Components.q01(obj, 0), 0, spannableString.length(), 33);
        k5Var.l(spannableString, false);
        k5Var.setAlpha(1.0f);
        frameLayout.addView(k5Var, w7.x5.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        org.telegram.ui.ActionBar.k5 k5Var2 = new org.telegram.ui.ActionBar.k5(activity);
        this.f39734c = k5Var2;
        k5Var2.setTextSize(16);
        k5Var2.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i11, false));
        k5Var2.l(spannableString, false);
        k5Var2.setAlpha(0.0f);
        frameLayout.addView(k5Var2, w7.x5.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        ImageView imageView = new ImageView(activity);
        this.d = imageView;
        imageView.setImageDrawable(getContext().getResources().getDrawable(R.drawable.ic_ab_other));
        imageView.setScaleType(ImageView.ScaleType.CENTER);
        imageView.setColorFilter(new PorterDuffColorFilter(org.telegram.ui.ActionBar.j6.w0(null, org.telegram.ui.ActionBar.j6.f19118r5, false), PorterDuff.Mode.SRC_IN));
        imageView.setAlpha(0.0f);
        imageView.setVisibility(8);
        imageView.setContentDescription(LocaleController.getString(R.string.AccDescrMoreOptions));
        imageView.setOnClickListener(new wz(this, 1));
        frameLayout.addView(imageView, w7.x5.d(40, 40.0f, 21, 4.0f, 4.0f, 4.0f, 4.0f));
        ci.j9 j9Var = new ci.j9(activity);
        Paint paint = new Paint();
        j9Var.f4856b = paint;
        j9Var.e = new float[8];
        j9Var.d = new Path();
        j9Var.setWillNotDraw(false);
        paint.setColor(org.telegram.ui.ActionBar.j6.w0(null, org.telegram.ui.ActionBar.j6.Oh, false));
        this.e = j9Var;
        addView(j9Var, w7.x5.d(-1, 42.0f, 55, 22.0f, 69.0f, 22.0f, 0.0f));
        ai.p4 p4Var = new ai.p4(activity, 25);
        this.f39735f = p4Var;
        p4Var.setGravity(17);
        int i12 = org.telegram.ui.ActionBar.j6.Sh;
        p4Var.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i12, false));
        p4Var.setBackground(org.telegram.ui.ActionBar.j6.Y(822083583, 8, 8));
        p4Var.setTypeface(AndroidUtilities.bold());
        p4Var.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder = new SpannableStringBuilder();
        spannableStringBuilder.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.oq(0, activity.getDrawable(R.drawable.msg_copy_filled)), 0, 1, 0);
        spannableStringBuilder.setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder.append((CharSequence) LocaleController.getString(R.string.LinkActionCopy));
        spannableStringBuilder.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(5.0f)), spannableStringBuilder.length() - 1, spannableStringBuilder.length(), 0);
        p4Var.setText(spannableStringBuilder);
        p4Var.setOnClickListener(new wz(this, 2));
        p4Var.setAlpha(0.0f);
        p4Var.setVisibility(8);
        j9Var.addView(p4Var, w7.x5.e(-1, -1, 3));
        ai.p4 p4Var2 = new ai.p4(activity, 26);
        this.h = p4Var2;
        p4Var2.setGravity(17);
        p4Var2.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i12, false));
        p4Var2.setBackground(org.telegram.ui.ActionBar.j6.Y(822083583, 8, 8));
        p4Var2.setTypeface(AndroidUtilities.bold());
        p4Var2.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder2 = new SpannableStringBuilder();
        spannableStringBuilder2.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.oq(0, activity.getDrawable(R.drawable.msg_share_filled)), 0, 1, 0);
        spannableStringBuilder2.setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder2.append((CharSequence) LocaleController.getString(R.string.LinkActionShare));
        spannableStringBuilder2.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(5.0f)), spannableStringBuilder2.length() - 1, spannableStringBuilder2.length(), 0);
        p4Var2.setText(spannableStringBuilder2);
        p4Var2.setOnClickListener(new wz(this, 3));
        p4Var2.setAlpha(0.0f);
        p4Var2.setVisibility(8);
        j9Var.addView(p4Var2, w7.x5.e(-1, -1, 5));
        TextView textView = new TextView(activity);
        this.f39736n = textView;
        textView.setGravity(17);
        textView.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i12, false));
        textView.setBackground(org.telegram.ui.ActionBar.j6.Y(822083583, 8, 8));
        textView.setTypeface(AndroidUtilities.bold());
        textView.setTextSize(14.0f);
        textView.setText("Generate Invite Link");
        textView.setOnClickListener(new ai.e2(this, 18));
        textView.setAlpha(1.0f);
        textView.setVisibility(0);
        j9Var.addView(textView, w7.x5.c(-1.0f, -1));
    }
}
