package org.telegram.ui;

import android.app.Activity;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffColorFilter;
import android.text.SpannableString;
import android.text.SpannableStringBuilder;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
public final class c00 extends xz {
    public final d00 E;

    public c00(d00 d00Var, Activity activity, org.telegram.ui.ActionBar.p2 p2Var) {
        super(activity);
        this.E = d00Var;
        this.f38851y = new float[2];
        this.f38847r = p2Var;
        FrameLayout frameLayout = new FrameLayout(activity);
        this.f38842a = frameLayout;
        int dp = AndroidUtilities.dp(8.0f);
        int i10 = org.telegram.ui.ActionBar.j6.e7;
        int w02 = org.telegram.ui.ActionBar.j6.w0(null, i10, false);
        int v = org.telegram.ui.ActionBar.j6.v(org.telegram.ui.ActionBar.j6.w0(null, i10, false), org.telegram.ui.ActionBar.j6.w0(null, org.telegram.ui.ActionBar.j6.f18017i6, false));
        frameLayout.setBackground(org.telegram.ui.ActionBar.j6.i0(dp, dp, dp, dp, w02, v, v));
        frameLayout.setOnClickListener(new wz(this, 0));
        addView(frameLayout, w7.a6.d(-1, 48.0f, 55, 22.0f, 9.0f, 22.0f, 0.0f));
        org.telegram.ui.ActionBar.l5 l5Var = new org.telegram.ui.ActionBar.l5(activity);
        this.f38843b = l5Var;
        l5Var.setTextSize(16);
        int i11 = org.telegram.ui.ActionBar.j6.G6;
        l5Var.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i11, false));
        SpannableString spannableString = new SpannableString("t.me/folder/N3k/dImA/bIo");
        ?? obj = new Object();
        obj.f21677a |= 256;
        spannableString.setSpan(new org.telegram.ui.Components.c11(obj, 0), 0, spannableString.length(), 33);
        l5Var.l(spannableString, false);
        l5Var.setAlpha(1.0f);
        frameLayout.addView(l5Var, w7.a6.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        org.telegram.ui.ActionBar.l5 l5Var2 = new org.telegram.ui.ActionBar.l5(activity);
        this.f38844c = l5Var2;
        l5Var2.setTextSize(16);
        l5Var2.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i11, false));
        l5Var2.l(spannableString, false);
        l5Var2.setAlpha(0.0f);
        frameLayout.addView(l5Var2, w7.a6.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        ImageView imageView = new ImageView(activity);
        this.d = imageView;
        imageView.setImageDrawable(getContext().getResources().getDrawable(R.drawable.ic_ab_other));
        imageView.setScaleType(ImageView.ScaleType.CENTER);
        imageView.setColorFilter(new PorterDuffColorFilter(org.telegram.ui.ActionBar.j6.w0(null, org.telegram.ui.ActionBar.j6.f18179r5, false), PorterDuff.Mode.SRC_IN));
        imageView.setAlpha(0.0f);
        imageView.setVisibility(8);
        imageView.setContentDescription(LocaleController.getString(R.string.AccDescrMoreOptions));
        imageView.setOnClickListener(new wz(this, 1));
        frameLayout.addView(imageView, w7.a6.d(40, 40.0f, 21, 4.0f, 4.0f, 4.0f, 4.0f));
        bi.la laVar = new bi.la(activity);
        Paint paint = new Paint();
        laVar.f3051b = paint;
        laVar.e = new float[8];
        laVar.d = new Path();
        laVar.setWillNotDraw(false);
        paint.setColor(org.telegram.ui.ActionBar.j6.w0(null, org.telegram.ui.ActionBar.j6.Oh, false));
        this.e = laVar;
        addView(laVar, w7.a6.d(-1, 42.0f, 55, 22.0f, 69.0f, 22.0f, 0.0f));
        di.h hVar = new di.h(activity, 24);
        this.f38845f = hVar;
        hVar.setGravity(17);
        int i12 = org.telegram.ui.ActionBar.j6.Sh;
        hVar.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i12, false));
        hVar.setBackground(org.telegram.ui.ActionBar.j6.Y(822083583, 8, 8));
        hVar.setTypeface(AndroidUtilities.bold());
        hVar.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder = new SpannableStringBuilder();
        spannableStringBuilder.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.uq(0, activity.getDrawable(R.drawable.msg_copy_filled)), 0, 1, 0);
        spannableStringBuilder.setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder.append((CharSequence) LocaleController.getString(R.string.LinkActionCopy));
        spannableStringBuilder.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(5.0f)), spannableStringBuilder.length() - 1, spannableStringBuilder.length(), 0);
        hVar.setText(spannableStringBuilder);
        hVar.setOnClickListener(new wz(this, 2));
        hVar.setAlpha(0.0f);
        hVar.setVisibility(8);
        laVar.addView(hVar, w7.a6.e(-1, -1, 3));
        di.h hVar2 = new di.h(activity, 25);
        this.h = hVar2;
        hVar2.setGravity(17);
        hVar2.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i12, false));
        hVar2.setBackground(org.telegram.ui.ActionBar.j6.Y(822083583, 8, 8));
        hVar2.setTypeface(AndroidUtilities.bold());
        hVar2.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder2 = new SpannableStringBuilder();
        spannableStringBuilder2.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.uq(0, activity.getDrawable(R.drawable.msg_share_filled)), 0, 1, 0);
        spannableStringBuilder2.setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder2.append((CharSequence) LocaleController.getString(R.string.LinkActionShare));
        spannableStringBuilder2.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(5.0f)), spannableStringBuilder2.length() - 1, spannableStringBuilder2.length(), 0);
        hVar2.setText(spannableStringBuilder2);
        hVar2.setOnClickListener(new wz(this, 3));
        hVar2.setAlpha(0.0f);
        hVar2.setVisibility(8);
        laVar.addView(hVar2, w7.a6.e(-1, -1, 5));
        TextView textView = new TextView(activity);
        this.f38846n = textView;
        textView.setGravity(17);
        textView.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, i12, false));
        textView.setBackground(org.telegram.ui.ActionBar.j6.Y(822083583, 8, 8));
        textView.setTypeface(AndroidUtilities.bold());
        textView.setTextSize(14.0f);
        textView.setText("Generate Invite Link");
        textView.setOnClickListener(new bi.d5(this, 17));
        textView.setAlpha(1.0f);
        textView.setVisibility(0);
        laVar.addView(textView, w7.a6.c(-1.0f, -1));
    }
}
