package org.telegram.ui;

import android.animation.ValueAnimator;
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.HashSet;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
import org.telegram.tgnet.TLRPC;
import org.telegram.ui.Components.RadialProgressView;
public final class le1 extends org.telegram.ui.ActionBar.o2 {
    public float E;
    public RadialProgressView F;
    public int G;
    public final int H;
    public final y5 I;
    public final t21 J;
    public final qk0 K;
    public org.telegram.ui.Components.yl0 f35328a;
    public org.telegram.ui.Components.yl0 f35329b;
    public TextView f35330c;
    public ie1 d;
    public ke1 e;
    public final ArrayList f35331f;
    public final ArrayList h;
    public n41 f35332n;
    public org.telegram.ui.Components.oz f35333r;
    public FrameLayout f35334s;
    public int v;
    public final HashSet f35335w;
    public org.telegram.ui.Cells.qa f35336x;
    public ValueAnimator f35337y;

    public le1(int i10) {
        super(null);
        this.f35331f = new ArrayList();
        this.h = new ArrayList();
        this.f35335w = new HashSet();
        this.H = AndroidUtilities.dp(64.0f);
        this.I = new y5(this, 14);
        this.J = new t21(this, 9);
        this.K = new qk0(this, 26);
        this.arguments = org.telegram.ui.Cells.c1.g(i10, "type");
    }

    @Override
    public final View createView(Context context) {
        this.G = this.arguments.getInt("type", 0);
        this.actionBar.setBackButtonImage(R.drawable.ic_ab_back);
        this.actionBar.setAllowOverlayTitle(true);
        this.actionBar.setTitle(LocaleController.getString(R.string.LimitReached));
        this.actionBar.setActionBarMenuOnItemClick(new h81(this, 5));
        org.telegram.ui.ActionBar.w0 a2 = this.actionBar.o().a(0, R.drawable.outline_header_search);
        a2.F();
        a2.H = new ge1(this);
        a2.setContentDescription(LocaleController.getString(R.string.Search));
        a2.setSearchFieldHint(LocaleController.getString(R.string.Search));
        FrameLayout frameLayout = new FrameLayout(context);
        this.fragmentView = frameLayout;
        org.telegram.ui.Components.yl0 yl0Var = new org.telegram.ui.Components.yl0(context, null);
        this.f35328a = yl0Var;
        yl0Var.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.yl0 yl0Var2 = this.f35328a;
        ie1 ie1Var = new ie1(this);
        this.d = ie1Var;
        yl0Var2.setAdapter(ie1Var);
        this.f35328a.setClipToPadding(false);
        org.telegram.ui.Components.yl0 yl0Var3 = this.f35328a;
        t21 t21Var = this.J;
        yl0Var3.setOnItemClickListener(t21Var);
        org.telegram.ui.Components.yl0 yl0Var4 = this.f35328a;
        qk0 qk0Var = this.K;
        yl0Var4.setOnItemLongClickListener(qk0Var);
        org.telegram.ui.Components.yl0 yl0Var5 = new org.telegram.ui.Components.yl0(context, null);
        this.f35329b = yl0Var5;
        yl0Var5.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.yl0 yl0Var6 = this.f35329b;
        ke1 ke1Var = new ke1(this);
        this.e = ke1Var;
        yl0Var6.setAdapter(ke1Var);
        this.f35329b.setOnItemClickListener(t21Var);
        this.f35329b.setOnItemLongClickListener(qk0Var);
        this.f35329b.setOnScrollListener(new lc1(this, 1));
        org.telegram.ui.Components.oz ozVar = new org.telegram.ui.Components.oz(context, null);
        this.f35333r = ozVar;
        ozVar.setShowAtCenter(true);
        this.f35333r.setText(LocaleController.getString(R.string.NoResult));
        this.f35333r.c();
        RadialProgressView radialProgressView = new RadialProgressView(context, null);
        this.F = radialProgressView;
        frameLayout.addView(radialProgressView, w7.y5.c(-2.0f, -2));
        this.d.E();
        this.F.setVisibility(8);
        frameLayout.addView(this.f35328a);
        FrameLayout frameLayout2 = new FrameLayout(context);
        this.f35334s = frameLayout2;
        frameLayout2.addView(this.f35329b);
        this.f35334s.addView(this.f35333r);
        this.f35334s.setVisibility(8);
        frameLayout.addView(this.f35334s);
        this.d.l();
        this.E = 0.0f;
        AndroidUtilities.runOnUIThread(this.I, 500L);
        getConnectionsManager().sendRequest(new TLRPC.TL_channels_getInactiveChannels(), new m(this, 22));
        View view = this.fragmentView;
        int i10 = org.telegram.ui.ActionBar.i6.f19057d6;
        view.setBackgroundColor(org.telegram.ui.ActionBar.i6.w0(null, i10, false));
        n41 n41Var = new n41(context, 6);
        this.f35332n = n41Var;
        n41Var.setWillNotDraw(false);
        TextView textView = new TextView(context);
        this.f35330c = textView;
        textView.setTextColor(org.telegram.ui.ActionBar.i6.w0(null, org.telegram.ui.ActionBar.i6.Sh, false));
        this.f35330c.setGravity(17);
        this.f35330c.setTextSize(1, 14.0f);
        this.f35330c.setTypeface(AndroidUtilities.bold());
        this.f35330c.setBackground(org.telegram.ui.ActionBar.y5.f(new float[]{4.0f}, org.telegram.ui.ActionBar.i6.Oh));
        frameLayout.addView(this.f35332n, w7.y5.e(-1, 64, 80));
        this.f35332n.setBackgroundColor(org.telegram.ui.ActionBar.i6.w0(null, i10, false));
        this.f35332n.addView(this.f35330c, w7.y5.d(-1, -1.0f, 0, 16.0f, 12.0f, 16.0f, 12.0f));
        this.f35332n.setVisibility(8);
        this.f35330c.setOnClickListener(new a41(this, 8));
        return this.fragmentView;
    }

    @Override
    public final ArrayList getThemeDescriptions() {
        ArrayList arrayList = new ArrayList();
        qy0 qy0Var = new qy0(8, this);
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 1, null, null, null, null, org.telegram.ui.ActionBar.i6.f19337s8));
        org.telegram.ui.ActionBar.l lVar = this.actionBar;
        int i10 = org.telegram.ui.ActionBar.i6.f19392v8;
        arrayList.add(new org.telegram.ui.ActionBar.k6(lVar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 256, null, null, null, null, org.telegram.ui.ActionBar.i6.f19356t8));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 134217728, null, null, null, null, org.telegram.ui.ActionBar.i6.C8));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 67108864, null, null, null, null, org.telegram.ui.ActionBar.i6.D8));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 128, null, null, null, null, org.telegram.ui.ActionBar.i6.A8));
        int i11 = org.telegram.ui.ActionBar.i6.f19225m9;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35336x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"imageView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35336x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"headerTextView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35336x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"messageTextView"}, null, null, -1, null, org.telegram.ui.ActionBar.i6.f19114g9));
        View view = this.fragmentView;
        int i12 = org.telegram.ui.ActionBar.i6.f19057d6;
        arrayList.add(new org.telegram.ui.ActionBar.k6(view, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35332n, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 32, new Class[]{org.telegram.ui.Cells.b7.class}, null, null, null, org.telegram.ui.ActionBar.i6.f19021b7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 48, new Class[]{org.telegram.ui.Cells.b7.class}, null, null, null, org.telegram.ui.ActionBar.i6.f19001a7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 0, new Class[]{org.telegram.ui.Cells.m4.class}, new String[]{"textView"}, null, null, -1, null, org.telegram.ui.ActionBar.i6.L6));
        int i13 = org.telegram.ui.ActionBar.i6.f19012ai;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        int i14 = org.telegram.ui.ActionBar.i6.f19148i7;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        int i15 = org.telegram.ui.ActionBar.i6.f19166j7;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        int i16 = org.telegram.ui.ActionBar.i6.f19186k7;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        int i17 = org.telegram.ui.ActionBar.i6.G6;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        int i18 = org.telegram.ui.ActionBar.i6.f19442y6;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        Drawable[] drawableArr = org.telegram.ui.ActionBar.i6.f19310r0;
        int i19 = org.telegram.ui.ActionBar.i6.J7;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35328a, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35329b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35329b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35329b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35329b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35329b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35329b, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35329b, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.i6.O7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.i6.P7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.i6.Q7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.i6.R7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.i6.S7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.i6.T7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.i6.U7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35333r, 4, null, null, null, null, org.telegram.ui.ActionBar.i6.f19040c7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35330c, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.i6.Oh));
        TextView textView = this.f35330c;
        int i20 = org.telegram.ui.ActionBar.i6.Qh;
        arrayList.add(new org.telegram.ui.ActionBar.k6(textView, 0, null, null, null, qy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.F, 0, null, null, null, qy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f35336x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"imageLayout"}, null, null, -1, null, org.telegram.ui.ActionBar.i6.f19278p7));
        return arrayList;
    }
}
