package org.telegram.ui;

import android.animation.ValueAnimator;
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.HashSet;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
import org.telegram.tgnet.TLRPC;
import org.telegram.ui.Components.RadialProgressView;
public final class le1 extends org.telegram.ui.ActionBar.n2 {
    public float E;
    public RadialProgressView F;
    public int G;
    public final int H;
    public final x5 I;
    public final s21 J;
    public final nl0 K;
    public org.telegram.ui.Components.ml0 f34956a;
    public org.telegram.ui.Components.ml0 f34957b;
    public TextView f34958c;
    public ie1 d;
    public ke1 e;
    public final ArrayList f34959f;
    public final ArrayList h;
    public l51 f34960n;
    public org.telegram.ui.Components.nz f34961r;
    public FrameLayout f34962s;
    public int v;
    public final HashSet f34963w;
    public org.telegram.ui.Cells.sa f34964x;
    public ValueAnimator f34965y;

    public le1(int i10) {
        super(null);
        this.f34959f = new ArrayList();
        this.h = new ArrayList();
        this.f34963w = new HashSet();
        this.H = AndroidUtilities.dp(64.0f);
        this.I = new x5(this, 14);
        this.J = new s21(this, 8);
        this.K = new nl0(this, 23);
        this.arguments = org.telegram.ui.Cells.q3.e(i10, "type");
    }

    @Override
    public final View createView(Context context) {
        this.G = this.arguments.getInt("type", 0);
        this.actionBar.setBackButtonImage(R.drawable.ic_ab_back);
        this.actionBar.setAllowOverlayTitle(true);
        this.actionBar.setTitle(LocaleController.getString(R.string.LimitReached));
        this.actionBar.setActionBarMenuOnItemClick(new o81(this, 4));
        org.telegram.ui.ActionBar.v0 a2 = this.actionBar.n().a(0, R.drawable.outline_header_search);
        a2.F();
        a2.H = new fe1(this);
        a2.setContentDescription(LocaleController.getString(R.string.Search));
        a2.setSearchFieldHint(LocaleController.getString(R.string.Search));
        FrameLayout frameLayout = new FrameLayout(context);
        this.fragmentView = frameLayout;
        org.telegram.ui.Components.ml0 ml0Var = new org.telegram.ui.Components.ml0(context, null);
        this.f34956a = ml0Var;
        ml0Var.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.ml0 ml0Var2 = this.f34956a;
        ie1 ie1Var = new ie1(this);
        this.d = ie1Var;
        ml0Var2.setAdapter(ie1Var);
        this.f34956a.setClipToPadding(false);
        org.telegram.ui.Components.ml0 ml0Var3 = this.f34956a;
        s21 s21Var = this.J;
        ml0Var3.setOnItemClickListener(s21Var);
        org.telegram.ui.Components.ml0 ml0Var4 = this.f34956a;
        nl0 nl0Var = this.K;
        ml0Var4.setOnItemLongClickListener(nl0Var);
        org.telegram.ui.Components.ml0 ml0Var5 = new org.telegram.ui.Components.ml0(context, null);
        this.f34957b = ml0Var5;
        ml0Var5.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.ml0 ml0Var6 = this.f34957b;
        ke1 ke1Var = new ke1(this);
        this.e = ke1Var;
        ml0Var6.setAdapter(ke1Var);
        this.f34957b.setOnItemClickListener(s21Var);
        this.f34957b.setOnItemLongClickListener(nl0Var);
        this.f34957b.setOnScrollListener(new ge1(this, 0));
        org.telegram.ui.Components.nz nzVar = new org.telegram.ui.Components.nz(context, null);
        this.f34961r = nzVar;
        nzVar.setShowAtCenter(true);
        this.f34961r.setText(LocaleController.getString(R.string.NoResult));
        this.f34961r.c();
        RadialProgressView radialProgressView = new RadialProgressView(context, null);
        this.F = radialProgressView;
        frameLayout.addView(radialProgressView, w7.x5.c(-2.0f, -2));
        this.d.E();
        this.F.setVisibility(8);
        frameLayout.addView(this.f34956a);
        FrameLayout frameLayout2 = new FrameLayout(context);
        this.f34962s = frameLayout2;
        frameLayout2.addView(this.f34957b);
        this.f34962s.addView(this.f34961r);
        this.f34962s.setVisibility(8);
        frameLayout.addView(this.f34962s);
        this.d.l();
        this.E = 0.0f;
        AndroidUtilities.runOnUIThread(this.I, 500L);
        getConnectionsManager().sendRequest(new TLRPC.TL_channels_getInactiveChannels(), new m(this, 22));
        View view = this.fragmentView;
        int i10 = org.telegram.ui.ActionBar.h6.f18789d6;
        view.setBackgroundColor(org.telegram.ui.ActionBar.h6.w0(null, i10, false));
        l51 l51Var = new l51(context, 5);
        this.f34960n = l51Var;
        l51Var.setWillNotDraw(false);
        TextView textView = new TextView(context);
        this.f34958c = textView;
        textView.setTextColor(org.telegram.ui.ActionBar.h6.w0(null, org.telegram.ui.ActionBar.h6.Sh, false));
        this.f34958c.setGravity(17);
        this.f34958c.setTextSize(1, 14.0f);
        this.f34958c.setTypeface(AndroidUtilities.bold());
        this.f34958c.setBackground(org.telegram.ui.ActionBar.x5.f(new float[]{4.0f}, org.telegram.ui.ActionBar.h6.Oh));
        frameLayout.addView(this.f34960n, w7.x5.e(-1, 64, 80));
        this.f34960n.setBackgroundColor(org.telegram.ui.ActionBar.h6.w0(null, i10, false));
        this.f34960n.addView(this.f34958c, w7.x5.d(-1, -1.0f, 0, 16.0f, 12.0f, 16.0f, 12.0f));
        this.f34960n.setVisibility(8);
        this.f34958c.setOnClickListener(new z31(this, 8));
        return this.fragmentView;
    }

    @Override
    public final ArrayList getThemeDescriptions() {
        ArrayList arrayList = new ArrayList();
        qy0 qy0Var = new qy0(8, this);
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 1, null, null, null, null, org.telegram.ui.ActionBar.h6.f19065s8));
        org.telegram.ui.ActionBar.k kVar = this.actionBar;
        int i10 = org.telegram.ui.ActionBar.h6.f19120v8;
        arrayList.add(new org.telegram.ui.ActionBar.j6(kVar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 256, null, null, null, null, org.telegram.ui.ActionBar.h6.f19084t8));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 134217728, null, null, null, null, org.telegram.ui.ActionBar.h6.C8));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 67108864, null, null, null, null, org.telegram.ui.ActionBar.h6.D8));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 128, null, null, null, null, org.telegram.ui.ActionBar.h6.A8));
        int i11 = org.telegram.ui.ActionBar.h6.f18956m9;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34964x, 0, new Class[]{org.telegram.ui.Cells.sa.class}, new String[]{"imageView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34964x, 0, new Class[]{org.telegram.ui.Cells.sa.class}, new String[]{"headerTextView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34964x, 0, new Class[]{org.telegram.ui.Cells.sa.class}, new String[]{"messageTextView"}, null, null, -1, null, org.telegram.ui.ActionBar.h6.f18846g9));
        View view = this.fragmentView;
        int i12 = org.telegram.ui.ActionBar.h6.f18789d6;
        arrayList.add(new org.telegram.ui.ActionBar.j6(view, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34960n, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 32, new Class[]{org.telegram.ui.Cells.a7.class}, null, null, null, org.telegram.ui.ActionBar.h6.f18753b7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 48, new Class[]{org.telegram.ui.Cells.a7.class}, null, null, null, org.telegram.ui.ActionBar.h6.f18733a7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 0, new Class[]{org.telegram.ui.Cells.m4.class}, new String[]{"textView"}, null, null, -1, null, org.telegram.ui.ActionBar.h6.L6));
        int i13 = org.telegram.ui.ActionBar.h6.f18744ai;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        int i14 = org.telegram.ui.ActionBar.h6.f18879i7;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        int i15 = org.telegram.ui.ActionBar.h6.f18897j7;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        int i16 = org.telegram.ui.ActionBar.h6.f18917k7;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        int i17 = org.telegram.ui.ActionBar.h6.G6;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        int i18 = org.telegram.ui.ActionBar.h6.f19170y6;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        Drawable[] drawableArr = org.telegram.ui.ActionBar.h6.f19038r0;
        int i19 = org.telegram.ui.ActionBar.h6.J7;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34956a, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34957b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34957b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34957b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34957b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34957b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34957b, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34957b, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.h6.O7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.h6.P7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.h6.Q7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.h6.R7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.h6.S7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.h6.T7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.h6.U7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34961r, 4, null, null, null, null, org.telegram.ui.ActionBar.h6.f18772c7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34958c, 0, null, null, null, qy0Var, org.telegram.ui.ActionBar.h6.Oh));
        TextView textView = this.f34958c;
        int i20 = org.telegram.ui.ActionBar.h6.Qh;
        arrayList.add(new org.telegram.ui.ActionBar.j6(textView, 0, null, null, null, qy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.F, 0, null, null, null, qy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f34964x, 0, new Class[]{org.telegram.ui.Cells.sa.class}, new String[]{"imageLayout"}, null, null, -1, null, org.telegram.ui.ActionBar.h6.f19008p7));
        return arrayList;
    }
}
