package org.telegram.ui;

import android.animation.ValueAnimator;
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.HashSet;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
import org.telegram.tgnet.TLRPC;
import org.telegram.ui.Components.RadialProgressView;
public final class le1 extends org.telegram.ui.ActionBar.m2 {
    public float E;
    public RadialProgressView F;
    public int G;
    public final int H;
    public final w5 I;
    public final r21 J;
    public final zp0 K;
    public org.telegram.ui.Components.zl0 f35430a;
    public org.telegram.ui.Components.zl0 f35431b;
    public TextView f35432c;
    public ie1 d;
    public ke1 e;
    public final ArrayList f35433f;
    public final ArrayList h;
    public m51 f35434n;
    public org.telegram.ui.Components.pz f35435r;
    public FrameLayout f35436s;
    public int v;
    public final HashSet f35437w;
    public org.telegram.ui.Cells.qa f35438x;
    public ValueAnimator f35439y;

    public le1(int i10) {
        super(null);
        this.f35433f = new ArrayList();
        this.h = new ArrayList();
        this.f35437w = new HashSet();
        this.H = AndroidUtilities.dp(64.0f);
        this.I = new w5(this, 14);
        this.J = new r21(this, 9);
        this.K = new zp0(this, 22);
        this.arguments = org.telegram.ui.Cells.c1.g(i10, "type");
    }

    @Override
    public final View createView(Context context) {
        this.G = this.arguments.getInt("type", 0);
        this.actionBar.setBackButtonImage(R.drawable.ic_ab_back);
        this.actionBar.setAllowOverlayTitle(true);
        this.actionBar.setTitle(LocaleController.getString(R.string.LimitReached));
        this.actionBar.setActionBarMenuOnItemClick(new f81(this, 5));
        org.telegram.ui.ActionBar.u0 a2 = this.actionBar.n().a(0, R.drawable.outline_header_search);
        a2.F();
        a2.H = new fe1(this);
        a2.setContentDescription(LocaleController.getString(R.string.Search));
        a2.setSearchFieldHint(LocaleController.getString(R.string.Search));
        FrameLayout frameLayout = new FrameLayout(context);
        this.fragmentView = frameLayout;
        org.telegram.ui.Components.zl0 zl0Var = new org.telegram.ui.Components.zl0(context, null);
        this.f35430a = zl0Var;
        zl0Var.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.zl0 zl0Var2 = this.f35430a;
        ie1 ie1Var = new ie1(this);
        this.d = ie1Var;
        zl0Var2.setAdapter(ie1Var);
        this.f35430a.setClipToPadding(false);
        org.telegram.ui.Components.zl0 zl0Var3 = this.f35430a;
        r21 r21Var = this.J;
        zl0Var3.setOnItemClickListener(r21Var);
        org.telegram.ui.Components.zl0 zl0Var4 = this.f35430a;
        zp0 zp0Var = this.K;
        zl0Var4.setOnItemLongClickListener(zp0Var);
        org.telegram.ui.Components.zl0 zl0Var5 = new org.telegram.ui.Components.zl0(context, null);
        this.f35431b = zl0Var5;
        zl0Var5.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.zl0 zl0Var6 = this.f35431b;
        ke1 ke1Var = new ke1(this);
        this.e = ke1Var;
        zl0Var6.setAdapter(ke1Var);
        this.f35431b.setOnItemClickListener(r21Var);
        this.f35431b.setOnItemLongClickListener(zp0Var);
        this.f35431b.setOnScrollListener(new ge1(this, 0));
        org.telegram.ui.Components.pz pzVar = new org.telegram.ui.Components.pz(context, null);
        this.f35435r = pzVar;
        pzVar.setShowAtCenter(true);
        this.f35435r.setText(LocaleController.getString(R.string.NoResult));
        this.f35435r.c();
        RadialProgressView radialProgressView = new RadialProgressView(context, null);
        this.F = radialProgressView;
        frameLayout.addView(radialProgressView, w7.y5.c(-2.0f, -2));
        this.d.E();
        this.F.setVisibility(8);
        frameLayout.addView(this.f35430a);
        FrameLayout frameLayout2 = new FrameLayout(context);
        this.f35436s = frameLayout2;
        frameLayout2.addView(this.f35431b);
        this.f35436s.addView(this.f35435r);
        this.f35436s.setVisibility(8);
        frameLayout.addView(this.f35436s);
        this.d.l();
        this.E = 0.0f;
        AndroidUtilities.runOnUIThread(this.I, 500L);
        getConnectionsManager().sendRequest(new TLRPC.TL_channels_getInactiveChannels(), new m(this, 22));
        View view = this.fragmentView;
        int i10 = org.telegram.ui.ActionBar.h6.f19076d6;
        view.setBackgroundColor(org.telegram.ui.ActionBar.h6.w0(null, i10, false));
        m51 m51Var = new m51(context, 5);
        this.f35434n = m51Var;
        m51Var.setWillNotDraw(false);
        TextView textView = new TextView(context);
        this.f35432c = textView;
        textView.setTextColor(org.telegram.ui.ActionBar.h6.w0(null, org.telegram.ui.ActionBar.h6.Sh, false));
        this.f35432c.setGravity(17);
        this.f35432c.setTextSize(1, 14.0f);
        this.f35432c.setTypeface(AndroidUtilities.bold());
        this.f35432c.setBackground(org.telegram.ui.ActionBar.w5.f(new float[]{4.0f}, org.telegram.ui.ActionBar.h6.Oh));
        frameLayout.addView(this.f35434n, w7.y5.e(-1, 64, 80));
        this.f35434n.setBackgroundColor(org.telegram.ui.ActionBar.h6.w0(null, i10, false));
        this.f35434n.addView(this.f35432c, w7.y5.d(-1, -1.0f, 0, 16.0f, 12.0f, 16.0f, 12.0f));
        this.f35434n.setVisibility(8);
        this.f35432c.setOnClickListener(new y31(this, 8));
        return this.fragmentView;
    }

    @Override
    public final ArrayList getThemeDescriptions() {
        ArrayList arrayList = new ArrayList();
        oy0 oy0Var = new oy0(8, this);
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 1, null, null, null, null, org.telegram.ui.ActionBar.h6.f19354s8));
        org.telegram.ui.ActionBar.k kVar = this.actionBar;
        int i10 = org.telegram.ui.ActionBar.h6.f19409v8;
        arrayList.add(new org.telegram.ui.ActionBar.j6(kVar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 256, null, null, null, null, org.telegram.ui.ActionBar.h6.f19373t8));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 134217728, null, null, null, null, org.telegram.ui.ActionBar.h6.C8));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 67108864, null, null, null, null, org.telegram.ui.ActionBar.h6.D8));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.actionBar, 128, null, null, null, null, org.telegram.ui.ActionBar.h6.A8));
        int i11 = org.telegram.ui.ActionBar.h6.f19243m9;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35438x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"imageView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35438x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"headerTextView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35438x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"messageTextView"}, null, null, -1, null, org.telegram.ui.ActionBar.h6.f19133g9));
        View view = this.fragmentView;
        int i12 = org.telegram.ui.ActionBar.h6.f19076d6;
        arrayList.add(new org.telegram.ui.ActionBar.j6(view, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35434n, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 32, new Class[]{org.telegram.ui.Cells.b7.class}, null, null, null, org.telegram.ui.ActionBar.h6.f19040b7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 48, new Class[]{org.telegram.ui.Cells.b7.class}, null, null, null, org.telegram.ui.ActionBar.h6.f19020a7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 0, new Class[]{org.telegram.ui.Cells.m4.class}, new String[]{"textView"}, null, null, -1, null, org.telegram.ui.ActionBar.h6.L6));
        int i13 = org.telegram.ui.ActionBar.h6.f19031ai;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        int i14 = org.telegram.ui.ActionBar.h6.f19166i7;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        int i15 = org.telegram.ui.ActionBar.h6.f19184j7;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        int i16 = org.telegram.ui.ActionBar.h6.f19204k7;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        int i17 = org.telegram.ui.ActionBar.h6.G6;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        int i18 = org.telegram.ui.ActionBar.h6.f19459y6;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        Drawable[] drawableArr = org.telegram.ui.ActionBar.h6.f19327r0;
        int i19 = org.telegram.ui.ActionBar.h6.J7;
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35430a, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35431b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35431b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35431b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35431b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35431b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35431b, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35431b, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, oy0Var, org.telegram.ui.ActionBar.h6.O7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, oy0Var, org.telegram.ui.ActionBar.h6.P7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, oy0Var, org.telegram.ui.ActionBar.h6.Q7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, oy0Var, org.telegram.ui.ActionBar.h6.R7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, oy0Var, org.telegram.ui.ActionBar.h6.S7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, oy0Var, org.telegram.ui.ActionBar.h6.T7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(null, 0, null, null, null, oy0Var, org.telegram.ui.ActionBar.h6.U7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35435r, 4, null, null, null, null, org.telegram.ui.ActionBar.h6.f19059c7));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35432c, 0, null, null, null, oy0Var, org.telegram.ui.ActionBar.h6.Oh));
        TextView textView = this.f35432c;
        int i20 = org.telegram.ui.ActionBar.h6.Qh;
        arrayList.add(new org.telegram.ui.ActionBar.j6(textView, 0, null, null, null, oy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.F, 0, null, null, null, oy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.j6(this.f35438x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"imageLayout"}, null, null, -1, null, org.telegram.ui.ActionBar.h6.f19296p7));
        return arrayList;
    }
}
