package org.telegram.ui;

import android.app.Activity;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffColorFilter;
import android.text.SpannableString;
import android.text.SpannableStringBuilder;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
public final class lz extends gz {
    public final mz A;

    public lz(mz mzVar, Activity activity, org.telegram.ui.ActionBar.o2 o2Var) {
        super(activity);
        this.A = mzVar;
        this.f38703y = new float[2];
        this.f38699r = o2Var;
        FrameLayout frameLayout = new FrameLayout(activity);
        this.f38693a = frameLayout;
        int dp = AndroidUtilities.dp(8.0f);
        int i10 = org.telegram.ui.ActionBar.g6.f23081e7;
        int w02 = org.telegram.ui.ActionBar.g6.w0(null, i10, false);
        int v = org.telegram.ui.ActionBar.g6.v(org.telegram.ui.ActionBar.g6.w0(null, i10, false), org.telegram.ui.ActionBar.g6.w0(null, org.telegram.ui.ActionBar.g6.f23152i6, false));
        frameLayout.setBackground(org.telegram.ui.ActionBar.g6.i0(dp, dp, dp, dp, w02, v, v));
        frameLayout.setOnClickListener(new fz(this, 0));
        addView(frameLayout, i7.f6.d(-1, 48.0f, 55, 22.0f, 9.0f, 22.0f, 0.0f));
        org.telegram.ui.ActionBar.h5 h5Var = new org.telegram.ui.ActionBar.h5(activity);
        this.f38694b = h5Var;
        h5Var.setTextSize(16);
        int i11 = org.telegram.ui.ActionBar.g6.G6;
        h5Var.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i11, false));
        SpannableString spannableString = new SpannableString("t.me/folder/N3k/dImA/bIo");
        ?? obj = new Object();
        obj.f29024a |= 256;
        spannableString.setSpan(new org.telegram.ui.Components.i01(obj, 0), 0, spannableString.length(), 33);
        h5Var.l(spannableString, false);
        h5Var.setAlpha(1.0f);
        frameLayout.addView(h5Var, i7.f6.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        org.telegram.ui.ActionBar.h5 h5Var2 = new org.telegram.ui.ActionBar.h5(activity);
        this.f38695c = h5Var2;
        h5Var2.setTextSize(16);
        h5Var2.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i11, false));
        h5Var2.l(spannableString, false);
        h5Var2.setAlpha(0.0f);
        frameLayout.addView(h5Var2, i7.f6.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        ImageView imageView = new ImageView(activity);
        this.d = imageView;
        imageView.setImageDrawable(getContext().getResources().getDrawable(R.drawable.ic_ab_other));
        imageView.setScaleType(ImageView.ScaleType.CENTER);
        imageView.setColorFilter(new PorterDuffColorFilter(org.telegram.ui.ActionBar.g6.w0(null, org.telegram.ui.ActionBar.g6.f23310r5, false), PorterDuff.Mode.SRC_IN));
        imageView.setAlpha(0.0f);
        imageView.setVisibility(8);
        imageView.setContentDescription(LocaleController.getString(R.string.AccDescrMoreOptions));
        imageView.setOnClickListener(new fz(this, 1));
        frameLayout.addView(imageView, i7.f6.d(40, 40.0f, 21, 4.0f, 4.0f, 4.0f, 4.0f));
        nh.i8 i8Var = new nh.i8(activity);
        Paint paint = new Paint();
        i8Var.d = paint;
        i8Var.f17907e = new float[8];
        i8Var.f17905b = new Path();
        i8Var.setWillNotDraw(false);
        paint.setColor(org.telegram.ui.ActionBar.g6.w0(null, org.telegram.ui.ActionBar.g6.Oh, false));
        this.f38696e = i8Var;
        addView(i8Var, i7.f6.d(-1, 42.0f, 55, 22.0f, 69.0f, 22.0f, 0.0f));
        eg.r rVar = new eg.r(activity, 24);
        this.f38697f = rVar;
        rVar.setGravity(17);
        int i12 = org.telegram.ui.ActionBar.g6.Sh;
        rVar.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i12, false));
        rVar.setBackground(org.telegram.ui.ActionBar.g6.Y(822083583, 8, 8));
        rVar.setTypeface(AndroidUtilities.bold());
        rVar.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder = new SpannableStringBuilder();
        spannableStringBuilder.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.iq(0, activity.getDrawable(R.drawable.msg_copy_filled)), 0, 1, 0);
        spannableStringBuilder.setSpan(new org.telegram.ui.Cells.n2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder.append((CharSequence) LocaleController.getString(R.string.LinkActionCopy));
        spannableStringBuilder.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.n2(AndroidUtilities.dp(5.0f)), spannableStringBuilder.length() - 1, spannableStringBuilder.length(), 0);
        rVar.setText(spannableStringBuilder);
        rVar.setOnClickListener(new fz(this, 2));
        rVar.setAlpha(0.0f);
        rVar.setVisibility(8);
        i8Var.addView(rVar, i7.f6.e(-1, -1, 3));
        eg.r rVar2 = new eg.r(activity, 25);
        this.h = rVar2;
        rVar2.setGravity(17);
        rVar2.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i12, false));
        rVar2.setBackground(org.telegram.ui.ActionBar.g6.Y(822083583, 8, 8));
        rVar2.setTypeface(AndroidUtilities.bold());
        rVar2.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder2 = new SpannableStringBuilder();
        spannableStringBuilder2.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.iq(0, activity.getDrawable(R.drawable.msg_share_filled)), 0, 1, 0);
        spannableStringBuilder2.setSpan(new org.telegram.ui.Cells.n2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder2.append((CharSequence) LocaleController.getString(R.string.LinkActionShare));
        spannableStringBuilder2.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.n2(AndroidUtilities.dp(5.0f)), spannableStringBuilder2.length() - 1, spannableStringBuilder2.length(), 0);
        rVar2.setText(spannableStringBuilder2);
        rVar2.setOnClickListener(new fz(this, 3));
        rVar2.setAlpha(0.0f);
        rVar2.setVisibility(8);
        i8Var.addView(rVar2, i7.f6.e(-1, -1, 5));
        TextView textView = new TextView(activity);
        this.f38698n = textView;
        textView.setGravity(17);
        textView.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i12, false));
        textView.setBackground(org.telegram.ui.ActionBar.g6.Y(822083583, 8, 8));
        textView.setTypeface(AndroidUtilities.bold());
        textView.setTextSize(14.0f);
        textView.setText("Generate Invite Link");
        textView.setOnClickListener(new bg.n(this, 22));
        textView.setAlpha(1.0f);
        textView.setVisibility(0);
        i8Var.addView(textView, i7.f6.c(-1.0f, -1));
    }
}
