package org.telegram.ui;

import android.app.Activity;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffColorFilter;
import android.text.SpannableString;
import android.text.SpannableStringBuilder;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;

public final class mz extends hz {
    public final nz A;

    public mz(nz nzVar, Activity activity, org.telegram.ui.ActionBar.n2 n2Var) {
        super(activity);
        this.A = nzVar;
        this.f38922y = new float[2];
        this.f38918r = n2Var;
        FrameLayout frameLayout = new FrameLayout(activity);
        this.f38912a = frameLayout;
        int iDp = AndroidUtilities.dp(8.0f);
        int i10 = org.telegram.ui.ActionBar.g6.f23073e7;
        int iW0 = org.telegram.ui.ActionBar.g6.w0(null, i10, false);
        int iV = org.telegram.ui.ActionBar.g6.v(org.telegram.ui.ActionBar.g6.w0(null, i10, false), org.telegram.ui.ActionBar.g6.w0(null, org.telegram.ui.ActionBar.g6.f23144i6, false));
        frameLayout.setBackground(org.telegram.ui.ActionBar.g6.i0(iDp, iDp, iDp, iDp, iW0, iV, iV));
        frameLayout.setOnClickListener(new gz(this, 0));
        addView(frameLayout, h7.z5.d(-1, 48.0f, 55, 22.0f, 9.0f, 22.0f, 0.0f));
        org.telegram.ui.ActionBar.h5 h5Var = new org.telegram.ui.ActionBar.h5(activity);
        this.f38913b = h5Var;
        h5Var.setTextSize(16);
        int i11 = org.telegram.ui.ActionBar.g6.G6;
        h5Var.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i11, false));
        SpannableString spannableString = new SpannableString("t.me/folder/N3k/dImA/bIo");
        org.telegram.ui.Components.xz0 xz0Var = new org.telegram.ui.Components.xz0();
        xz0Var.f34734a |= 256;
        spannableString.setSpan(new org.telegram.ui.Components.yz0(xz0Var, 0), 0, spannableString.length(), 33);
        h5Var.l(spannableString, false);
        h5Var.setAlpha(1.0f);
        frameLayout.addView(h5Var, h7.z5.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        org.telegram.ui.ActionBar.h5 h5Var2 = new org.telegram.ui.ActionBar.h5(activity);
        this.f38914c = h5Var2;
        h5Var2.setTextSize(16);
        h5Var2.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i11, false));
        h5Var2.l(spannableString, false);
        h5Var2.setAlpha(0.0f);
        frameLayout.addView(h5Var2, h7.z5.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        ImageView imageView = new ImageView(activity);
        this.d = imageView;
        imageView.setImageDrawable(getContext().getResources().getDrawable(R.drawable.ic_ab_other));
        imageView.setScaleType(ImageView.ScaleType.CENTER);
        imageView.setColorFilter(new PorterDuffColorFilter(org.telegram.ui.ActionBar.g6.w0(null, org.telegram.ui.ActionBar.g6.f23300r5, false), PorterDuff.Mode.SRC_IN));
        imageView.setAlpha(0.0f);
        imageView.setVisibility(8);
        imageView.setContentDescription(LocaleController.getString(R.string.AccDescrMoreOptions));
        imageView.setOnClickListener(new gz(this, 1));
        frameLayout.addView(imageView, h7.z5.d(40, 40.0f, 21, 4.0f, 4.0f, 4.0f, 4.0f));
        lh.t8 t8Var = new lh.t8(activity);
        Paint paint = new Paint();
        t8Var.f16873b = paint;
        t8Var.f16875e = new float[8];
        t8Var.d = new Path();
        t8Var.setWillNotDraw(false);
        paint.setColor(org.telegram.ui.ActionBar.g6.w0(null, org.telegram.ui.ActionBar.g6.Oh, false));
        this.f38915e = t8Var;
        addView(t8Var, h7.z5.d(-1, 42.0f, 55, 22.0f, 69.0f, 22.0f, 0.0f));
        cg.q qVar = new cg.q(activity, 26);
        this.f38916f = qVar;
        qVar.setGravity(17);
        int i12 = org.telegram.ui.ActionBar.g6.Sh;
        qVar.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i12, false));
        qVar.setBackground(org.telegram.ui.ActionBar.g6.Y(822083583, 8, 8));
        qVar.setTypeface(AndroidUtilities.bold());
        qVar.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder = new SpannableStringBuilder();
        spannableStringBuilder.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.cq(0, activity.getDrawable(R.drawable.msg_copy_filled)), 0, 1, 0);
        spannableStringBuilder.setSpan(new org.telegram.ui.Cells.n2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder.append((CharSequence) LocaleController.getString(R.string.LinkActionCopy));
        spannableStringBuilder.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.n2(AndroidUtilities.dp(5.0f)), spannableStringBuilder.length() - 1, spannableStringBuilder.length(), 0);
        qVar.setText(spannableStringBuilder);
        qVar.setOnClickListener(new gz(this, 2));
        qVar.setAlpha(0.0f);
        qVar.setVisibility(8);
        t8Var.addView(qVar, h7.z5.e(-1, -1, 3));
        cg.q qVar2 = new cg.q(activity, 27);
        this.h = qVar2;
        qVar2.setGravity(17);
        qVar2.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i12, false));
        qVar2.setBackground(org.telegram.ui.ActionBar.g6.Y(822083583, 8, 8));
        qVar2.setTypeface(AndroidUtilities.bold());
        qVar2.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder2 = new SpannableStringBuilder();
        spannableStringBuilder2.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.cq(0, activity.getDrawable(R.drawable.msg_share_filled)), 0, 1, 0);
        spannableStringBuilder2.setSpan(new org.telegram.ui.Cells.n2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder2.append((CharSequence) LocaleController.getString(R.string.LinkActionShare));
        spannableStringBuilder2.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.n2(AndroidUtilities.dp(5.0f)), spannableStringBuilder2.length() - 1, spannableStringBuilder2.length(), 0);
        qVar2.setText(spannableStringBuilder2);
        qVar2.setOnClickListener(new gz(this, 3));
        qVar2.setAlpha(0.0f);
        qVar2.setVisibility(8);
        t8Var.addView(qVar2, h7.z5.e(-1, -1, 5));
        TextView textView = new TextView(activity);
        this.f38917n = textView;
        textView.setGravity(17);
        textView.setTextColor(org.telegram.ui.ActionBar.g6.w0(null, i12, false));
        textView.setBackground(org.telegram.ui.ActionBar.g6.Y(822083583, 8, 8));
        textView.setTypeface(AndroidUtilities.bold());
        textView.setTextSize(14.0f);
        textView.setText("Generate Invite Link");
        textView.setOnClickListener(new ag.l2(this, 22));
        textView.setAlpha(1.0f);
        textView.setVisibility(0);
        t8Var.addView(textView, h7.z5.c(-1.0f, -1));
    }
}
