package org.telegram.ui;

import android.animation.ValueAnimator;
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.HashSet;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
import org.telegram.tgnet.TLRPC;
import org.telegram.ui.Components.RadialProgressView;
public final class se1 extends org.telegram.ui.ActionBar.n2 {
    public float E;
    public RadialProgressView F;
    public int G;
    public final int H;
    public final w5 I;
    public final z21 J;
    public final ol0 K;
    public org.telegram.ui.Components.wl0 f37265a;
    public org.telegram.ui.Components.wl0 f37266b;
    public TextView f37267c;
    public pe1 d;
    public re1 e;
    public final ArrayList f37268f;
    public final ArrayList h;
    public r41 f37269n;
    public org.telegram.ui.Components.mz f37270r;
    public FrameLayout f37271s;
    public int v;
    public final HashSet f37272w;
    public org.telegram.ui.Cells.qa f37273x;
    public ValueAnimator f37274y;

    public se1(int i10) {
        super(null);
        this.f37268f = new ArrayList();
        this.h = new ArrayList();
        this.f37272w = new HashSet();
        this.H = AndroidUtilities.dp(64.0f);
        this.I = new w5(this, 14);
        this.J = new z21(this, 8);
        this.K = new ol0(this, 24);
        this.arguments = org.telegram.ui.Cells.c1.f(i10, "type");
    }

    @Override
    public final View createView(Context context) {
        this.G = this.arguments.getInt("type", 0);
        this.actionBar.setBackButtonImage(R.drawable.ic_ab_back);
        this.actionBar.setAllowOverlayTitle(true);
        this.actionBar.setTitle(LocaleController.getString(R.string.LimitReached));
        this.actionBar.setActionBarMenuOnItemClick(new v81(this, 4));
        org.telegram.ui.ActionBar.v0 a2 = this.actionBar.n().a(0, R.drawable.outline_header_search);
        a2.F();
        a2.H = new me1(this);
        a2.setContentDescription(LocaleController.getString(R.string.Search));
        a2.setSearchFieldHint(LocaleController.getString(R.string.Search));
        FrameLayout frameLayout = new FrameLayout(context);
        this.fragmentView = frameLayout;
        org.telegram.ui.Components.wl0 wl0Var = new org.telegram.ui.Components.wl0(context, null);
        this.f37265a = wl0Var;
        wl0Var.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.wl0 wl0Var2 = this.f37265a;
        pe1 pe1Var = new pe1(this);
        this.d = pe1Var;
        wl0Var2.setAdapter(pe1Var);
        this.f37265a.setClipToPadding(false);
        org.telegram.ui.Components.wl0 wl0Var3 = this.f37265a;
        z21 z21Var = this.J;
        wl0Var3.setOnItemClickListener(z21Var);
        org.telegram.ui.Components.wl0 wl0Var4 = this.f37265a;
        ol0 ol0Var = this.K;
        wl0Var4.setOnItemLongClickListener(ol0Var);
        org.telegram.ui.Components.wl0 wl0Var5 = new org.telegram.ui.Components.wl0(context, null);
        this.f37266b = wl0Var5;
        wl0Var5.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.wl0 wl0Var6 = this.f37266b;
        re1 re1Var = new re1(this);
        this.e = re1Var;
        wl0Var6.setAdapter(re1Var);
        this.f37266b.setOnItemClickListener(z21Var);
        this.f37266b.setOnItemLongClickListener(ol0Var);
        this.f37266b.setOnScrollListener(new ne1(this, 0));
        org.telegram.ui.Components.mz mzVar = new org.telegram.ui.Components.mz(context, null);
        this.f37270r = mzVar;
        mzVar.setShowAtCenter(true);
        this.f37270r.setText(LocaleController.getString(R.string.NoResult));
        this.f37270r.c();
        RadialProgressView radialProgressView = new RadialProgressView(context, null);
        this.F = radialProgressView;
        frameLayout.addView(radialProgressView, w7.y5.c(-2.0f, -2));
        this.d.E();
        this.F.setVisibility(8);
        frameLayout.addView(this.f37265a);
        FrameLayout frameLayout2 = new FrameLayout(context);
        this.f37271s = frameLayout2;
        frameLayout2.addView(this.f37266b);
        this.f37271s.addView(this.f37270r);
        this.f37271s.setVisibility(8);
        frameLayout.addView(this.f37271s);
        this.d.l();
        this.E = 0.0f;
        AndroidUtilities.runOnUIThread(this.I, 500L);
        getConnectionsManager().sendRequest(new TLRPC.TL_channels_getInactiveChannels(), new m(this, 22));
        View view = this.fragmentView;
        int i10 = org.telegram.ui.ActionBar.j6.f19062d6;
        view.setBackgroundColor(org.telegram.ui.ActionBar.j6.w0(null, i10, false));
        r41 r41Var = new r41(context, 6);
        this.f37269n = r41Var;
        r41Var.setWillNotDraw(false);
        TextView textView = new TextView(context);
        this.f37267c = textView;
        textView.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, org.telegram.ui.ActionBar.j6.Sh, false));
        this.f37267c.setGravity(17);
        this.f37267c.setTextSize(1, 14.0f);
        this.f37267c.setTypeface(AndroidUtilities.bold());
        this.f37267c.setBackground(org.telegram.ui.ActionBar.y5.f(new float[]{4.0f}, org.telegram.ui.ActionBar.j6.Oh));
        frameLayout.addView(this.f37269n, w7.y5.e(-1, 64, 80));
        this.f37269n.setBackgroundColor(org.telegram.ui.ActionBar.j6.w0(null, i10, false));
        this.f37269n.addView(this.f37267c, w7.y5.d(-1, -1.0f, 0, 16.0f, 12.0f, 16.0f, 12.0f));
        this.f37269n.setVisibility(8);
        this.f37267c.setOnClickListener(new g41(this, 8));
        return this.fragmentView;
    }

    @Override
    public final ArrayList getThemeDescriptions() {
        ArrayList arrayList = new ArrayList();
        wy0 wy0Var = new wy0(8, this);
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 1, null, null, null, null, org.telegram.ui.ActionBar.j6.f19340s8));
        org.telegram.ui.ActionBar.k kVar = this.actionBar;
        int i10 = org.telegram.ui.ActionBar.j6.f19395v8;
        arrayList.add(new org.telegram.ui.ActionBar.l6(kVar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 256, null, null, null, null, org.telegram.ui.ActionBar.j6.f19359t8));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 134217728, null, null, null, null, org.telegram.ui.ActionBar.j6.C8));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 67108864, null, null, null, null, org.telegram.ui.ActionBar.j6.D8));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 128, null, null, null, null, org.telegram.ui.ActionBar.j6.A8));
        int i11 = org.telegram.ui.ActionBar.j6.f19230m9;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37273x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"imageView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37273x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"headerTextView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37273x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"messageTextView"}, null, null, -1, null, org.telegram.ui.ActionBar.j6.f19119g9));
        View view = this.fragmentView;
        int i12 = org.telegram.ui.ActionBar.j6.f19062d6;
        arrayList.add(new org.telegram.ui.ActionBar.l6(view, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37269n, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 32, new Class[]{org.telegram.ui.Cells.b7.class}, null, null, null, org.telegram.ui.ActionBar.j6.f19026b7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 48, new Class[]{org.telegram.ui.Cells.b7.class}, null, null, null, org.telegram.ui.ActionBar.j6.f19006a7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 0, new Class[]{org.telegram.ui.Cells.m4.class}, new String[]{"textView"}, null, null, -1, null, org.telegram.ui.ActionBar.j6.L6));
        int i13 = org.telegram.ui.ActionBar.j6.f19017ai;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        int i14 = org.telegram.ui.ActionBar.j6.f19153i7;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        int i15 = org.telegram.ui.ActionBar.j6.f19171j7;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        int i16 = org.telegram.ui.ActionBar.j6.f19191k7;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        int i17 = org.telegram.ui.ActionBar.j6.G6;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        int i18 = org.telegram.ui.ActionBar.j6.f19445y6;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        Drawable[] drawableArr = org.telegram.ui.ActionBar.j6.f19313r0;
        int i19 = org.telegram.ui.ActionBar.j6.J7;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37265a, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37266b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37266b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37266b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37266b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37266b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37266b, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37266b, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, wy0Var, org.telegram.ui.ActionBar.j6.O7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, wy0Var, org.telegram.ui.ActionBar.j6.P7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, wy0Var, org.telegram.ui.ActionBar.j6.Q7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, wy0Var, org.telegram.ui.ActionBar.j6.R7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, wy0Var, org.telegram.ui.ActionBar.j6.S7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, wy0Var, org.telegram.ui.ActionBar.j6.T7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, wy0Var, org.telegram.ui.ActionBar.j6.U7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37270r, 4, null, null, null, null, org.telegram.ui.ActionBar.j6.f19045c7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37267c, 0, null, null, null, wy0Var, org.telegram.ui.ActionBar.j6.Oh));
        TextView textView = this.f37267c;
        int i20 = org.telegram.ui.ActionBar.j6.Qh;
        arrayList.add(new org.telegram.ui.ActionBar.l6(textView, 0, null, null, null, wy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.F, 0, null, null, null, wy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f37273x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"imageLayout"}, null, null, -1, null, org.telegram.ui.ActionBar.j6.f19283p7));
        return arrayList;
    }
}
