package org.telegram.ui;

import android.animation.ValueAnimator;
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.HashSet;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
import org.telegram.tgnet.TLRPC;
import org.telegram.ui.Components.RadialProgressView;
public final class te1 extends org.telegram.ui.ActionBar.n2 {
    public float E;
    public RadialProgressView F;
    public int G;
    public final int H;
    public final w5 I;
    public final a31 J;
    public final tl0 K;
    public org.telegram.ui.Components.ll0 f37648a;
    public org.telegram.ui.Components.ll0 f37649b;
    public TextView f37650c;
    public qe1 d;
    public se1 e;
    public final ArrayList f37651f;
    public final ArrayList h;
    public t51 f37652n;
    public org.telegram.ui.Components.mz f37653r;
    public FrameLayout f37654s;
    public int v;
    public final HashSet f37655w;
    public org.telegram.ui.Cells.ra f37656x;
    public ValueAnimator f37657y;

    public te1(int i10) {
        super(null);
        this.f37651f = new ArrayList();
        this.h = new ArrayList();
        this.f37655w = new HashSet();
        this.H = AndroidUtilities.dp(64.0f);
        this.I = new w5(this, 14);
        this.J = new a31(this, 8);
        this.K = new tl0(this, 23);
        this.arguments = org.telegram.ui.Cells.q3.e(i10, "type");
    }

    @Override
    public final View createView(Context context) {
        this.G = this.arguments.getInt("type", 0);
        this.actionBar.setBackButtonImage(R.drawable.ic_ab_back);
        this.actionBar.setAllowOverlayTitle(true);
        this.actionBar.setTitle(LocaleController.getString(R.string.LimitReached));
        this.actionBar.setActionBarMenuOnItemClick(new w81(this, 4));
        org.telegram.ui.ActionBar.v0 a2 = this.actionBar.n().a(0, R.drawable.outline_header_search);
        a2.F();
        a2.H = new ne1(this);
        a2.setContentDescription(LocaleController.getString(R.string.Search));
        a2.setSearchFieldHint(LocaleController.getString(R.string.Search));
        FrameLayout frameLayout = new FrameLayout(context);
        this.fragmentView = frameLayout;
        org.telegram.ui.Components.ll0 ll0Var = new org.telegram.ui.Components.ll0(context, null);
        this.f37648a = ll0Var;
        ll0Var.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.ll0 ll0Var2 = this.f37648a;
        qe1 qe1Var = new qe1(this);
        this.d = qe1Var;
        ll0Var2.setAdapter(qe1Var);
        this.f37648a.setClipToPadding(false);
        org.telegram.ui.Components.ll0 ll0Var3 = this.f37648a;
        a31 a31Var = this.J;
        ll0Var3.setOnItemClickListener(a31Var);
        org.telegram.ui.Components.ll0 ll0Var4 = this.f37648a;
        tl0 tl0Var = this.K;
        ll0Var4.setOnItemLongClickListener(tl0Var);
        org.telegram.ui.Components.ll0 ll0Var5 = new org.telegram.ui.Components.ll0(context, null);
        this.f37649b = ll0Var5;
        ll0Var5.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.ll0 ll0Var6 = this.f37649b;
        se1 se1Var = new se1(this);
        this.e = se1Var;
        ll0Var6.setAdapter(se1Var);
        this.f37649b.setOnItemClickListener(a31Var);
        this.f37649b.setOnItemLongClickListener(tl0Var);
        this.f37649b.setOnScrollListener(new oe1(this, 0));
        org.telegram.ui.Components.mz mzVar = new org.telegram.ui.Components.mz(context, null);
        this.f37653r = mzVar;
        mzVar.setShowAtCenter(true);
        this.f37653r.setText(LocaleController.getString(R.string.NoResult));
        this.f37653r.c();
        RadialProgressView radialProgressView = new RadialProgressView(context, null);
        this.F = radialProgressView;
        frameLayout.addView(radialProgressView, w7.x5.c(-2.0f, -2));
        this.d.E();
        this.F.setVisibility(8);
        frameLayout.addView(this.f37648a);
        FrameLayout frameLayout2 = new FrameLayout(context);
        this.f37654s = frameLayout2;
        frameLayout2.addView(this.f37649b);
        this.f37654s.addView(this.f37653r);
        this.f37654s.setVisibility(8);
        frameLayout.addView(this.f37654s);
        this.d.l();
        this.E = 0.0f;
        AndroidUtilities.runOnUIThread(this.I, 500L);
        getConnectionsManager().sendRequest(new TLRPC.TL_channels_getInactiveChannels(), new m(this, 22));
        View view = this.fragmentView;
        int i10 = org.telegram.ui.ActionBar.i6.f18834d6;
        view.setBackgroundColor(org.telegram.ui.ActionBar.i6.w0(null, i10, false));
        t51 t51Var = new t51(context, 5);
        this.f37652n = t51Var;
        t51Var.setWillNotDraw(false);
        TextView textView = new TextView(context);
        this.f37650c = textView;
        textView.setTextColor(org.telegram.ui.ActionBar.i6.w0(null, org.telegram.ui.ActionBar.i6.Sh, false));
        this.f37650c.setGravity(17);
        this.f37650c.setTextSize(1, 14.0f);
        this.f37650c.setTypeface(AndroidUtilities.bold());
        this.f37650c.setBackground(org.telegram.ui.ActionBar.y5.f(new float[]{4.0f}, org.telegram.ui.ActionBar.i6.Oh));
        frameLayout.addView(this.f37652n, w7.x5.e(-1, 64, 80));
        this.f37652n.setBackgroundColor(org.telegram.ui.ActionBar.i6.w0(null, i10, false));
        this.f37652n.addView(this.f37650c, w7.x5.d(-1, -1.0f, 0, 16.0f, 12.0f, 16.0f, 12.0f));
        this.f37652n.setVisibility(8);
        this.f37650c.setOnClickListener(new h41(this, 8));
        return this.fragmentView;
    }

    @Override
    public final ArrayList getThemeDescriptions() {
        ArrayList arrayList = new ArrayList();
        xy0 xy0Var = new xy0(8, this);
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 1, null, null, null, null, org.telegram.ui.ActionBar.i6.f19110s8));
        org.telegram.ui.ActionBar.k kVar = this.actionBar;
        int i10 = org.telegram.ui.ActionBar.i6.f19165v8;
        arrayList.add(new org.telegram.ui.ActionBar.k6(kVar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 256, null, null, null, null, org.telegram.ui.ActionBar.i6.f19129t8));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 134217728, null, null, null, null, org.telegram.ui.ActionBar.i6.C8));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 67108864, null, null, null, null, org.telegram.ui.ActionBar.i6.D8));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.actionBar, 128, null, null, null, null, org.telegram.ui.ActionBar.i6.A8));
        int i11 = org.telegram.ui.ActionBar.i6.f19001m9;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37656x, 0, new Class[]{org.telegram.ui.Cells.ra.class}, new String[]{"imageView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37656x, 0, new Class[]{org.telegram.ui.Cells.ra.class}, new String[]{"headerTextView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37656x, 0, new Class[]{org.telegram.ui.Cells.ra.class}, new String[]{"messageTextView"}, null, null, -1, null, org.telegram.ui.ActionBar.i6.f18891g9));
        View view = this.fragmentView;
        int i12 = org.telegram.ui.ActionBar.i6.f18834d6;
        arrayList.add(new org.telegram.ui.ActionBar.k6(view, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37652n, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 32, new Class[]{org.telegram.ui.Cells.a7.class}, null, null, null, org.telegram.ui.ActionBar.i6.f18798b7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 48, new Class[]{org.telegram.ui.Cells.a7.class}, null, null, null, org.telegram.ui.ActionBar.i6.f18778a7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 0, new Class[]{org.telegram.ui.Cells.m4.class}, new String[]{"textView"}, null, null, -1, null, org.telegram.ui.ActionBar.i6.L6));
        int i13 = org.telegram.ui.ActionBar.i6.f18789ai;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        int i14 = org.telegram.ui.ActionBar.i6.f18924i7;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        int i15 = org.telegram.ui.ActionBar.i6.f18942j7;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        int i16 = org.telegram.ui.ActionBar.i6.f18962k7;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        int i17 = org.telegram.ui.ActionBar.i6.G6;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        int i18 = org.telegram.ui.ActionBar.i6.f19215y6;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        Drawable[] drawableArr = org.telegram.ui.ActionBar.i6.f19083r0;
        int i19 = org.telegram.ui.ActionBar.i6.J7;
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37648a, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37649b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37649b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37649b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37649b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37649b, 4, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37649b, 262148, new Class[]{org.telegram.ui.Cells.g4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37649b, 0, new Class[]{org.telegram.ui.Cells.g4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.i6.O7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.i6.P7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.i6.Q7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.i6.R7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.i6.S7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.i6.T7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.i6.U7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37653r, 4, null, null, null, null, org.telegram.ui.ActionBar.i6.f18817c7));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37650c, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.i6.Oh));
        TextView textView = this.f37650c;
        int i20 = org.telegram.ui.ActionBar.i6.Qh;
        arrayList.add(new org.telegram.ui.ActionBar.k6(textView, 0, null, null, null, xy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.F, 0, null, null, null, xy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.k6(this.f37656x, 0, new Class[]{org.telegram.ui.Cells.ra.class}, new String[]{"imageLayout"}, null, null, -1, null, org.telegram.ui.ActionBar.i6.f19053p7));
        return arrayList;
    }
}
