package org.telegram.ui;

import android.animation.ValueAnimator;
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.HashSet;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
import org.telegram.tgnet.TLRPC;
import org.telegram.ui.Components.RadialProgressView;
public final class te1 extends org.telegram.ui.ActionBar.n2 {
    public float E;
    public RadialProgressView F;
    public int G;
    public final int H;
    public final w5 I;
    public final b31 J;
    public final vl0 K;
    public org.telegram.ui.Components.ll0 f40728a;
    public org.telegram.ui.Components.ll0 f40729b;
    public TextView f40730c;
    public qe1 d;
    public se1 f40731e;
    public final ArrayList f40732f;
    public final ArrayList h;
    public v51 f40733n;
    public org.telegram.ui.Components.mz f40734r;
    public FrameLayout f40735s;
    public int v;
    public final HashSet f40736w;
    public org.telegram.ui.Cells.qa f40737x;
    public ValueAnimator f40738y;

    public te1(int i10) {
        super(null);
        this.f40732f = new ArrayList();
        this.h = new ArrayList();
        this.f40736w = new HashSet();
        this.H = AndroidUtilities.dp(64.0f);
        this.I = new w5(this, 14);
        this.J = new b31(this, 8);
        this.K = new vl0(this, 23);
        this.arguments = org.telegram.ui.Cells.p6.e(i10, "type");
    }

    @Override
    public final View createView(Context context) {
        this.G = this.arguments.getInt("type", 0);
        this.actionBar.setBackButtonImage(R.drawable.ic_ab_back);
        this.actionBar.setAllowOverlayTitle(true);
        this.actionBar.setTitle(LocaleController.getString(R.string.LimitReached));
        this.actionBar.setActionBarMenuOnItemClick(new o81(this, 5));
        org.telegram.ui.ActionBar.v0 a2 = this.actionBar.n().a(0, R.drawable.outline_header_search);
        a2.F();
        a2.H = new ne1(this);
        a2.setContentDescription(LocaleController.getString(R.string.Search));
        a2.setSearchFieldHint(LocaleController.getString(R.string.Search));
        FrameLayout frameLayout = new FrameLayout(context);
        this.fragmentView = frameLayout;
        org.telegram.ui.Components.ll0 ll0Var = new org.telegram.ui.Components.ll0(context, null);
        this.f40728a = ll0Var;
        ll0Var.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.ll0 ll0Var2 = this.f40728a;
        qe1 qe1Var = new qe1(this);
        this.d = qe1Var;
        ll0Var2.setAdapter(qe1Var);
        this.f40728a.setClipToPadding(false);
        org.telegram.ui.Components.ll0 ll0Var3 = this.f40728a;
        b31 b31Var = this.J;
        ll0Var3.setOnItemClickListener(b31Var);
        org.telegram.ui.Components.ll0 ll0Var4 = this.f40728a;
        vl0 vl0Var = this.K;
        ll0Var4.setOnItemLongClickListener(vl0Var);
        org.telegram.ui.Components.ll0 ll0Var5 = new org.telegram.ui.Components.ll0(context, null);
        this.f40729b = ll0Var5;
        ll0Var5.setLayoutManager(new s4.c0());
        org.telegram.ui.Components.ll0 ll0Var6 = this.f40729b;
        se1 se1Var = new se1(this);
        this.f40731e = se1Var;
        ll0Var6.setAdapter(se1Var);
        this.f40729b.setOnItemClickListener(b31Var);
        this.f40729b.setOnItemLongClickListener(vl0Var);
        this.f40729b.setOnScrollListener(new oe1(this, 0));
        org.telegram.ui.Components.mz mzVar = new org.telegram.ui.Components.mz(context, null);
        this.f40734r = mzVar;
        mzVar.setShowAtCenter(true);
        this.f40734r.setText(LocaleController.getString(R.string.NoResult));
        this.f40734r.c();
        RadialProgressView radialProgressView = new RadialProgressView(context, null);
        this.F = radialProgressView;
        frameLayout.addView(radialProgressView, w7.x5.c(-2.0f, -2));
        this.d.E();
        this.F.setVisibility(8);
        frameLayout.addView(this.f40728a);
        FrameLayout frameLayout2 = new FrameLayout(context);
        this.f40735s = frameLayout2;
        frameLayout2.addView(this.f40729b);
        this.f40735s.addView(this.f40734r);
        this.f40735s.setVisibility(8);
        frameLayout.addView(this.f40735s);
        this.d.l();
        this.E = 0.0f;
        AndroidUtilities.runOnUIThread(this.I, 500L);
        getConnectionsManager().sendRequest(new TLRPC.TL_channels_getInactiveChannels(), new m(this, 22));
        View view = this.fragmentView;
        int i10 = org.telegram.ui.ActionBar.j6.f20663d6;
        view.setBackgroundColor(org.telegram.ui.ActionBar.j6.w0(null, i10, false));
        v51 v51Var = new v51(context, 5);
        this.f40733n = v51Var;
        v51Var.setWillNotDraw(false);
        TextView textView = new TextView(context);
        this.f40730c = textView;
        textView.setTextColor(org.telegram.ui.ActionBar.j6.w0(null, org.telegram.ui.ActionBar.j6.Sh, false));
        this.f40730c.setGravity(17);
        this.f40730c.setTextSize(1, 14.0f);
        this.f40730c.setTypeface(AndroidUtilities.bold());
        this.f40730c.setBackground(org.telegram.ui.ActionBar.y5.f(new float[]{4.0f}, org.telegram.ui.ActionBar.j6.Oh));
        frameLayout.addView(this.f40733n, w7.x5.e(-1, 64, 80));
        this.f40733n.setBackgroundColor(org.telegram.ui.ActionBar.j6.w0(null, i10, false));
        this.f40733n.addView(this.f40730c, w7.x5.d(-1, -1.0f, 0, 16.0f, 12.0f, 16.0f, 12.0f));
        this.f40733n.setVisibility(8);
        this.f40730c.setOnClickListener(new j41(this, 8));
        return this.fragmentView;
    }

    @Override
    public final ArrayList getThemeDescriptions() {
        ArrayList arrayList = new ArrayList();
        xy0 xy0Var = new xy0(8, this);
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 1, null, null, null, null, org.telegram.ui.ActionBar.j6.f20937s8));
        org.telegram.ui.ActionBar.k kVar = this.actionBar;
        int i10 = org.telegram.ui.ActionBar.j6.f20992v8;
        arrayList.add(new org.telegram.ui.ActionBar.l6(kVar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 256, null, null, null, null, org.telegram.ui.ActionBar.j6.f20956t8));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 64, null, null, null, null, i10));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 134217728, null, null, null, null, org.telegram.ui.ActionBar.j6.C8));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 67108864, null, null, null, null, org.telegram.ui.ActionBar.j6.D8));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.actionBar, 128, null, null, null, null, org.telegram.ui.ActionBar.j6.A8));
        int i11 = org.telegram.ui.ActionBar.j6.f20830m9;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40737x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"imageView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40737x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"headerTextView"}, null, null, -1, null, i11));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40737x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"messageTextView"}, null, null, -1, null, org.telegram.ui.ActionBar.j6.f20721g9));
        View view = this.fragmentView;
        int i12 = org.telegram.ui.ActionBar.j6.f20663d6;
        arrayList.add(new org.telegram.ui.ActionBar.l6(view, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40733n, 1, null, null, null, null, i12));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 32, new Class[]{org.telegram.ui.Cells.a7.class}, null, null, null, org.telegram.ui.ActionBar.j6.f20627b7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 48, new Class[]{org.telegram.ui.Cells.a7.class}, null, null, null, org.telegram.ui.ActionBar.j6.f20607a7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 0, new Class[]{org.telegram.ui.Cells.l4.class}, new String[]{"textView"}, null, null, -1, null, org.telegram.ui.ActionBar.j6.L6));
        int i13 = org.telegram.ui.ActionBar.j6.f20618ai;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        int i14 = org.telegram.ui.ActionBar.j6.f20754i7;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        int i15 = org.telegram.ui.ActionBar.j6.f20772j7;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        int i16 = org.telegram.ui.ActionBar.j6.f20792k7;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        int i17 = org.telegram.ui.ActionBar.j6.G6;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        int i18 = org.telegram.ui.ActionBar.j6.f21042y6;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 262148, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        Drawable[] drawableArr = org.telegram.ui.ActionBar.j6.f20910r0;
        int i19 = org.telegram.ui.ActionBar.j6.J7;
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40728a, 0, new Class[]{org.telegram.ui.Cells.f4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40729b, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"textView"}, null, null, -1, null, i13));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40729b, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"checkBox"}, null, null, -1, null, i14));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40729b, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"checkBox"}, null, null, -1, null, i15));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40729b, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"checkBox"}, null, null, -1, null, i16));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40729b, 4, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"nameTextView"}, null, null, -1, null, i17));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40729b, 262148, new Class[]{org.telegram.ui.Cells.f4.class}, new String[]{"statusTextView"}, null, null, -1, null, i18));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40729b, 0, new Class[]{org.telegram.ui.Cells.f4.class}, null, drawableArr, null, i19));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.j6.O7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.j6.P7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.j6.Q7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.j6.R7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.j6.S7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.j6.T7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(null, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.j6.U7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40734r, 4, null, null, null, null, org.telegram.ui.ActionBar.j6.f20646c7));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40730c, 0, null, null, null, xy0Var, org.telegram.ui.ActionBar.j6.Oh));
        TextView textView = this.f40730c;
        int i20 = org.telegram.ui.ActionBar.j6.Qh;
        arrayList.add(new org.telegram.ui.ActionBar.l6(textView, 0, null, null, null, xy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.F, 0, null, null, null, xy0Var, i20));
        arrayList.add(new org.telegram.ui.ActionBar.l6(this.f40737x, 0, new Class[]{org.telegram.ui.Cells.qa.class}, new String[]{"imageLayout"}, null, null, -1, null, org.telegram.ui.ActionBar.j6.f20880p7));
        return arrayList;
    }
}
