package org.telegram.ui;

import android.app.Activity;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffColorFilter;
import android.text.SpannableString;
import android.text.SpannableStringBuilder;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.LocaleController;
import org.telegram.messenger.R;
public final class xz extends sz {
    public final yz B;

    public xz(yz yzVar, Activity activity, org.telegram.ui.ActionBar.p2 p2Var) {
        super(activity);
        this.B = yzVar;
        this.f41405y = new float[2];
        this.f41401r = p2Var;
        FrameLayout frameLayout = new FrameLayout(activity);
        this.f41395a = frameLayout;
        int dp = AndroidUtilities.dp(8.0f);
        int i10 = org.telegram.ui.ActionBar.k6.f21678e7;
        int w02 = org.telegram.ui.ActionBar.k6.w0(null, i10, false);
        int v = org.telegram.ui.ActionBar.k6.v(org.telegram.ui.ActionBar.k6.w0(null, i10, false), org.telegram.ui.ActionBar.k6.w0(null, org.telegram.ui.ActionBar.k6.f21750i6, false));
        frameLayout.setBackground(org.telegram.ui.ActionBar.k6.i0(dp, dp, dp, dp, w02, v, v));
        frameLayout.setOnClickListener(new qz(this, 0));
        addView(frameLayout, k7.c6.d(-1, 48.0f, 55, 22.0f, 9.0f, 22.0f, 0.0f));
        org.telegram.ui.ActionBar.l5 l5Var = new org.telegram.ui.ActionBar.l5(activity);
        this.f41396b = l5Var;
        l5Var.setTextSize(16);
        int i11 = org.telegram.ui.ActionBar.k6.G6;
        l5Var.setTextColor(org.telegram.ui.ActionBar.k6.w0(null, i11, false));
        SpannableString spannableString = new SpannableString("t.me/folder/N3k/dImA/bIo");
        ?? obj = new Object();
        obj.f31225a |= 256;
        spannableString.setSpan(new org.telegram.ui.Components.u01(obj, 0), 0, spannableString.length(), 33);
        l5Var.l(spannableString, false);
        l5Var.setAlpha(1.0f);
        frameLayout.addView(l5Var, k7.c6.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        org.telegram.ui.ActionBar.l5 l5Var2 = new org.telegram.ui.ActionBar.l5(activity);
        this.f41397c = l5Var2;
        l5Var2.setTextSize(16);
        l5Var2.setTextColor(org.telegram.ui.ActionBar.k6.w0(null, i11, false));
        l5Var2.l(spannableString, false);
        l5Var2.setAlpha(0.0f);
        frameLayout.addView(l5Var2, k7.c6.d(-1, -2.0f, 23, 20.0f, 0.0f, 40.0f, 0.0f));
        ImageView imageView = new ImageView(activity);
        this.d = imageView;
        imageView.setImageDrawable(getContext().getResources().getDrawable(R.drawable.ic_ab_other));
        imageView.setScaleType(ImageView.ScaleType.CENTER);
        imageView.setColorFilter(new PorterDuffColorFilter(org.telegram.ui.ActionBar.k6.w0(null, org.telegram.ui.ActionBar.k6.f21911r5, false), PorterDuff.Mode.SRC_IN));
        imageView.setAlpha(0.0f);
        imageView.setVisibility(8);
        imageView.setContentDescription(LocaleController.getString(R.string.AccDescrMoreOptions));
        imageView.setOnClickListener(new qz(this, 1));
        frameLayout.addView(imageView, k7.c6.d(40, 40.0f, 21, 4.0f, 4.0f, 4.0f, 4.0f));
        rz rzVar = new rz(activity);
        Paint paint = new Paint();
        rzVar.d = paint;
        rzVar.f41078e = new float[8];
        rzVar.f41077c = new Path();
        rzVar.setWillNotDraw(false);
        paint.setColor(org.telegram.ui.ActionBar.k6.w0(null, org.telegram.ui.ActionBar.k6.Oh, false));
        this.f41398e = rzVar;
        addView(rzVar, k7.c6.d(-1, 42.0f, 55, 22.0f, 69.0f, 22.0f, 0.0f));
        hg.q qVar = new hg.q(activity, 24);
        this.f41399f = qVar;
        qVar.setGravity(17);
        int i12 = org.telegram.ui.ActionBar.k6.Sh;
        qVar.setTextColor(org.telegram.ui.ActionBar.k6.w0(null, i12, false));
        qVar.setBackground(org.telegram.ui.ActionBar.k6.Y(822083583, 8, 8));
        qVar.setTypeface(AndroidUtilities.bold());
        qVar.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder = new SpannableStringBuilder();
        spannableStringBuilder.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.oq(0, activity.getDrawable(R.drawable.msg_copy_filled)), 0, 1, 0);
        spannableStringBuilder.setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder.append((CharSequence) LocaleController.getString(R.string.LinkActionCopy));
        spannableStringBuilder.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(5.0f)), spannableStringBuilder.length() - 1, spannableStringBuilder.length(), 0);
        qVar.setText(spannableStringBuilder);
        qVar.setOnClickListener(new qz(this, 2));
        qVar.setAlpha(0.0f);
        qVar.setVisibility(8);
        rzVar.addView(qVar, k7.c6.e(-1, -1, 3));
        hg.q qVar2 = new hg.q(activity, 25);
        this.h = qVar2;
        qVar2.setGravity(17);
        qVar2.setTextColor(org.telegram.ui.ActionBar.k6.w0(null, i12, false));
        qVar2.setBackground(org.telegram.ui.ActionBar.k6.Y(822083583, 8, 8));
        qVar2.setTypeface(AndroidUtilities.bold());
        qVar2.setTextSize(14.0f);
        SpannableStringBuilder spannableStringBuilder2 = new SpannableStringBuilder();
        spannableStringBuilder2.append((CharSequence) "..").setSpan(new org.telegram.ui.Components.oq(0, activity.getDrawable(R.drawable.msg_share_filled)), 0, 1, 0);
        spannableStringBuilder2.setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(8.0f)), 1, 2, 0);
        spannableStringBuilder2.append((CharSequence) LocaleController.getString(R.string.LinkActionShare));
        spannableStringBuilder2.append((CharSequence) ".").setSpan(new org.telegram.ui.Cells.p2(AndroidUtilities.dp(5.0f)), spannableStringBuilder2.length() - 1, spannableStringBuilder2.length(), 0);
        qVar2.setText(spannableStringBuilder2);
        qVar2.setOnClickListener(new qz(this, 3));
        qVar2.setAlpha(0.0f);
        qVar2.setVisibility(8);
        rzVar.addView(qVar2, k7.c6.e(-1, -1, 5));
        TextView textView = new TextView(activity);
        this.f41400n = textView;
        textView.setGravity(17);
        textView.setTextColor(org.telegram.ui.ActionBar.k6.w0(null, i12, false));
        textView.setBackground(org.telegram.ui.ActionBar.k6.Y(822083583, 8, 8));
        textView.setTypeface(AndroidUtilities.bold());
        textView.setTextSize(14.0f);
        textView.setText("Generate Invite Link");
        textView.setOnClickListener(new eg.m(this, 20));
        textView.setAlpha(1.0f);
        textView.setVisibility(0);
        rzVar.addView(textView, k7.c6.c(-1.0f, -1));
    }
}
