package h7;
public final class x2 implements s9.d {
    public static final x2 f7798a = new Object();
    public static final s9.c f7800b = new s9.c("systemInfo", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(1))));
    public static final s9.c f7802c = new s9.c("eventName", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(2))));
    public static final s9.c d = new s9.c("isThickClient", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(37))));
    public static final s9.c f7805e = new s9.c("clientType", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(61))));
    public static final s9.c f7807f = new s9.c("modelDownloadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(3))));
    public static final s9.c f7809g = new s9.c("customModelLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(20))));
    public static final s9.c h = new s9.c("customModelInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(4))));
    public static final s9.c f7812i = new s9.c("customModelCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(29))));
    public static final s9.c f7814j = new s9.c("onDeviceFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(5))));
    public static final s9.c f7816k = new s9.c("onDeviceFaceLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(59))));
    public static final s9.c f7818l = new s9.c("onDeviceTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(6))));
    public static final s9.c f7820m = new s9.c("onDeviceTextDetectionLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(79))));
    public static final s9.c f7821n = new s9.c("onDeviceBarcodeDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(7))));
    public static final s9.c f7823o = new s9.c("onDeviceBarcodeLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(58))));
    public static final s9.c f7825p = new s9.c("onDeviceImageLabelCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(48))));
    public static final s9.c f7827q = new s9.c("onDeviceImageLabelLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(49))));
    public static final s9.c f7829r = new s9.c("onDeviceImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(18))));
    public static final s9.c f7831s = new s9.c("onDeviceObjectCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(26))));
    public static final s9.c f7833t = new s9.c("onDeviceObjectLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(27))));
    public static final s9.c f7835u = new s9.c("onDeviceObjectInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(28))));
    public static final s9.c v = new s9.c("onDevicePoseDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(44))));
    public static final s9.c f7838w = new s9.c("onDeviceSegmentationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(45))));
    public static final s9.c f7840x = new s9.c("onDeviceSmartReplyLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(19))));
    public static final s9.c f7842y = new s9.c("onDeviceLanguageIdentificationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(21))));
    public static final s9.c f7844z = new s9.c("onDeviceTranslationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(22))));
    public static final s9.c A = new s9.c("cloudFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(8))));
    public static final s9.c B = new s9.c("cloudCropHintDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(9))));
    public static final s9.c C = new s9.c("cloudDocumentTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(10))));
    public static final s9.c D = new s9.c("cloudImagePropertiesDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(11))));
    public static final s9.c E = new s9.c("cloudImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(12))));
    public static final s9.c F = new s9.c("cloudLandmarkDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(13))));
    public static final s9.c G = new s9.c("cloudLogoDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(14))));
    public static final s9.c H = new s9.c("cloudSafeSearchDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(15))));
    public static final s9.c I = new s9.c("cloudTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(16))));
    public static final s9.c J = new s9.c("cloudWebSearchDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(17))));
    public static final s9.c K = new s9.c("automlImageLabelingCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(23))));
    public static final s9.c L = new s9.c("automlImageLabelingLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(24))));
    public static final s9.c M = new s9.c("automlImageLabelingInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(25))));
    public static final s9.c N = new s9.c("isModelDownloadedLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(39))));
    public static final s9.c O = new s9.c("deleteModelLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(40))));
    public static final s9.c P = new s9.c("aggregatedAutomlImageLabelingInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(30))));
    public static final s9.c Q = new s9.c("aggregatedCustomModelInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(31))));
    public static final s9.c R = new s9.c("aggregatedOnDeviceFaceDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(32))));
    public static final s9.c S = new s9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(33))));
    public static final s9.c T = new s9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(34))));
    public static final s9.c U = new s9.c("aggregatedOnDeviceObjectInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(35))));
    public static final s9.c V = new s9.c("aggregatedOnDeviceTextDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(36))));
    public static final s9.c W = new s9.c("aggregatedOnDevicePoseDetectionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(46))));
    public static final s9.c X = new s9.c("aggregatedOnDeviceSegmentationLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(47))));
    public static final s9.c Y = new s9.c("pipelineAccelerationInferenceEvents", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(69))));
    public static final s9.c Z = new s9.c("remoteConfigLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(42))));
    public static final s9.c f7799a0 = new s9.c("inputImageConstructionLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(50))));
    public static final s9.c f7801b0 = new s9.c("leakedHandleEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(51))));
    public static final s9.c f7803c0 = new s9.c("cameraSourceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(52))));
    public static final s9.c f7804d0 = new s9.c("imageLabelOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(53))));
    public static final s9.c f7806e0 = new s9.c("languageIdentificationOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(54))));
    public static final s9.c f7808f0 = new s9.c("faceDetectionOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(60))));
    public static final s9.c f7810g0 = new s9.c("nlClassifierOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(55))));
    public static final s9.c f7811h0 = new s9.c("nlClassifierClientLibraryLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(56))));
    public static final s9.c f7813i0 = new s9.c("accelerationAllowlistLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(57))));
    public static final s9.c f7815j0 = new s9.c("toxicityDetectionCreateEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(62))));
    public static final s9.c f7817k0 = new s9.c("toxicityDetectionLoadEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(63))));
    public static final s9.c f7819l0 = new s9.c("toxicityDetectionInferenceEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(64))));
    public static final s9.c m0 = new s9.c("barcodeDetectionOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(65))));
    public static final s9.c f7822n0 = new s9.c("customImageLabelOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(66))));
    public static final s9.c f7824o0 = new s9.c("codeScannerScanApiEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(67))));
    public static final s9.c f7826p0 = new s9.c("codeScannerOptionalModuleEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(68))));
    public static final s9.c f7828q0 = new s9.c("onDeviceExplicitContentCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(70))));
    public static final s9.c f7830r0 = new s9.c("onDeviceExplicitContentLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(71))));
    public static final s9.c f7832s0 = new s9.c("onDeviceExplicitContentInferenceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(72))));
    public static final s9.c f7834t0 = new s9.c("aggregatedOnDeviceExplicitContentLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(73))));
    public static final s9.c f7836u0 = new s9.c("onDeviceSelfieFaceCreateLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(74))));
    public static final s9.c f7837v0 = new s9.c("onDeviceSelfieFaceLoadLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(75))));
    public static final s9.c f7839w0 = new s9.c("onDeviceSelfieFaceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(76))));
    public static final s9.c f7841x0 = new s9.c("aggregatedOnDeviceSelfieFaceLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(77))));
    public static final s9.c f7843y0 = new s9.c("smartReplyOptionalModuleLogEvent", u3.c.h(com.google.android.recaptcha.internal.a.p(i.class, new e(78))));

    @Override
    public final void a(Object obj, Object obj2) {
        l6 l6Var = (l6) obj;
        s9.e eVar = (s9.e) obj2;
        eVar.e(f7800b, l6Var.f7694a);
        eVar.e(f7802c, l6Var.f7695b);
        eVar.e(d, null);
        eVar.e(f7805e, l6Var.f7696c);
        eVar.e(f7807f, null);
        eVar.e(f7809g, null);
        eVar.e(h, null);
        eVar.e(f7812i, null);
        eVar.e(f7814j, null);
        eVar.e(f7816k, null);
        eVar.e(f7818l, null);
        eVar.e(f7820m, null);
        eVar.e(f7821n, null);
        eVar.e(f7823o, null);
        eVar.e(f7825p, null);
        eVar.e(f7827q, null);
        eVar.e(f7829r, null);
        eVar.e(f7831s, null);
        eVar.e(f7833t, null);
        eVar.e(f7835u, null);
        eVar.e(v, null);
        eVar.e(f7838w, null);
        eVar.e(f7840x, null);
        eVar.e(f7842y, l6Var.d);
        eVar.e(f7844z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f7799a0, null);
        eVar.e(f7801b0, null);
        eVar.e(f7803c0, null);
        eVar.e(f7804d0, null);
        eVar.e(f7806e0, null);
        eVar.e(f7808f0, null);
        eVar.e(f7810g0, null);
        eVar.e(f7811h0, null);
        eVar.e(f7813i0, null);
        eVar.e(f7815j0, null);
        eVar.e(f7817k0, null);
        eVar.e(f7819l0, null);
        eVar.e(m0, null);
        eVar.e(f7822n0, null);
        eVar.e(f7824o0, null);
        eVar.e(f7826p0, null);
        eVar.e(f7828q0, null);
        eVar.e(f7830r0, null);
        eVar.e(f7832s0, null);
        eVar.e(f7834t0, null);
        eVar.e(f7836u0, null);
        eVar.e(f7837v0, null);
        eVar.e(f7839w0, null);
        eVar.e(f7841x0, null);
        eVar.e(f7843y0, null);
    }
}
