package g7;
public final class g3 implements q9.d {
    public static final g3 f7182a = new Object();
    public static final q9.c f7184b = new q9.c("systemInfo", ta.b.g(e2.c.r(d.class, new a(1))));
    public static final q9.c f7186c = new q9.c("eventName", ta.b.g(e2.c.r(d.class, new a(2))));
    public static final q9.c d = new q9.c("isThickClient", ta.b.g(e2.c.r(d.class, new a(37))));
    public static final q9.c f7189e = new q9.c("clientType", ta.b.g(e2.c.r(d.class, new a(61))));
    public static final q9.c f7191f = new q9.c("modelDownloadLogEvent", ta.b.g(e2.c.r(d.class, new a(3))));
    public static final q9.c f7193g = new q9.c("customModelLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(20))));
    public static final q9.c h = new q9.c("customModelInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(4))));
    public static final q9.c f7196i = new q9.c("customModelCreateLogEvent", ta.b.g(e2.c.r(d.class, new a(29))));
    public static final q9.c f7198j = new q9.c("onDeviceFaceDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(5))));
    public static final q9.c f7200k = new q9.c("onDeviceFaceLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(59))));
    public static final q9.c f7202l = new q9.c("onDeviceTextDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(6))));
    public static final q9.c f7204m = new q9.c("onDeviceTextDetectionLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(79))));
    public static final q9.c f7205n = new q9.c("onDeviceBarcodeDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(7))));
    public static final q9.c f7207o = new q9.c("onDeviceBarcodeLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(58))));
    public static final q9.c f7209p = new q9.c("onDeviceImageLabelCreateLogEvent", ta.b.g(e2.c.r(d.class, new a(48))));
    public static final q9.c f7211q = new q9.c("onDeviceImageLabelLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(49))));
    public static final q9.c f7213r = new q9.c("onDeviceImageLabelDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(18))));
    public static final q9.c f7215s = new q9.c("onDeviceObjectCreateLogEvent", ta.b.g(e2.c.r(d.class, new a(26))));
    public static final q9.c f7217t = new q9.c("onDeviceObjectLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(27))));
    public static final q9.c f7219u = new q9.c("onDeviceObjectInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(28))));
    public static final q9.c v = new q9.c("onDevicePoseDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(44))));
    public static final q9.c f7222w = new q9.c("onDeviceSegmentationLogEvent", ta.b.g(e2.c.r(d.class, new a(45))));
    public static final q9.c f7224x = new q9.c("onDeviceSmartReplyLogEvent", ta.b.g(e2.c.r(d.class, new a(19))));
    public static final q9.c f7226y = new q9.c("onDeviceLanguageIdentificationLogEvent", ta.b.g(e2.c.r(d.class, new a(21))));
    public static final q9.c f7228z = new q9.c("onDeviceTranslationLogEvent", ta.b.g(e2.c.r(d.class, new a(22))));
    public static final q9.c A = new q9.c("cloudFaceDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(8))));
    public static final q9.c B = new q9.c("cloudCropHintDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(9))));
    public static final q9.c C = new q9.c("cloudDocumentTextDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(10))));
    public static final q9.c D = new q9.c("cloudImagePropertiesDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(11))));
    public static final q9.c E = new q9.c("cloudImageLabelDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(12))));
    public static final q9.c F = new q9.c("cloudLandmarkDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(13))));
    public static final q9.c G = new q9.c("cloudLogoDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(14))));
    public static final q9.c H = new q9.c("cloudSafeSearchDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(15))));
    public static final q9.c I = new q9.c("cloudTextDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(16))));
    public static final q9.c J = new q9.c("cloudWebSearchDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(17))));
    public static final q9.c K = new q9.c("automlImageLabelingCreateLogEvent", ta.b.g(e2.c.r(d.class, new a(23))));
    public static final q9.c L = new q9.c("automlImageLabelingLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(24))));
    public static final q9.c M = new q9.c("automlImageLabelingInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(25))));
    public static final q9.c N = new q9.c("isModelDownloadedLogEvent", ta.b.g(e2.c.r(d.class, new a(39))));
    public static final q9.c O = new q9.c("deleteModelLogEvent", ta.b.g(e2.c.r(d.class, new a(40))));
    public static final q9.c P = new q9.c("aggregatedAutomlImageLabelingInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(30))));
    public static final q9.c Q = new q9.c("aggregatedCustomModelInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(31))));
    public static final q9.c R = new q9.c("aggregatedOnDeviceFaceDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(32))));
    public static final q9.c S = new q9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(33))));
    public static final q9.c T = new q9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(34))));
    public static final q9.c U = new q9.c("aggregatedOnDeviceObjectInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(35))));
    public static final q9.c V = new q9.c("aggregatedOnDeviceTextDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(36))));
    public static final q9.c W = new q9.c("aggregatedOnDevicePoseDetectionLogEvent", ta.b.g(e2.c.r(d.class, new a(46))));
    public static final q9.c X = new q9.c("aggregatedOnDeviceSegmentationLogEvent", ta.b.g(e2.c.r(d.class, new a(47))));
    public static final q9.c Y = new q9.c("pipelineAccelerationInferenceEvents", ta.b.g(e2.c.r(d.class, new a(69))));
    public static final q9.c Z = new q9.c("remoteConfigLogEvent", ta.b.g(e2.c.r(d.class, new a(42))));
    public static final q9.c f7183a0 = new q9.c("inputImageConstructionLogEvent", ta.b.g(e2.c.r(d.class, new a(50))));
    public static final q9.c f7185b0 = new q9.c("leakedHandleEvent", ta.b.g(e2.c.r(d.class, new a(51))));
    public static final q9.c f7187c0 = new q9.c("cameraSourceLogEvent", ta.b.g(e2.c.r(d.class, new a(52))));
    public static final q9.c f7188d0 = new q9.c("imageLabelOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(53))));
    public static final q9.c f7190e0 = new q9.c("languageIdentificationOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(54))));
    public static final q9.c f7192f0 = new q9.c("faceDetectionOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(60))));
    public static final q9.c f7194g0 = new q9.c("documentDetectionOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(85))));
    public static final q9.c f7195h0 = new q9.c("documentCroppingOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(86))));
    public static final q9.c f7197i0 = new q9.c("documentEnhancementOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(87))));
    public static final q9.c f7199j0 = new q9.c("nlClassifierOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(55))));
    public static final q9.c f7201k0 = new q9.c("nlClassifierClientLibraryLogEvent", ta.b.g(e2.c.r(d.class, new a(56))));
    public static final q9.c f7203l0 = new q9.c("accelerationAllowlistLogEvent", ta.b.g(e2.c.r(d.class, new a(57))));
    public static final q9.c m0 = new q9.c("toxicityDetectionCreateEvent", ta.b.g(e2.c.r(d.class, new a(62))));
    public static final q9.c f7206n0 = new q9.c("toxicityDetectionLoadEvent", ta.b.g(e2.c.r(d.class, new a(63))));
    public static final q9.c f7208o0 = new q9.c("toxicityDetectionInferenceEvent", ta.b.g(e2.c.r(d.class, new a(64))));
    public static final q9.c f7210p0 = new q9.c("barcodeDetectionOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(65))));
    public static final q9.c f7212q0 = new q9.c("customImageLabelOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(66))));
    public static final q9.c f7214r0 = new q9.c("codeScannerScanApiEvent", ta.b.g(e2.c.r(d.class, new a(67))));
    public static final q9.c f7216s0 = new q9.c("codeScannerOptionalModuleEvent", ta.b.g(e2.c.r(d.class, new a(68))));
    public static final q9.c f7218t0 = new q9.c("onDeviceExplicitContentCreateLogEvent", ta.b.g(e2.c.r(d.class, new a(70))));
    public static final q9.c f7220u0 = new q9.c("onDeviceExplicitContentLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(71))));
    public static final q9.c f7221v0 = new q9.c("onDeviceExplicitContentInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(72))));
    public static final q9.c f7223w0 = new q9.c("aggregatedOnDeviceExplicitContentLogEvent", ta.b.g(e2.c.r(d.class, new a(73))));
    public static final q9.c f7225x0 = new q9.c("onDeviceFaceMeshCreateLogEvent", ta.b.g(e2.c.r(d.class, new a(74))));
    public static final q9.c f7227y0 = new q9.c("onDeviceFaceMeshLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(75))));
    public static final q9.c f7229z0 = new q9.c("onDeviceFaceMeshLogEvent", ta.b.g(e2.c.r(d.class, new a(76))));
    public static final q9.c A0 = new q9.c("aggregatedOnDeviceFaceMeshLogEvent", ta.b.g(e2.c.r(d.class, new a(77))));
    public static final q9.c B0 = new q9.c("smartReplyOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(78))));
    public static final q9.c C0 = new q9.c("textDetectionOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(80))));
    public static final q9.c D0 = new q9.c("onDeviceImageQualityAnalysisCreateLogEvent", ta.b.g(e2.c.r(d.class, new a(81))));
    public static final q9.c E0 = new q9.c("onDeviceImageQualityAnalysisLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(82))));
    public static final q9.c F0 = new q9.c("onDeviceImageQualityAnalysisLogEvent", ta.b.g(e2.c.r(d.class, new a(83))));
    public static final q9.c G0 = new q9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", ta.b.g(e2.c.r(d.class, new a(84))));
    public static final q9.c H0 = new q9.c("imageQualityAnalysisOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(88))));
    public static final q9.c I0 = new q9.c("imageCaptioningOptionalModuleLogEvent", ta.b.g(e2.c.r(d.class, new a(89))));
    public static final q9.c J0 = new q9.c("onDeviceImageCaptioningCreateLogEvent", ta.b.g(e2.c.r(d.class, new a(90))));
    public static final q9.c K0 = new q9.c("onDeviceImageCaptioningLoadLogEvent", ta.b.g(e2.c.r(d.class, new a(91))));
    public static final q9.c L0 = new q9.c("onDeviceImageCaptioningInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(92))));
    public static final q9.c M0 = new q9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", ta.b.g(e2.c.r(d.class, new a(93))));

    @Override
    public final void a(Object obj, Object obj2) {
        j7 j7Var = (j7) obj;
        q9.e eVar = (q9.e) obj2;
        eVar.g(f7184b, j7Var.f7257a);
        eVar.g(f7186c, j7Var.f7258b);
        eVar.g(d, null);
        eVar.g(f7189e, null);
        eVar.g(f7191f, null);
        eVar.g(f7193g, null);
        eVar.g(h, null);
        eVar.g(f7196i, null);
        eVar.g(f7198j, null);
        eVar.g(f7200k, null);
        eVar.g(f7202l, null);
        eVar.g(f7204m, null);
        eVar.g(f7205n, null);
        eVar.g(f7207o, null);
        eVar.g(f7209p, null);
        eVar.g(f7211q, null);
        eVar.g(f7213r, null);
        eVar.g(f7215s, null);
        eVar.g(f7217t, null);
        eVar.g(f7219u, null);
        eVar.g(v, null);
        eVar.g(f7222w, null);
        eVar.g(f7224x, null);
        eVar.g(f7226y, null);
        eVar.g(f7228z, null);
        eVar.g(A, null);
        eVar.g(B, null);
        eVar.g(C, null);
        eVar.g(D, null);
        eVar.g(E, null);
        eVar.g(F, null);
        eVar.g(G, null);
        eVar.g(H, null);
        eVar.g(I, null);
        eVar.g(J, null);
        eVar.g(K, null);
        eVar.g(L, null);
        eVar.g(M, null);
        eVar.g(N, null);
        eVar.g(O, null);
        eVar.g(P, null);
        eVar.g(Q, null);
        eVar.g(R, null);
        eVar.g(S, null);
        eVar.g(T, null);
        eVar.g(U, null);
        eVar.g(V, null);
        eVar.g(W, null);
        eVar.g(X, null);
        eVar.g(Y, null);
        eVar.g(Z, null);
        eVar.g(f7183a0, j7Var.f7259c);
        eVar.g(f7185b0, null);
        eVar.g(f7187c0, null);
        eVar.g(f7188d0, null);
        eVar.g(f7190e0, null);
        eVar.g(f7192f0, null);
        eVar.g(f7194g0, null);
        eVar.g(f7195h0, null);
        eVar.g(f7197i0, null);
        eVar.g(f7199j0, null);
        eVar.g(f7201k0, null);
        eVar.g(f7203l0, null);
        eVar.g(m0, null);
        eVar.g(f7206n0, null);
        eVar.g(f7208o0, null);
        eVar.g(f7210p0, null);
        eVar.g(f7212q0, null);
        eVar.g(f7214r0, null);
        eVar.g(f7216s0, null);
        eVar.g(f7218t0, null);
        eVar.g(f7220u0, null);
        eVar.g(f7221v0, null);
        eVar.g(f7223w0, null);
        eVar.g(f7225x0, null);
        eVar.g(f7227y0, null);
        eVar.g(f7229z0, null);
        eVar.g(A0, null);
        eVar.g(B0, null);
        eVar.g(C0, null);
        eVar.g(D0, null);
        eVar.g(E0, null);
        eVar.g(F0, null);
        eVar.g(G0, null);
        eVar.g(H0, null);
        eVar.g(I0, null);
        eVar.g(J0, null);
        eVar.g(K0, null);
        eVar.g(L0, null);
        eVar.g(M0, null);
    }
}
