package n7;
public final class g5 implements u9.d {
    public static final g5 f14366a = new Object();
    public static final u9.c f14369b = new u9.c("systemInfo", vh.v2.h(kh.a2.p(w.class, new s(1))));
    public static final u9.c f14372c = new u9.c("eventName", vh.v2.h(kh.a2.p(w.class, new s(2))));
    public static final u9.c d = new u9.c("isThickClient", vh.v2.h(kh.a2.p(w.class, new s(37))));
    public static final u9.c e = new u9.c("clientType", vh.v2.h(kh.a2.p(w.class, new s(61))));
    public static final u9.c f14379f = new u9.c("modelDownloadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(3))));
    public static final u9.c f14382g = new u9.c("customModelLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(4))));
    public static final u9.c f14387i = new u9.c("customModelCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(29))));
    public static final u9.c f14390j = new u9.c("onDeviceFaceDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(5))));
    public static final u9.c f14393k = new u9.c("onDeviceFaceLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(59))));
    public static final u9.c f14396l = new u9.c("onDeviceTextDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(6))));
    public static final u9.c f14398m = new u9.c("onDeviceTextDetectionLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(79))));
    public static final u9.c f14400n = new u9.c("onDeviceBarcodeDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(7))));
    public static final u9.c f14403o = new u9.c("onDeviceBarcodeLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(58))));
    public static final u9.c f14406p = new u9.c("onDeviceImageLabelCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(48))));
    public static final u9.c f14409q = new u9.c("onDeviceImageLabelLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(49))));
    public static final u9.c f14412r = new u9.c("onDeviceImageLabelDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(18))));
    public static final u9.c f14415s = new u9.c("onDeviceObjectCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(26))));
    public static final u9.c f14418t = new u9.c("onDeviceObjectLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(27))));
    public static final u9.c f14421u = new u9.c("onDeviceObjectInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(44))));
    public static final u9.c f14426w = new u9.c("onDeviceSegmentationLogEvent", vh.v2.h(kh.a2.p(w.class, new s(45))));
    public static final u9.c f14429x = new u9.c("onDeviceSmartReplyLogEvent", vh.v2.h(kh.a2.p(w.class, new s(19))));
    public static final u9.c f14432y = new u9.c("onDeviceLanguageIdentificationLogEvent", vh.v2.h(kh.a2.p(w.class, new s(21))));
    public static final u9.c f14435z = new u9.c("onDeviceTranslationLogEvent", vh.v2.h(kh.a2.p(w.class, new s(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", vh.v2.h(kh.a2.p(w.class, new s(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", vh.v2.h(kh.a2.p(w.class, new s(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", vh.v2.h(kh.a2.p(w.class, new s(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", vh.v2.h(kh.a2.p(w.class, new s(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", vh.v2.h(kh.a2.p(w.class, new s(42))));
    public static final u9.c f14367a0 = new u9.c("inputImageConstructionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(50))));
    public static final u9.c f14370b0 = new u9.c("leakedHandleEvent", vh.v2.h(kh.a2.p(w.class, new s(51))));
    public static final u9.c f14373c0 = new u9.c("cameraSourceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(52))));
    public static final u9.c f14375d0 = new u9.c("imageLabelOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(53))));
    public static final u9.c f14377e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(54))));
    public static final u9.c f14380f0 = new u9.c("faceDetectionOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(60))));
    public static final u9.c f14383g0 = new u9.c("documentDetectionOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(85))));
    public static final u9.c f14385h0 = new u9.c("documentCroppingOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(86))));
    public static final u9.c f14388i0 = new u9.c("documentEnhancementOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(87))));
    public static final u9.c f14391j0 = new u9.c("nlClassifierOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(55))));
    public static final u9.c f14394k0 = new u9.c("nlClassifierClientLibraryLogEvent", vh.v2.h(kh.a2.p(w.class, new s(56))));
    public static final u9.c f14397l0 = new u9.c("accelerationAllowlistLogEvent", vh.v2.h(kh.a2.p(w.class, new s(57))));
    public static final u9.c m0 = new u9.c("toxicityDetectionCreateEvent", vh.v2.h(kh.a2.p(w.class, new s(62))));
    public static final u9.c f14401n0 = new u9.c("toxicityDetectionLoadEvent", vh.v2.h(kh.a2.p(w.class, new s(63))));
    public static final u9.c f14404o0 = new u9.c("toxicityDetectionInferenceEvent", vh.v2.h(kh.a2.p(w.class, new s(64))));
    public static final u9.c f14407p0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(65))));
    public static final u9.c f14410q0 = new u9.c("customImageLabelOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(66))));
    public static final u9.c f14413r0 = new u9.c("codeScannerScanApiEvent", vh.v2.h(kh.a2.p(w.class, new s(67))));
    public static final u9.c f14416s0 = new u9.c("codeScannerOptionalModuleEvent", vh.v2.h(kh.a2.p(w.class, new s(68))));
    public static final u9.c f14419t0 = new u9.c("onDeviceExplicitContentCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(70))));
    public static final u9.c f14422u0 = new u9.c("onDeviceExplicitContentLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(71))));
    public static final u9.c f14424v0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(72))));
    public static final u9.c f14427w0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", vh.v2.h(kh.a2.p(w.class, new s(73))));
    public static final u9.c f14430x0 = new u9.c("onDeviceFaceMeshCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(74))));
    public static final u9.c f14433y0 = new u9.c("onDeviceFaceMeshLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(75))));
    public static final u9.c f14436z0 = new u9.c("onDeviceFaceMeshLogEvent", vh.v2.h(kh.a2.p(w.class, new s(76))));
    public static final u9.c A0 = new u9.c("aggregatedOnDeviceFaceMeshLogEvent", vh.v2.h(kh.a2.p(w.class, new s(77))));
    public static final u9.c B0 = new u9.c("smartReplyOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(78))));
    public static final u9.c C0 = new u9.c("textDetectionOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(80))));
    public static final u9.c D0 = new u9.c("onDeviceImageQualityAnalysisCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(81))));
    public static final u9.c E0 = new u9.c("onDeviceImageQualityAnalysisLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(82))));
    public static final u9.c F0 = new u9.c("onDeviceImageQualityAnalysisLogEvent", vh.v2.h(kh.a2.p(w.class, new s(83))));
    public static final u9.c G0 = new u9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", vh.v2.h(kh.a2.p(w.class, new s(84))));
    public static final u9.c H0 = new u9.c("imageQualityAnalysisOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(88))));
    public static final u9.c I0 = new u9.c("imageCaptioningOptionalModuleLogEvent", vh.v2.h(kh.a2.p(w.class, new s(89))));
    public static final u9.c J0 = new u9.c("onDeviceImageCaptioningCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(90))));
    public static final u9.c K0 = new u9.c("onDeviceImageCaptioningLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(91))));
    public static final u9.c L0 = new u9.c("onDeviceImageCaptioningInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(92))));
    public static final u9.c M0 = new u9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", vh.v2.h(kh.a2.p(w.class, new s(93))));
    public static final u9.c N0 = new u9.c("onDeviceDocumentDetectionCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(94))));
    public static final u9.c O0 = new u9.c("onDeviceDocumentDetectionLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(95))));
    public static final u9.c P0 = new u9.c("onDeviceDocumentDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(96))));
    public static final u9.c Q0 = new u9.c("aggregatedOnDeviceDocumentDetectionLogEvent", vh.v2.h(kh.a2.p(w.class, new s(97))));
    public static final u9.c R0 = new u9.c("onDeviceDocumentCroppingCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(98))));
    public static final u9.c S0 = new u9.c("onDeviceDocumentCroppingLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(99))));
    public static final u9.c T0 = new u9.c("onDeviceDocumentCroppingLogEvent", vh.v2.h(kh.a2.p(w.class, new s(100))));
    public static final u9.c U0 = new u9.c("aggregatedOnDeviceDocumentCroppingLogEvent", vh.v2.h(kh.a2.p(w.class, new s(101))));
    public static final u9.c V0 = new u9.c("onDeviceDocumentEnhancementCreateLogEvent", vh.v2.h(kh.a2.p(w.class, new s(102))));
    public static final u9.c W0 = new u9.c("onDeviceDocumentEnhancementLoadLogEvent", vh.v2.h(kh.a2.p(w.class, new s(103))));
    public static final u9.c X0 = kh.a2.s(104, u9.c.a("onDeviceDocumentEnhancementLogEvent"));
    public static final u9.c Y0 = kh.a2.s(105, u9.c.a("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    public static final u9.c Z0 = kh.a2.s(106, u9.c.a("scannerAutoZoomEvent"));
    public static final u9.c f14368a1 = kh.a2.s(107, u9.c.a("lowLightAutoExposureComputationEvent"));
    public static final u9.c f14371b1 = kh.a2.s(108, u9.c.a("lowLightFrameProcessEvent"));
    public static final u9.c f14374c1 = kh.a2.s(109, u9.c.a("lowLightSceneDetectionEvent"));
    public static final u9.c f14376d1 = kh.a2.s(110, u9.c.a("onDeviceStainRemovalLogEvent"));
    public static final u9.c f14378e1 = kh.a2.s(111, u9.c.a("aggregatedOnDeviceStainRemovalLogEvent"));
    public static final u9.c f14381f1 = kh.a2.s(112, u9.c.a("stainRemovalOptionalModuleLogEvent"));
    public static final u9.c f14384g1 = kh.a2.s(113, u9.c.a("onDeviceShadowRemovalLogEvent"));
    public static final u9.c f14386h1 = kh.a2.s(114, u9.c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
    public static final u9.c f14389i1 = kh.a2.s(115, u9.c.a("shadowRemovalOptionalModuleLogEvent"));
    public static final u9.c f14392j1 = kh.a2.s(116, u9.c.a("onDeviceDigitalInkSegmentationLogEvent"));
    public static final u9.c f14395k1 = kh.a2.s(117, u9.c.a("onDeviceDocumentScannerStartLogEvent"));
    public static final u9.c l1 = kh.a2.s(118, u9.c.a("onDeviceDocumentScannerFinishLogEvent"));
    public static final u9.c f14399m1 = kh.a2.s(119, u9.c.a("onDeviceDocumentScannerUiStartLogEvent"));
    public static final u9.c f14402n1 = kh.a2.s(120, u9.c.a("onDeviceDocumentScannerUiFinishLogEvent"));
    public static final u9.c f14405o1 = kh.a2.s(121, u9.c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
    public static final u9.c f14408p1 = kh.a2.s(122, u9.c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    public static final u9.c f14411q1 = kh.a2.s(123, u9.c.a("onDeviceDocumentScannerUiCreateLogEvent"));
    public static final u9.c f14414r1 = kh.a2.s(124, u9.c.a("onDeviceSubjectSegmentationCreateLogEvent"));
    public static final u9.c f14417s1 = kh.a2.s(125, u9.c.a("onDeviceSubjectSegmentationLoadLogEvent"));
    public static final u9.c f14420t1 = kh.a2.s(126, u9.c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
    public static final u9.c f14423u1 = kh.a2.s(127, u9.c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    public static final u9.c f14425v1 = kh.a2.s(128, u9.c.a("subjectSegmentationOptionalModuleLogEvent"));
    public static final u9.c f14428w1 = kh.a2.s(129, u9.c.a("documentScannerUiModuleScreenViewEvent"));
    public static final u9.c f14431x1 = kh.a2.s(130, u9.c.a("documentScannerUiModuleScreenClickEvent"));
    public static final u9.c f14434y1 = kh.a2.s(131, u9.c.a("documentScannerUiModuleScreenErrorEvent"));

    @Override
    public final void a(Object obj, Object obj2) {
        jb jbVar = (jb) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f14369b, jbVar.f14622a);
        eVar.e(f14372c, jbVar.f14623b);
        eVar.e(d, null);
        eVar.e(e, jbVar.f14624c);
        eVar.e(f14379f, null);
        eVar.e(f14382g, null);
        eVar.e(h, null);
        eVar.e(f14387i, null);
        eVar.e(f14390j, null);
        eVar.e(f14393k, null);
        eVar.e(f14396l, null);
        eVar.e(f14398m, null);
        eVar.e(f14400n, null);
        eVar.e(f14403o, null);
        eVar.e(f14406p, null);
        eVar.e(f14409q, null);
        eVar.e(f14412r, null);
        eVar.e(f14415s, null);
        eVar.e(f14418t, null);
        eVar.e(f14421u, null);
        eVar.e(v, null);
        eVar.e(f14426w, null);
        eVar.e(f14429x, null);
        eVar.e(f14432y, null);
        eVar.e(f14435z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f14367a0, null);
        eVar.e(f14370b0, null);
        eVar.e(f14373c0, null);
        eVar.e(f14375d0, null);
        eVar.e(f14377e0, null);
        eVar.e(f14380f0, null);
        eVar.e(f14383g0, null);
        eVar.e(f14385h0, null);
        eVar.e(f14388i0, null);
        eVar.e(f14391j0, null);
        eVar.e(f14394k0, null);
        eVar.e(f14397l0, null);
        eVar.e(m0, null);
        eVar.e(f14401n0, null);
        eVar.e(f14404o0, null);
        eVar.e(f14407p0, null);
        eVar.e(f14410q0, null);
        eVar.e(f14413r0, null);
        eVar.e(f14416s0, null);
        eVar.e(f14419t0, null);
        eVar.e(f14422u0, null);
        eVar.e(f14424v0, null);
        eVar.e(f14427w0, null);
        eVar.e(f14430x0, null);
        eVar.e(f14433y0, null);
        eVar.e(f14436z0, null);
        eVar.e(A0, null);
        eVar.e(B0, null);
        eVar.e(C0, null);
        eVar.e(D0, null);
        eVar.e(E0, null);
        eVar.e(F0, null);
        eVar.e(G0, null);
        eVar.e(H0, null);
        eVar.e(I0, null);
        eVar.e(J0, null);
        eVar.e(K0, null);
        eVar.e(L0, null);
        eVar.e(M0, null);
        eVar.e(N0, null);
        eVar.e(O0, null);
        eVar.e(P0, null);
        eVar.e(Q0, null);
        eVar.e(R0, null);
        eVar.e(S0, null);
        eVar.e(T0, null);
        eVar.e(U0, null);
        eVar.e(V0, null);
        eVar.e(W0, null);
        eVar.e(X0, null);
        eVar.e(Y0, null);
        eVar.e(Z0, null);
        eVar.e(f14368a1, null);
        eVar.e(f14371b1, null);
        eVar.e(f14374c1, null);
        eVar.e(f14376d1, null);
        eVar.e(f14378e1, null);
        eVar.e(f14381f1, null);
        eVar.e(f14384g1, null);
        eVar.e(f14386h1, null);
        eVar.e(f14389i1, null);
        eVar.e(f14392j1, null);
        eVar.e(f14395k1, null);
        eVar.e(l1, null);
        eVar.e(f14399m1, null);
        eVar.e(f14402n1, null);
        eVar.e(f14405o1, null);
        eVar.e(f14408p1, null);
        eVar.e(f14411q1, null);
        eVar.e(f14414r1, jbVar.d);
        eVar.e(f14417s1, jbVar.e);
        eVar.e(f14420t1, jbVar.f14625f);
        eVar.e(f14423u1, jbVar.f14626g);
        eVar.e(f14425v1, null);
        eVar.e(f14428w1, null);
        eVar.e(f14431x1, null);
        eVar.e(f14434y1, null);
    }
}
