package n7;
public final class g5 implements u9.d {
    public static final g5 f14351a = new Object();
    public static final u9.c f14354b = new u9.c("systemInfo", vh.w2.h(kf.k0.p(w.class, new s(1))));
    public static final u9.c f14357c = new u9.c("eventName", vh.w2.h(kf.k0.p(w.class, new s(2))));
    public static final u9.c d = new u9.c("isThickClient", vh.w2.h(kf.k0.p(w.class, new s(37))));
    public static final u9.c e = new u9.c("clientType", vh.w2.h(kf.k0.p(w.class, new s(61))));
    public static final u9.c f14364f = new u9.c("modelDownloadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(3))));
    public static final u9.c f14367g = new u9.c("customModelLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(4))));
    public static final u9.c f14372i = new u9.c("customModelCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(29))));
    public static final u9.c f14375j = new u9.c("onDeviceFaceDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(5))));
    public static final u9.c f14378k = new u9.c("onDeviceFaceLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(59))));
    public static final u9.c f14381l = new u9.c("onDeviceTextDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(6))));
    public static final u9.c f14383m = new u9.c("onDeviceTextDetectionLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(79))));
    public static final u9.c f14385n = new u9.c("onDeviceBarcodeDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(7))));
    public static final u9.c f14388o = new u9.c("onDeviceBarcodeLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(58))));
    public static final u9.c f14391p = new u9.c("onDeviceImageLabelCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(48))));
    public static final u9.c f14394q = new u9.c("onDeviceImageLabelLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(49))));
    public static final u9.c f14397r = new u9.c("onDeviceImageLabelDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(18))));
    public static final u9.c f14400s = new u9.c("onDeviceObjectCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(26))));
    public static final u9.c f14403t = new u9.c("onDeviceObjectLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(27))));
    public static final u9.c f14406u = new u9.c("onDeviceObjectInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(44))));
    public static final u9.c f14411w = new u9.c("onDeviceSegmentationLogEvent", vh.w2.h(kf.k0.p(w.class, new s(45))));
    public static final u9.c f14414x = new u9.c("onDeviceSmartReplyLogEvent", vh.w2.h(kf.k0.p(w.class, new s(19))));
    public static final u9.c f14417y = new u9.c("onDeviceLanguageIdentificationLogEvent", vh.w2.h(kf.k0.p(w.class, new s(21))));
    public static final u9.c f14420z = new u9.c("onDeviceTranslationLogEvent", vh.w2.h(kf.k0.p(w.class, new s(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", vh.w2.h(kf.k0.p(w.class, new s(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", vh.w2.h(kf.k0.p(w.class, new s(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", vh.w2.h(kf.k0.p(w.class, new s(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", vh.w2.h(kf.k0.p(w.class, new s(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", vh.w2.h(kf.k0.p(w.class, new s(42))));
    public static final u9.c f14352a0 = new u9.c("inputImageConstructionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(50))));
    public static final u9.c f14355b0 = new u9.c("leakedHandleEvent", vh.w2.h(kf.k0.p(w.class, new s(51))));
    public static final u9.c f14358c0 = new u9.c("cameraSourceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(52))));
    public static final u9.c f14360d0 = new u9.c("imageLabelOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(53))));
    public static final u9.c f14362e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(54))));
    public static final u9.c f14365f0 = new u9.c("faceDetectionOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(60))));
    public static final u9.c f14368g0 = new u9.c("documentDetectionOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(85))));
    public static final u9.c f14370h0 = new u9.c("documentCroppingOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(86))));
    public static final u9.c f14373i0 = new u9.c("documentEnhancementOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(87))));
    public static final u9.c f14376j0 = new u9.c("nlClassifierOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(55))));
    public static final u9.c f14379k0 = new u9.c("nlClassifierClientLibraryLogEvent", vh.w2.h(kf.k0.p(w.class, new s(56))));
    public static final u9.c f14382l0 = new u9.c("accelerationAllowlistLogEvent", vh.w2.h(kf.k0.p(w.class, new s(57))));
    public static final u9.c m0 = new u9.c("toxicityDetectionCreateEvent", vh.w2.h(kf.k0.p(w.class, new s(62))));
    public static final u9.c f14386n0 = new u9.c("toxicityDetectionLoadEvent", vh.w2.h(kf.k0.p(w.class, new s(63))));
    public static final u9.c f14389o0 = new u9.c("toxicityDetectionInferenceEvent", vh.w2.h(kf.k0.p(w.class, new s(64))));
    public static final u9.c f14392p0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(65))));
    public static final u9.c f14395q0 = new u9.c("customImageLabelOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(66))));
    public static final u9.c f14398r0 = new u9.c("codeScannerScanApiEvent", vh.w2.h(kf.k0.p(w.class, new s(67))));
    public static final u9.c f14401s0 = new u9.c("codeScannerOptionalModuleEvent", vh.w2.h(kf.k0.p(w.class, new s(68))));
    public static final u9.c f14404t0 = new u9.c("onDeviceExplicitContentCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(70))));
    public static final u9.c f14407u0 = new u9.c("onDeviceExplicitContentLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(71))));
    public static final u9.c f14409v0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(72))));
    public static final u9.c f14412w0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", vh.w2.h(kf.k0.p(w.class, new s(73))));
    public static final u9.c f14415x0 = new u9.c("onDeviceFaceMeshCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(74))));
    public static final u9.c f14418y0 = new u9.c("onDeviceFaceMeshLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(75))));
    public static final u9.c f14421z0 = new u9.c("onDeviceFaceMeshLogEvent", vh.w2.h(kf.k0.p(w.class, new s(76))));
    public static final u9.c A0 = new u9.c("aggregatedOnDeviceFaceMeshLogEvent", vh.w2.h(kf.k0.p(w.class, new s(77))));
    public static final u9.c B0 = new u9.c("smartReplyOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(78))));
    public static final u9.c C0 = new u9.c("textDetectionOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(80))));
    public static final u9.c D0 = new u9.c("onDeviceImageQualityAnalysisCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(81))));
    public static final u9.c E0 = new u9.c("onDeviceImageQualityAnalysisLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(82))));
    public static final u9.c F0 = new u9.c("onDeviceImageQualityAnalysisLogEvent", vh.w2.h(kf.k0.p(w.class, new s(83))));
    public static final u9.c G0 = new u9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", vh.w2.h(kf.k0.p(w.class, new s(84))));
    public static final u9.c H0 = new u9.c("imageQualityAnalysisOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(88))));
    public static final u9.c I0 = new u9.c("imageCaptioningOptionalModuleLogEvent", vh.w2.h(kf.k0.p(w.class, new s(89))));
    public static final u9.c J0 = new u9.c("onDeviceImageCaptioningCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(90))));
    public static final u9.c K0 = new u9.c("onDeviceImageCaptioningLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(91))));
    public static final u9.c L0 = new u9.c("onDeviceImageCaptioningInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(92))));
    public static final u9.c M0 = new u9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", vh.w2.h(kf.k0.p(w.class, new s(93))));
    public static final u9.c N0 = new u9.c("onDeviceDocumentDetectionCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(94))));
    public static final u9.c O0 = new u9.c("onDeviceDocumentDetectionLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(95))));
    public static final u9.c P0 = new u9.c("onDeviceDocumentDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(96))));
    public static final u9.c Q0 = new u9.c("aggregatedOnDeviceDocumentDetectionLogEvent", vh.w2.h(kf.k0.p(w.class, new s(97))));
    public static final u9.c R0 = new u9.c("onDeviceDocumentCroppingCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(98))));
    public static final u9.c S0 = new u9.c("onDeviceDocumentCroppingLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(99))));
    public static final u9.c T0 = new u9.c("onDeviceDocumentCroppingLogEvent", vh.w2.h(kf.k0.p(w.class, new s(100))));
    public static final u9.c U0 = new u9.c("aggregatedOnDeviceDocumentCroppingLogEvent", vh.w2.h(kf.k0.p(w.class, new s(101))));
    public static final u9.c V0 = new u9.c("onDeviceDocumentEnhancementCreateLogEvent", vh.w2.h(kf.k0.p(w.class, new s(102))));
    public static final u9.c W0 = new u9.c("onDeviceDocumentEnhancementLoadLogEvent", vh.w2.h(kf.k0.p(w.class, new s(103))));
    public static final u9.c X0 = kf.k0.s(104, u9.c.a("onDeviceDocumentEnhancementLogEvent"));
    public static final u9.c Y0 = kf.k0.s(105, u9.c.a("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    public static final u9.c Z0 = kf.k0.s(106, u9.c.a("scannerAutoZoomEvent"));
    public static final u9.c f14353a1 = kf.k0.s(107, u9.c.a("lowLightAutoExposureComputationEvent"));
    public static final u9.c f14356b1 = kf.k0.s(108, u9.c.a("lowLightFrameProcessEvent"));
    public static final u9.c f14359c1 = kf.k0.s(109, u9.c.a("lowLightSceneDetectionEvent"));
    public static final u9.c f14361d1 = kf.k0.s(110, u9.c.a("onDeviceStainRemovalLogEvent"));
    public static final u9.c f14363e1 = kf.k0.s(111, u9.c.a("aggregatedOnDeviceStainRemovalLogEvent"));
    public static final u9.c f14366f1 = kf.k0.s(112, u9.c.a("stainRemovalOptionalModuleLogEvent"));
    public static final u9.c f14369g1 = kf.k0.s(113, u9.c.a("onDeviceShadowRemovalLogEvent"));
    public static final u9.c f14371h1 = kf.k0.s(114, u9.c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
    public static final u9.c f14374i1 = kf.k0.s(115, u9.c.a("shadowRemovalOptionalModuleLogEvent"));
    public static final u9.c f14377j1 = kf.k0.s(116, u9.c.a("onDeviceDigitalInkSegmentationLogEvent"));
    public static final u9.c f14380k1 = kf.k0.s(117, u9.c.a("onDeviceDocumentScannerStartLogEvent"));
    public static final u9.c l1 = kf.k0.s(118, u9.c.a("onDeviceDocumentScannerFinishLogEvent"));
    public static final u9.c f14384m1 = kf.k0.s(119, u9.c.a("onDeviceDocumentScannerUiStartLogEvent"));
    public static final u9.c f14387n1 = kf.k0.s(120, u9.c.a("onDeviceDocumentScannerUiFinishLogEvent"));
    public static final u9.c f14390o1 = kf.k0.s(121, u9.c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
    public static final u9.c f14393p1 = kf.k0.s(122, u9.c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    public static final u9.c f14396q1 = kf.k0.s(123, u9.c.a("onDeviceDocumentScannerUiCreateLogEvent"));
    public static final u9.c f14399r1 = kf.k0.s(124, u9.c.a("onDeviceSubjectSegmentationCreateLogEvent"));
    public static final u9.c f14402s1 = kf.k0.s(125, u9.c.a("onDeviceSubjectSegmentationLoadLogEvent"));
    public static final u9.c f14405t1 = kf.k0.s(126, u9.c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
    public static final u9.c f14408u1 = kf.k0.s(127, u9.c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    public static final u9.c f14410v1 = kf.k0.s(128, u9.c.a("subjectSegmentationOptionalModuleLogEvent"));
    public static final u9.c f14413w1 = kf.k0.s(129, u9.c.a("documentScannerUiModuleScreenViewEvent"));
    public static final u9.c f14416x1 = kf.k0.s(130, u9.c.a("documentScannerUiModuleScreenClickEvent"));
    public static final u9.c f14419y1 = kf.k0.s(131, u9.c.a("documentScannerUiModuleScreenErrorEvent"));

    @Override
    public final void a(Object obj, Object obj2) {
        jb jbVar = (jb) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f14354b, jbVar.f14607a);
        eVar.e(f14357c, jbVar.f14608b);
        eVar.e(d, null);
        eVar.e(e, jbVar.f14609c);
        eVar.e(f14364f, null);
        eVar.e(f14367g, null);
        eVar.e(h, null);
        eVar.e(f14372i, null);
        eVar.e(f14375j, null);
        eVar.e(f14378k, null);
        eVar.e(f14381l, null);
        eVar.e(f14383m, null);
        eVar.e(f14385n, null);
        eVar.e(f14388o, null);
        eVar.e(f14391p, null);
        eVar.e(f14394q, null);
        eVar.e(f14397r, null);
        eVar.e(f14400s, null);
        eVar.e(f14403t, null);
        eVar.e(f14406u, null);
        eVar.e(v, null);
        eVar.e(f14411w, null);
        eVar.e(f14414x, null);
        eVar.e(f14417y, null);
        eVar.e(f14420z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f14352a0, null);
        eVar.e(f14355b0, null);
        eVar.e(f14358c0, null);
        eVar.e(f14360d0, null);
        eVar.e(f14362e0, null);
        eVar.e(f14365f0, null);
        eVar.e(f14368g0, null);
        eVar.e(f14370h0, null);
        eVar.e(f14373i0, null);
        eVar.e(f14376j0, null);
        eVar.e(f14379k0, null);
        eVar.e(f14382l0, null);
        eVar.e(m0, null);
        eVar.e(f14386n0, null);
        eVar.e(f14389o0, null);
        eVar.e(f14392p0, null);
        eVar.e(f14395q0, null);
        eVar.e(f14398r0, null);
        eVar.e(f14401s0, null);
        eVar.e(f14404t0, null);
        eVar.e(f14407u0, null);
        eVar.e(f14409v0, null);
        eVar.e(f14412w0, null);
        eVar.e(f14415x0, null);
        eVar.e(f14418y0, null);
        eVar.e(f14421z0, null);
        eVar.e(A0, null);
        eVar.e(B0, null);
        eVar.e(C0, null);
        eVar.e(D0, null);
        eVar.e(E0, null);
        eVar.e(F0, null);
        eVar.e(G0, null);
        eVar.e(H0, null);
        eVar.e(I0, null);
        eVar.e(J0, null);
        eVar.e(K0, null);
        eVar.e(L0, null);
        eVar.e(M0, null);
        eVar.e(N0, null);
        eVar.e(O0, null);
        eVar.e(P0, null);
        eVar.e(Q0, null);
        eVar.e(R0, null);
        eVar.e(S0, null);
        eVar.e(T0, null);
        eVar.e(U0, null);
        eVar.e(V0, null);
        eVar.e(W0, null);
        eVar.e(X0, null);
        eVar.e(Y0, null);
        eVar.e(Z0, null);
        eVar.e(f14353a1, null);
        eVar.e(f14356b1, null);
        eVar.e(f14359c1, null);
        eVar.e(f14361d1, null);
        eVar.e(f14363e1, null);
        eVar.e(f14366f1, null);
        eVar.e(f14369g1, null);
        eVar.e(f14371h1, null);
        eVar.e(f14374i1, null);
        eVar.e(f14377j1, null);
        eVar.e(f14380k1, null);
        eVar.e(l1, null);
        eVar.e(f14384m1, null);
        eVar.e(f14387n1, null);
        eVar.e(f14390o1, null);
        eVar.e(f14393p1, null);
        eVar.e(f14396q1, null);
        eVar.e(f14399r1, jbVar.d);
        eVar.e(f14402s1, jbVar.e);
        eVar.e(f14405t1, jbVar.f14610f);
        eVar.e(f14408u1, jbVar.f14611g);
        eVar.e(f14410v1, null);
        eVar.e(f14413w1, null);
        eVar.e(f14416x1, null);
        eVar.e(f14419y1, null);
    }
}
