package n7;
public final class g5 implements u9.d {
    public static final g5 f15351a = new Object();
    public static final u9.c f15354b = new u9.c("systemInfo", w.c.h(l.d.p(w.class, new s(1))));
    public static final u9.c f15357c = new u9.c("eventName", w.c.h(l.d.p(w.class, new s(2))));
    public static final u9.c d = new u9.c("isThickClient", w.c.h(l.d.p(w.class, new s(37))));
    public static final u9.c f15362e = new u9.c("clientType", w.c.h(l.d.p(w.class, new s(61))));
    public static final u9.c f15365f = new u9.c("modelDownloadLogEvent", w.c.h(l.d.p(w.class, new s(3))));
    public static final u9.c f15368g = new u9.c("customModelLoadLogEvent", w.c.h(l.d.p(w.class, new s(20))));
    public static final u9.c h = new u9.c("customModelInferenceLogEvent", w.c.h(l.d.p(w.class, new s(4))));
    public static final u9.c f15373i = new u9.c("customModelCreateLogEvent", w.c.h(l.d.p(w.class, new s(29))));
    public static final u9.c f15376j = new u9.c("onDeviceFaceDetectionLogEvent", w.c.h(l.d.p(w.class, new s(5))));
    public static final u9.c f15379k = new u9.c("onDeviceFaceLoadLogEvent", w.c.h(l.d.p(w.class, new s(59))));
    public static final u9.c f15382l = new u9.c("onDeviceTextDetectionLogEvent", w.c.h(l.d.p(w.class, new s(6))));
    public static final u9.c f15384m = new u9.c("onDeviceTextDetectionLoadLogEvent", w.c.h(l.d.p(w.class, new s(79))));
    public static final u9.c f15386n = new u9.c("onDeviceBarcodeDetectionLogEvent", w.c.h(l.d.p(w.class, new s(7))));
    public static final u9.c f15389o = new u9.c("onDeviceBarcodeLoadLogEvent", w.c.h(l.d.p(w.class, new s(58))));
    public static final u9.c f15392p = new u9.c("onDeviceImageLabelCreateLogEvent", w.c.h(l.d.p(w.class, new s(48))));
    public static final u9.c f15395q = new u9.c("onDeviceImageLabelLoadLogEvent", w.c.h(l.d.p(w.class, new s(49))));
    public static final u9.c f15398r = new u9.c("onDeviceImageLabelDetectionLogEvent", w.c.h(l.d.p(w.class, new s(18))));
    public static final u9.c f15401s = new u9.c("onDeviceObjectCreateLogEvent", w.c.h(l.d.p(w.class, new s(26))));
    public static final u9.c f15404t = new u9.c("onDeviceObjectLoadLogEvent", w.c.h(l.d.p(w.class, new s(27))));
    public static final u9.c f15407u = new u9.c("onDeviceObjectInferenceLogEvent", w.c.h(l.d.p(w.class, new s(28))));
    public static final u9.c v = new u9.c("onDevicePoseDetectionLogEvent", w.c.h(l.d.p(w.class, new s(44))));
    public static final u9.c f15412w = new u9.c("onDeviceSegmentationLogEvent", w.c.h(l.d.p(w.class, new s(45))));
    public static final u9.c f15415x = new u9.c("onDeviceSmartReplyLogEvent", w.c.h(l.d.p(w.class, new s(19))));
    public static final u9.c f15418y = new u9.c("onDeviceLanguageIdentificationLogEvent", w.c.h(l.d.p(w.class, new s(21))));
    public static final u9.c f15421z = new u9.c("onDeviceTranslationLogEvent", w.c.h(l.d.p(w.class, new s(22))));
    public static final u9.c A = new u9.c("cloudFaceDetectionLogEvent", w.c.h(l.d.p(w.class, new s(8))));
    public static final u9.c B = new u9.c("cloudCropHintDetectionLogEvent", w.c.h(l.d.p(w.class, new s(9))));
    public static final u9.c C = new u9.c("cloudDocumentTextDetectionLogEvent", w.c.h(l.d.p(w.class, new s(10))));
    public static final u9.c D = new u9.c("cloudImagePropertiesDetectionLogEvent", w.c.h(l.d.p(w.class, new s(11))));
    public static final u9.c E = new u9.c("cloudImageLabelDetectionLogEvent", w.c.h(l.d.p(w.class, new s(12))));
    public static final u9.c F = new u9.c("cloudLandmarkDetectionLogEvent", w.c.h(l.d.p(w.class, new s(13))));
    public static final u9.c G = new u9.c("cloudLogoDetectionLogEvent", w.c.h(l.d.p(w.class, new s(14))));
    public static final u9.c H = new u9.c("cloudSafeSearchDetectionLogEvent", w.c.h(l.d.p(w.class, new s(15))));
    public static final u9.c I = new u9.c("cloudTextDetectionLogEvent", w.c.h(l.d.p(w.class, new s(16))));
    public static final u9.c J = new u9.c("cloudWebSearchDetectionLogEvent", w.c.h(l.d.p(w.class, new s(17))));
    public static final u9.c K = new u9.c("automlImageLabelingCreateLogEvent", w.c.h(l.d.p(w.class, new s(23))));
    public static final u9.c L = new u9.c("automlImageLabelingLoadLogEvent", w.c.h(l.d.p(w.class, new s(24))));
    public static final u9.c M = new u9.c("automlImageLabelingInferenceLogEvent", w.c.h(l.d.p(w.class, new s(25))));
    public static final u9.c N = new u9.c("isModelDownloadedLogEvent", w.c.h(l.d.p(w.class, new s(39))));
    public static final u9.c O = new u9.c("deleteModelLogEvent", w.c.h(l.d.p(w.class, new s(40))));
    public static final u9.c P = new u9.c("aggregatedAutomlImageLabelingInferenceLogEvent", w.c.h(l.d.p(w.class, new s(30))));
    public static final u9.c Q = new u9.c("aggregatedCustomModelInferenceLogEvent", w.c.h(l.d.p(w.class, new s(31))));
    public static final u9.c R = new u9.c("aggregatedOnDeviceFaceDetectionLogEvent", w.c.h(l.d.p(w.class, new s(32))));
    public static final u9.c S = new u9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", w.c.h(l.d.p(w.class, new s(33))));
    public static final u9.c T = new u9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", w.c.h(l.d.p(w.class, new s(34))));
    public static final u9.c U = new u9.c("aggregatedOnDeviceObjectInferenceLogEvent", w.c.h(l.d.p(w.class, new s(35))));
    public static final u9.c V = new u9.c("aggregatedOnDeviceTextDetectionLogEvent", w.c.h(l.d.p(w.class, new s(36))));
    public static final u9.c W = new u9.c("aggregatedOnDevicePoseDetectionLogEvent", w.c.h(l.d.p(w.class, new s(46))));
    public static final u9.c X = new u9.c("aggregatedOnDeviceSegmentationLogEvent", w.c.h(l.d.p(w.class, new s(47))));
    public static final u9.c Y = new u9.c("pipelineAccelerationInferenceEvents", w.c.h(l.d.p(w.class, new s(69))));
    public static final u9.c Z = new u9.c("remoteConfigLogEvent", w.c.h(l.d.p(w.class, new s(42))));
    public static final u9.c f15352a0 = new u9.c("inputImageConstructionLogEvent", w.c.h(l.d.p(w.class, new s(50))));
    public static final u9.c f15355b0 = new u9.c("leakedHandleEvent", w.c.h(l.d.p(w.class, new s(51))));
    public static final u9.c f15358c0 = new u9.c("cameraSourceLogEvent", w.c.h(l.d.p(w.class, new s(52))));
    public static final u9.c f15360d0 = new u9.c("imageLabelOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(53))));
    public static final u9.c f15363e0 = new u9.c("languageIdentificationOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(54))));
    public static final u9.c f15366f0 = new u9.c("faceDetectionOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(60))));
    public static final u9.c f15369g0 = new u9.c("documentDetectionOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(85))));
    public static final u9.c f15371h0 = new u9.c("documentCroppingOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(86))));
    public static final u9.c f15374i0 = new u9.c("documentEnhancementOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(87))));
    public static final u9.c f15377j0 = new u9.c("nlClassifierOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(55))));
    public static final u9.c f15380k0 = new u9.c("nlClassifierClientLibraryLogEvent", w.c.h(l.d.p(w.class, new s(56))));
    public static final u9.c f15383l0 = new u9.c("accelerationAllowlistLogEvent", w.c.h(l.d.p(w.class, new s(57))));
    public static final u9.c m0 = new u9.c("toxicityDetectionCreateEvent", w.c.h(l.d.p(w.class, new s(62))));
    public static final u9.c f15387n0 = new u9.c("toxicityDetectionLoadEvent", w.c.h(l.d.p(w.class, new s(63))));
    public static final u9.c f15390o0 = new u9.c("toxicityDetectionInferenceEvent", w.c.h(l.d.p(w.class, new s(64))));
    public static final u9.c f15393p0 = new u9.c("barcodeDetectionOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(65))));
    public static final u9.c f15396q0 = new u9.c("customImageLabelOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(66))));
    public static final u9.c f15399r0 = new u9.c("codeScannerScanApiEvent", w.c.h(l.d.p(w.class, new s(67))));
    public static final u9.c f15402s0 = new u9.c("codeScannerOptionalModuleEvent", w.c.h(l.d.p(w.class, new s(68))));
    public static final u9.c f15405t0 = new u9.c("onDeviceExplicitContentCreateLogEvent", w.c.h(l.d.p(w.class, new s(70))));
    public static final u9.c f15408u0 = new u9.c("onDeviceExplicitContentLoadLogEvent", w.c.h(l.d.p(w.class, new s(71))));
    public static final u9.c f15410v0 = new u9.c("onDeviceExplicitContentInferenceLogEvent", w.c.h(l.d.p(w.class, new s(72))));
    public static final u9.c f15413w0 = new u9.c("aggregatedOnDeviceExplicitContentLogEvent", w.c.h(l.d.p(w.class, new s(73))));
    public static final u9.c f15416x0 = new u9.c("onDeviceFaceMeshCreateLogEvent", w.c.h(l.d.p(w.class, new s(74))));
    public static final u9.c f15419y0 = new u9.c("onDeviceFaceMeshLoadLogEvent", w.c.h(l.d.p(w.class, new s(75))));
    public static final u9.c f15422z0 = new u9.c("onDeviceFaceMeshLogEvent", w.c.h(l.d.p(w.class, new s(76))));
    public static final u9.c A0 = new u9.c("aggregatedOnDeviceFaceMeshLogEvent", w.c.h(l.d.p(w.class, new s(77))));
    public static final u9.c B0 = new u9.c("smartReplyOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(78))));
    public static final u9.c C0 = new u9.c("textDetectionOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(80))));
    public static final u9.c D0 = new u9.c("onDeviceImageQualityAnalysisCreateLogEvent", w.c.h(l.d.p(w.class, new s(81))));
    public static final u9.c E0 = new u9.c("onDeviceImageQualityAnalysisLoadLogEvent", w.c.h(l.d.p(w.class, new s(82))));
    public static final u9.c F0 = new u9.c("onDeviceImageQualityAnalysisLogEvent", w.c.h(l.d.p(w.class, new s(83))));
    public static final u9.c G0 = new u9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", w.c.h(l.d.p(w.class, new s(84))));
    public static final u9.c H0 = new u9.c("imageQualityAnalysisOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(88))));
    public static final u9.c I0 = new u9.c("imageCaptioningOptionalModuleLogEvent", w.c.h(l.d.p(w.class, new s(89))));
    public static final u9.c J0 = new u9.c("onDeviceImageCaptioningCreateLogEvent", w.c.h(l.d.p(w.class, new s(90))));
    public static final u9.c K0 = new u9.c("onDeviceImageCaptioningLoadLogEvent", w.c.h(l.d.p(w.class, new s(91))));
    public static final u9.c L0 = new u9.c("onDeviceImageCaptioningInferenceLogEvent", w.c.h(l.d.p(w.class, new s(92))));
    public static final u9.c M0 = new u9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", w.c.h(l.d.p(w.class, new s(93))));
    public static final u9.c N0 = new u9.c("onDeviceDocumentDetectionCreateLogEvent", w.c.h(l.d.p(w.class, new s(94))));
    public static final u9.c O0 = new u9.c("onDeviceDocumentDetectionLoadLogEvent", w.c.h(l.d.p(w.class, new s(95))));
    public static final u9.c P0 = new u9.c("onDeviceDocumentDetectionLogEvent", w.c.h(l.d.p(w.class, new s(96))));
    public static final u9.c Q0 = new u9.c("aggregatedOnDeviceDocumentDetectionLogEvent", w.c.h(l.d.p(w.class, new s(97))));
    public static final u9.c R0 = new u9.c("onDeviceDocumentCroppingCreateLogEvent", w.c.h(l.d.p(w.class, new s(98))));
    public static final u9.c S0 = new u9.c("onDeviceDocumentCroppingLoadLogEvent", w.c.h(l.d.p(w.class, new s(99))));
    public static final u9.c T0 = new u9.c("onDeviceDocumentCroppingLogEvent", w.c.h(l.d.p(w.class, new s(100))));
    public static final u9.c U0 = new u9.c("aggregatedOnDeviceDocumentCroppingLogEvent", w.c.h(l.d.p(w.class, new s(101))));
    public static final u9.c V0 = new u9.c("onDeviceDocumentEnhancementCreateLogEvent", w.c.h(l.d.p(w.class, new s(102))));
    public static final u9.c W0 = new u9.c("onDeviceDocumentEnhancementLoadLogEvent", w.c.h(l.d.p(w.class, new s(103))));
    public static final u9.c X0 = l.d.s(104, u9.c.a("onDeviceDocumentEnhancementLogEvent"));
    public static final u9.c Y0 = l.d.s(105, u9.c.a("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    public static final u9.c Z0 = l.d.s(106, u9.c.a("scannerAutoZoomEvent"));
    public static final u9.c f15353a1 = l.d.s(107, u9.c.a("lowLightAutoExposureComputationEvent"));
    public static final u9.c f15356b1 = l.d.s(108, u9.c.a("lowLightFrameProcessEvent"));
    public static final u9.c f15359c1 = l.d.s(109, u9.c.a("lowLightSceneDetectionEvent"));
    public static final u9.c f15361d1 = l.d.s(110, u9.c.a("onDeviceStainRemovalLogEvent"));
    public static final u9.c f15364e1 = l.d.s(111, u9.c.a("aggregatedOnDeviceStainRemovalLogEvent"));
    public static final u9.c f15367f1 = l.d.s(112, u9.c.a("stainRemovalOptionalModuleLogEvent"));
    public static final u9.c f15370g1 = l.d.s(113, u9.c.a("onDeviceShadowRemovalLogEvent"));
    public static final u9.c f15372h1 = l.d.s(114, u9.c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
    public static final u9.c f15375i1 = l.d.s(115, u9.c.a("shadowRemovalOptionalModuleLogEvent"));
    public static final u9.c f15378j1 = l.d.s(116, u9.c.a("onDeviceDigitalInkSegmentationLogEvent"));
    public static final u9.c f15381k1 = l.d.s(117, u9.c.a("onDeviceDocumentScannerStartLogEvent"));
    public static final u9.c l1 = l.d.s(118, u9.c.a("onDeviceDocumentScannerFinishLogEvent"));
    public static final u9.c f15385m1 = l.d.s(119, u9.c.a("onDeviceDocumentScannerUiStartLogEvent"));
    public static final u9.c f15388n1 = l.d.s(120, u9.c.a("onDeviceDocumentScannerUiFinishLogEvent"));
    public static final u9.c f15391o1 = l.d.s(121, u9.c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
    public static final u9.c f15394p1 = l.d.s(122, u9.c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    public static final u9.c f15397q1 = l.d.s(123, u9.c.a("onDeviceDocumentScannerUiCreateLogEvent"));
    public static final u9.c f15400r1 = l.d.s(124, u9.c.a("onDeviceSubjectSegmentationCreateLogEvent"));
    public static final u9.c f15403s1 = l.d.s(125, u9.c.a("onDeviceSubjectSegmentationLoadLogEvent"));
    public static final u9.c f15406t1 = l.d.s(126, u9.c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
    public static final u9.c f15409u1 = l.d.s(127, u9.c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    public static final u9.c f15411v1 = l.d.s(128, u9.c.a("subjectSegmentationOptionalModuleLogEvent"));
    public static final u9.c f15414w1 = l.d.s(129, u9.c.a("documentScannerUiModuleScreenViewEvent"));
    public static final u9.c f15417x1 = l.d.s(130, u9.c.a("documentScannerUiModuleScreenClickEvent"));
    public static final u9.c f15420y1 = l.d.s(131, u9.c.a("documentScannerUiModuleScreenErrorEvent"));

    @Override
    public final void a(Object obj, Object obj2) {
        jb jbVar = (jb) obj;
        u9.e eVar = (u9.e) obj2;
        eVar.e(f15354b, jbVar.f15612a);
        eVar.e(f15357c, jbVar.f15613b);
        eVar.e(d, null);
        eVar.e(f15362e, jbVar.f15614c);
        eVar.e(f15365f, null);
        eVar.e(f15368g, null);
        eVar.e(h, null);
        eVar.e(f15373i, null);
        eVar.e(f15376j, null);
        eVar.e(f15379k, null);
        eVar.e(f15382l, null);
        eVar.e(f15384m, null);
        eVar.e(f15386n, null);
        eVar.e(f15389o, null);
        eVar.e(f15392p, null);
        eVar.e(f15395q, null);
        eVar.e(f15398r, null);
        eVar.e(f15401s, null);
        eVar.e(f15404t, null);
        eVar.e(f15407u, null);
        eVar.e(v, null);
        eVar.e(f15412w, null);
        eVar.e(f15415x, null);
        eVar.e(f15418y, null);
        eVar.e(f15421z, null);
        eVar.e(A, null);
        eVar.e(B, null);
        eVar.e(C, null);
        eVar.e(D, null);
        eVar.e(E, null);
        eVar.e(F, null);
        eVar.e(G, null);
        eVar.e(H, null);
        eVar.e(I, null);
        eVar.e(J, null);
        eVar.e(K, null);
        eVar.e(L, null);
        eVar.e(M, null);
        eVar.e(N, null);
        eVar.e(O, null);
        eVar.e(P, null);
        eVar.e(Q, null);
        eVar.e(R, null);
        eVar.e(S, null);
        eVar.e(T, null);
        eVar.e(U, null);
        eVar.e(V, null);
        eVar.e(W, null);
        eVar.e(X, null);
        eVar.e(Y, null);
        eVar.e(Z, null);
        eVar.e(f15352a0, null);
        eVar.e(f15355b0, null);
        eVar.e(f15358c0, null);
        eVar.e(f15360d0, null);
        eVar.e(f15363e0, null);
        eVar.e(f15366f0, null);
        eVar.e(f15369g0, null);
        eVar.e(f15371h0, null);
        eVar.e(f15374i0, null);
        eVar.e(f15377j0, null);
        eVar.e(f15380k0, null);
        eVar.e(f15383l0, null);
        eVar.e(m0, null);
        eVar.e(f15387n0, null);
        eVar.e(f15390o0, null);
        eVar.e(f15393p0, null);
        eVar.e(f15396q0, null);
        eVar.e(f15399r0, null);
        eVar.e(f15402s0, null);
        eVar.e(f15405t0, null);
        eVar.e(f15408u0, null);
        eVar.e(f15410v0, null);
        eVar.e(f15413w0, null);
        eVar.e(f15416x0, null);
        eVar.e(f15419y0, null);
        eVar.e(f15422z0, null);
        eVar.e(A0, null);
        eVar.e(B0, null);
        eVar.e(C0, null);
        eVar.e(D0, null);
        eVar.e(E0, null);
        eVar.e(F0, null);
        eVar.e(G0, null);
        eVar.e(H0, null);
        eVar.e(I0, null);
        eVar.e(J0, null);
        eVar.e(K0, null);
        eVar.e(L0, null);
        eVar.e(M0, null);
        eVar.e(N0, null);
        eVar.e(O0, null);
        eVar.e(P0, null);
        eVar.e(Q0, null);
        eVar.e(R0, null);
        eVar.e(S0, null);
        eVar.e(T0, null);
        eVar.e(U0, null);
        eVar.e(V0, null);
        eVar.e(W0, null);
        eVar.e(X0, null);
        eVar.e(Y0, null);
        eVar.e(Z0, null);
        eVar.e(f15353a1, null);
        eVar.e(f15356b1, null);
        eVar.e(f15359c1, null);
        eVar.e(f15361d1, null);
        eVar.e(f15364e1, null);
        eVar.e(f15367f1, null);
        eVar.e(f15370g1, null);
        eVar.e(f15372h1, null);
        eVar.e(f15375i1, null);
        eVar.e(f15378j1, null);
        eVar.e(f15381k1, null);
        eVar.e(l1, null);
        eVar.e(f15385m1, null);
        eVar.e(f15388n1, null);
        eVar.e(f15391o1, null);
        eVar.e(f15394p1, null);
        eVar.e(f15397q1, null);
        eVar.e(f15400r1, jbVar.d);
        eVar.e(f15403s1, jbVar.f15615e);
        eVar.e(f15406t1, jbVar.f15616f);
        eVar.e(f15409u1, jbVar.f15617g);
        eVar.e(f15411v1, null);
        eVar.e(f15414w1, null);
        eVar.e(f15417x1, null);
        eVar.e(f15420y1, null);
    }
}
